---
settings:
  name: SANtricity commands
  internal:
    pdf_enabled: false
  prod:
    pdf_enabled: true
    harmony_enabled: false
  rss_page: whats-new.html
  pdf:
    zip-level: 1
    zip-filename: santricity-commands.zip
  langs: ja-jp,us-en,zh-cn,zh-tw,ko-kr
sidebar:
  entries:
  - title: SANtricity CLIのドキュメント
    url: "/index.html"
  - title: 新機能
    url: "/whats-new.html"
  - section: get-started
  - section: commands-category
  - section: commands-a-z
  - title: 法的通知
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: はじめに
    links:
    - title: CLIの概要
      url: get-started/overview-format-commands.html
    - title: CLIコマンドの構造
      url: get-started/structure-of-a-cli-command.html
  - title: Eシリーズのドキュメント
    links:
    - title: Eシリーズシステムのドキュメント
      url: https://docs.netapp.com/us-en/e-series/index.html
    - title: SANtricity システムマネージャ 11.7
      url: https://docs.netapp.com/us-en/e-series-santricity/system-manager/index.html
    - title: SANtricity Unified Manager 5.
      url: https://docs.netapp.com/us-en/e-series-santricity/unified-manager/index.html
  - title: ツールのサポート
    links:
    - title: NetApp Interoperability Matrix を参照してください
      url: http://mysupport.netapp.com/matrix/
    - title: ネットアップナレッジベース
      url: https://kb.netapp.com/
    - title: Active IQ （ログインが必要）
      url: https://activeiq.netapp.com/?source=aiqnsspage
    - title: E シリーズ / SANtricity のダウンロード（ログインが必要）
      url: https://mysupport.netapp.com/site/downloads#E
product-family:
  name: E-Series
  repo: e-series-family
