---
permalink: whats-new.html 
sidebar: sidebar 
keywords: 'what"s new' 
summary: このトピックでは、SANtricity System Managerの最新リリースでのCLIコマンドとスクリプトコマンドの変更点を示します。 
---
= 新機能
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
このトピックでは、SANtricity System Managerの最新リリースでのCLIコマンドとスクリプトコマンドの変更点を示します。

[NOTE]
====
コマンドプロンプトでSMcliコマンドを実行する場合、バックスラッシュを追加で入力する必要があります (`\`) Windows OSを使用しているときに、入力ファイルまたは出力ファイルのファイルパス名にエスケープ文字として使用します。追加のバックスラッシュ (`\`uオプションでロールベースアクセス管理ユーザを指定し、SMcliをセキュアなHTTPSモードで使用する場合、を含める必要があります。例 `C:\\dir\\subdir\\filename`

====
[NOTE]
====
現在SANtricity 11.52以前を使用している場合は、従来のCLIを使用してSANtricity の最新バージョンにアップグレードできません。SANtricity 11.52からそれ以降のバージョンへのアップグレードは、SMcliを使用してのみ実行できます。

====


[[santricity-12-10]]
== SANtricity 12.10

以下の表は、リリース12.10におけるCLIおよびスクリプトコマンドの変更点を示しています。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-storagearray-host-io-protocol.html["ストレージアレイホストI/Oプロトコルの設定"]
 a| 
コマンドに `nvmeTcp`オプションを追加しました。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/create-raid-volume-automatic-drive-select.html["RAIDボリュームの作成（自動ドライブ選択）"]
 a| 
 `userLabel`パラメータの文字制限を30文字から60文字に拡大しました。


NOTE: SANtricity 12.10 から以前のバージョンへのダウングレードは、 `userLabel`パラメータが 30 文字を超える場合はサポートされていません。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/create-raid-volume-free-extent-based-select.html["RAIDボリュームの作成（空きエクステントベースの選択）"]
 a| 
 `userLabel`パラメータの文字制限を30文字から60文字に拡大しました。


NOTE: SANtricity 12.10 から以前のバージョンへのダウングレードは、 `userLabel`パラメータが 30 文字を超える場合はサポートされていません。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/create-raid-volume-manual-drive-select.html["RAIDボリュームの作成（手動ドライブ選択）"]
 a| 
 `userLabel`パラメータの文字制限を30文字から60文字に拡大しました。


NOTE: SANtricity 12.10 から以前のバージョンへのダウングレードは、 `userLabel`パラメータが 30 文字を超える場合はサポートされていません。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/create-volume-diskpool.html["ディスクプール内にボリュームを作成します"]
 a| 
 `userLabel`パラメータの文字制限を30文字から60文字に拡大しました。


NOTE: SANtricity 12.10 から以前のバージョンへのダウングレードは、 `userLabel`パラメータが 30 文字を超える場合はサポートされていません。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/recover-volume.html["RAIDボリュームをリカバリします"]
 a| 
 `userLabel`パラメータの文字制限を30文字から60文字に拡大しました。


NOTE: SANtricity 12.10 から以前のバージョンへのダウングレードは、 `userLabel`パラメータが 30 文字を超える場合はサポートされていません。

|===


[[santricity-12-00]]
== SANtricity 12.00

次の表は、リリース12.00におけるCLIコマンドとスクリプト コマンドの変更点をまとめたものです。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-storagearray-host-io-protocol.html["ストレージアレイホストI/Oプロトコルの設定"]
 a| 
コマンドを追加しました。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/show-storage-array-host-io-protocol.html["ストレージアレイホストI／Oプロトコル情報を表示する"]
 a| 
コマンドを追加しました。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/start-storagearray-externalkeymanagement-test.html["外部キー管理通信のテスト"]
 a| 
KMS通信テストの結果をコマンド出力に追加しました。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-storagearray-managementinterface.html["ストレージアレイ管理インターフェイスを設定します"]
 a| 
コマンドを削除しました。

|===


[[santricity-11-90]]
== SANtricity 11.90

次の表に、リリース11.90でのCLIコマンドとスクリプトコマンドの変更点を示します。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-autosupport-dispatch-limit.html["AutoSupportディスパッチサイズ制限の設定"]
 a| 
コマンドが追加されました



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/save-controller-arraymanagementcsr.html["コントローラアレイの保存管理CSR"]
 a| 
パラメータを追加しました `KeySize`。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/set-email-smtp-delivery-method.html["Eメール（SMTP）の配信方法を設定する"]
 a| 
パラメータを追加しました `destinationAddress`。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/show-storagearray-autosupport.html#examples["AutoSupport設定の表示"]
 a| 
コマンドの出力例にディスパッチサイズの制限と送信先Eメールアドレスが追加されました。



 a| 
https://docs.netapp.com/us-en/e-series-cli/commands-a-z/download-storagearray-keymanagementcertificate.html["storageArray keyManagementCertificateをダウンロード"]
 a| 
パラメータを追加しました `privateKeyFile`。

|===


[[santricity-11-81]]
== SANtricity 11.81

次の表に、リリース11.81でのCLIコマンドとスクリプトコマンドの変更点を示します。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
https://docs.netapp.com/us-en/e-series-cli/get-started/downloadable-smcli-parameters.html#identify-devices["デバイスの識別"]
 a| 
を追加しました `identifyDevices` パラメータ

|===


[[santricity-11-80]]
== SANtricity 11.80

次の表に、リリース11.80のCLIコマンドとスクリプトコマンドの変更点を示します。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
xref:./commands-a-z/save-check-vol-parity-job-errors.adoc[保存チェックボリュームパリティジョブのパリティエラー]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/start-check-vol-parity-job.adoc[ボリュームのパリティチェックジョブの開始]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/show-check-vol-parity-jobs.adoc[ボリュームパリティチェックジョブを表示します。]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/show-check-vol-parity-job.adoc[ボリュームのパリティチェックジョブを表示します。]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/stop-check-vol-parity-job.adoc[ボリュームのパリティチェックジョブを停止します。]
 a| 
コマンドが追加されました



 a| 
xref:./get-started/command-line-parameters.adoc[従来のコマンドラインパラメータ]
 a| 
を追加しました `-useLegacyTransferPort` パラメータ



 a| 
xref:./commands-a-z/autoconfigure-storagearray.adoc[ストレージアレイを自動設定します]
 a| 
blocksizeパラメータを追加



 a| 
xref:./commands-a-z/check-volume-parity.adoc[ボリュームのパリティをチェックします]
 a| 
廃止されたコマンドです。

|===


[[santricity-11-70-5]]
== SANtricity 11.70.5

リリース11.70.5では、CLIコマンドとスクリプトコマンドの変更はありません。



[[santricity-11-70-4]]
== SANtricity 11.70.4

次の表は、リリース11.70.4におけるCLIコマンドとスクリプトコマンドの変更点を示しています。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
xref:./get-started/downloadable-smcli-parameters.adoc[SMcliコマンドラインパラメータをダウンロードします]
 a| 
を追加しました `-t` および `-T` 多要素認証用のアクセストークンパラメータの説明。

|===


[[santricity-11-70-3]]
== SANtricity 11.70.3

次の表に、リリース11.70.3のCLIコマンドとスクリプトコマンドの変更点を示します。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
xref:./commands-a-z/start-diskpool-resourceprovisioning.adoc[ディスクプールリソースのプロビジョニングを開始します]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/start-volumegroup-resourceprovisioning.adoc[ボリュームグループリソースのプロビジョニングを開始します]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/start-diskpool-fullprovisioning.adoc[ディスクプールのフルプロビジョニングを開始します]
 a| 
「disableResourceProvisioning」パラメータ概要 を更新。



 a| 
xref:./commands-a-z/start-volumegroup-fullprovisioning.adoc[ボリュームグループのフルプロビジョニングを開始します]
 a| 
「disableResourceProvisioning」パラメータ概要 を更新。



 a| 
xref:./commands-a-z/recreate-storagearray-securitykey.adoc[外部セキュリティキーを再作成します]
 a| 
「deleteOldKey」パラメータが追加されました。



 a| 
xref:./commands-a-z/create-diskpool.adoc[ディスクプールを作成]
 a| 
「driveCount」パラメータ概要 を更新。

|===


[[santricity-11-70-2]]
== SANtricity 11.70.2の略

次の表は、リリース11.70.2のCLIコマンドとスクリプトコマンドの変更点を示しています。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
xref:./commands-a-z/create-snmpuser-username.adoc[SNMPv3 USMユーザを登録します]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/set-snmpuser-username.adoc[SNMPv3 USMユーザを更新します]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/show-allsnmpusers.adoc[SNMPv3 USMユーザを表示します]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/delete-snmpuser-username.adoc[SNMPv3 USMユーザの登録を解除します]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/create-snmptrapdestination.adoc[SNMPトラップの送信先を登録します]
 a| 
「username」および「engineid」パラメータを追加。



 a| 
xref:./commands-a-z/set-snmptrapdestination-trapreceiverip.adoc[SNMPトラップの送信先を更新してください]
 a| 
「username」および「engineid」パラメータを追加。



 a| 
xref:./commands-a-z/start-snmptrapdestination.adoc[SNMPトラップの送信先をテストします]
 a| 
「username」および「engineid」パラメータを追加。

|===


[[santricity-11-70-1]]
== SANtricity 11.70.1

次の表は、リリース11.70.1のCLIコマンドとスクリプトコマンドの変更点を示しています。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
xref:./commands-a-z/start-drive-erase.adoc[ドライブの消去を開始します]
 a| 
コマンドが追加されました



 a| 
xref:./commands-a-z/import-storagearray-securitykey-file.adoc[ストレージアレイのセキュリティキーをインポートします]
 a| 
「forceOverwrite」パラメータが追加されました。



 a| 
xref:./commands-a-z/set-controller-hostport.adoc[コントローラのホストポートのプロパティを設定します]
 a| 
「fecMode」パラメータを追加。



 a| 
xref:./commands-a-z/show-syslog-summary.adoc[syslog設定を表示します]
 a| 
「syslogFormat」パラメータが追加されました。



 a| 
xref:./commands-a-z/set-syslog.adoc[syslogを設定します]
 a| 
「syslogFormat」パラメータが追加されました。



 a| 
xref:./commands-a-z/set-emailalert.adoc[Eメールアラートを設定]
 a| 
「serverEncryption」、「ServerPort」、「serverUsername」、および「serverPassword」パラメータを追加しました。



 a| 
xref:./commands-a-z/show-emailalert-summary.adoc[Eメールアラート設定を表示します]
 a| 
SMTP暗号化'ポート'およびクレデンシャル・パラメータ・データが追加されました



 a| 
xref:./commands-a-z/recover-volume.adoc[RAIDボリュームをリカバリします]
 a| 
blocksizeパラメータを追加

|===


[[santricity-11-70]]
== SANtricity 11.70

次の表は、リリース11.70のCLIコマンドとスクリプトコマンドの変更点を示しています。

[cols="2*"]
|===
| コマンドを実行します | 概要 of Changeの略 


 a| 
xref:./commands-a-z/download-storagearray-firmware.adoc[ストレージアレイのファームウェア/ NVSRAMをダウンロードします]
 a| 
「healthCheckNeedsAttnOverride」パラメータが追加されました。



 a| 
xref:./commands-a-z/create-volume-diskpool.adoc[ディスクプール内にボリュームを作成します]
 a| 
raidLevelパラメータが追加されました



 a| 
xref:./commands-a-z/enable-storagearray-externalkeymanagement-file.adoc[外部セキュリティキー管理を有効にします]
 a| 
saveFileパラメータを追加



 a| 
xref:./commands-a-z/disable-storagearray-externalkeymanagement-file.adoc[外部セキュリティキー管理を無効にします]
 a| 
saveFileパラメータを追加



 a| 
xref:./commands-a-z/recover-volume.adoc[RAIDボリュームをリカバリします]
 a| 
hostUnmapEnabled'パラメータが追加されました。

|===