---
permalink: get-started/command-line-parameters.html 
sidebar: sidebar 
keywords: legacy, command line, parameters 
summary: SANtricity OS 11.40リリースでは、Webサービスが組み込まれたE2800およびE5700コントローラ向けに、セキュアなHTTPSプロトコルを使用してコマンドラインを操作する機能が導入されました。これらのコントローラでは、必要に応じてSYMbolプロトコルを使用してコマンドラインを操作することもできます。 
---
= 従来のコマンドラインパラメータ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity OS 11.40リリースでは、Webサービスが組み込まれたE2800およびE5700コントローラ向けに、セキュアなHTTPSプロトコルを使用してコマンドラインを操作する機能が導入されました。これらのコントローラでは、必要に応じてSYMbolプロトコルを使用してコマンドラインを操作することもできます。



== 11.53以前のコマンドラインパラメータ

SYMbolプロトコルは、E2700およびE5600コントローラでサポートされる唯一のプロトコルです。既存のスクリプトを引き続き使用できるようにし、移行の手間を最小限に抑えるために、CLIのオプションと構文はできるだけそのままにしてあります。ただし、E2800およびE5700コントローラのセキュリティ、認証、AutoSupport 、アラートメッセージの機能にはいくつかの変更があるため、これらのコントローラでは一部のCLI構文が廃止されています。一部の構文は、E2800またはE5700で新しいHTTPSプロトコルが使用される場合にのみ廃止されます。

「* https *」クライアントタイプにのみ適用される新しいパラメータについては、E2800またはE5700コントローラにのみ適用されます。

[cols="2*"]
|===
| パラメータ | 定義（ Definition ） 


 a| 
-clientType
 a| 
この引数は、適切なスクリプトエンジンを強制的に作成します。このパラメータはオプションで、次のいずれかの値を指定します。

* '*auto*'-適切なスクリプト・エンジン・タイプを検出するために'デバイス検出が自動的に実行されます
* *https*- RESTベースのスクリプトエンジンが作成されます。
* `*symbol*`-シンボルベースのスクリプトエンジンが作成されます。




 a| 
「-u」
 a| 
このパラメータには'_username_'変数を指定しますユーザ名は'*https*'クライアント・タイプにのみ必要ですこの引数は'*symbol*'クライアント・タイプには適用されず'無視されます

username引数を指定すると、デバイス検出が実行されて正しいクライアント・タイプ（「* https *」対）が決定されます「* symbol *」）を参照してください。



 a| 
「-P」
 a| 
この引数には次の2つの引数のいずれかが必要です。

* `_password_file`-認証に使用するパスワードを格納します
* `-`(one Dash)- stdin`からパスワードを読み込みます


この引数の追加は'*https*'クライアント・タイプと'*symbol*'クライアント・タイプのどちらが使用されているかにかかわらず'すべてのコントローラに適用されます



 a| 
「-k」
 a| 
このオプション引数を指定すると'*https*'クライアントは安全でないモードで動作しますつまり、ストレージアレイの証明書は検証されません。デフォルトでは、省略すると適切な認証が実行されます。この引数は'*symbol*'クライアント・タイプには適用されず'無視されます

|===


== E2700またはE5600コントローラにのみ該当するコマンドラインパラメータ

E2700およびE5600コントローラにはアラート管理機能が組み込まれていないため、以下のコマンドラインパラメータを使用できます。これらのパラメータは、E2800またはE5700コントローラには該当しません。

[cols="2*"]
|===
| パラメータ | 定義（ Definition ） 


 a| 
「- A」
 a| 
簡易ネットワーク管理プロトコル（SNMP）トラップの送信先またはアラートの送信先のEメールアドレスを追加します。

* SNMPトラップの送信先を追加すると、SNMPコミュニティがトラップのコミュニティ名として自動的に定義され、「* host *」はトラップの送信先システムのIPアドレスまたはドメインネームサーバ（DNS）ホスト名です。
* アラートの送信先の電子メールアドレスを追加する場合、「* email-address *」は、警告メッセージの送信先となる電子メールアドレスです。


[NOTE]
====
このコマンドラインオプションは、E2800とE5700のストレージアレイに対しては廃止されています。RESTful API、SANtricity システムマネージャ、またはcURLコマンドを使用してください。

====


 a| 
「-m」と入力します
 a| 
Eメールアラート通知の送信元であるEメールサーバのホスト名またはIPアドレスを指定します。

[NOTE]
====
このコマンドラインオプションは、E2800とE5700のストレージアレイに対しては廃止されています。RESTful API、SANtricity システムマネージャ、またはcURLコマンドを使用してください。

====


 a| 
-s（小文字）
 a| 
に'-d'パラメータとともに使用した場合の構成ファイルのアラート設定を示します

[NOTE]
====
このコマンドラインオプションは、E2800とE5700のストレージアレイに対しては廃止されています。RESTful API、SANtricity システムマネージャ、またはcURLコマンドを使用してください。

====


 a| 
`-x`(小文字)
 a| 
SNMPトラップの送信先またはアラートの送信先Eメールアドレスを削除します。「_community_`」はトラップのSNMPコミュニティ名で、「_host_」はトラップの送信先システムのIPアドレスまたはDNSホスト名です。

[NOTE]
====
このコマンドラインオプションは、E2800とE5700のストレージアレイに対しては廃止されています。RESTful API、SANtricity システムマネージャ、またはcURLコマンドを使用してください。

====
|===


== symbolクライアントタイプで実行されているすべてのコントローラに適用されるコマンドラインパラメータ

[cols="2*"]
|===
| パラメータ | 定義（ Definition ） 


 a| 
「R」（大文字）
 a| 
パスワードのユーザロールを定義します。ロールには次のいずれかを指定できます。

* `*admin*`--ユーザーはストレージ・アレイの構成を変更する権限を持っています
* *monitor*--ユーザーにはストレージアレイの構成を表示する権限がありますが'変更はできません


'*-R*'パラメータは'*–p *'パラメータとともに使用する場合にのみ有効ですこのパラメータは'ストレージ・アレイのパスワードを定義することを指定します

「*-R*」パラメータは、ストレージ・アレイでデュアル・パスワード機能が有効になっている場合にのみ必要です。これらの条件では'*-R*'パラメータは不要です

* ストレージアレイでデュアルパスワード機能が有効になっていません。
* ストレージアレイにAdminロールが1つだけ設定されていて、Monitorロールが設定されていない。


|===


== すべてのコントローラおよびすべてのクライアントタイプに適用可能なコマンドラインパラメータ

[cols="2*"]
|===
| パラメータ | 定義（ Definition ） 


 a| 
`_host-name-or -ip-address_`
 a| 
帯域内管理ストレージ・アレイまたは帯域外管理ストレージ・アレイのホスト名またはインターネット・プロトコル（IP）アドレス（`_xxx.xxx.xxx.xxx）を指定します

* ホストからインバンド・ストレージ管理を使用してストレージ・アレイを管理する場合'複数のストレージ・アレイがホストに接続されている場合は'-n'パラメータまたは-w'パラメータを使用する必要があります
* 各コントローラ上のイーサネット接続を介したアウトオブバンドストレージ管理を使用してストレージアレイを管理する場合は、コントローラの「_host-name-or -ip-address_」を指定する必要があります。
* 以前にEnterprise Management Windowでストレージ・アレイを設定済みの場合は'-n'パラメータを使用して'ユーザーが指定した名前でストレージ・アレイを指定できます
* 以前にEnterprise Management Windowでストレージアレイを設定済みの場合は、World Wide Identifier（WWID）を使用してストレージアレイを指定できます。




 a| 
「- A」
 a| 
構成ファイルにストレージアレイを追加します。'-a'パラメータに'_host-name-or -ip-address_'を指定しない場合'自動検出は'ローカル・サブネットをスキャンしてストレージ・アレイを検出します



 a| 
「-c」
 a| 
指定したストレージアレイで実行するスクリプトコマンドを入力することを示します。各コマンドをセミコロン(`;`)で終了します。同じコマンド行に複数の`-c'パラメータを配置することはできません「-c」パラメータの後には、複数のスクリプトコマンドを含めることができます。



 a| 
d`
 a| 
スクリプト構成ファイルの内容を表示します。ファイルの内容は、「_storage-system-name host_name1 host_name2_`」の形式になります



 a| 
「-e」と入力します
 a| 
構文チェックを実行せずにコマンドを実行します。



 a| 
F（大文字）
 a| 
すべてのアラートの送信元となるEメールアドレスを指定します。



 a| 
`-f`(小文字)
 a| 
指定したストレージアレイで実行するスクリプトコマンドを含むファイルの名前を指定します。'-f'パラメータはどちらもスクリプト・コマンドを実行するためのものであるという点で'-c'パラメータと似ています-cパラメータは'個のスクリプト・コマンドを実行します-fパラメータは'スクリプト・コマンドのファイルを実行しますデフォルトでは、ファイルでスクリプトコマンドを実行したときに発生したエラーは無視され、ファイルは引き続き実行されます。この動作をオーバーライドするには、スクリプトファイルで「set session errorAction=stop」コマンドを使用します。



 a| 
「-g」
 a| 
Eメール送信者の連絡先情報が格納されたASCIIファイルを指定します。この連絡先はすべてのEメールアラート通知に記載されます。区切り記号や書式設定のない、テキストのみのASCIIファイルを指定する必要があります。「userdata.txt」ファイルが存在する場合は、「-g」パラメータは使用しないでください。



 a| 
「 -h 」と入力します
 a| 
ストレージアレイの接続先であるSNMPエージェントを実行しているホストの名前を指定します。「-h」パラメータは、次のパラメータとともに使用します。

* 「- A」
* 「-x」と入力します




 a| 
「-i」（大文字）
 a| 
Eメールアラート通知に含める情報のタイプを指定します。次の値を選択できます。

* eventOnly-イベント情報のみが電子メールに含まれています
* profile --イベントとアレイのプロファイル情報が電子メールに含まれています


電子メール配信の頻度は'-qパラメータを使用して指定できます



 a| 
「-i」(小文字)
 a| 
既知のストレージアレイのIPアドレスを表示します。「-i」パラメータは、「-d」パラメータとともに使用します。ファイルの内容の形式は'_storage-system-name IP-address1 ipAddress2_'です



 a| 
「-n」
 a| 
スクリプトコマンドを実行するストレージアレイの名前を指定します。この名前は'_host-name-or -ip-address_'を使用する場合は省略可能ですストレージ・アレイの管理にインバンド方式を使用している場合'複数のストレージ・アレイが指定されたアドレスでホストに接続されている場合は'-n'パラメータを使用する必要があります「_host-name-or -ip-address_」が使用されていない場合、ストレージアレイ名は必須です。Enterprise Management Windowで使用するように設定したストレージアレイの名前（構成ファイルに定義されている名前）が、設定済みの他のストレージアレイの名前と重複しないようにしてください。



 a| 
「-o」と入力します
 a| 
スクリプトコマンドの実行で生成されるすべての出力テキストのファイル名を指定します。-o'パラメータは、次のパラメータとともに使用します。

* 「-c」
* 「 -f 」


出力ファイルを指定しない場合、出力テキストは標準出力（stdout）に出力されます。このパラメータが設定されているかどうかに関係なく、スクリプトコマンド以外のコマンドからの出力はすべてstdoutに送信されます。



 a| 
「 -p 」
 a| 
コマンドを実行するストレージアレイのパスワードを定義します。次の場合、パスワードは必要ありません。

* ストレージアレイにパスワードが設定されていません。
* パスワードは、実行しているスクリプトファイルで指定します。
* パスワードを指定するには'-c'パラメータと次のコマンドを使用します


[listing]
----
set session password=password
----


 a| 
「-P」
 a| 
この引数には次の2つの引数のいずれかが必要です。

* `_password_file`-認証に使用するパスワードを格納します
* `-`(Dash)- stdin`からパスワードを読み込みます


この引数の追加は'*https*'クライアント・タイプと'*symbol*'クライアント・タイプのどちらが使用されているかにかかわらず'すべてのコントローラに適用されます



 a| 
「-q」と入力します
 a| 
イベント通知を受信する頻度およびイベント通知で返される情報のタイプを指定します。重大イベントについては、最低でも基本的なイベント情報を含むEメールアラート通知が生成されます。これらの値は'-qパラメータに有効です

* everyEvent`--すべての電子メールアラート通知と共に情報が返される。
* `2`--情報は2時間ごとに何回も返されない。
* `4`--情報は4時間ごとに何回も返されない。
* `8`--情報は8時間ごとに何度も返されない。
* 12日--情報は12時間ごとに1回しか返されません。
* 24日--情報は24時間ごとに1回しか返されません。


-iパラメータを使用すると'メール・アラート通知に含まれる情報のタイプを指定できます

* 「-i」パラメータを「eventOnly」に設定した場合、「-q」パラメータに有効な値は「everyEvent」のみです。
* 「-i」パラメータを「profile」値または「supportbundle」値に設定した場合、この情報は、「-q」パラメータで指定された頻度で電子メールに含まれます。




 a| 
「-quick`」
 a| 
単一行の処理に要する時間を短縮します。単一行操作の例としては'recreate snapshot volumeコマンドがありますこのパラメータは、コマンドの実行中にバックグラウンドプロセスを実行しないことで時間を短縮します。単一行の処理が複数含まれる処理には、このパラメータを使用しないでください。このコマンドを多用した場合、コントローラの処理能力を超える数のコマンドが実行されてオーバーランが発生し、処理が失敗する可能性があります。また、通常バックグラウンドプロセスから収集されるステータスおよび設定の更新をCLIで使用することはできません。このパラメータを指定すると、バックグラウンド情報に依存する処理が失敗します。



 a| 
「-S」（大文字）
 a| 
スクリプトコマンドの実行時に表示される、進捗状況を示す情報メッセージが表示されないようにします。（この情報メッセージはサイレントモードとも呼ばれます）。 このパラメータを指定すると、次のメッセージは表示さ

* 構文チェックを実行しています
* 構文チェックが完了しました
* 「スクリプトの実行」
* 「スクリプトの実行が完了しました」
* SMcliは正常に完了しました




 a| 
`-useLegacyTransferPort`
 a| 
転送ポートをに設定します。 `8443` デフォルトの代わりに `443`。



 a| 
「-v」
 a| 
-dパラメータとともに使用した場合'構成ファイル内の既知のデバイスの現在のグローバルステータスを表示します



 a| 
「-w」
 a| 
ストレージアレイのWWIDを指定します。このパラメータは'-n'パラメータに代わるものです既知のストレージ・アレイのWWIDを表示するには'-d'パラメータとともに-w'パラメータを使用しますファイルの内容の形式は、「_storage-system-name worldwide ID IP-address1 IP-address2_」です



 a| 
`-X (大文字)
 a| 
ストレージアレイを構成から削除します。



 a| 
「-?`」
 a| 
CLIコマンドの使用方法を表示します。

|===