---
permalink: get-started/detailed-error-reporting.html 
sidebar: sidebar 
keywords: detailed, error, report 
summary: CLIで発生したエラーから収集されたデータはファイルに書き込まれます。 
---
= SANtricity CLIの詳細なエラーレポートについて学ぶ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
CLIで発生したエラーから収集されたデータはファイルに書き込まれます。

CLIでの詳細なエラーレポートは、次のように機能します。

* 実行中のCLIコマンドとスクリプトコマンドを異常終了させる必要がある場合は、CLIの終了前にエラーデータが収集されて保存されます。
* CLIは、標準のファイル名にデータを書き込むことによってエラーデータを保存します。
* CLIはデータを自動的にファイルに保存します。エラーデータの保存には、特殊なコマンドラインオプションは必要ありません。
* エラーデータをファイルに保存するための操作は必要ありません。
* CLIには、エラーデータが含まれる既存バージョンのファイルが上書きされないようにするためのプロビジョニングはありません。


エラー処理では、エラーは次の2つのタイプとして表示されます。

* 入力による端末エラーまたは構文エラー。
* 操作上のエラーの結果として発生した例外。


CLIは、どちらかのタイプのエラーを検出すると、そのエラーを説明する情報をコマンドラインに直接書き込み、戻りコードを設定します。リターンコードによっては、CLIは、エラーの原因となった端末に関する追加情報 を書き込む場合もあります。また、想定していたコマンド構文に関する情報も書き込まれ、入力した構文のエラーを特定する上で役立ちます。

コマンドの実行中に例外が発生した場合、CLIはエラーをキャプチャします。コマンド処理の最後に（コマンド処理情報がコマンドラインに書き込まれたあと）、CLIはエラー情報を自動的にファイルに保存します。

エラー情報を保存するファイルの名前は「exprpt.txt」です。CLIは'devmgr.datadir'システム・プロパティによって指定されたディレクトリに'exprpt.txt'ファイルを配置しようとします何らかの理由でCLIが'devmgr.datadir'で指定されたディレクトリにファイルを配置できない場合'CLIはCLIが実行されているディレクトリに'exprpt.txt'ファイルを保存しますファイル名や場所は変更できません。「exprpt.txt」ファイルは、例外が発生するたびに上書きされます。情報を"exprpt.txt"ファイルに保存する場合は'情報を新しいファイルまたは新しいディレクトリにコピーする必要があります
