---
permalink: get-started/downloadable-smcli-parameters.html 
sidebar: sidebar 
keywords: downloadable, smcli, command line, parameters, identify, devices, SAML, multifactor, authentication, https, certificate, array, 
summary: SANtricity OS 11.60以降のリリースでは、SANtricityシステムマネージャからHTTPベースバージョンのCLI（Secure CLIまたはSMcliとも呼ばれる）を直接ダウンロードしてインストールできます。 
---
= ダウンロード可能なSMcliコマンドラインパラメータ
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SANtricity OS 11.60以降のリリースでは、SANtricityシステムマネージャからHTTPベースバージョンのCLI（「Secure CLI」またはSMcliとも呼ばれます）を直接ダウンロードしてインストールできます。



== 11.60以降のダウンロード可能なSMcliコマンドラインパラメータ

SMcliは、E4000、EF600、EF300、E5700、EF570、E2800、EF280、EF300C、EF600Cの各コントローラでダウンロード可能です。SANtricityシステムマネージャからSMcliをダウンロードするには、*[設定]*[システム]*および*[アドオン]*[コマンドラインインターフェイス]*を選択します。


NOTE: CLIコマンドを実行する管理システムに、Java Runtime Environment（JRE）バージョン8以降がインストールされている必要があります。

以前のバージョンのSMcliと同様、SANtricity System Managerからダウンロード可能なSMcliには、固有のパラメータセットがあります。SANtricity OS 11.53以前のリリースでのコマンドラインパラメータの使用方法については、を参照してください link:https://docs.netapp.com/us-en/e-series-cli/get-started/command-line-parameters.html["従来のコマンドラインパラメータ"]。



=== 多要素認証

SAML（Security Assertion Markup Language）が有効になっている場合は、CLIで使用できるのはアクセストークンのみです。SAMLが有効になっていない場合は、ユーザ名とパスワード、またはアクセストークンを使用できます。アクセストークンは、SANtricity システムマネージャを使用して生成できます。

[cols="2*"]
|===
| パラメータ | 定義（ Definition ） 


 a| 
`-t`
 a| 
ストレージアレイでの認証に使用するアクセストークンを定義します。アクセストークンは、ユーザ名とパスワードの入力に代わるものです。



 a| 
`-T` （大文字）
 a| 
この引数には次の2つの引数のいずれかが必要です。

* `access_token-file` -認証に使用するアクセストークンが含まれます
* `-(dash)` - stdinからアクセストークンを読み取ります




 a| 
「-u」
 a| 
このパラメータは、とともに使用します `_username_` 変数（Variable）：このパラメータは、アクセストークンを使用しない場合に必要です。



 a| 
「 -p 」
 a| 
コマンドを実行するストレージアレイのパスワードを定義します。次の場合、パスワードは必要ありません。

* ストレージアレイにパスワードが設定されていません。
* パスワードは、実行しているスクリプトファイルで指定します。




 a| 
`-P` （大文字）
 a| 
この引数には次の2つの引数のいずれかが必要です。

* `_password_file`-認証に使用するパスワードを格納します
* `-`(one Dash)- stdin`からパスワードを読み込みます


|===


=== 一般的なhttpsモードのコマンドラインパラメータ

ダウンロード可能なSMcliは、httpsモードのみをサポートしています。httpsモードで一般的に使用されるコマンドラインパラメータを次に示します。

[cols="2*"]
|===
| パラメータ | 定義（ Definition ） 


 a| 
`_host-name-or -ip-address_`
 a| 
ホスト名またはインターネットプロトコル（IP）アドレスを指定します (`_xxx.xxx.xxx.xxx_`）を使用できます。

各コントローラのイーサネット接続を使用してアウトオブバンドストレージの管理を管理する場合は、を指定する必要があります `_host-name-or-IP-address_` をクリックします。



 a| 
「-k」
 a| 
このオプションの引数では、を使用できます `*https*` クライアントをセキュアでないモードで実行してください。つまり、ストレージアレイの証明書は検証されません。省略した場合、デフォルトで適切な検証が実行されます。


NOTE: ストレージアレイ証明書の管理に関する追加情報 については、を参照してください <<storedcertificates,保存されている証明書のコマンドラインパラメータの管理>>。



 a| 
「-e」と入力します
 a| 
構文チェックを実行せずにコマンドを実行します。



 a| 
`-L` （大文字）
 a| 
ダウンロード可能なSMcliに関する法的通知を表示します。



 a| 
「-n」
 a| 
スクリプトコマンドを実行するローカルに格納されるラベルを指定します。を使用する場合、これはオプションです `_host-name-or-IP-address_`。を使用する場合は、ローカルに保存されたラベルが必要です `_host-name-or-IP-address_` は使用されません。


NOTE: ローカルに格納されたラベルを使用したストレージアレイの管理に関する追加情報 の詳細については、を参照してください <<managearrays,格納されているアレイのコマンドラインパラメータの管理>>。



 a| 
「-o」と入力します
 a| 
スクリプトコマンドの実行で生成されるすべての出力テキストのファイル名を指定します。-o'パラメータは、次のパラメータとともに使用します。

* 「-c」
* 「 -f 」


出力ファイルを指定しない場合、出力テキストは標準出力になります  `stdout`）。スクリプトコマンドではないコマンドからの出力は、すべてに送信されます `stdout`このパラメータが設定されているかどうかは関係ありません。



 a| 
「-S」（大文字）
 a| 
スクリプトコマンドの実行時に表示される、進捗状況を示す情報メッセージが表示されないようにします。（この情報メッセージはサイレントモードとも呼ばれます）。 このパラメータを指定すると、次のメッセージは表示さ

* 構文チェックを実行しています
* 構文チェックが完了しました
* 「スクリプトの実行」
* 「スクリプトの実行が完了しました」
* SMcliは正常に完了しました




 a| 
`-version`
 a| 
ダウンロード可能なSMcliのバージョンを表示します



 a| 
「-?`」
 a| 
CLIコマンドの使用方法を表示します。

|===


=== 格納されているアレイの管理

次のコマンド・ライン・パラメータでは、ローカルに保存されたラベルを使用して、格納されたアレイを管理できます。


NOTE: ローカルに格納されたラベルが、SANtricity システムマネージャに表示される実際のストレージアレイ名と一致しない場合があります。

[cols="2*"]
|===
| パラメータ | 定義（ Definition ） 


 a| 
`SMcli storageArrayLabel show all`
 a| 
ローカルに保存されているすべてのラベルとその関連アドレスを表示します



 a| 
`SMcli storageArrayLabel show label <LABEL>`
 a| 
ローカルに保存されているというラベルに関連付けられているアドレスが表示されます `<LABEL>`



 a| 
`SMcli storageArrayLabel delete all`
 a| 
ローカルに保存されたすべてのラベルを削除します



 a| 
`SMcli storageArrayLabel delete label <LABEL>`
 a| 
ローカルに保存されたという名前のラベルを削除します `<LABEL>`



 a| 
`SMcli <host-name-or-IP-address> [host-name-or-IP-address] storageArrayLabel add label <LABEL>`
 a| 
* ローカルに保存されたラベルを名前とともに追加します `<LABEL>` 指定したアドレスを含む
* アップデートは直接サポートされていません。更新するには、ラベルを削除してから再度追加してください。



NOTE: SMcliは、ローカルに保存されたラベルを追加する場合、ストレージアレイに接続しません。

|===
[cols="2*"]
|===
| パラメータ | 定義（ Definition ） 


 a| 
`SMcli localCertificate show all`
 a| 
ローカルに保存されているすべての信頼された証明書



 a| 
`SMcli localCertificate show alias <ALIAS>`
 a| 
ローカルに保存されている信頼された証明書とエイリアスを表示します `<ALIAS>`



 a| 
`SMcli localCertificate delete all`
 a| 
ローカルに保存されている信頼された証明書をすべて



 a| 
`SMcli localCertificate delete alias <ALIAS>`
 a| 
ローカルに保存されている信頼された証明書をエイリアスで削除します `<ALIAS>`



 a| 
`SMcli localCertificate trust file <CERT_FILE> alias <ALIAS>`
 a| 
* 信頼できる証明書をエイリアスで保存します `<ALIAS>`
* 信頼される証明書は、Webブラウザなどの別の操作でコントローラからダウンロードされます




 a| 
`SMcli <host-name-or-IP-address> [host-name-or-IP-address] localCertificate trust`
 a| 
* 各アドレスに接続し、信頼された証明書ストアに返された証明書を保存します
* 指定したホスト名またはIPアドレスは、この方法で保存された各証明書のエイリアスとして使用されます
* このコマンドを実行する前に、コントローラの証明書が信頼できるものであることをユーザが確認する必要があります
* 最高のセキュリティを実現するには、ファイルを受け取るtrustコマンドを使用して、証明書がユーザ検証と実行中の間で変更されないようにする必要があります


|===


=== デバイスの識別

次のコマンドラインパラメータを使用すると、ホストが認識できるすべての該当するデバイスの情報を表示できます。


NOTE: SANtricity 11.81リリース以降のSMcli `identifyDevices` パラメータは、以前にSMdevicesツールで使用できた機能を置き換えます。

[cols="2*"]
|===
| パラメータ | 定義（ Definition ） 


 a| 
`identifyDevices`
 a| 
ストレージアレイに関連付けられているすべてのSCSIネイティブブロックデバイスを検索します。検出された各デバイスについて、では、ネイティブOS固有のデバイス名、関連付けられているストレージアレイ、ボリューム名、LUN情報など、さまざまな情報が報告されます。

|===


==== 例

次の例を参照してください。 `-identifyDevices` LinuxおよびWindowsオペレーティングシステム内のパラメータ。

.Linux の場合
[listing]
----
ICTAE11S05H01:~/osean/SMcli-01.81.00.10004/bin # ./SMcli -identifyDevices
  <n/a> (/dev/sg2) [Storage Array ictae11s05a01, Volume 1, LUN 0, Volume ID <600a098000bbd04f00001c7365426b58>, Alternate Path (Controller-A): Non owning controller - Active/Non-optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  /dev/sdb (/dev/sg3) [Storage Array ictae11s05a01, Volume Access, LUN 7, Volume ID <600a098000bbcdd3000002005a731d29>]
  <n/a> (/dev/sg4) [Storage Array ictae11s05a01, Volume 1, LUN 0, Volume ID <600a098000bbd04f00001c7365426b58>, Preferred Path (Controller-B): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  /dev/sdc (/dev/sg5) [Storage Array ictae11s05a01, Volume Access, LUN 7, Volume ID <600a098000bbcdd3000002005a731d29>]
SMcli completed successfully.
----
.Windows の場合
[listing]
----
PS C:\Users\Administrator\Downloads\SMcli-01.81.00.0017\bin> .\SMcli -identifyDevices
  \\.\PHYSICALDRIVE1 [Storage Array ICTAG22S08A01, Volume Vol1, LUN 1, Volume ID <600a0980006cee060000592e6564fa6a>, Preferred Path (Controller-B): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  \\.\PHYSICALDRIVE2 [Storage Array ICTAG22S08A01, Volume Vol2, LUN 2, Volume ID <600a0980006ce727000001096564f9f5>, Preferred Path (Controller-A): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  \\.\PHYSICALDRIVE3 [Storage Array ICTAG22S08A01, Volume Vol3, LUN 3, Volume ID <600a0980006cee06000059326564fa76>, Preferred Path (Controller-B): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
  \\.\PHYSICALDRIVE4 [Storage Array ICTAG22S08A01, Volume Vol4, LUN 4, Volume ID <600a0980006ce7270000010a6564fa01>, Preferred Path (Controller-A): Owning controller - Active/Optimized, Preferred Path Auto Changeable: Yes, Implicit Failback: Yes]
SMcli completed successfully.
----


==== その他の注意事項

* x86-64プラットフォームを実行するLinuxおよびWindowsオペレーティングシステムで、SCSIベースのホストインターフェイスのみで互換性があります。
+
** NVMeベースのホストインターフェイスはサポートされません。


* 。 `identifyDevices` パラメータでは、OSレベルでの再スキャンは原因されません。OSによって認識されている既存のデバイスを反復します。
* を実行するための十分なユーザ権限が必要です。 `identifyDevices` コマンドを実行します
+
** これには、OSネイティブのブロックデバイスからの読み取りとSCSI Inquiryコマンドの実行が含まれます。



