---
permalink: get-started/firmware-compatibility-levels.html 
sidebar: sidebar 
keywords: firmware, compatibility, levels 
summary: スクリプトコマンドとコマンドパラメータは、すべてのバージョンのコントローラファームウェアで実行されるわけではありません。 
---
= ファームウェアの互換性レベル
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


スクリプトコマンドとコマンドパラメータは、すべてのバージョンのコントローラファームウェアで実行されるわけではありません。以降のセクションのスクリプトコマンドでは、スクリプトコマンドを実行できる最小ファームウェアレベルを示します。スクリプト・コマンドでは'ファームウェア・レベルは最小ファームウェア・レベルという見出しの下に表示されます 次に、ファームウェアレベルに関する情報の解釈方法について説明します。

* スクリプトコマンドにコントローラファームウェアの最小レベルがリストされていない場合、そのスクリプトコマンドと、スクリプトコマンドに関連付けられているすべてのパラメータは、どのレベルのコントローラファームウェアでも実行できます。
* コントローラファームウェアの番号に説明情報がない場合、コントローラファームウェアレベルの環境 スクリプトコマンド全体と、そのスクリプトコマンドのすべてのパラメータが含まれています。
* パラメータに関連付けられたコントローラファームウェアの番号は、そのパラメータを実行できるコントローラファームウェアの最小レベルを示します。


[NOTE]
====
コントローラファームウェアの最小レベルは、コマンドをリリースするソフトウェアによるサポート、および用法を判別するすべてのストレージ管理ソフトウェアによるサポートを示します。CLIのサポート機能は、使用しているハードウェアによって異なります。サポートされていないコマンドを入力すると、エラーメッセージが表示されます。

====


== ファームウェアの互換性レベルの例

create hostGroupコマンドには'次のセクションがあります

*最小ファームウェアレベル*

8.10で

このレベルは、スクリプトコマンド全体がコントローラファームウェアのバージョン8.10以上で実行されることを示します。

create ssdCacheコマンドには'次のセクションがあります

*最小ファームウェアレベル*

7.84

8.20.11 -「* securityType *」パラメータが追加されました。

これらの表記は'スクリプト・コマンドと'*securityType*'を除くすべてのパラメータが'コントローラ・ファームウェアのバージョン7.84以上で実行されることを示しています`*securityType*`パラメータは、コントローラファームウェアのバージョン8.20_M3以上で実行されます。
