---
permalink: get-started/formatting-cli-commands.html 
sidebar: sidebar 
keywords: format, rules, cli, commands 
summary: 入力した値または名前に基づいて、CLIコマンドには特定の形式ルールが適用されます。 
---
= CLIコマンドの表記規則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
入力した値または名前に基づいて、CLIコマンドには特定の形式ルールが適用されます。



== CLI形式のルール

Windows、Linux、またはSolarisオペレーティングシステムでCLIコマンドおよびスクリプトコマンドを実行する場合は、名前またはラベルの一部として使用される二重引用符（""）に特別な考慮が必要です。

二重引用符（""）が名前または値の一部である場合は、各二重引用符の前にバックスラッシュ（\）を挿入する必要があります。

例：

[listing]
----
-c "set storageArray userLabel=\"Engineering\";"
----
この例では、「"Engineering"」がストレージアレイ名です。

2つ目の例は次のとおりです。

[listing]
----
-n \"My\"_Array
----
この例では、「My」_Arrayはストレージアレイの名前です。

二重引用符（""）は、スクリプトコマンド内で文字列（文字列リテラルとも呼ばれます）の一部として使用することはできません。たとえば、次の文字列を入力してストレージアレイ名を「"Finance" Array」に設定することはできません。

[listing]
----
-c "set storageArray userLabel=\"\"Finance\"Array\";"
----
Windowsオペレーティングシステムでは、名前の前後に二重引用符（""）を使用しない場合は、特殊なスクリプト文字の前にそれぞれキャレット（｛キャレット｝）を挿入する必要があります。特殊文字には、｛キャレット｝、|、<、>を使用できます。

端末「-n」、「-o」、「-f」、「-p」とともに使用する場合は、特殊なスクリプト文字の前にそれぞれキャレットを挿入します。たとえば、ストレージアレイ「CLI>CLIENT」を指定するには、次の文字列を入力します。

[listing]
----
-n CLI^>CLIENT
----
スクリプトコマンドの文字列リテラルで使用する場合は、特殊なスクリプト文字の前にそれぞれキャレット（｛キャレット｝）を1つずつ挿入します。たとえば、ストレージアレイの名前を「FINANCE_|_PAYROLL」に変更するには、次の文字列を入力します。

[listing]
----
-c "set storageArray userLabel=\"FINANCE_^|_PAYROLL\";"
----
[NOTE]
====
Windows OSを使用する環境でSMcliコマンドをコマンドプロンプトから実行する場合、入力ファイルまたは出力ファイルのファイルパス名にエスケープ文字としてバックスラッシュ（「\」）を追加する必要があります。ロールベースアクセス管理ユーザを指定する-uオプションを提供して、セキュアなhttpsモードでSMcliを使用する場合は、バックスラッシュ（「\」）を追加する必要があります。* 例： *

[listing]
----
C:\\dir\\subdir\\filename
----
====