---
permalink: get-started/formatting-rules-for-script-commands.html 
sidebar: sidebar 
keywords: format, rules, script, commands 
summary: 特定のスクリプトコマンドに固有の構文については、各スクリプトコマンド概要 の最後にある「メモ」セクションで説明しています。 
---
= スクリプトコマンドの形式ルール
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
特定のスクリプトコマンドに固有の構文については、各スクリプトコマンド概要 の最後にある「メモ」セクションで説明しています。

*大文字と小文字の区別*--スクリプトコマンドでは大文字と小文字は区別されません。スクリプトコマンドは、小文字、大文字、または大文字と小文字を混在させて入力できます。（次のコマンドの説明では、コマンド名を読みやすくし、コマンドの目的を理解しやすくするために、大文字と小文字を混在させています）。

*spaces *--コマンドの説明に示されているように、スクリプトコマンドにスペースを入力する必要があります。

*角括弧*--角括弧は、次の2つの方法で使用されます。

* コマンド構文の一部として。
* パラメータがオプションであることを示すため。パラメータ値を角かっこで囲む必要があるかどうかは、各パラメータの概要 で説明されています。


* parenthes*-コマンド構文に表示されるかっこは、パラメータの特定の選択肢を囲みます。つまり、パラメータを使用する場合は、丸かっこで囲まれた値のいずれかを入力する必要があります。一般的に、スクリプトコマンドには丸かっこは含めません。ただし、場合によっては、リストを入力するときに、リストを丸かっこで囲む必要があります。該当するリストとしては、トレイIDの値やスロットIDの値のリストがあります。パラメータ値をかっこで囲む必要があるかどうかは、各パラメータの概要 で説明されています。

*Vertical bars*--スクリプトコマンド内の縦棒は"`"または"`"を示し'パラメータの有効な値を区切りますたとえば、コマンド概要 の'raidLevel'パラメータの構文は次のようになります。

[listing]
----
 raidLevel=(0 | 1 | 3 | 5 | 6)
----
raidLevelパラメータを使用してRAIDレベル5を設定するには'次の値を入力します

[listing]
----
 raidLevel=5
----
*ドライブの場所*--ドライブの場所を識別するCLIコマンドは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブの場所を特定するもう1つの方法は、ドライブトレイのIDを指定し、ドロワーのIDを0に設定し、ドライブが格納されているスロットのIDを指定することです。ID値はカンマで区切ります。ID値のセットを複数入力する場合は、値のセットをそれぞれスペースで区切ります。

CLIでドライブを指定する場合は2つの規則があります。使用する規則は各コマンドで指定されています。1つ目の規則では、等号と丸かっこを使用します。

[listing]
----

        drive=\(trayID,[drawerID,]slotID\)
----
2つ目の規則では、等号は使用せず、指定したドライブを角かっこで囲みます。

[listing]
----

        drive \[trayID,[drawerID,]slotID\]
----
丸かっこを使用する例をいくつか示します。

[listing]
----
(1,1 1,2 1,3 1,4 2,1 2,2 2,3 2,4)
----
大容量ドライブトレイの場合は、次の例になります。

[listing]
----
(1,1,1 1,2,2 1,3,3 1,4,4 2,1,1 2,2,2 2,3,3 2,4,4)
----
*斜体の用語*--コマンド内の斜体の用語は、指定する必要がある値または情報を示します。たとえば、次のような斜体の用語があるとします。

[listing]
----

          *numberOfDrives*
----
この場合は、斜体の用語を、スクリプトコマンドに含めるドライブの数に置き換えます。

*セミコロン*--スクリプトコマンドはセミコロン(`;`)で終了する必要がありますコマンドライン上またはスクリプトファイル内では、複数のスクリプトコマンドを入力できます。たとえば、次のスクリプトファイルでは、セミコロンを使用して各スクリプトコマンドが区切られています。

[listing]
----
create volume drives=(0,2 0,3 1,4 1,5 2,6 2,7) raidLevel=5 userLabel=”v1” capacity=2gb owner=a;
create volume volumeGroup=2 userLabel=”v2” capacity=1gb owner=b;
create volume volumeGroup=2 userLabel=”v3” capacity=1gb owner=a;
----
[listing]
----
create volume drives=(0,4 0,5 1,6 1,7 2,8 2,9) raidLevel=5 userLabel=”v4” capacity=2gb owner=b;
create volume volumeGroup=3 userLabel=”v5” capacity=1gb owner=a;
create volume volumeGroup=3 userLabel=”v6” capacity=1gb owner=b;
----