---
permalink: get-started/learn-about-volume-group-migration.html 
sidebar: sidebar 
keywords: volume, group, migration, learn, data, access, export, import, component 
summary: ボリュームグループの移行では、ボリュームグループをエクスポートして、別のストレージアレイにインポートすることができます。ボリュームグループをエクスポートして、オフラインの状態でデータを格納することもできます。 
---
= ボリュームグループの移行について説明します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ボリュームグループの移行では、ボリュームグループをエクスポートして、別のストレージアレイにインポートすることができます。ボリュームグループをエクスポートして、オフラインの状態でデータを格納することもできます。

[CAUTION]
====
ボリュームグループがNVMeまたはFIPS対応ドライブで構成されている場合は、ターゲットアレイへの移行を開始する前にドライブのロックを解除するために、セキュリティキーとパスフレーズをソースアレイから記録/保存する必要があります。セキュリティキーとパスフレーズが不明な場合やデータの整合性が不要な場合は、セキュリティの消去を実行できます。Eシリーズストレージシステムでは、異なる暗号化セキュリティドライブの混在はサポートされていません。セキュリティキーを使用してドライブのロックを解除し、FIPSドライブを消去し、ロックされたNVMeドライブのロックを解除またはリセットする方法の詳細については、SANtricity System Managerのオンラインヘルプを参照してください。

====
[NOTE]
====
*データアクセスが失われる可能性*-ボリュームグループを移動する前、またはボリュームグループをインポートする前に、ボリュームグループをエクスポートする必要があります。

====


== ボリュームグループをエクスポートします

ボリュームグループのエクスポート処理では、ボリュームグループ内のドライブの削除の準備をします。オフラインのストレージのドライブを削除したり、ボリュームグループを別のストレージアレイにインポートしたりできます。ボリュームグループのエクスポート処理が完了すると、すべてのドライブがオフラインになります。関連付けられているボリュームまたは空き容量ノードはストレージ管理ソフトウェアに表示されなくなります。



== エクスポートできないコンポーネント

ボリュームグループ手順 のエクスポートを完了する前に、エクスポートできないコンポーネントを削除する必要があります。削除する必要があるコンポーネントは次のとおりです。

* 永続的予約
* マッピング
* ボリュームコピーペア
* リモートミラーペア
* ミラーリポジトリ




== ボリュームグループのエクスポートの基本手順

ボリュームグループをエクスポートするには、_source_storageアレイで次の手順を実行します。

. ストレージアレイ構成を保存します。
. すべての I/O を停止します
. ボリュームグループ内のボリューム上のデータをバックアップします。
. ボリュームグループ内のボリューム上のファイルシステムをアンマウントまたは切断します。
. ボリュームグループを特定し、ドライブにソースとデスティネーションのストレージアレイ名、ボリュームグループ名、ボリュームグループ内のドライブの総数のラベルを付けます。
. ボリュームグループをオフラインにします。
. トレイ内の適切な通気を確保するために、空のドライブキャニスターまたは新しいドライブを入手して、エクスポートするボリュームグループに関連付けられているドライブを取り外したあとでドライブを交換できるようにします。


ボリュームグループをエクスポートするには、_target_storageアレイで次の手順を実行します。

. ターゲットストレージアレイに使用可能なドライブスロットがあることを確認します。
. インポートするドライブがターゲットストレージアレイでサポートされていることを確認します。
. 新しいボリュームがターゲットストレージアレイでサポートされていることを確認します。
. 最新バージョンのファームウェアがコントローラにインストールされていることを確認します。
. RAIDレベル6のボリュームグループをエクスポートする場合は、RAIDレベル6がターゲットストレージアレイでサポートされていることを確認します。
. 最新バージョンのストレージ管理ソフトウェアがターゲットストレージアレイにインストールされていることを確認します。
. ドライブセキュリティが有効なボリュームグループをエクスポートする場合は、ターゲットストレージアレイでドライブセキュリティが有効になっていることを確認します。




== ボリュームグループをインポートします

ボリュームグループのインポート処理では、インポートしたボリュームグループをターゲットストレージアレイに追加します。ボリュームグループのインポート処理が完了すると、すべてのドライブのステータスが最適になります。これで、関連付けられているボリュームまたは空き容量ノードが、ターゲットストレージアレイにインストールされているストレージ管理ソフトウェアに表示されるようになります。



== ボリュームグループのインポートの基本手順

[NOTE]
====
ボリュームグループをインポートする前に、ボリュームグループ内のすべてのドライブをトレイに挿入する必要があります。

====
ボリュームグループをインポートするには、_target_storageアレイで次の手順を実行します。

. エクスポートしたドライブを使用可能なドライブスロットに挿入します。
. インポートするボリュームグループの概要については、インポートレポートを確認してください。
. インポートできないコンポーネントがないかどうかを確認します。
. 手順 のインポートを続行することを確認します。




== インポートできないコンポーネント

ボリュームグループ手順 のインポート中に、一部のコンポーネントをインポートできません。手順 では、次のコンポーネントが削除されます。

* 永続的予約
* マッピング
* ボリュームコピーペア
* リモートミラーペア
* ミラーリポジトリ

