---
permalink: get-started/naming-conventions.html 
sidebar: sidebar 
keywords: name, conventions 
summary: 名前の最大文字数は30文字です。 
---
= 命名規則
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


* 名前の最大文字数は30文字です。
* 次のコンポーネントの名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。
+
** ストレージアレイ
** ホストグループ
** ホスト
** ボリュームグループ
** 動的ディスクプール
** 個のボリューム
** HBAホストポート


* 一意の名前を使用する必要があります。一意の名前を使用しないと、コントローラファームウェアからエラーが返されます。
* 名前に複数の単語、ハイフン、またはアンダースコアが含まれている場合は、名前を二重引用符（"``")で囲みます。使用方法によっては、名前を角かっこ（[]）で囲む必要があります。各パラメータの概要 は、パラメータを二重引用符、角かっこ、またはその両方で囲む必要があるかどうかを示します。
* 名前の文字列に新しい行を含めることはできません。
* Windowsオペレーティングシステムでは、他の区切り記号に加えて、名前を2つのバックスラッシュ（\\）で囲む必要があります。たとえば、Windowsオペレーティングシステムで実行するコマンドでは、次の名前が使用されます。
+
[listing]
----
[\“Engineering\”]
----
* UNIXオペレーティングシステムでは、スクリプトファイルで使用する場合に、名前が次の例のように表示されます。
+
[listing]
----
[“Engineering”]
----
* HBAホストポートのWorld Wide Identifier（WWID）を入力する際は、WWIDを二重引用符で囲まなければならない場合があります。また、WWIDを山かっこ（<>）で囲まなければならない場合もあります。WWIDのパラメータの概要 は、WWIDを二重引用符または山かっこで囲む必要があるかどうかを示しています。




== 数字の名前を入力します

ストレージアレイがストレージ管理ソフトウェアで自動的に設定される場合は、数字で構成される名前がストレージ管理ソフトウェアによって割り当てられます。数字のみで構成される名前は有効です。ただし、数字の名前はアルファベットで始まる名前とは異なる方法で処理する必要があります。

* 1や2など、数字だけの名前
* 1 Diskや32 Volumeなど、数値で始まる名前
* 「[\「1」]」
* 「[\“1Disk\”」


[NOTE]
====
名前の有効性が疑わしい場合は、二重引用符と角かっこの両方を使用してください。両方を使用すると、名前が問題なく機能し、原因 による処理の問題も発生しません。

====