---
permalink: commands-a-z/activate-synchronous-mirroring.html 
sidebar: sidebar 
keywords: activate, synchronous mirroring, supported arrays, roles, context, syntax, parameters, data assurance management, minimum firmware level 
summary: activate storageArray featureコマンドは、同期ミラーリング機能をアクティブ化し、ミラーリポジトリボリュームを作成します。 
---
= 同期ミラーリングを有効にする - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
activate storageArray feature'コマンドは'同期ミラーリング機能をアクティブ化し'ミラーリポジトリボリュームを作成します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドを使用すると、次の3つのいずれかの方法でミラーリポジトリボリュームを定義できます。

* ユーザ定義のドライブ
* ユーザ定義のボリュームグループ
* ユーザ定義のドライブ数


ドライブ数の定義を選択する場合は、コントローラファームウェアによって、ミラーリポジトリボリュームに使用するドライブが選択されます。

[NOTE]
====
このコマンドの以前のバージョンでは、機能識別子は「remoteMirror」でした。この機能識別子は有効ではなくなり' SyncMirror に置き換えられます

====


== 構文（ユーザ定義のドライブ）

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 3 | 5 | 6)
repositoryDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1,_]pass:quotes[_slotID1 ... trayIDn_,pass:quotes[[_drawerIDn_,]pass:quotes[_slotIDn_
[driveType=(fibre | SATA | SAS | NVMe4K)]
)
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(0 |1 | 5 | 6)
repositoryDrives=pass:quotes[_(trayID1,_]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn)_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== 構文（ユーザ定義のボリュームグループ）

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryVolumeGroup=pass:quotes[_volumeGroupName_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
----


== 構文（ユーザ定義のドライブ数）

[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----
[source, cli, subs="+macros"]
----
activate storageArray feature=syncMirror
repositoryRAIDLevel=(1 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
[repositoryVolumeGroupUserLabel=pass:quotes[_"volumeGroupName"_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
repositoryRAIDLevel
 a| 
ミラーリポジトリボリュームのRAIDレベル。有効な値は'0`'1' 3`'5`または'6`です



 a| 
repositoryDrives
 a| 
ミラーリポジトリボリュームのドライブ。大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
repositoryVolumeGroupUserLabel
 a| 
ミラーリポジトリボリュームの配置先となる新しいボリュームグループに付ける名前。ボリュームグループ名は二重引用符（""）で囲みます。



 a| 
repositoryVolumeGroup'
 a| 
ミラーリポジトリボリュームが配置されているミラーリポジトリボリュームグループの名前。（ストレージアレイ内のボリュームグループの名前を決定するには、「show storageArray profile'」コマンドを実行します）。



 a| 
「freeCapacityArea」
 a| 
ミラーリポジトリボリュームの作成に使用する、既存のボリュームグループ内の空きスペースのインデックス番号。空き容量は、ボリュームグループ内の既存のボリューム間の空き容量として定義されます。たとえば、ボリュームグループの領域が、ボリューム1、空き容量、ボリューム2、空き容量、ボリューム3、 空き容量：ボリューム2の次の空き容量を使用するには、次のように指定します。

[listing]
----
freeCapacityArea=2
----
show volumegroupコマンドを実行して'空き容量領域が存在するかどうかを確認します



 a| 
repositoryDriveCount
 a| 
ミラーリポジトリボリュームに使用する未割り当てのドライブの数。



 a| 
「ドライブタイプ」
 a| 
情報を取得するドライブのタイプ。ドライブタイプを混在させることはできません。

有効なドライブタイプは次のとおりです。

* 「ファイバ」
* 「sata」と入力します
* 「SAS」
* NVMeネームスペース4K


ドライブタイプを指定しない場合、このコマンドはデフォルトでall typeになります。



 a| 
「trayLossProtect`」
 a| 
ミラーリポジトリボリュームを作成するときにトレイ損失の保護を有効にする設定。トレイ損失の保護を有効にするには'このパラメータをTRUEに設定しますデフォルト値は'FALSE'です



 a| 
「drawerLossProtect`」
 a| 
ミラーリポジトリボリュームを作成するときにドロワー損失の保護を有効にする設定。ドロワー損失の保護を有効にするには、このパラメータを「true」に設定します。デフォルト値は'FALSE'です

|===


== 注：

repositoryDrivesパラメータでは、大容量ドライブトレイと小容量ドライブトレイの両方がサポートされます。大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。

repositoryDrivesパラメータ用に選択したドライブが他のパラメータ(repositoryRAIDLevel'パラメータなど)と互換性がない場合、スクリプトコマンドはエラーを返し、同期ミラーリングはアクティブ化されません。このエラーは、ミラーリポジトリボリュームに必要なスペース容量を返します。その後、コマンドを再入力し、適切なスペース容量を指定できます。

リポジトリストレージのスペースとして入力した値がミラーリポジトリボリュームにとって小さすぎる場合、コントローラファームウェアは、ミラーリポジトリボリュームに必要なスペースの量を示すエラーメッセージを返します。コマンドでは、同期ミラーリングのアクティブ化は試行されません。エラーメッセージに示されるリポジトリストレージスペースの値を使用して、コマンドを再入力できます。

ドライブを割り当てるときに、trayLossProtectパラメータをTRUEに設定し、いずれか1つのトレイから複数のドライブを選択した場合、ストレージアレイはエラーを返します。trayLossProtect`パラメータをFALSEに設定すると'ストレージ・アレイは操作を実行しますが'作成するボリューム・グループにはトレイ損失の保護がない可能性があります

コントローラファームウェアがドライブを割り当てるときに、trayLossProtectパラメータを「true」に設定すると、新しいボリュームグループにトレイ損失の保護を提供するドライブをコントローラファームウェアが提供できない場合、ストレージアレイはエラーを返します。trayLossProtectパラメータをFALSEに設定すると、ボリュームグループにトレイ損失の保護がない可能性がある場合でも、ストレージアレイは処理を実行します。

「drawerLossProtect」パラメータは、ドロワーに障害が発生した場合にボリューム上のデータにアクセスできるかどうかを決定します。ドライブを割り当てるときに'drawerLossProtect'パラメータをTRUEに設定し'1つのドロワーから複数のドライブを選択すると'ストレージアレイはエラーを返しますdrawerLossProtectパラメータをFALSEに設定すると、ストレージアレイは処理を実行しますが、作成するボリュームグループにドロワー損失の保護が適用されない可能性があります。



== Data Assurance管理

Data Assurance（DA）機能を使用すると、ストレージシステム全体のデータの整合性が向上します。ホストとドライブの間でデータが移動されたときにストレージアレイがエラーの有無をチェックします。この機能を有効にすると、ボリューム内の各データブロックに巡回冗長検査（CRC）と呼ばれるエラーチェック用のコードが付加されます。データブロックが移動されると、ストレージアレイはこれらのCRCコードを使用して、転送中にエラーが発生したかどうかを判断します。破損している可能性があるデータはディスクに書き込まれず、ホストにも返されません。

DA機能を使用する場合は、まず最初にDAがサポートされているドライブのみを含むプールまたはボリュームグループを作成します。次に、DA対応ボリュームを作成します。最後に、DAに対応したI/Oインターフェイスを使用してDA対応ボリュームをホストにマッピングします。DAに対応したI/Oインターフェイスには、Fibre Channel、SAS、iSER over InfiniBand（iSCSI Extensions for RDMA/IB）があります。iSCSI over EthernetやSRP over InfiniBandではDAはサポートされていません。

[NOTE]
====
すべてのドライブがDA対応の場合は'dataAssuranceパラメータをEnabledに設定し'特定の操作でDAを使用できますたとえば、DA対応ドライブが含まれるボリュームグループを作成し、そのボリュームグループにDA対応のボリュームを作成できます。DA対応ボリュームを使用する他の処理には、DA機能をサポートするオプションがあります。

====
「dataAssurance」パラメータが「enabled」に設定されている場合、Data Assurance対応のドライブのみがボリューム候補とみなされます。それ以外の場合は、Data Assurance対応ドライブとData Assurance対応でないドライブの両方が考慮されます。DA対応ドライブのみが使用可能な場合、新しいボリュームグループは、有効なDA対応ドライブを使用して作成されます。



== 最小ファームウェアレベル

7.10で、RAIDレベル6機能が追加されました。

7.60で'drawerID'ユーザー入力'driveMediaType'パラメータ'およびdrawerLossProtect'パラメータが追加されました

7.75で'dataAssuranceパラメータが追加されました

8.10で'driveMediaType'パラメータが削除されました

8.60で、「drivetype」パラメータが追加されました。
