---
permalink: commands-a-z/add-volume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: add volume, asynchronous, mirror group, supported arrays, roles, context, syntax, parameter, minimum firmware level 
summary: add volume asyncMirrorGroupコマンドは、非同期ミラーグループにプライマリボリュームを追加します。 
---
= 非同期ミラーグループにボリュームを追加する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
add volume asyncMirrorGroupコマンドは'非同期ミラー・グループにプライマリ・ボリュームを追加します



== サポートされているアレイ

このコマンドは、一部制限付きで個々のストレージアレイを環境 接続します。E2700またはE5600のアレイに対して実行する場合は、制限はありません。

[NOTE]
====
このコマンドは、E4000、E2800、E5700、EF600、およびEF300のプラットフォームではサポートされていません。

====


== ロール

該当なし



== コンテキスト（Context）

このコマンドは、プライマリボリュームを追加する非同期ミラーグループを含むローカルストレージアレイでのみ有効です。非同期ミラーグループには、リポジトリボリュームがあり、非同期ミラーグループに含まれるすべての「ポイントインタイム」イメージのデータの保存に使用されます。非同期ミラーグループ内の各プライマリボリュームには、リモートストレージアレイに対応するミラーボリュームがあります。



== 構文

[source, cli, subs="+macros"]
----
pass:quotes[add volume="_volumeName_" asyncMirrorGroup="_asyncMirrorGroupName_"
remotePassword="_password_"
(repositoryVolume="repos_xxxx" |
repositoryVolume=(_volumeGroupName_ ]pass:quotes[[capacity=_capacityValue_])]
repositoryVolume=pass:quotes[(_diskPoolName_] pass:quotes[[capacity=_capacityValue_]))
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
非同期ミラーグループに追加するプライマリボリュームの名前。ボリューム名は二重引用符（""）で囲みます。



 a| 
「asyncMirrorGroup」
 a| 
プライマリボリュームを追加する非同期ミラーグループの名前。非同期ミラーグループ名は二重引用符（""）で囲みます。



 a| 
「remotePassword」
 a| 
このパラメータはオプションです。このパラメータは、リモートストレージアレイがパスワードで保護されている場合に使用します。パスワードは二重引用符（""）で囲みます。



 a| 
リポジトリボリューム
 a| 
プライマリボリュームの変更されたデータが格納されるリポジトリボリュームの名前。

リポジトリボリュームの名前を定義する方法は2つあります。

* 既存のリポジトリボリュームの名前を使用します。
* このコマンドを実行するときに新しいリポジトリボリュームを作成します。


既存のリポジトリボリュームの名前は次の2つの部分で構成されます。

* 「repos」という単語
* ストレージ管理ソフトウェアがリポジトリボリューム名に割り当てる4桁の数値識別子。


既存のリポジトリボリュームの名前は二重引用符（""）で囲みます。

このコマンドを実行するときに新しいリポジトリボリュームを作成する場合は、リポジトリボリュームを含めるボリュームグループまたはディスクプールの名前を入力する必要があります。必要に応じて、リポジトリボリュームの容量を定義することもできます。容量を定義する場合は、次の値を使用できます。

* ベースボリュームの容量の割合を表す整数値
* ベースボリュームの容量の割合を表す小数値。
* リポジトリボリュームの具体的なサイズ。サイズは'bytes'KB'MB`'GB'TB'の単位で定義されます


容量を定義しない場合は、ストレージ管理ソフトウェアによって、プライマリボリュームの容量の20%に設定されます。

ストレージ管理ソフトウェアはリポジトリボリュームを作成し、プライマリボリュームにリンクします。

|===


== 注：

* ミラーアクティビティに使用されるローカルストレージアレイとリモートストレージアレイで、非同期ミラーリング機能が有効化され、アクティブ化されている必要があります。
* ローカルとリモートのストレージアレイが適切なFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続されている必要があります。
* リモートストレージアレイには、ローカルストレージアレイのプライマリボリュームと同等以上の容量のボリュームが必要です。リモートストレージアレイのボリュームがミラーボリュームとして使用されます。




== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
