---
permalink: commands-a-z/add-drives-to-ssd-cache.html 
sidebar: sidebar 
keywords: add drives ssd cache, supported arrays, syntax, parameters, minimum firmware level 
summary: set ssdCacheコマンドは、Solid State Disk（SSD；ソリッドステートディスク）を追加することで既存のSSDキャッシュの容量を拡張します。 
---
= SSD キャッシュにドライブを追加する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set ssdCacheコマンドは'SSD（ソリッド・ステート・ディスク）を追加することにより'既存のSSDキャッシュの容量を拡張します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。

[NOTE]
====
このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Support Adminロールが必要です。

====


== 構文

[source, cli, subs="+macros"]
----
pass:quotes[set ssdCache [_ssdCacheName_]]
pass:quotes[addDrives=(_trayID1_,[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_,]pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「ssdCache」
 a| 
SSDを追加するSSDキャッシュの名前。名前は角かっこ（[]）で囲みます。SSDキャッシュ名が特殊文字を含んでいる場合または数字のみで構成される場合は、名前を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「addDrives」を参照してください
 a| 
SSDキャッシュに追加するドライブ。大容量ドライブトレイの場合は、ドライブのトレイID値、ドロワーID値、およびスロットID値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

|===


== 注：

SSDキャッシュには、任意の数のSSDを格納できます。SSDキャッシュの最大サイズは5TBですが、コントローラのプライマリキャッシュのサイズによってはそれよりも小さくなる可能性があります。



== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
