---
permalink: commands-a-z/change-ssd-cache-application-type.html 
sidebar: sidebar 
keywords: ssd cache application type 
summary: set ssdCacheコマンドは、SSDキャッシュに関連付けられているアプリケーションタイプを変更します。アプリケーションタイプは、Webサーバ、データベース、マルチメディアのいずれかです。アプリケーションタイプを変更すると、SSDキャッシュの基盤となるボリュームのブロックサイズ、サブブロックサイズ、読み取り時の取り込みしきい値、書き込み時の取り込みしきい値が変更されます。 
---
= SSD キャッシュ アプリケーションの種類を変更する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set ssdCacheコマンドは、SSDキャッシュに関連付けられたアプリケーションタイプを変更します。アプリケーションタイプは、Webサーバ、データベース、マルチメディアのいずれかです。アプリケーションタイプを変更すると、SSDキャッシュの基盤となるボリュームのブロックサイズ、サブブロックサイズ、読み取り時の取り込みしきい値、書き込み時の取り込みしきい値が変更されます。



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Support Adminロールが必要です。



[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
set ssdCache pass:quotes[[_ssdCacheName_]]usageHint=(webServer|dataBase|fileSystem)
----


[[parameter]]
== パラメータ

|===
| パラメータ | 説明 


 a| 
「ssdCache」
 a| 
アプリケーションタイプを変更するSSDキャッシュの名前。SSDキャッシュ名は角かっこ（[]）で囲みます。SSDキャッシュ名が特殊文字を含んでいる場合または数字のみで構成される場合は、SSDキャッシュ名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「usageHint`」
 a| 
SSDキャッシュを使用するアプリケーションの標準的なI/O使用パターンに基づいて値を設定します。有効な値は'webServer'database'または'filesystem'です

|===


[[minimum-firmware-level]]
== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
