---
permalink: commands-a-z/change-ssd-cache-application-type.html 
sidebar: sidebar 
keywords: ssd cache application type 
summary: set ssdCacheコマンドは、SSDキャッシュに関連付けられているアプリケーションタイプを変更します。アプリケーションタイプは、Webサーバ、データベース、マルチメディアのいずれかです。アプリケーションタイプを変更すると、SSDキャッシュの基盤となるボリュームのブロックサイズ、サブブロックサイズ、読み取り時の取り込みしきい値、書き込み時の取り込みしきい値が変更されます。 
---
= SSDキャッシュのアプリケーションタイプを変更します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set ssdCacheコマンドは、SSDキャッシュに関連付けられたアプリケーションタイプを変更します。アプリケーションタイプは、Webサーバ、データベース、マルチメディアのいずれかです。アプリケーションタイプを変更すると、SSDキャッシュの基盤となるボリュームのブロックサイズ、サブブロックサイズ、読み取り時の取り込みしきい値、書き込み時の取り込みしきい値が変更されます。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700などの個 々 のストレージアレイを環境に設定します。 EF600およびEF300アレイ（すべてのSMcliパッケージがインストールされている必要があります。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Support Adminロールが必要です。



== 構文

[listing, subs="+macros"]
----
set ssdCache pass:quotes[[_ssdCacheName_]]usageHint=(webServer|dataBase|fileSystem)
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「ssdCache」
 a| 
アプリケーションタイプを変更するSSDキャッシュの名前。SSDキャッシュ名は角かっこ（[]）で囲みます。SSDキャッシュ名が特殊文字を含んでいる場合または数字のみで構成される場合は、SSDキャッシュ名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「usageHint`」
 a| 
SSDキャッシュを使用するアプリケーションの標準的なI/O使用パターンに基づいて値を設定します。有効な値は'webServer'database'または'filesystem'です

|===


== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
