---
permalink: commands-a-z/check-volume-parity.html 
sidebar: sidebar 
keywords: check, volume, parity 
summary: ボリュームのパリティチェックコマンドは、ボリュームのパリティエラーとメディアエラーをチェックして、チェック結果をファイルに書き込みます。 
---
= ボリュームのパリティをチェックします
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
'check volume parity 'コマンドは'ボリュームにパリティ・エラーとメディア・エラーがないかどうかをチェックし'チェックの結果をファイルに書き込みます



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[listing, subs="+macros"]
----
check volume pass:quotes[[_volumeName_]] parity
[parityErrorFile=pass:quotes[_filename_]]
[mediaErrorFile=pass:quotes[_filename_]]
[priority=(highest | high | medium | low | lowest)]
[startingLBA=pass:quotes[_LBAvalue_]]
[endingLBA=pass:quotes[_LBAvalue_]]
[verbose=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
パリティをチェックする特定のボリュームの名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名が特殊文字を含んでいる場合または数字のみで構成される場合は、識別子を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
'parityErrorFile'
 a| 
パリティエラー情報の保存先となるファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。例：

'file="C:\Program Files\CLI\logs\parerr.txt

このコマンドでは、保存されているファイルにファイル拡張子は自動的に付加されません。ファイル名にはファイル拡張子を指定する必要があります。



 a| 
「mediaErrorFile」
 a| 
メディアエラー情報の保存先となるファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。例：

'file="C:\Program Files\CLI\logs\mederr.txt

このコマンドでは、保存されているファイルにファイル拡張子は自動的に付加されません。ファイル名にはファイル拡張子を指定する必要があります。



 a| 
「 priority 」
 a| 
ホストのI/Oアクティビティに対するパリティチェックの優先度。有効な値は'high`'high`'medium'low''low''またはlowestです優先度が最も低い値はシステムのパフォーマンスに影響しますが'パリティ・チェックにかかる時間は長くなります優先度を最も高くすると、パリティチェックにかかる時間は短縮されますが、システムパフォーマンスが低下する可能性があります。



 a| 
「StartingLBA」
 a| 
論理ブロックの開始アドレス。



 a| 
「endinglba`」
 a| 
論理ブロックの終了アドレス。



 a| 
「冗長」
 a| 
完了した割合などの進捗状況の詳細をキャプチャするための設定、およびボリュームのパリティのスキャン時の情報を表示するための設定。進行状況の詳細をキャプチャするには、このパラメータを「true」に設定します。進行状況の詳細をキャプチャしないようにするには'このパラメータをFALSEに設定します

|===


== 注：

論理ブロックの開始アドレスと論理ブロックの終了アドレスは、非常に大規模な単一ボリュームのLUNまたはネームスペースに役立ちます。非常に大規模な単一ボリュームのLUNまたはネームスペースにおけるボリュームのパリティチェックには時間がかかる可能性があります。データブロックの開始アドレスと終了アドレスを定義することで、ボリュームのパリティチェックの完了までにかかる時間を短縮できます。



== 最小ファームウェアレベル

11.80 -このコマンドは廃止されました。
