---
permalink: commands-a-z/check-storagearray-connectivity.html 
sidebar: sidebar 
keywords: check, storage array, connectivity 
summary: check storageArray connectivityコマンドを使用すると、ローカルストレージアレイとリモートストレージアレイに通信パスがあることが確認され、ローカルストレージアレイとリモートストレージアレイ間の接続の詳細が表示されます。 
---
= ストレージアレイの接続を確認してください
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
check storageArray connectivity'コマンドは'ローカルストレージアレイとリモートストレージアレイに通信パスがあることを確認し'ローカルストレージアレイとリモートストレージアレイ間の接続の詳細を表示します



== サポートされているアレイ

このコマンドは、一部制限付きで個々のストレージアレイを環境 接続します。E2700またはE5600のアレイに対して実行する場合は、制限はありません。

[NOTE]
====
このコマンドは、E2800、E5700、EF600、およびEF300のプラットフォームではサポートされていません。

====


== ロール

このコマンドをE2800またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

非同期ミラーグループを作成する前に、ローカルストレージアレイとリモートストレージアレイが相互に通信できるかどうかを確認する必要があります。このコマンドを実行すると、該当するすべてのホストポート上のリモートストレージアレイが照会され、リモートストレージアレイに接続されているポートが特定されます。テストの結果として、ローカルストレージアレイ上のすべてのポートのリスト、およびそのポート経由でアクセス可能なリモートストレージアレイのポートアドレスのリストが作成されます。

[NOTE]
====
すべての有効なチャネルを使用して接続がテストされます。デュアルコントローラ構成の場合は、各コントローラから接続がチェックされます。2つのストレージアレイ間の接続のチェックには最大20分かかる場合があります。

====


== 構文

[listing, subs="+macros"]
----
check storageArray connectivity
(remoteStorageArrayName=pass:quotes[_"storageArrayName"_]|
remoteStorageArrayWwid=<pass:quotes[_wwID_]>)
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
remoteStorageArrayName
 a| 
接続をチェックするリモートストレージアレイの名前。ストレージアレイ名は二重引用符（""）で囲みます。



 a| 
remoteStorageArrayWwid
 a| 
接続をチェックするストレージアレイのWorld Wide Identifier（WWID）。ストレージアレイ名の代わりにWWIDを使用してストレージアレイを識別できます。WWIDは山かっこ（<>）で囲みます。

|===


== 注：

2つのストレージアレイ間のミラーを確立する前に、Fibre Channel接続またはiSCSI接続を使用して、2つのストレージアレイを接続する必要があります。

ミラーリングまたは接続のチェックのためのストレージアレイの相互通信を行う前に、両方のストレージアレイでFibre Channelによる非同期ミラーリングをアクティブ化する必要があります。

ローカルストレージアレイでiSCSIがサポートされる場合は、iSCSI経由の接続がチェックされます。ローカルストレージアレイでFibre Channelがサポートされており、Fibre Channel経由のミラーリングがアクティブ化されている場合は、Fibre Channel経由の接続がチェックされます。ローカルストレージアレイでiSCSIまたはFibre Channelがサポートされない場合は、エラーメッセージが表示されて処理が中止されます。



== 最小ファームウェアレベル

7.84
