---
permalink: commands-a-z/check-syncmirror.html 
sidebar: sidebar 
keywords: check, synchronous, mirroring status 
summary: check SyncMirror コマンドは、リモートミラーボリュームのステータスを返します。このコマンドを使用して、リモートミラーボリュームのステータスが最適になったタイミングを確認します。 
---
= 同期ミラーリングのステータスを確認する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
check SyncMirror コマンドは'リモート・ミラー・ボリュームのステータスを返しますこのコマンドを使用して、リモートミラーボリュームのステータスが最適になったタイミングを確認します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
このコマンドの以前のバージョンでは、機能識別子は「remoteMirror」でした。この機能識別子は有効ではなくなり' SyncMirror に置き換えられます

====


== 構文

[source, cli, subs="+macros"]
----
check syncMirror localVolume pass:quotes[[_volumeName_]] optimalStatus timeout=pass:quotes[_timeoutValue_]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「localVolume」です
 a| 
リモートミラーボリュームの名前。リモートミラーペアのプライマリボリュームまたはセカンダリボリュームをリモートミラーボリュームとして使用できます。ボリューム名は角かっこ（[]）で囲みます。ボリューム名に特殊文字が含まれている場合は、ボリューム名を二重引用符（""）で囲む必要があります。



 a| 
タイムアウト
 a| 
ソフトウェアがリモートミラーボリュームのステータスを返すことのできる期間。タイムアウト値は分単位です。

|===


== 注：

このコマンドは、ステータスが最適になるか、タイムアウト間隔が経過するまで待機します。非同期同期ミラーリングユーティリティの実行時にこのコマンドを使用します。
