---
permalink: commands-a-z/clear-asyncmirrorfault.html 
sidebar: sidebar 
keywords: clear, asynchronous mirroring, fault 
summary: clear asyncMirrorFaultコマンドは、1つ以上の非同期ミラーグループおよび1つ以上の非同期ミラーグループメンバーボリュームから、非同期ミラーリングの「ティック」エラーをクリアします。 
---
= 非同期ミラーリング障害のクリア - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clear asyncMirrorFaultコマンドは、1つ以上の非同期ミラーグループおよび1つ以上の非同期ミラーグループメンバーボリュームから、非同期ミラーリングの「スティッキー」エラーをクリアします。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

非同期ミラーグループとそのメンバーボリュームで、非同期ミラーリングの「スティッキー」エラーが発生することがあります。このエラーは単一時点で発生し、ミラーの機能には影響しません。このタイプの障害については確認が必要ですが、設定の変更が不要な場合もあります。

非同期ミラーグループとそのメンバーボリュームで、関連するスティッキーエラーが複数発生する場合があります。このコマンドは、非同期ミラーグループとそのメンバーボリュームに関連するすべてのエラーを解消します。ただし、非同期ミラーグループとそのメンバーボリュームの1つでそれぞれにエラーが発生した場合は、非同期ミラーグループでエラーを解消してもメンバーボリュームのエラーは解消されません。



== 構文

[source, cli, subs="+macros"]
----
clear asyncMirrorFault(all |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]] |
asyncMirrorGroups pass:quotes[[_"asyncMirrorGroupName1"
... "asyncMirrorGroupNameN"_]] |
volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_"volumeName1" ... "volumeNameN"_]])
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「すべて」
 a| 
このパラメータは、すべての非同期ミラーグループおよびすべての非同期ミラーグループメンバーボリュームですべての非同期ミラーリングエラーを解消する場合に使用します。



 a| 
「asyncMirrorGroup」
 a| 
非同期ミラーリングエラーを解消する非同期ミラーグループの名前。非同期ミラーグループ名は角かっこ（[]）で囲みます。非同期ミラーグループ名が特殊文字を含んでいる場合または数字のみで構成される場合は、名前を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「asyncMirrorGroups」を参照してください
 a| 
非同期ミラーリングエラーを解消する複数の非同期ミラーグループの名前。以下のルールを使用して、非同期ミラーグループの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
「 volume 」
 a| 
非同期ミラーリングエラーを解消する特定のメンバーボリューム（非同期ミラーグループ内）の名前。メンバーボリューム名は角かっこ（[]）で囲みます。ボリューム名が特殊文字を含んでいる場合または数字のみで構成される場合は、名前を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「ボリューム」
 a| 
非同期ミラーリングエラーを解消する複数のメンバーボリューム（非同期ミラーグループ内）の名前。以下のルールを使用して、メンバーボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。


|===


== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
