---
permalink: commands-a-z/clear-storagearray-configuration.html 
sidebar: sidebar 
keywords: clear, storage array, configuration 
summary: clear storageArray configurationコマンドは、ストレージアレイ構成全体またはストレージアレイ構成の一部をクリアするか、ボリュームグループとボリューム構成のみをクリアします。 
---
= ストレージアレイの構成のクリア
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
clear storageArray configuration'コマンドは'ストレージ・アレイ構成全体またはストレージ・アレイ構成の一部をクリアするか'ボリューム・グループおよびボリューム構成のみをクリアします



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

次のいずれかの処理を実行するには、このコマンドを使用します。

* ストレージアレイ構成全体をクリアし、初期インストール状態に戻します。
* セキュリティ情報と識別情報以外の設定をクリアします。
* ボリュームグループの構成情報とボリュームの構成情報のみをクリアします。


[NOTE]
====
*ストレージアレイ構成への損傷の可能性*--このコマンドを実行すると、既存のストレージアレイ構成がただちに削除されます。

====


== 構文

[listing]
----
clear storageArray configuration (all | volumeGroups)
----
[listing]
----
clear storageArray configuration factoryReset
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
* なし *
 a| 
パラメータを1つも入力しないと、セキュリティと識別に関連する情報を除くストレージアレイのすべての構成情報が削除されます。



 a| 
「すべて」
 a| 
セキュリティ情報と識別情報を含むストレージアレイの構成全体を削除するための設定。構成情報をすべて削除すると、ストレージアレイは初期状態に戻ります。



 a| 
「ボリュームグループ」
 a| 
ボリューム構成とボリュームグループ構成を削除するための設定。残りの構成はそのまま維持されます。



 a| 
「FactoryReset」を参照してください
 a| 
この設定を選択すると、ストレージ・アレイの構成全体が削除されますが（「all」パラメータと同じ機能）、コントローラに保存されているネットワーク構成とパスワード情報もリセットされます。



 a| 
「supportReset」を参照してください
 a| 
[NOTE]
====
このコマンドはテクニカルサポート専用です。

====
この設定は'FactoryReset'パラメータと同様に動作しますが'すべてのバンドルキーもクリアされます

|===


== 注：

このコマンドでは、ストレージアレイの構成をさまざまな方法でクリアできます。ストレージアレイのボリュームグループをクリアすると、自動的にリカバリモードが開始されます。リカバリモードでは、オンボード（キャッシュ）バックアップ（プラットフォームに存在する場合）が保持されます。ストレージアレイがリカバリモードの場合は、必要に応じて、ホストベースのバックアップファイルまたはいずれかのオンボード（キャッシュ）バックアップからストレージアレイ構成をリストアできます。

このコマンドはストレージアレイの識別子もリセットします。キーファイルで有効化されたプレミアム機能がすべて無効になるため、新しいプレミアム機能キーを作成して適用する必要があります。テクニカルサポートにお問い合わせください。

このコマンドを実行すると、ストレージアレイが応答しなくなり、すべてのスクリプト処理がキャンセルされます。ホストとの通信を再開するには、ストレージアレイを削除して再び追加する必要があります。応答しないストレージアレイを削除するには、次のSMcliラッパーコマンドを使用します。

[listing, subs="+macros"]
----
SMcli -X -n pass:quotes[_storageArrayName_]
----
「X」は一意のSMcli端末であり、大文字で入力する必要があります。

ストレージアレイを再び追加するには、次のSMcliラッパーコマンドを使用します。

[listing, subs="+macros"]
----
SMcli -A -n pass:quotes[_storageArrayName_]
----
「A」はSMcliのユニークなターミナルで、大文字で入力する必要があります。



== 最小ファームウェアレベル

7.10で、次のパラメータが追加されまし

* 「すべて」
* 「ボリュームグループ」


7.83で、リカバリモード機能が追加されました。

11.41で追加されたパラメータは次のとおりです

* 「FactoryReset」を参照してください
* 「supportReset」を参照してください

