---
permalink: commands-a-z/clear-storagearray-recoverymode.html 
sidebar: sidebar 
keywords: clear, storage array, recovery, mode 
summary: clear storageArray recoveryModeコマンドを使用すると、ストレージアレイのリカバリモードが強制的に終了します。 
---
= ストレージアレイのリカバリモードをクリアする - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
clear storageArray recoveryModeコマンドを使用すると、ストレージアレイが強制的にリカバリモードを終了します。



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[syntax]]
== 構文

[source, cli]
----
clear storageArray recoveryMode
----


[[parameters]]
== パラメータ

なし



[[notes]]
== 注：

[NOTE]
====
一日の開始処理中にシステム構成がクリアされ、有効なオンボードバックアップが使用可能な場合、リカバリモードに切り替わります。バックアップ先からシステム構成をリストアするか、既存のオンボードバックアップを消去すると、このモードは終了します。リカバリモードに切り替わると、needs attention状態となり、ユーザインターフェイスからRecovery Guruを参照できます。ただし、リカバリモード中、システム構成は空です。

====
[NOTE]
====
ストレージアレイを以前の構成に戻す場合は、リカバリモードをクリアする前にバックアップから設定をリストアする必要があります。リストアが正常に完了したことを確認するには、検証チェックを実行するか、テクニカルサポートに確認する必要があります。リストアが正常に完了したことを確認したら、リカバリモードをクリアできます。

====


[[minimum-firmware-level]]
== 最小ファームウェアレベル

7.83
