---
permalink: commands-a-z/create-raid-volume-free-extent-based-select.html 
sidebar: sidebar 
keywords: create, raid, volume, free, extent, based, select 
summary: create volumeコマンドは、ボリュームグループの空きスペースにボリュームを作成します。 
---
= RAIDボリュームの作成（空きエクステントベースの選択）
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
create volumeコマンドは'ボリューム・グループの空き領域にボリュームを作成します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[listing, subs="+macros"]
----
create volume volumeGroup=pass:quotes[_"volumeGroupName"_
userLabel="_volumeName"_]
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
[capacity=pass:quotes[_volumeCapacity_]]
[owner=(a|b)]
[cacheReadPrefetch=(TRUE | FALSE)]
[segmentSize=pass:quotes[_segmentSizeValue_]]
[usageHint=(fileSystem | dataBase | multiMedia)]
[dssPreAllocate=(TRUE | FALSE)]
[securityType=(none | capable | enabled)]
[dataAssurance=(none | enabled)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「volumeGroup」のように指定します
 a| 
ストレージアレイ内の特定のボリュームグループの名前。ボリュームグループ名は二重引用符（""）で囲みます。



 a| 
「userLabel」のように入力します
 a| 
新しいボリュームに付ける名前。新しいボリューム名は二重引用符（""）で囲みます。

[NOTE]
====
このパラメータは必須です。

====


 a| 
「freeCapacityArea」
 a| 
新しいボリュームの作成に使用する、既存のボリュームグループ内の空きスペースのインデックス番号。空き容量は、ボリュームグループ内の既存のボリューム間の空き容量として定義されます。たとえば、ボリュームグループの領域が、ボリューム1、空き容量、ボリューム2、空き容量、ボリューム3、 空き容量：ボリューム2の次の空き容量を使用するには、インデックス番号を次のように入力します。

freeCapacityArea = 2`

[NOTE]
====
show volumegroupコマンドを実行して'空き容量領域が存在するかどうかを確認します

====
[NOTE]
====
このパラメータを指定しない場合、番号が最も小さく、ボリューム用の十分な容量のある空き容量領域にボリュームが作成されます。

====


 a| 
「容量」
 a| 
ストレージアレイに追加するボリュームのサイズ。サイズは'bytes'KB'MB`'GB'TB'の単位で定義されます



 a| 
「owner」をクリックします
 a| 
ボリュームを所有するコントローラ。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラです所有者を指定しない場合は、コントローラファームウェアによって所有者が決定されます。



 a| 
「cacheReadPrefetch」というメッセージが表示されます
 a| 
キャッシュ読み取りプリフェッチをオンまたはオフにする設定。キャッシュ読み取りプリフェッチをオンにするには'このパラメータをTRUEに設定しますキャッシュ読み取りプリフェッチをオフにするには'このパラメータをFALSEに設定します



 a| 
「segmentSize」のように表示されます
 a| 
コントローラがボリューム内の1つのドライブに書き込めるデータ量（KB）を指定します。有効な値は'8`'16`'32`'64`'128`'です 「256」または「512」。



 a| 
「usageHint`」
 a| 
「cacheReadPrefetch」パラメータと「segmentSize」パラメータの両方の設定がデフォルト値になります。デフォルト値は、ボリュームを使用しているアプリケーションの標準的なI/O使用パターンに基づいています。有効な値は'filesystem'database'または'multiMediaです



 a| 
dssPreAllocate
 a| 
今後のセグメントサイズの拡大に備えてリザーブ容量が割り当てられていることを確認する設定。デフォルト値は「true」です。



 a| 
「securityType」
 a| 
ボリュームグループおよび関連するすべてのボリュームの作成時にセキュリティレベルを指定する設定。有効な設定は次のとおりです。

'none`--ボリュームグループとボリュームは安全ではありません。

capable --ボリュームグループとボリュームにはセキュリティを設定する機能がありますが'セキュリティは有効になっていません

有効-ボリューム・グループとボリュームでセキュリティが有効になっています

|===


== 注：

名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。名前の最大文字数は30文字です。

ownerパラメータは'ボリュームを所有するコントローラを定義しますボリュームの優先コントローラ所有者は、ボリュームグループを現在所有しているコントローラです。

「capacity」パラメータを使用して容量を指定しない場合は、ボリュームグループの空き容量領域で使用可能な容量がすべて使用されます。容量の単位を指定しない場合'デフォルト値としてbytesが使用されます



== セグメントサイズ

コントローラがボリューム内の1つのドライブに書き込めるデータブロックの数は、セグメントのサイズによって決まります。各データブロックには512バイトのデータが格納されます。データブロックはストレージの最小単位です。セグメントのサイズによって、格納されるデータブロックの数が決まります。たとえば、8KBのセグメントには16個のデータブロックが含まれます。64KBのセグメントには128個のデータブロックが含まれます。

セグメントサイズの値を入力すると、その値は、実行時にコントローラで指定される、サポートされている値と照合されます。入力した値が無効な場合、コントローラは有効な値のリストを返します。1つの要求に対して1つのドライブを使用することで、他のドライブでは他の要求に同時に対応できます。ボリュームが属している環境で、1人のユーザが大量のデータ（マルチメディアなど）を転送している場合は、1つのデータ転送要求を1つのデータストライプで処理すると、パフォーマンスが最大化されます。（データストライプはセグメントサイズであり、これに、データ転送に使用されるボリュームグループ内のドライブ数が掛けられます）。 この場合、同じ要求に対して複数のドライブが使用されますが、各ドライブへのアクセスは1回だけとなります。

マルチユーザデータベースまたはファイルシステムのストレージ環境で最適なパフォーマンスを実現するには、データ転送要求を満たすために必要なドライブ数が最小限になるように、セグメントサイズを設定します。



== 使用上のヒント

[NOTE]
====
「cacheReadPrefetch」パラメータまたは「segmentSize」パラメータの値を入力する必要はありません。値を入力しない場合'コントローラ・ファームウェアは'filesystem'をデフォルト値として'usageHint'パラメータを使用します「usageHint」パラメータの値と「cacheReadPrefetch」パラメータの値、または「segmentSize」パラメータの値を入力しても、原因 にエラーは表示されません。「cacheReadPrefetch」パラメータまたは「segmentSize」パラメータに入力する値は、「usageHint」パラメータの値よりも優先されます。さまざまな使用方法のヒントに対するセグメントサイズおよびキャッシュ読み取りプリフェッチの設定を、次の表に示します。

====
|===
| 使用方法のヒント | セグメントサイズの設定 | 動的キャッシュ読み取りプリフェッチの設定 


 a| 
ファイルシステム
 a| 
128 KB
 a| 
有効



 a| 
データベース
 a| 
128 KB
 a| 
有効



 a| 
マルチメディア
 a| 
256 KB
 a| 
有効

|===


== キャッシュ読み取りプリフェッチ

キャッシュ読み取りプリフェッチを使用すると、コントローラは、ホストによって要求されたデータブロックをドライブから読み取ってキャッシュにコピーすると同時に、追加のデータブロックをキャッシュにコピーできます。これにより、以降のデータ要求をキャッシュから処理できる可能性が高くなります。キャッシュ読み取りプリフェッチは、シーケンシャルデータ転送を使用するマルチメディアアプリケーションにとって重要です。「cacheReadPrefetch」パラメータの有効な値は「TRUE」または「FALSE」です。デフォルトは「true」です。



== セキュリティタイプ

ストレージ・アレイのセキュリティ設定を指定するには'securityType'パラメータを使用します

'securityType'パラメータを'enabled'に設定する前に'ストレージ・アレイのセキュリティ・キーを作成する必要がありますストレージ・アレイのセキュリティ・キーを作成するには'create storageArray securityKey'コマンドを使用します次のコマンドがセキュリティキーに関連しています。

* 「create storageArray securityKey」のように指定します
* 「export storageArray securityKey」のように指定します
* 「import storageArray securityKey」のように入力します
* 「set storageArray securityKey」のように指定します
* [Enable volumeGroup [volumeGroupName] security]を有効にします
* 「enable diskPool [diskPoolName]のセキュリティ」を参照してください




== 最小ファームウェアレベル

7.10で、dssPreAllocateパラメータが追加されました。

7.50で、「securityType」パラメータが追加されました。

7.75で'dataAssuranceパラメータが追加されました
