---
permalink: commands-a-z/create-storagearray-securitykey.html 
sidebar: sidebar 
keywords: create, storage, array, security, key 
summary: create storageArray securityKeyコマンドは、Full Disk Encryption（FDE）ドライブが搭載されたストレージアレイの新しいセキュリティキーを作成または変更します。 
---
= ストレージアレイのセキュリティキーを作成します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
create storageArray securityKey'コマンドは'フルディスク暗号化(FDE)ドライブを持つストレージアレイの新しいセキュリティキーを作成または変更します



== サポートされているアレイ

外部キー管理が有効になっている場合、このコマンドはE2800、E5700、EF600、およびEF300アレイにのみ適用されます。内部キー管理が有効になっている場合、すべてのSMcliパッケージがインストールされていれば、コマンド環境 は個々のストレージアレイを対象とします。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Security Adminロールが必要です。



== コンテキスト（Context）

内部キー管理の場合、このコマンドは、内部キー管理機能を有効にしてセキュリティキーを作成します。キーを作成したら、「set storageArray securityKey」コマンドを使用してキーを使用可能にします。このコマンドを使用して、セキュリティキーを変更することもできます。

外部キー管理の場合、このコマンドは、機能を有効にしたときに最初に作成されたキーの代わりに使用するキーを作成します。外部キー管理機能をイネーブルにし、初期セキュリティキーを作成するには、「enable storageArray externalKeyManagement」コマンドを使用します。このコマンドを使用して、セキュリティキーを変更することもできます。



== 構文

[listing, subs="+macros"]
----
create storageArray securityKey
[keyIdentifier=pass:quotes[_"keyIdentifierString"_]]
passPhrase=pass:quotes[_"passPhraseString"_
file=_"fileName"_]
[commitSecurityKey=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「keyIdentifier」-内部キー管理にのみ適用されます
 a| 
セキュリティキーのラッパーである、読み取り可能な文字列。キー識別子は二重引用符（""）で囲みます。

内部セキュリティキーのキー識別子には、あとでキーを特定するのに役立つ文字を入力できます。表記規則は次のとおりです。

* キー識別子には最大189文字の英数字を入力できます。キー識別子には、次の文字は使用できません。
+
** スペース
** 句読点
** 記号


* 内部キーの「keyIdentifier'」パラメータを入力しない場合、コントローラは自動的に「keyIdentifier'」パラメータを生成します。


追加の文字が自動的に生成され、入力したキー識別子の文字列の末尾に追加されます。「keyIdentifier」パラメータに文字列を入力しない場合、キー識別子は自動的に生成される文字のみで構成されます。

[NOTE]
====
外部キー管理の場合、キー識別子は完全に自動生成されるため、このパラメータは無視されます。ストレージ・アレイにユーザー・ラベルがある場合'この自動的に生成される文字列は'sa'の後にストレージ・アレイのユーザー・ラベル'ストレージ・アレイの識別子'ランダムに生成された文字列で構成されますユーザラベル内の英数字以外の文字はすべて、アンダースコア（「_」）文字に変換されます。たとえば、abc#8というユーザラベルは、sa.abc_8`に変換されてから、キー識別子の残りの部分の先頭に付加されます。ユーザラベルのないストレージアレイの場合、キー識別子はストレージアレイの識別子とランダムに生成された文字列で構成されます。

====


 a| 
パスフレーズ
 a| 
セキュリティキーを外部ファイルに格納できるように、セキュリティキーを暗号化する文字列。パスフレーズは二重引用符（""）で囲みます。

有効なパスフレーズを作成するための正しい形式については、このコマンド概要 の「メモ」を参照してください。

パスフレーズは次の条件を満たしている必要があります。

* 8~32文字で指定する必要があります。
* 空白を含まない。
* 大文字を1つ以上含む。
* 小文字を1つ以上含む。
* 数字を1つ以上含む。
* 英数字以外の文字（<>@+など）を少なくとも1文字含める必要があります。


[NOTE]
====
パスフレーズがこれらの条件を満たしていない場合は、エラーメッセージが表示され、コマンドを再試行するように求められます。

====


 a| 
'file'
 a| 
セキュリティキーの保存先となるファイルパスとファイル名。例：

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
ファイル名の拡張子は「.slk」でなければなりません。

====
ファイルのパスと名前は二重引用符（""）で囲みます。



 a| 
commitSecurityKey -内部キー管理にのみ適用されます
 a| 
このパラメータは、すべてのFDEドライブのストレージアレイ、およびコントローラに対してセキュリティキーをコミットします。セキュリティキーがコミットされたあとに、ストレージアレイ内のセキュリティが有効なドライブ上のデータにアクセスするには、キーが必要です。データはキーを使用した場合にのみ読み取りまたは変更できます。また、データを使用不可にするか、ドライブを完全に消去する場合を除き、セキュアでないモードでドライブを使用することはできません。

デフォルト値はFALSEです。このパラメータがFALSEに設定されている場合は、別の「set storageArray securityKey」コマンドを送信して、ストレージアレイにセキュリティキーをコミットします。

|===


== 最小ファームウェアレベル

7.40で、内部キー管理が導入されました

8.40で、外部キー管理用に導入されました
