---
permalink: commands-a-z/create-diskpool.html 
sidebar: sidebar 
keywords: create, disk pool 
summary: create diskPoolコマンドは、指定したパラメータに基づいて新しいディスクプールを作成します。 
---
= ディスクプールを作成
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create diskPoolコマンドは'指定したパラメータに基づいて新しいディスク・プールを作成します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

ディスクプールを作成するには、ドライブのリストまたはディスクプールに使用するドライブのタイプを入力します。

[NOTE]
====
ドライブのリストを入力する場合は、すべてのドライブの容量が同じであることを確認してください。ドライブの容量が同じでない場合は、ディスクプール内の各ドライブで、最小ドライブと同じ容量が報告されます。

====


== 構文

[source, cli, subs="+macros"]
----
create diskPool
(drives=pass:quotes[_(trayID1_],pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDN_],pass:quotes[[_drawerIDN,_]]pass:quotes[_slotIDN)_]|
driveType=(fibre | SATA | SAS | NVMe4K))
 userLabel=pass:quotes[_"diskPoolName"_]
[driveCount=pass:quotes[_driveCountValue_]]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[warningThreshold=(pass:quotes[_warningThresholdValue_] | default)]
[criticalThreshold=(pass:quotes[_criticalThresholdValue_] | default)]
[criticalPriority=(highest|high|medium|low|lowest)]
[backgroundPriority=(highest|high|medium|low|lowest)]
[degradedPriority=(highest|high|medium|low|lowest)]
[securityType=(none | capable | enabled )]
[secureDrives=(fips | fde )]
[driveMediaType=(hdd | ssd | allMedia | unknown)]
[dataAssurance=(none|enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「ドライブ」
 a| 
作成するディスクプールに割り当てるドライブ。大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800、E5700、EF600、およびEF300コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。



 a| 
「userLabel」のように入力します
 a| 
新しいディスクプールに付ける名前。ディスクプール名は二重引用符（""）で囲みます。



 a| 
「driveCount」
 a| 
driveCountパラメータは'ディスク・プールの候補を指定した数に制限しますこのパラメータを使用する場合、HDDドライブに入力できる最小値は11です。SSDドライブの場合、入力できる最小値は8です。

[NOTE]
====
ドライブ数が11未満のSSDプールは、RAID 1ボリュームに制限されます。

====


 a| 
「warningThreshold」
 a| 
ストレージ容量がこの割合に達すると、ディスクプールの上限に近づいているという警告アラートが表示されます。整数値を使用します。たとえば、60という値は60%を意味します。最適な操作を行うには、このパラメータの値を「criticalThreshold」パラメータの値よりも小さくする必要があります。

有効な値は0~100です。

デフォルト値は50です。

このパラメータを0（ゼロ）に設定すると、警告アラートが無効になります。

これをデフォルトに設定した場合'警告アラートのしきい値はコントローラファームウェアによって決定されます



 a| 
「criticalThreshold」です
 a| 
ストレージ容量がこの割合に達すると、ディスクプールの上限に近づいているという重大アラートが表示されます。整数値を使用します。たとえば、70という値は70%を意味します。最適な操作を行うには'このパラメータの値をwarningThresholdパラメータの値よりも大きくする必要があります

有効な値は0~100です。

デフォルト値は85%です。

このパラメータを0（ゼロ）に設定すると、警告アラートと重大アラートの両方が無効になります。

これをデフォルトに設定した場合'クリティカル・アラートのしきい値はコントローラ・ファームウェアによって決定されます



 a| 
「criticalPriority」です
 a| 
ディスクプール上の重大イベントの再構築処理の優先度。たとえば、少なくとも2つのドライブ障害が発生したあとのディスクプールの再構築などです。

有効な値は'high`'high`'high`'medium`'low''low'lowest`ですデフォルト値は「highest」です。



 a| 
「backgroundPriority」
 a| 
ディスクプール上のバックグラウンド処理の優先度。

有効な値は'high`'high`'high`'medium`'low''low'lowest`ですデフォルト値は'low'です



 a| 
「degradedPriority」
 a| 
ディスクプール上のデグレードされたアクティビティの優先度。たとえば、1つのドライブ障害が発生したあとのディスクプールの再構築などです。

有効な値は'high`'high`'high`'medium`'low''low'lowest`ですデフォルト値は'high'です



 a| 
「securityType」
 a| 
ディスクプールの作成時にセキュリティレベルを指定する設定。ディスクプールのすべてのボリューム候補が、指定されたセキュリティタイプになります。

有効な設定は次のとおりです。

* 'none`--ボリューム候補は安全ではありません。
* capable --ボリューム候補はセキュリティを設定することができますが'セキュリティは有効になっていません
* 有効-ボリューム候補はセキュリティが有効になっています


デフォルト値は「 NONE 」です。



 a| 
「secureDrives」を参照してください
 a| 
ボリュームグループで使用するセキュアドライブのタイプ。有効な設定は次のとおりです。

* fips -- FIPS準拠のドライブのみを使用します
* fde -- FDE準拠のドライブを使用します


[NOTE]
====
このパラメータは'securityType'パラメータとともに使用しますsecurityTypeパラメータに「none」を指定すると、「secureDrives」パラメータの値は無視されます。これは、セキュアでないディスクプールにセキュアドライブタイプを指定する必要がないためです。

====
[NOTE]
====
「driveCount」パラメータも使用しない限り、このパラメータは無視されます。数を指定するのではなく、ディスクプールに使用するドライブを指定する場合は、必要なセキュリティタイプに基づいて、選択リストで適切なドライブタイプを指定します。

====


 a| 
driveMediaType
 a| 
ディスクプールに使用するドライブメディアのタイプ。

ストレージアレイ内に複数のタイプのドライブメディアがある場合は、このパラメータを使用する必要があります。

有効なドライブメディアは、次のとおりです。

* hdd --ハードドライブがある場合は'このオプションを使用します
* ssd --ソリッド・ステート・ディスクがある場合は'このオプションを使用します
* 不明--どのタイプのドライブメディアがドライブトレイにあるかわからない場合は'このオプションを使用します
* [allMedia]--ドライブトレイにあるすべてのタイプのドライブメディアを使用する場合に'このオプションを使用します


デフォルト値は「hdd」です。

[NOTE]
====
コントローラ・ファームウェアは'選択した設定を使用しても'HDD'とSSD'ドライブ・メディアを同じディスク・プールに混在させません

====


 a| 
「resourceProvisioningCapability」
 a| 
リソースプロビジョニング機能が有効かどうかを指定する設定。リソースプロビジョニングをディセーブルにするには、このパラメータをFALSEに設定します。デフォルト値は「true」です。

|===


== 注：

ディスクプール名は一意である必要があります。ユーザラベルには、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。ユーザラベルの最大文字数は30文字です。

使用可能な候補ドライブの中に、指定したパラメータを満たすものがない場合、コマンドは失敗します。通常は、QoS属性に一致するすべてのドライブが上位候補として返されます。ただし、ドライブリストを指定している場合は、候補として返される使用可能なドライブの一部が、QoS属性に一致しない場合があります。

オプションパラメータの値を指定しない場合は、デフォルト値が割り当てられます。



== ドライブ

「drivetype」パラメータを使用すると、そのドライブタイプの未割り当てドライブがすべてディスクプールの作成に使用されます。ディスクプール内の「drivetype」パラメータによって検出されるドライブの数を制限する場合は、「driveCount」パラメータを使用してドライブの数を指定できます。driveCountパラメータを使用できるのは、「drivetype」パラメータを使用する場合だけです。

drivs'パラメータは'大容量ドライブ・トレイと低容量ドライブ・トレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。

大容量ドライブトレイの仕様を入力したにもかかわらず、使用可能なドライブトレイがない場合は、ストレージ管理ソフトウェアからエラーメッセージが返されます。



== ディスクプールのアラートのしきい値

各ディスクプールには2段階の重大度レベルのアラートがあり、ディスクプールのストレージ容量が上限に近づいたときにユーザに通知します。アラートのしきい値は、ディスクプール内の使用可能な総容量に対する使用済み容量の割合です。アラートは次のとおりです。

* 警告--第1レベルのアラートですこのレベルは、ディスクプール内の使用済み容量が上限に近づいていることを示します。警告アラートのしきい値に達すると、要注意状態が生成され、ストレージ管理ソフトウェアにイベントが送信されます。警告しきい値よりも、重大しきい値のほうが優先されます。デフォルトの警告しきい値は50%です。
* 重大--最も重大なレベルのアラートですこのレベルは、ディスクプール内の使用済み容量が上限に近づいていることを示します。重大アラートのしきい値に達すると、要注意状態が生成され、ストレージ管理ソフトウェアにイベントが送信されます。警告しきい値よりも、重大しきい値のほうが優先されます。重大アラートのデフォルトのしきい値は85%です。


警告アラートの値は常に重大アラートの値より小さくする必要があります。警告アラートの値が重大アラートの値と同じ場合は、重大アラートのみが送信されます。



== ディスクプールのバックグラウンド処理

ディスクプールは次のバックグラウンド処理をサポートします。

* 再構築
* Instant Availability Format（IAF）
* の形式で入力し
* 容量の動的拡張（DCE）
* Dynamic Volume Expansion（DVE）（ディスクプールの場合、DVEは実際はバックグラウンド処理ではなく、同期処理としてサポートされています）。


ディスクプールでは、バックグラウンドコマンドはキューに配置されません。複数のバックグラウンドコマンドを順次開始できますが、複数のバックグラウンド処理を一度に開始すると、前に開始したコマンドの完了が遅延します。サポートされているバックグラウンド処理には、次の相対的な優先度レベルがあります。

. 再構築
. の形式で入力し
. IAF
. DCE




== セキュリティタイプ

ストレージ・アレイのセキュリティ設定を指定するには'securityType'パラメータを使用します

'securityType'パラメータを'enabled'に設定する前に'ストレージ・アレイのセキュリティ・キーを作成する必要がありますストレージ・アレイのセキュリティ・キーを作成するには'create storageArray securityKey'コマンドを使用します次のコマンドがセキュリティキーに関連しています。

* 「create storageArray securityKey」のように指定します
* 「export storageArray securityKey」のように指定します
* 「import storageArray securityKey」のように入力します
* 「set storageArray securityKey」のように指定します
* [Enable volumeGroup [volumeGroupName] security]を有効にします
* 「enable diskPool [diskPoolName]のセキュリティ」を参照してください




== セキュアドライブ

セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。secureDrivesパラメータを使用して、使用するセキュアドライブのタイプを指定します。使用できる値は'FIPs'とFDEです



== コマンドの例

[listing]
----
create diskPool driveType=SAS userLabel="FIPS_Pool" driveCount=11 securityType=capable secureDrives=fips;
----


== 最小ファームウェアレベル

7.83

8.20で、次のパラメータが追加されまし

* 「trayLossProtect`」
* 「drawerLossProtect`」


8.25で'secureDrives'パラメータが追加されました

8.63で'resourceProvisioningCapableパラメータが追加されました

11.73は'driveCount'パラメータを更新します
