---
permalink: commands-a-z/create-snmptrapdestination.html 
sidebar: sidebar 
keywords: register, snmp, trap, destination 
summary: create snmpTrapDestinationコマンドを使用すると、新しい簡易ネットワーク管理プロトコル（SNMP）トラップの送信先が作成されます。トラップの送信先は、トラップメッセージを受信するSNMPマネージャです。 
---
= SNMPトラップの宛先を登録する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create snmpTrapDestinationコマンドは、新しい簡易ネットワーク管理プロトコル（SNMP）トラップの宛先を作成します。トラップの送信先は、トラップメッセージを受信するSNMPマネージャです。



== サポートされているアレイ

このコマンドは、E4000、E2800、E5700、EF600、またはEF300の個 々 のストレージアレイに適用されます。E2700またはE5600のストレージアレイに対しては機能しません。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
create snmpTrapDestination trapReceiverIP=ipAddress
    (communityName=pass:quotes[_"communityName" | (userName="userName"_] [engineId=(local | engineId)]))
    [sendAuthenticationFailureTraps=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「trapReceverIP」と入力します
 a| 
トラップメッセージの送信先であるSNMPマネージャのIPアドレス。



 a| 
「CommunityName」の略
 a| 
トラップメッセージを送信するSNMPコミュニティの名前。



 a| 
「ユーザ名」
 a| 
トラップメッセージを送信するSNMPユーザの名前。



 a| 
「engineID」
 a| 
トラップメッセージを送信するSNMPユーザのエンジンID。同じユーザ名を使用するUSMユーザが複数ある場合は、エンジンIDが必要です。ローカルSNMPエージェントを指定する値は「[.code]`local`」です。ローカルSNMPエージェントは権限のあるエージェントで、16進数の数字で、リモートSNMPエージェントエンジンIDを指定します。



 a| 
「sendAuthenticationFailureTraps」
 a| 
このパラメータは、SNMPマネージャへの認証エラーメッセージの送信をオンまたはオフにします。認証失敗メッセージを送信するには、パラメータを「true」に設定します。認証失敗メッセージを送信しないようにするには、パラメータをFALSEに設定します。デフォルトは「true」です。

|===


== 最小ファームウェアレベル

8.30
