---
permalink: commands-a-z/create-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: create, asynchronous, mirror, group 
summary: create asyncMirrorGroupコマンドを使用すると、ローカルストレージアレイとリモートストレージアレイの両方に、新しい空の非同期ミラーグループが作成されます。 
---
= 非同期ミラーグループの作成 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create asyncMirrorGroup'コマンドは'ローカル・ストレージ・アレイとリモート・ストレージ・アレイの両方に'新しい空の非同期ミラー・グループを作成します



== サポートされているアレイ

このコマンドは、一部制限付きで個々のストレージアレイを環境 接続します。E2700またはE5600のアレイに対して実行する場合は、制限はありません。

[NOTE]
====
このコマンドは、E4000、E2800、E5700、EF600、およびEF300のプラットフォームではサポートされていません。

====


== ロール

該当なし



== コンテキスト（Context）

非同期ミラーグループとはミラーペアのコンテナであり、複数のミラーペアを格納して1つのエンティティとして管理できます。非同期ミラーグループを作成すると、グループ内のすべてのミラーペアの同期設定を定義できます。非同期ミラーグループ内の各ミラーペアでは、同じ同期設定、プライマリとセカンダリのロール、書き込みモードが共有されています。

非同期ミラーグループには、ミラーリングに使用されるローカルストレージアレイとリモートストレージアレイが関連付けられます。ローカルストレージアレイは非同期ミラーグループのプライマリ側であり、リモートストレージアレイは非同期ミラーグループのセカンダリ側です。ローカルストレージアレイの非同期ミラーグループに追加したすべてのボリュームには、ミラー関係のプライマリロールが割り当てられます。そのあとに、リモートストレージアレイの非同期ミラーグループに追加したすべてのボリュームには、ミラー関係のセカンダリロールが割り当てられます。

ローカル・ストレージ・アレイ上でCreate Asynchronous Mirror Groupコマンドを実行していることを確認します非同期ミラーグループの作成は、ミラー関係のプライマリロールが割り当てられたボリュームを含むストレージアレイから開始されます。Create Asynchronous Mirror Groupコマンドを使用して、ミラー関係のセカンダリ・ロールを持つボリュームを含むリモート・ストレージ・アレイのIDを指定します。



== 構文

[source, cli, subs="+macros"]
----
create asyncMirrorGroup userLabel=pass:quotes[_"asyncMirrorGroupName"_]
(remoteStorageArrayName=pass:quotes[_"storageArrayName"_] | remoteStorageArrayWWN=pass:quotes[_"wwID"_])
[remotePassword=pass:quotes[_"password"_]
interfaceType=(FC | iSCSI)
[syncInterval=pass:quotes[_integer_](minutes | hours | days)]
[warningSyncThreshold=pass:quotes[_integer_](minutes | hours | days)]
[warningRecoveryThreshold=pass:quotes[_integer_](minutes | hours | days)]
[warningThresholdPercent=pass:quotes[_percentValue_]]
[autoResync=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「userLabel」のように入力します
 a| 
作成する新しい非同期ミラーグループの名前。新しい非同期ミラーグループ名は二重引用符（""）で囲みます。

この名前は、ローカルストレージアレイとリモートストレージアレイで一意である必要があります。



 a| 
remoteStorageArrayName
 a| 
非同期ミラーグループをミラーリングするリモートストレージアレイの名前。ストレージアレイ名は二重引用符（""）で囲みます。

リモートストレージアレイの接続タイプはローカルストレージアレイと同じである必要があります。



 a| 
remoteStorageArrayWWN
 a| 
非同期ミラーグループをミラーリングするリモートストレージアレイのWorld Wide Identifier（WWID）。ストレージアレイ名の代わりにWWIDを使用してストレージアレイを識別できます。WWIDは山かっこ（<>）で囲みます。

リモートストレージアレイの接続タイプはローカルストレージアレイと同じである必要があります。



 a| 
「remotePassword」
 a| 
リモートストレージアレイのパスワード。このパラメータは、リモートストレージアレイがパスワードで保護されている場合に使用します。パスワードは二重引用符（""）で囲みます。



 a| 
'InterfaceType'
 a| 
使用する接続の種類をFibre ChannelファブリックまたはiSCSIインターフェイスで指定します。（デフォルトはFibre Channel）。 ローカルストレージアレイとリモートストレージアレイが適切なFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続されている必要があります。



 a| 
「syncInterval」
 a| 
変更されたデータの更新をローカルストレージアレイからリモートストレージアレイに自動的に送信する間隔を指定します。時間は、分、時間、または日数で指定できます。

[NOTE]
====
整数と時間の間にスペースを追加しないでください。

====
例:「10分」



 a| 
「warningSyncThreshold」
 a| 
非同期ミラーグループ内のすべてのボリュームの同期にかかる時間が指定した時間よりも長い場合に、警告がトリガーされるまでの待機時間を指定します。時間は、分、時間、または日数で指定できます。

[NOTE]
====
整数と時間の間にスペースを追加しないでください。

====
例:「30分」



 a| 
「warningRecoveryThreshold」
 a| 
リモートストレージアレイのポイントインタイムイメージの自動データ更新が指定した時間よりも古くなった場合に、警告がトリガーされるまでの待機時間を指定します。しきい値は、前回の更新終了時点からの経過日数で定義します。時間は、分、時間、または日数で指定できます。

[NOTE]
====
リカバリポイントのしきい値は、同期間隔のしきい値の2倍に設定する必要があります。

====
[NOTE]
====
整数と時間の間にスペースを追加しないでください。

====
例:「60分」



 a| 
「warningThresholdPercent」
 a| 
ミラーリポジトリボリュームの容量が指定した割合に達したときに、警告がトリガーされるまでの待機時間を指定します。しきい値は、残りの容量の割合（%）で定義します。



 a| 
「autoResync」
 a| 
非同期ミラーグループ内の非同期ミラーペアのプライマリボリュームとセカンダリボリュームの間の自動再同期の設定。このパラメータには次の値があります。

* [enabled]--自動再同期がオンになっています何もしなくても、プライマリボリュームとセカンダリボリュームは再同期されます。
* disabled --自動再同期がオフになっていますプライマリ・ボリュームとセカンダリ・ボリュームを再同期するには'resume asyncMirrorGroupコマンドを実行する必要があります


|===


== 注：

* ミラーアクティビティに使用されるローカルストレージアレイとリモートストレージアレイで非同期ミラーリング機能を有効化し、アクティブ化する必要があります。
* 名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。名前の最大文字数は30文字です。
* ローカルとリモートのストレージアレイがFibre ChannelファブリックまたはiSCSIインターフェイスを介して接続されている必要があります。
* パスワードは、管理ドメイン内の各ストレージアレイに保存されます。以前にパスワードが設定されていない場合は、パスワードは必要ありません。パスワードは、最大30文字の英数字を任意に組み合わせて指定できます。（ストレージアレイのパスワードは、「set storageArray」コマンドを使用して定義できます）。
* 設定によっては、1つのストレージアレイに作成できる非同期ミラーグループの数に制限があります。
* 非同期ミラーグループは空で作成され、あとからミラーペアが追加されます。非同期ミラーグループにはミラーペアのみを追加できます。各ミラーペアは1つの非同期ミラーグループにのみ関連付けられます。
* 非同期ミラーリングプロセスは、定義された同期間隔で開始されます。定期的な「ポイントインタイム」イメージは、ボリューム全体ではなく変更されたデータのみがコピーされたときにレプリケートされます。




== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
