---
permalink: commands-a-z/create-initiator.html 
sidebar: sidebar 
keywords: create, initiator 
summary: イニシエータオブジェクトの作成には、create initiatorコマンドを使用します。 
---
= イニシエーターの作成 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create initiatorコマンドは'イニシエータ・オブジェクトを作成します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
このコマンドは、廃止されたを置き換えます xref:create-iscsiinitiator.adoc[iSCSIイニシエータを作成する] コマンドを実行します

====
[NOTE]
====
このコマンドは、iSCSI、iSER、NVMe over RoCE、NVMe over InfiniBand、NVMe over Fibre Channelに対してのみ使用できます。

====


== 構文

[source, cli]
----
create initiator identifier="initiatorQualifiedName" userLabel="initiatorName" host="hostName"
interfaceType=(iscsi | iser | nvmeof) [chapSecret="securityKey"]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「identifier`」
 a| 
イニシエータを作成するための識別子修飾名（iqnやnqnなど）を指定できます。識別子は二重引用符（""）で囲みます。



 a| 
「userLabel」のように入力します
 a| 
イニシエータのユーザラベルを指定できます。名前は二重引用符（""）で囲みます。



 a| 
ホスト
 a| 
イニシエータのインストール先のホスト名を指定できます。名前は二重引用符（""）で囲みます。



 a| 
'InterfaceType'
 a| 
イニシエータが対応するインターフェイスタイプを指定できます。有効な選択肢は、iscsi、iser、またはnvmeofです。



 a| 
「チャプターシークレット」
 a| 
ピア接続の認証に使用するセキュリティキーを入力できます。セキュリティキーは二重引用符（""）で囲みます。このパラメータは、iSCSIおよびiSERのホストインターフェイスタイプにのみ該当します。

|===


== 最小ファームウェアレベル

8.41
