---
permalink: commands-a-z/create-ssdcache.html 
sidebar: sidebar 
keywords: create, ssd, cache 
summary: create ssdCacheコマンドは、ソリッドステートディスク（SSD）を使用してストレージアレイの読み取りキャッシュを作成します。 
---
= SSDキャッシュを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
create ssdCacheコマンドは'SSD（ソリッド・ステート・ディスク）を使用してストレージ・アレイのリード・キャッシュを作成します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700のアレイを含む個々のストレージアレイを環境 で処理します。 すべてのSMcliパッケージがインストールされていること。



== ロール

このコマンドをE2800またはE5700のストレージアレイに対して実行するには、Support Adminロールが必要です。



== コンテキスト（Context）

ハイパフォーマンスのSSDを使用して読み取りデータをキャッシュすると、アプリケーションのI/Oパフォーマンスと応答時間が向上し、特に高IOPのワークロードで、異なるワークロード間のパフォーマンスが継続的に向上します。SSDキャッシュにより、高価な高速SSDを最大限に活用できます。SSDキャッシュは、コントローラDRAM内のプライマリキャッシュに加えて使用されます。コントローラキャッシュでは、データはホスト読み取り後にDRAMに格納されます。SSDキャッシュでは、データはユーザ指定のベースボリュームからコピーされ、SSDにキャッシュされます。



== 構文

[listing, subs="+macros"]
----
create ssdCache userLabel=pass:quotes[_"ssdCacheName"_]
drives=pass:quotes[_(trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn,[drawerIDn,_]]pass:quotes[_slotIDn_)]
[updateExistingVolumes=(TRUE|FALSE)]
[securityType=(none|capable|enabled)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「userLabel」のように入力します
 a| 
新しいSSDキャッシュに付ける名前。SSDキャッシュ名は二重引用符（""）で囲みます。



 a| 
「ドライブ」
 a| 
SSDキャッシュの作成に使用するドライブ。大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
updateExistingVolumes
 a| 
このオプションパラメータは、ストレージアレイ内のすべての既存ボリュームに対してSSDキャッシュを有効にするかどうかを指定します。既存のすべてのボリュームに対してSSDキャッシュを有効にするには、このパラメータを「true」に設定します。あとで個々のボリュームに対してSSDキャッシュを有効にする場合は、このパラメータをFALSEに設定します。デフォルト値は「true」です。



 a| 
「securityType」
 a| 
このオプションのパラメータは、SSDキャッシュの作成時にセキュリティレベルを指定します。有効な設定は次のとおりです。

* 'none'- SSDキャッシュはセキュアではありません。
* capable - SSDキャッシュにはセキュリティを設定する機能がありますが、セキュリティは有効になっていません。
* [Enabled]：SSDキャッシュでセキュリティがイネーブルになっています。


|===


== 注：

名前には、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。名前の最大文字数は30文字です。

1つのストレージアレイに配置できるSSDキャッシュは1つだけです。

ハードディスクドライブを使用して作成されたボリュームのみがSSDキャッシュを使用できます。SnapshotイメージではSSDキャッシュを有効にすることはできません。

SSDキャッシュのすべてのSSDがData Assurance（DA）対応であり、DA機能が有効になっている場合、DAはSSDキャッシュに対して自動的に有効になり、無効にすることはできません。また、DA非対応のSSDをDA対応のSSDキャッシュに追加することはできません。



== 最小ファームウェアレベル

7.84

8.20 _M3 - FDEドライブがサポートされるようになりました。「securityType」パラメータが追加されました。
