---
permalink: commands-a-z/create-host.html 
sidebar: sidebar 
keywords: create, host 
summary: create hostコマンドを実行すると、新しいホストが作成されます。 
---
= ホストを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
create hostコマンドを実行すると'新しいホストが作成されます



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

E2700およびE5600のストレージアレイの場合、新しいホストの作成先とするホストグループを指定しない場合、新しいホストはデフォルトグループ内に作成されます。



== 構文

[listing, subs="+macros"]
----
create host userLabel=pass:quotes[_"hostName"_]
[hostGroup=pass:quotes[(_"hostGroupName"_] | defaultGroup)]
[hostType=(hostTypeIndexLabel | hostTypeIndexNumber)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「userLabel」のように入力します
 a| 
作成するホストに付ける名前。ホスト名は二重引用符（""）で囲みます。



 a| 
「hostGroup」と入力します
 a| 
新しいホストの作成先のホストグループの名前。ホストグループ名は二重引用符（""）で囲みます。（ホスト・グループが存在しない場合は'create hostGroup'コマンドを使用して新しいホスト・グループを作成できます） defaultGroupオプションは'ボリュームがマップされているホストを含むホスト・グループです



 a| 
「hostType」
 a| 
ホストタイプを識別するインデックスラベルまたはインデックス番号。使用可能なホストタイプ識別子のリストを生成するには、「show storageArray hostTypeTable」コマンドを使用します。ホストタイプに特殊文字が含まれている場合は、ホストタイプを二重引用符（""）で囲みます。

|===


== 注：

名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。名前の最大文字数は30文字です。

ホストとは、ストレージアレイに接続されていて、ホストポート経由でストレージアレイ上のボリュームにアクセスするコンピュータのことです。個々のホストに特定のマッピングを定義できます。また、ボリュームへのアクセスを共有するホストグループにホストを割り当てることもできます。

ホストグループはオプションのトポロジ要素であり、同じボリュームへのアクセスを共有する一連のホストを指定するかどうかを定義できます。ホストグループは論理エンティティです。ホストグループは、同じボリュームへのアクセスを共有するホストが複数ある場合にのみ定義してください。

作成するホストの配置先となるホストグループを指定しない場合、新しく定義されたホストはデフォルトのホストグループに属します。



== 最小ファームウェアレベル

5.20

7.10で、「hostType」パラメータが追加されました。
