---
permalink: commands-a-z/create-volumegroup.html 
sidebar: sidebar 
keywords: create, volume, group 
summary: create volumeGroupコマンドは、一連の未割り当てドライブを入力したときに、空き容量のあるボリュームグループまたは1個のボリュームを含むボリュームグループを作成します。 
---
= ボリュームグループの作成 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create volumegroupコマンドは'未割り当てドライブのセットを入力すると'空き容量のあるボリューム・グループまたは1つのボリュームを持つボリューム・グループを作成します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
create volumeGroup
drives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]pass:quotes[_slotIDn)_]
raidLevel=(0 | 1 | 3 | 5 | 6)
userLabel=pass:quotes[_"volumeGroupName"_]
[driveMediaType=(HDD | SSD | unknown | allMedia)]
[driveType=(SAS | NVMe4K)]
[trayLossProtect=(TRUE | FALSE)]
[drawerLossProtect=(TRUE | FALSE)]
[securityType=(none | capable | enabled )]
[dataAssurance=(none | enabled)]
[resourceProvisioningCapable=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「ドライブ」
 a| 
作成するボリュームグループに割り当てるドライブ。大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
raidLevel
 a| 
ボリュームが含まれているボリュームグループのRAIDレベル。有効な値は'0`'1' 3`'5`または'6`です



 a| 
「userLabel」のように入力します
 a| 
新しいボリュームグループに付ける名前。ボリュームグループ名は二重引用符（""）で囲みます。



 a| 
driveMediaType
 a| 
ボリュームグループに使用するドライブメディアのタイプ

ストレージアレイ内に複数のタイプのドライブメディアがある場合は、このパラメータを使用する必要があります。

有効なドライブメディアは、次のとおりです。

* [HDD]--ドライブトレイにハードドライブがある場合は'このオプションを使用します
* SSD'--ドライブトレイにソリッドステートドライブがある場合は'このオプションを使用します
* 不明--どのタイプのドライブメディアがドライブトレイにあるかわからない場合は'このオプションを使用します
* [allMedia]--ドライブトレイにあるすべてのタイプのドライブメディアを使用する場合に'このオプションを使用します




 a| 
「ドライブタイプ」
 a| 
ボリュームグループで使用するドライブのタイプ。ドライブタイプを混在させることはできません。

ストレージアレイ内に複数のドライブタイプがある場合は、このパラメータを使用する必要があります。

有効なドライブタイプは、次のとおりです。

* 「SAS」
* 「NVMe4K」


ドライブタイプを指定しない場合、指定したドライブがこのドライブタイプであるかどうかはコードで検証されません。



 a| 
「trayLossProtect`」
 a| 
ボリュームグループを作成するときにトレイ損失の保護を有効にする設定。トレイ損失の保護を有効にするには'このパラメータをTRUEに設定しますデフォルト値は'FALSE'です



 a| 
「drawerLossProtect`」
 a| 
ボリュームグループを作成するときにドロワー損失の保護を有効にする設定。ドロワー損失の保護を有効にするには、このパラメータを「true」に設定します。デフォルト値は'FALSE'です



 a| 
「securityType」
 a| 
ボリュームグループおよび関連するすべてのボリュームの作成時にセキュリティレベルを指定する設定。有効な設定は次のとおりです。

* 'none`--ボリュームグループとボリュームは安全ではありません。
* capable --ボリュームグループとボリュームにはセキュリティを設定する機能がありますが'セキュリティは有効になっていません
* 有効-ボリューム・グループとボリュームでセキュリティが有効になっています




 a| 
「resourceProvisioningCapability」
 a| 
リソースプロビジョニング機能が有効かどうかを指定する設定。リソースプロビジョニングをディセーブルにするには、このパラメータをFALSEに設定します。デフォルト値は「true」です。

|===


== ドライブとボリュームグループ

ボリュームグループは、ストレージアレイのコントローラによって論理的にグループ化された一連のドライブです。ボリュームグループ内のドライブ数は、RAIDレベルとコントローラファームウェアによって制限されます。ボリュームグループを作成する際は、次のガイドラインに従ってください。

* ファームウェアバージョン7.10以降では、あとから使用するために容量をリザーブできるように、空のボリュームグループを作成できます。
* 1つのボリュームグループでドライブタイプを混在させることはできません。
* 1つのボリュームグループでHDDドライブとSSDドライブを混在させることはできません。
* ボリュームグループの最大ドライブ数は、次の条件によって異なります。
+
** コントローラのタイプ
** RAIDレベル


* RAIDレベルには、0、1、3、5、および6があります。
+
** RAIDレベル3、RAIDレベル5、またはRAIDレベル6のボリュームグループに配置できるドライブは最大30本です。
** RAIDレベル6のボリュームグループには、少なくとも5本のドライブが必要です。
** RAIDレベル1のボリュームグループに4本以上のドライブがある場合、ストレージ管理ソフトウェアはボリュームグループをRAIDレベル10に自動的に変換します。RAIDレベル1 + RAIDレベル0です。


* トレイ/ドロワー損失の保護を有効にする場合のその他の条件については、次の表を参照してください。


|===
| レベル | トレイ損失の保護の基準 | 必要なトレイの最小数 


 a| 
ディスク・プール
 a| 
ディスクプールに同じトレイのドライブが3本以上含まれない
 a| 
6.



 a| 
「RAID 6」
 a| 
ボリュームグループに同じトレイのドライブが3本以上含まれない
 a| 
3.



 a| 
RAID 3またはRAID 5
 a| 
ボリュームグループ内のドライブがすべて別々のトレイに配置されている
 a| 
3.



 a| 
RAID 1
 a| 
RAID 1ペアのドライブがそれぞれ別のトレイに配置されている
 a| 
2.



 a| 
RAID 0
 a| 
トレイ損失の保護は実現できない。
 a| 
該当なし

|===
|===
| レベル | ドロワー損失の保護の基準 | 必要なドロワーの最小数 


 a| 
ディスク・プール
 a| 
プールに5つのドロワーすべてのドライブが含まれていて、各ドロワーに同じ数のドライブが配置されている。60ドライブのトレイでは、ディスクプールの構成が15、20、25、30、35の場合にドロワー損失の保護を実現できます。 40、45、50、55、または60ドライブ。
 a| 
5.



 a| 
「RAID 6」
 a| 
ボリュームグループに同じドロワーのドライブが3本以上含まれない。
 a| 
3.



 a| 
RAID 3またはRAID 5
 a| 
ボリュームグループ内のドライブがすべて別々のドロワーに配置されている。
 a| 
3.



 a| 
RAID 1
 a| 
ミラーペアのドライブがそれぞれ別のドロワーに配置されている。
 a| 
2.



 a| 
RAID 0
 a| 
ドロワー損失の保護は実現できない。
 a| 
該当なし

|===


== ホットスペア

ボリュームグループでは、データを保護するための重要な戦略は、ストレージアレイ内の使用可能なドライブをホットスペアドライブとして割り当てることです。ホットスペアは、データが格納されていないドライブで、RAID 1、RAID 3、RAID 5、またはRAID 6のボリュームグループでドライブに障害が発生した場合に、ストレージアレイでスタンバイとして機能します。ホットスペアを使用すると、ストレージアレイの冗長性が向上します。

一般に、ホットスペアドライブには、保護対象のドライブの使用済み容量以上の容量が必要です。ホットスペアドライブのメディアタイプ、インターフェイスタイプ、および容量は、保護対象のドライブと同じである必要があります。

ストレージアレイのドライブで障害が発生した場合、通常は障害が発生したドライブの代わりにホットスペアが自動的に使用されます。ドライブ障害の発生時にホットスペアが使用可能であれば、冗長性データパリティを使用してホットスペアにデータが再構築されます。データ退避のサポートでは、障害が発生したドライブとしてマークされる前に、データをホットスペアにコピーすることもできます。

障害が発生したドライブを物理的に交換したら、次のいずれかのオプションを使用してデータをリストアできます。

障害が発生したドライブを交換すると、ホットスペアのデータが交換用ドライブにコピーされます。この操作をコピーバックと呼びます。

ホットスペアドライブをボリュームグループの永続的メンバーとして指定する場合は、コピーバック処理は不要です。

ボリュームグループのトレイ損失の保護およびドロワー損失の保護が可能かどうかは、ボリュームグループを構成するドライブの場所によって異なります。ドライブの障害とホットスペアドライブの場所によっては、トレイ損失の保護とドロワー損失の保護が失われる場合があります。トレイ損失の保護とドロワー損失の保護が影響を受けないようにするには、障害が発生したドライブを交換してコピーバックプロセスを開始する必要があります。

ストレージアレイでは、Data Assurance（DA）が有効なボリュームのホットスペア対象範囲としてDA対応ドライブが自動的に選択されます。

DAが有効なボリュームのホットスペア対象範囲のストレージアレイにDA対応ドライブがあることを確認してください。DA対応ドライブの詳細については、Data Assurance機能を参照してください。

セキュリティ対応（FIPSおよびFDE）ドライブは、セキュリティ対応とセキュリティ非対応の両方のドライブのホットスペアとして使用できます。セキュリティ非対応ドライブは、他のセキュリティ非対応ドライブに対して、また、ボリュームグループでセキュリティが有効になっていない場合はセキュリティ対応ドライブに対しても、対応可能です。FIPSボリュームグループは、FIPSドライブのみをホットスペアとして使用できます。ただし、FIPSホットスペアは、セキュリティ非対応、セキュリティ対応、およびセキュリティ有効のボリュームグループに対して使用できます。

ホットスペアがない場合でも、ストレージアレイの動作中に、障害が発生したドライブを交換できます。RAID 1、RAID 3、RAID 5、またはRAID 6のボリュームグループの一部であるドライブは、冗長性データパリティを使用して、交換用ドライブにデータを自動的に再構築します。この操作を再構築と呼びます。



== セグメントサイズ

コントローラがボリューム内の1つのドライブに書き込めるデータブロックの数は、セグメントのサイズによって決まります。各データブロックには512バイトのデータが格納されます。データブロックはストレージの最小単位です。セグメントのサイズによって、格納されるデータブロックの数が決まります。たとえば、8KBのセグメントには16個のデータブロックが含まれます。64KBのセグメントには128個のデータブロックが含まれます。

セグメントサイズの値を入力すると、その値は、実行時にコントローラで指定される、サポートされている値と照合されます。入力した値が無効な場合、コントローラは有効な値のリストを返します。1つの要求に対して1つのドライブを使用することで、他のドライブでは他の要求に同時に対応できます。ボリュームが属している環境で、1人のユーザが大量のデータ（マルチメディアなど）を転送している場合は、1つのデータ転送要求を1つのデータストライプで処理すると、パフォーマンスが最大化されます。（データストライプはセグメントサイズであり、これに、データ転送に使用されるボリュームグループ内のドライブ数が掛けられます）。 この場合、同じ要求に対して複数のドライブが使用されますが、各ドライブへのアクセスは1回だけとなります。

マルチユーザデータベースまたはファイルシステムのストレージ環境で最適なパフォーマンスを実現するには、データ転送要求を満たすために必要なドライブ数が最小限になるように、セグメントサイズを設定します。



== 使用上のヒント

[NOTE]
====
「cacheReadPrefetch」パラメータまたは「segmentSize」パラメータの値を入力する必要はありません。値を入力しない場合'コントローラ・ファームウェアは'filesystem'をデフォルト値として'usageHint'パラメータを使用します「usageHint」パラメータの値と「cacheReadPrefetch」パラメータの値、または「segmentSize」パラメータの値を入力しても、原因 にエラーは表示されません。「cacheReadPrefetch」パラメータまたは「segmentSize」パラメータに入力する値は、「usageHint」パラメータの値よりも優先されます。さまざまな使用方法のヒントに対するセグメントサイズおよびキャッシュ読み取りプリフェッチの設定を、次の表に示します。

====
|===
| 使用方法のヒント | セグメントサイズの設定 | 動的キャッシュ読み取りプリフェッチの設定 


 a| 
ファイルシステム
 a| 
128 KB
 a| 
有効



 a| 
データベース
 a| 
128 KB
 a| 
有効



 a| 
マルチメディア
 a| 
256 KB
 a| 
有効

|===


== キャッシュ読み取りプリフェッチ

キャッシュ読み取りプリフェッチを使用すると、コントローラは、ホストによって要求されたデータブロックをドライブから読み取ってキャッシュにコピーすると同時に、追加のデータブロックをキャッシュにコピーできます。これにより、以降のデータ要求をキャッシュから処理できる可能性が高くなります。キャッシュ読み取りプリフェッチは、シーケンシャルデータ転送を使用するマルチメディアアプリケーションにとって重要です。「cacheReadPrefetch」パラメータの有効な値は「TRUE」または「FALSE」です。デフォルトは「true」です。



== セキュリティタイプ

ストレージ・アレイのセキュリティ設定を指定するには'securityType'パラメータを使用します

'securityType'パラメータを'enabled'に設定する前に'ストレージ・アレイのセキュリティ・キーを作成する必要がありますストレージ・アレイのセキュリティ・キーを作成するには'create storageArray securityKey'コマンドを使用します次のコマンドがセキュリティキーに関連しています。

* 「create storageArray securityKey」のように指定します
* 「export storageArray securityKey」のように指定します
* 「import storageArray securityKey」のように入力します
* 「set storageArray securityKey」のように指定します
* [Enable volumeGroup [volumeGroupName] security]を有効にします
* 「enable diskPool [diskPoolName]のセキュリティ」を参照してください




== セキュアドライブ

セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。secureDrivesパラメータを使用して、使用するセキュアドライブのタイプを指定します。使用できる値は'FIPs'とFDEです



== Data Assurance管理

Data Assurance（DA）機能を使用すると、ストレージシステム全体のデータの整合性が向上します。ホストとドライブの間でデータが移動されたときにストレージアレイがエラーの有無をチェックします。この機能を有効にすると、ボリューム内の各データブロックに巡回冗長検査（CRC）と呼ばれるエラーチェック用のコードが付加されます。データブロックが移動されると、ストレージアレイはこれらのCRCコードを使用して、転送中にエラーが発生したかどうかを判断します。破損している可能性があるデータはディスクに書き込まれず、ホストにも返されません。

DA機能を使用する場合は、まず最初にDAがサポートされているドライブのみを含むプールまたはボリュームグループを作成します。次に、DA対応ボリュームを作成します。最後に、DAに対応したI/Oインターフェイスを使用してDA対応ボリュームをホストにマッピングします。DAに対応したI/Oインターフェイスには、Fibre Channel、SAS、iSER over InfiniBand（iSCSI Extensions for RDMA/IB）があります。iSCSI over EthernetやSRP over InfiniBandではDAはサポートされていません。

[NOTE]
====
すべてのドライブがDA対応の場合は'dataAssuranceパラメータをEnabledに設定し'特定の操作でDAを使用できますたとえば、DA対応ドライブが含まれるボリュームグループを作成し、そのボリュームグループにDA対応のボリュームを作成できます。DA対応ボリュームを使用する他の処理には、DA機能をサポートするオプションがあります。

====
「dataAssurance」パラメータが「enabled」に設定されている場合、Data Assurance対応のドライブのみがボリューム候補とみなされます。それ以外の場合は、Data Assurance対応ドライブとData Assurance対応でないドライブの両方が考慮されます。DA対応ドライブのみが使用可能な場合、新しいボリュームグループは、有効なDA対応ドライブを使用して作成されます。



== 最小ファームウェアレベル

7.10

7.50で、「securityType」パラメータが追加されました。

7.60で'drawerID'ユーザー入力'driveMediaType'パラメータ'およびdrawerLossProtect'パラメータが追加されました

7.75で'dataAssuranceパラメータが追加されました

8.63で'resourceProvisioningCapableパラメータが追加されました
