---
permalink: commands-a-z/create-hostport.html 
sidebar: sidebar 
keywords: create, host, port 
summary: create HostPortコマンドは、ホストバスアダプタ（HBA）またはホストチャネルアダプタ（HCA）に新しいホストポートIDを作成します。 
---
= ホストポートの作成 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create HostPortコマンドは'ホスト・バス・アダプタ（HBA）またはホスト・チャネル・アダプタ（HCA）に新しいホスト・ポートIDを作成します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

ホストポートIDは、コントローラに対する物理的なHBAまたはHCAホストポートを表すソフトウェア値です。正しいホストポートIDがないと、コントローラはホストポートから指示やデータを受信できません。



== 構文

[source, cli, subs="+macros"]
----
create hostPort identifier=pass:quotes[_("wwID"_ | "_gid"_)
userLabel="_portLabel"_]
[host=pass:quotes[_"hostName"_]]
[interfaceType=(FC | SAS | IB)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「identifier`」
 a| 
HBAまたはHCAホストポートの8バイトのWorld Wide Identifier（WWID）または16バイトのグループ識別子（GID）。WWIDまたはGIDは二重引用符（""）で囲みます。



 a| 
「userLabel」のように入力します
 a| 
新しいHBAまたはHCAホストポートに付ける名前。ホストポートラベルは二重引用符（""）で囲みます。



 a| 
ホスト
 a| 
HBAまたはHCAホストポートを定義するホストの名前。ホスト名は二重引用符（""）で囲みます。



 a| 
'InterfaceType'
 a| 
ホストポートのインターフェイスタイプの識別子。

ホストポートインターフェイスのタイプの選択肢は次のとおりです。

* 'FC'--ファイバチャネル
* sas --シリアル接続SCSI
* `ib`-- InfiniBand


FCまたはSASを選択する場合は8バイトのWWIDが必要です。IBを選択する場合は16バイトのグループ識別子（GID）が必要です。

インタフェースのタイプを指定しない場合'FC'がホストポートのデフォルトインタフェースとして使用されます

|===


== 注：

HBAホストポートまたはHCAホストポートは、ホストコンピュータにあるホストバスアダプタ上またはホストチャネルアダプタ上の物理接続です。HBAホストポートまたはHCAホストポートは、ストレージアレイ内のボリュームへのホストアクセスを提供します。HBAまたはHCAの物理接続が1つだけ（ホストポート1つ）の場合、ホストポートとホストバスアダプタまたはホストチャネルアダプタは同義です。

名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。名前の最大文字数は30文字です。



== 最小ファームウェアレベル

5.20

7.10で、「hostType」パラメータが廃止されました。「hostType」パラメータが「create host」コマンドに追加されました。

7.32で、'InterfaceType'パラメータが追加されました。
