---
permalink: commands-a-z/create-syncmirror.html 
sidebar: sidebar 
keywords: create, synchronous, mirroring 
summary: create SyncMirror コマンドは、同期リモートミラーペアのプライマリボリュームとセカンダリボリュームの両方を作成します。このコマンドは、書き込みモード（同期書き込みモードまたは非同期書き込みモード）と同期優先度も設定します。 
---
= 同期ミラーリングの作成 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create SyncMirror コマンドは'同期リモート・ミラー・ペアのプライマリ・ボリュームとセカンダリ・ボリュームの両方を作成しますこのコマンドは、書き込みモード（同期書き込みモードまたは非同期書き込みモード）と同期優先度も設定します。



== サポートされているアレイ

このコマンドは、一部制限付きで個々のストレージアレイを環境 接続します。E2700またはE5600のアレイに対して実行する場合は、制限はありません。

[NOTE]
====
このコマンドは、E4000、E2800、E5700、EF600、およびEF300のプラットフォームではサポートされていません。

====


== ロール

該当なし



== コンテキスト（Context）

[NOTE]
====
このコマンドの以前のバージョンでは、機能識別子は「remoteMirror」でした。この機能識別子は有効ではなくなり' SyncMirror に置き換えられます

====


== 構文

[source, cli, subs="+macros"]
----
create syncMirror primary=pass:quotes[_"primaryVolumeName_"
secondary="_secondaryVolumeName_"
(remoteStorageArrayName="_storageArrayName_" |
remoteStorageArrayWwn="_wwID_")]
[remotePassword="password"]
[syncPriority=(highest | high | medium | low | lowest)]
[autoResync=(enabled | disabled)]
[writeOrder=(preserved | notPreserved)]
[writeMode=(synchronous | asynchronous)]
[role=(primary | secondary)]
[force=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「プライマリ」
 a| 
プライマリボリュームに使用する、ローカルストレージアレイ上の既存のボリュームの名前。プライマリボリューム名は二重引用符（""）で囲みます。



 a| 
' 二次
 a| 
セカンダリボリュームに使用する、リモートストレージアレイ上の既存のボリュームの名前。セカンダリボリューム名は二重引用符（""）で囲みます。



 a| 
remoteStorageArrayName
 a| 
リモートストレージアレイの名前。リモートストレージアレイ名は二重引用符（""）で囲みます。



 a| 
remoteStorageArrayWwn`
 a| 
リモートストレージアレイのWorld Wide Identifier（WWID）。WWIDは二重引用符（""）で囲みます。



 a| 
「remotePassword」
 a| 
リモートストレージアレイのパスワード。このパラメータは、リモートストレージアレイがパスワードで保護されている場合に使用します。パスワードは二重引用符（""）で囲みます。



 a| 
「syncPriority」
 a| 
ホストI/Oアクティビティに対する完全同期の優先度。有効な値は'highest'high`'high`'medium`'low''low'lowest`です



 a| 
「autoResync」
 a| 
リモートミラーペアのプライマリボリュームとセカンダリボリュームの間の自動再同期の設定。このパラメータには次の値があります。

* [enabled]--自動再同期がオンになっています何もしなくても、プライマリボリュームとセカンダリボリュームは再同期されます。
* disabled --自動再同期がオフになっていますプライマリ・ボリュームとセカンダリ・ボリュームを再同期させるには'resume SyncMirror コマンドを実行する必要があります




 a| 
「writeOrder」です
 a| 
プライマリボリュームとセカンダリボリュームの間のデータ転送の書き込み順序。有効な値は「preserved」または「notPreserved」です。



 a| 
「writeMode」です
 a| 
プライマリボリュームからセカンダリボリュームへの書き込み方法。有効な値は「synchronous」または「asynchronous」です。



 a| 
「役割」
 a| 
このパラメータを使用して、非同期ミラーグループをプライマリロールに昇格するか、非同期ミラーグループをセカンダリロールに降格します。非同期ミラーグループをプライマリロールとして定義するには'このパラメータをprimaryに設定します非同期ミラーグループをセカンダリロールとして定義するには'このパラメータをsecondaryに設定します



 a| 
「フォース」
 a| 
ストレージアレイ間の通信リンクがダウンすると、強制的にロールが反転されるため、ローカル側で昇格または降格を行うと、プライマリまたはセカンダリが二重で存在する状態になります。ロール反転を強制的に実行するには'このパラメータをTRUEに設定しますデフォルト値は'FALSE'です

|===


== 注：

名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。名前の最大文字数は30文字です。

プライマリボリュームとセカンダリボリュームを選択するときは、セカンダリボリュームのサイズをプライマリボリューム以上にする必要があります。セカンダリボリュームのRAIDレベルをプライマリボリュームと同じにする必要はありません。

パスワードは、管理ドメイン内の各ストレージアレイに保存されます。以前にパスワードが設定されていない場合は、パスワードは必要ありません。パスワードは、最大30文字の英数字を任意に組み合わせて指定できます。（ストレージアレイのパスワードは、「set storageArray」コマンドを使用して定義できます）。

同期優先度によって、ミラー関係のプライマリボリュームとセカンダリボリュームの間のデータの同期に使用されるシステムリソースの量が定義されます。最高の優先度レベルを選択すると、ほとんどのシステムリソースを使用してデータの完全同期が実行されるため、ホストのデータ転送パフォーマンスが低下します。

「writeOrder」パラメータは非同期書き込みモードにのみ適用され、ミラーペアをコンシステンシグループに組み込みます。「writeOrder」パラメータを「preserved」に設定すると、リモート・ミラー・ペアは、ホストからプライマリ・ボリュームへの書き込みと同じ順序で、プライマリ・ボリュームからセカンダリ・ボリュームへデータを送信します。送信リンクに障害が発生した場合、完全な同期が行われるまで、データはバッファされます。この処理では、バッファされたデータを維持するために追加のシステムオーバーヘッドが必要になる可能性があるため、処理が遅くなります「writeOrder」パラメータを「notPreserved」に設定すると、システムはバッファ内のデータを維持する必要がなくなりますが、セカンダリボリュームのデータがプライマリボリュームと同じになるように、完全な同期を強制的に実行する必要があります。



== 最小ファームウェアレベル

6.10
