---
permalink: commands-a-z/create-consistencygroup.html 
sidebar: sidebar 
keywords: create, consistency, group 
summary: create consistencyGroupコマンドは、スナップショットグループを含むことができる、新しい空のコンシステンシグループを作成します。set consistencyGroup addCGMemberコマンドを使用して、Snapshotグループを追加する必要があります。 
---
= 整合性グループの作成 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create consistencyGroupコマンドは'スナップショット・グループを含むことができる'新しい空のコンシステンシ・グループを作成しますset consistencyGroup addCGMember'コマンドを使用して、Snapshotグループを追加する必要があります。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
create consistencyGroup userLabel=pass:quotes[_"consistencyGroupName"_]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapSchedule_])]
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「userLabel」のように入力します
 a| 
作成する新しい整合グループの名前。新しい整合性グループ名は二重引用符（""）で囲みます。



 a| 
repositoryFullPolicy
 a| 
Snapshotリポジトリボリュームの容量が上限に達している場合にSnapshot処理をどのように続行するかを指定します。ベースボリュームへの書き込みを停止する（failBaseWrites）か、Snapshotイメージを削除（パージ）する（purgeSnapImages）かを選択できます。デフォルトのアクションはpurgeSnapImagesです



 a| 
repositoryFullLimit
 a| 
リポジトリの容量がこの割合に達すると、Snapshotリポジトリボリュームの上限に近づいているという警告が表示されます。整数値を使用します。たとえば、70という値は70%を意味します。デフォルト値は75です。



 a| 
'autoDeleteLimit'
 a| 
各Snapshotグループでは、Snapshotイメージの自動削除を実行して、グループ内のSnapshotイメージの総数を指定したレベル以下に保つように設定できます。このオプションを有効にすると、Snapshotグループ内に新しいSnapshotイメージが作成されるたびに、制限値に準拠するためにグループ内の最も古いSnapshotイメージが自動的に削除されます。この処理によってリポジトリ容量が解放されて、残りのSnapshotイメージに対するcopy-on-write要求に使用できるようになります。



 a| 
「enableSchedule
 a| 
Snapshot処理をスケジュールする機能をオンにするかオフにするかを指定します。スナップショットのスケジュール設定をオンにするには'このパラメータをTRUEに設定しますスナップショットのスケジュール設定をオフにするには'このパラメータをFALSEに設定します



 a| 
「rollBackPriority」を参照してください
 a| 
システムのパフォーマンスを犠牲にしてシステムリソースをロールバック処理に割り当てるかどうかを決定します。値がHighの場合は'ロールバック・オペレーションが他のすべてのホストI/Oより優先されることを示します値が'low'の場合'ホストI/Oへの影響を最小限に抑えてロールバック操作を実行する必要があります

|===


== 注：

整合性グループは論理エンティティであり、グループに追加するすべてのSnapshotイメージをバッチ形式で管理できます。整合性グループは、Snapshotイメージに関して整合性の要件や依存関係を相互に持つSnapshotグループの集まりです。この収集用に作成して使用するSnapshotイメージは、整合性の依存関係に従って管理する必要があります。

名前には、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。名前の最大文字数は30文字です。

整合性グループのSnapshotイメージは、あるSnapshotイメージが整合性グループに存在するかどうかに基づいて推測できます。1つの整合性グループ内に存在するすべてのSnapshotイメージは、共通のタイムスタンプとシーケンス番号を共有します。

Snapshotイメージの整合性グループ上での処理は単一の要求として処理されます。これにより、各メンバーの関連付けられているベースボリュームに対する保留中のI/O処理はすべて、削除され、Snapshotイメージの作成前に中断されます。整合性グループのすべてのメンバーに関してSnapshotイメージの作成を正常に完了できない場合は、処理が失敗し、何も行われません（つまり、新しいSnapshotイメージは作成されません）。

この動作に基づいて、整合性グループのすべてのメンバーで、通常はSnapshotイメージの数が同じになります。ただし、整合性グループに新しいメンバーが追加された場合、その整合性グループの既存のメンバー上で以前に作成されたSnapshotイメージは、新しいメンバーにはありません。Snapshotイメージが存在しないことは、エラー状態とはみなされません。その後、整合性グループの一部のメンバーのみに存在するSnapshotイメージの削除またはロールバックの要求を行うと、指定したSnapshotイメージが実際に存在するメンバーのみに影響します。



== 自動削除

各Snapshotグループでは、Snapshotイメージの自動削除を実行して、グループ内のSnapshotイメージの総数を指定したレベル以下に保つように設定できます。Snapshotグループ内のSnapshotイメージの数が上限に達すると、「autoDeleteLimit」パラメータは、Snapshotグループ内に新しいSnapshotイメージが作成されるたびにSnapshotイメージを自動的に削除します。autoDeleteLimitパラメータは、パラメータで定義されたイメージの最大数に達するまで、Snapshotグループ内の最も古いSnapshotイメージを削除します。この処理によってリポジトリ容量が解放されて、残りのSnapshotイメージに対するcopy-on-write要求に使用できるようになります。



== 整合性グループのSnapshotイメージのスケジュール設定

enableSchedule'パラメータとschedule'パラメータを使用すると'スナップショットをスケジュールすることができますこれらのパラメータを使用すると、日単位、週単位、または月単位（曜日単位または日付単位）でSnapshotをスケジュールできます。enableScheduleパラメータは'スナップショットをスケジュールする機能をオンまたはオフにしますスケジューリングをイネーブルにする場合は'schedule'パラメータを使用して'スナップショットをいつ実行するかを定義します

次の表では'schedule'パラメータのオプションの使用方法について説明します

|===
| パラメータ | 説明 


 a| 
「スケジュール」
 a| 
スケジュールパラメータの指定に必要です。



 a| 
「即時」
 a| 
処理をただちに開始します。この項目は、他のスケジュールパラメータと同時に指定することはできません。



 a| 
「enableSchedule
 a| 
「true」に設定すると、スケジューリングがオンになります。falseに設定すると'スケジュールはオフになります

[NOTE]
====
デフォルトは「 false 」です。

====


 a| 
「startDate」と入力します
 a| 
処理を開始する特定の日付。日付の入力形式はMM：DD：YYです。デフォルトは現在の日付です。このオプションの例は'startDate=06:27:11`です



 a| 
「scheduleDay」のように指定します
 a| 
処理を開始する曜日。次の値をすべてまたは1つ以上指定できます。

* 「月曜」
* 「火曜日」
* 「水曜日」
* 「木曜日」
* 「Friday`」
* 「土曜」
* 日曜日


[NOTE]
====
値はかっこで囲みます。たとえば、「scheduleDay=（wednesday）」のように指定します。

====
複数の曜日を指定する場合は、各曜日をスペースで区切り、全体を丸かっこで囲みます。たとえば、「scheduleDay=」（monday wednesday friday）を指定します。

[NOTE]
====
このパラメータは、月次スケジュールとは互換性がありません。

====


 a| 
「startTime」と入力します
 a| 
処理を開始する時刻。時刻の入力形式はHH：MMで、HHは時間、MMは分です。24時間方式のクロックを使用します。たとえば、午後2：00は14：00です。このオプションの例は'startTime=14:27`です



 a| 
「scheduleInterval」
 a| 
処理の最小間隔を分単位で指定します。スケジュール間隔は1440（24時間）以下の30の倍数にする必要があります。

このオプションの例は'scheduleInterval=180``です



 a| 
「endDate」
 a| 
処理を停止する特定の日付。日付の入力形式はMM：DD：YYです。終了日を指定する必要がない場合は'noEndDate'を指定できますこのオプションの例は'endDate=11:26:11`です



 a| 
「timesPerDay」を参照してください
 a| 
1日に処理を実行する回数。このオプションの例は'timesPerDay=4`です



 a| 
「timezone」
 a| 
スケジュールに使用するタイムゾーンを指定します。次の2つの方法で指定できます。

* * GMT±HH：MM *
+
GMTからのタイムゾーンのオフセット。例:`timezone=GMT-06：00`。

* *テキスト文字列*
+
標準的なタイムゾーンのテキスト文字列を引用符で囲む必要があります。例:`timezone="America/Chicago"``





 a| 
「scheduleDate」です
 a| 
処理を実行する日にち。日にちの値は1~31の数値です。

[NOTE]
====
このパラメータは、週次スケジュールとは互換性がありません。

====
「scheduleDate」オプションの例は、「scheduleDate=（"15")`です。



 a| 
「月」
 a| 
処理を実行する特定の月。月の値は次のとおりです。

* 1月〜1月
* 2月〜2月
* 「3月」- 3月
* 4月〜4月
* 「5月」- 5月
* 6月〜6月
* 7月〜7月
* 8月〜8月
* 「sep」- 9月
* 10月〜10月
* 11月〜11月
* dec - 12月


[NOTE]
====
値はかっこで囲みます。たとえば'`month=(jan)`と指定します

====
複数の月を指定する場合は、各月をスペースで区切り、全体を丸かっこで囲みます。たとえば'month=(jan jul dec )`と指定します

このパラメータは「scheduleDate」パラメータとともに使用して、特定の日にちに処理を実行します。

[NOTE]
====
このパラメータは、週次スケジュールとは互換性がありません。

====
|===
次の表では'timezone'パラメータの使用方法について説明します

|===
| タイムゾーン名 | GMTオフセット 


 a| 
「Etc/GMT+12」
 a| 
「GMT-12:00」



 a| 
「Etc/GMT+11」
 a| 
「GMT-11：00」



 a| 
太平洋/ホノルル
 a| 
「GMT-10：00」



 a| 
「アメリカ/アンカレッジ」
 a| 
「GMT-09:00」



 a| 
「America/Santa Isabel」と入力します
 a| 
「GMT-08:00」



 a| 
「America/LOS_Angeles
 a| 
「GMT-08:00」



 a| 
「アメリカ/フェニックス」
 a| 
「GMT-07：00」



 a| 
「アメリカ/チワワ」
 a| 
「GMT-07：00」



 a| 
「アメリカ/デンバー」
 a| 
「GMT-07：00」



 a| 
「アメリカ/グアテマラ」
 a| 
「GMT-06：00」



 a| 
「America/Chicago」と入力します
 a| 
「GMT-06：00」



 a| 
「America/Mexico City」
 a| 
「GMT-06：00」



 a| 
「アメリカ/レジーナ」
 a| 
「GMT-06：00」



 a| 
「アメリカ/ボゴタ」
 a| 
「GMT-05：00」



 a| 
「America/New_York`」
 a| 
「GMT-05：00」



 a| 
「Etc/GMT+5」
 a| 
「GMT-05：00」



 a| 
「アメリカ/カラカス」
 a| 
「GMT-04：30」



 a| 
「アメリカ/アスンシオン」
 a| 
「GMT-04：00」



 a| 
「America/Halifax」
 a| 
「GMT-04：00」



 a| 
「America/Cuiaba」
 a| 
「GMT-04：00」



 a| 
「America/La _Paz」と入力します
 a| 
「GMT-04：00」



 a| 
「アメリカ/サンティアゴ」
 a| 
「GMT-04：00」



 a| 
「America/St_Johns」
 a| 
「GMT-03：30」



 a| 
「America/Sao Paulo」
 a| 
「GMT-03：00」



 a| 
「America/Buenos Aire`
 a| 
「GMT-03：00」



 a| 
「America/Cayenne」
 a| 
「GMT-03：00」



 a| 
「America/Godthab
 a| 
「GMT-03：00」



 a| 
「アメリカ/モンテビデオ」
 a| 
「GMT-03：00」



 a| 
「Etc/GMT+2」
 a| 
「GMT-02:00」



 a| 
「大西洋/アゾレス」
 a| 
「GMT-01：00」



 a| 
「Atlantic」または「Cape Verde」があります
 a| 
「GMT-01：00」



 a| 
アフリカ/カサブランカ
 a| 
「GMT」



 a| 
「Etc/GMT」
 a| 
「GMT」



 a| 
「ヨーロッパ/ロンドン」
 a| 
「GMT」



 a| 
「大西洋/レイキャビク」
 a| 
「GMT」



 a| 
「ヨーロッパ/ベルリン」
 a| 
「GMT+01:00」



 a| 
「ヨーロッパ/ブダペスト」
 a| 
「GMT+01:00」



 a| 
「ヨーロッパ/パリ」
 a| 
「GMT+01:00」



 a| 
「ヨーロッパ/ワルシャワ
 a| 
「GMT+01:00」



 a| 
アフリカ/ラゴス
 a| 
「GMT+01:00」



 a| 
アフリカ/ウィンドフック
 a| 
「GMT+01:00」



 a| 
「アジア/アンマン」
 a| 
「GMT+02:00`」



 a| 
「アジア/ベイルート
 a| 
「GMT+02:00`」



 a| 
アフリカ/カイロ
 a| 
「GMT+02:00`」



 a| 
「アジア/ダマスカス」
 a| 
「GMT+02:00`」



 a| 
アフリカ/ヨハネスブルグ
 a| 
「GMT+02:00`」



 a| 
「ヨーロッパ/キエフ
 a| 
「GMT+02:00`」



 a| 
「アジア/エルサレム」
 a| 
「GMT+02:00`」



 a| 
「ヨーロッパ/イスタンブール」
 a| 
「GMT+03:00`」



 a| 
「ヨーロッパ/ミンスク」
 a| 
「GMT+02:00`」



 a| 
アジア/バグダッド
 a| 
「GMT+03:00`」



 a| 
「アジア/リヤド」
 a| 
「GMT+03:00`」



 a| 
アフリカ/ナイロビ
 a| 
「GMT+03:00`」



 a| 
「アジア/テヘラン」
 a| 
「GMT+03：30`」



 a| 
「ヨーロッパ/モスクワ」
 a| 
「GMT+04：00



 a| 
「アジア/ドバイ」
 a| 
「GMT+04：00



 a| 
「アジア/バクー」
 a| 
「GMT+04：00



 a| 
「インド/モーリシャス」
 a| 
「GMT+04：00



 a| 
「アジア/トビリシ
 a| 
「GMT+04：00



 a| 
「アジア/イェレバン」
 a| 
「GMT+04：00



 a| 
「アジア/カブール
 a| 
「GMT+04：30`



 a| 
「アジア/カラチ」
 a| 
「GMT+05:00



 a| 
「アジア//タシケント」
 a| 
「GMT+05:00



 a| 
「アジア/カルカッタ」
 a| 
「GMT+05：30`



 a| 
「アジア/コロンボ」
 a| 
「GMT+05：30`



 a| 
「アジア/カトマンズ」
 a| 
「GMT+05：45」



 a| 
「アジア/エカテリンブルグ」
 a| 
「GMT+06:00」



 a| 
「アジア/アルマティ」
 a| 
「GMT+06:00」



 a| 
アジア/ダッカ
 a| 
「GMT+06:00」



 a| 
「アジア/ラングーン」
 a| 
「GMT+06:30`」



 a| 
「アジア/ノヴォシビルスク」
 a| 
「GMT+07:00`」



 a| 
「アジア/バンコク」
 a| 
「GMT+07:00`」



 a| 
「asia/Krasnoyarsk.」と入力します
 a| 
「GMT+08:00」



 a| 
「アジア/上海」
 a| 
「GMT+08:00」



 a| 
「アジア/シンガポール」
 a| 
「GMT+08:00」



 a| 
オーストラリア/パース
 a| 
「GMT+08:00」



 a| 
「アジア/台北」
 a| 
「GMT+08:00」



 a| 
「アジア/ウランバートル
 a| 
「GMT+08:00」



 a| 
「アジア/イルクーツク」
 a| 
「GMT+09：00



 a| 
「アジア/東京」
 a| 
「GMT+09：00



 a| 
「アジア/ソウル
 a| 
「GMT+09：00



 a| 
オーストラリア/アデレード
 a| 
「GMT+09:30」



 a| 
「オーストラリア/ダーウィン」
 a| 
「GMT+09:30」



 a| 
「アジア/ヤクーツク」
 a| 
「GMT+10：00



 a| 
「オーストラリア/ブリスベン」
 a| 
「GMT+10：00



 a| 
オーストラリア/シドニー
 a| 
「GMT+10：00



 a| 
「太平洋/ポートモレスビー」
 a| 
「GMT+10：00



 a| 
「オーストラリア/ホバート」
 a| 
「GMT+10：00



 a| 
「Asia / Vladivostok」と入力します
 a| 
「GMT+11:00`」



 a| 
「太平洋/グアダル運河」
 a| 
「GMT+11:00`」



 a| 
「太平洋/オークランド」
 a| 
「GMT+12：00」



 a| 
「Etc/GMT-12」
 a| 
「GMT+12：00」



 a| 
「太平洋/フィジー」
 a| 
「GMT+12：00」



 a| 
「アジア/カムチャッカ」
 a| 
「GMT+12：00」



 a| 
「太平洋/トンガタプ
 a| 
「GMT+13:00」

|===
スケジュールを定義するためのコード文字列の例を次に示します。

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
「scheduleInterval」オプションも使用する場合、ファームウェアでは、2つのオプションの最小値を選択することにより、「timesPerDay」オプションと「scheduleInterval」オプションの間が選択されます。ファームウェアでは、「scheduleInterval」オプションの値を設定した「scheduleInterval」オプションの値で1440を割ることによって、「scheduleInterval」オプションの整数値を計算します。たとえば、1440/180 = 8のようになります。ファームウェアは'timesPerDay'の整数値と'計算されたscheduleInterval'の整数値を比較し'より小さい値を使用します

スケジュールを削除するには'schedule'パラメータを指定してdelete volumeコマンドを使用します'schedule'パラメータを指定してdelete volumeコマンドを実行すると'スケジュールのみが削除され'スナップショット・ボリュームは削除されません

整合性グループでロールバックを実行する場合、デフォルトの処理では、整合性グループのすべてのメンバーがロールバックされます。整合性グループのすべてのメンバーに関してロールバックを正常に開始できない場合、ロールバックは失敗し、何の処理も行われません。Snapshotイメージはロールバックされません。



== 最小ファームウェアレベル

7.83

7.86で、「scheduleDate」オプションおよび「month」オプションが追加されました。
