---
permalink: commands-a-z/create-volumecopy.html 
sidebar: sidebar 
keywords: create, volume, copy 
summary: create VolumeCopyコマンドを使用すると、ボリュームコピーが作成され、ボリュームコピー処理が開始されます。このコマンドは、Snapshotイメージのボリュームコピーペアに対して有効です。 
---
= ボリュームコピーを作成する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create VolumeCopyコマンドは'ボリューム・コピーを作成し'ボリューム・コピー操作を開始しますこのコマンドは、Snapshotイメージのボリュームコピーペアに対して有効です。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
ボリュームコピー処理を開始すると、ターゲットボリューム上の既存のデータはすべて上書きされ、ターゲットボリュームがホストに対して読み取り専用になり、ターゲットボリュームに関連付けられているSnapshotイメージボリュームがある場合はすべて使用が停止されます。以前にターゲットボリュームをコピーとして使用したことがある場合は、データが不要になっていること、またはデータをバックアップ済みであることを確認してください。

====
このコマンドは、次の2つの方法でボリュームコピーを作成します。

* Snapshotイメージを含まないボリュームコピーは、_offline_volume copyとも呼ばれます
* Snapshotイメージを含むボリュームコピー。online_volume copyとも呼ばれます


Snapshotイメージを含まないボリュームコピーを使用する場合は、コピー処理が完了するまで、ソースボリュームへの書き込みはできません。コピー処理の完了前にソースボリュームに書き込みできるようにする場合は、Snapshotイメージを含むボリュームコピーを使用します。Snapshotイメージを含むボリュームコピーは、コマンド構文でオプションのパラメータを使用して選択できます。

Snapshotイメージを含むボリュームコピーの処理が完了すると、Snapshotイメージは削除され、Snapshotボリュームが無効になります。

[NOTE]
====
同時に実行できるボリュームコピーの最大数は8個です。一度に8つ以上のボリュームコピーを作成しようとすると、実行中のボリュームコピーのいずれかが完了してCompleteのステータスを返すまでの間、コントローラから保留のステータスが返されます。

====


== 構文

[source, cli, subs="+macros"]
----
create volumeCopy source=pass:quotes[_"sourceName"_
target="_targetName_"]
[copyPriority=(highest | high | medium | low | lowest)]
[targetReadOnlyEnabled=(TRUE | FALSE)]
[copyType=(offline | online)]
[repositoryPercentOfBase=(20 | 40 | 60 | 120 | default)]
[repositoryGroupPreference=(sameAsSource | otherThanSource | default)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「source」を参照してください
 a| 
ソースボリュームとして使用する既存のボリュームの名前。ソースボリューム名は二重引用符（""）で囲みます。



 a| 
「target」と入力します
 a| 
ターゲットボリュームとして使用する既存のボリュームの名前。ターゲットボリューム名は二重引用符（""）で囲みます。



 a| 
「copyPriority」
 a| 
ホストのI/Oアクティビティに対するボリュームコピーの優先度。有効な値は'highest'high`'high`'medium`'low''low'lowest`です



 a| 
targetReadOnlyEnabled
 a| 
ターゲットボリュームへの書き込みを可能にするか、ターゲットボリュームからの読み取りのみを可能にするかを選択する設定。ターゲット・ボリュームに書き込むには'このパラメータをFALSEに設定しますターゲット・ボリュームに書き込みできないようにするには'このパラメータをTRUEに設定します



 a| 
「copyType」
 a| 
このパラメータを使用して、Snapshotイメージを含むボリュームコピーを作成します。Snapshotイメージを含むボリュームコピーを作成すると、ボリュームコピーの作成中もソースボリュームへの書き込みを続行できます。Snapshotイメージを含むボリュームコピーを作成するには、このパラメータを「online」に設定します。Snapshotイメージを含まないボリュームコピーを作成するには、このパラメータを「offline」に設定します。

このパラメータを使用しない場合、ボリュームコピーはSnapshotイメージなしで作成されます。



 a| 
「repositoryPercentOfBase」です
 a| 
このパラメータは、Snapshotイメージを含むボリュームコピーの作成時に、Snapshotイメージのリポジトリボリュームのサイズを決定します。リポジトリボリュームのサイズは、ベースボリュームとも呼ばれる、ソースボリュームの割合で表されます。このパラメータの有効な値は'20`'40`'60`'120`'default`ですデフォルト値は20です。このパラメータを使用しない場合、ファームウェアは20%という値を使用します。

copyTypeパラメータは'repositoryPercentOfBase'パラメータとともに使用する必要があります



 a| 
repositoryGroupPreferenceの2つのグループがあります
 a| 
このパラメータは、Snapshotイメージのリポジトリボリュームの書き込み先となるボリュームグループを決定します。次の選択肢があります。

* sameAsSource --スナップショットイメージボリュームは'スペースが使用可能な場合'ソースボリュームと同じボリュームグループに書き込まれます
* otherThanSource'--廃止されたパラメータ。使用しないでください
* デフォルト--スナップショット・イメージ・リポジトリ・ボリュームは'スペースを持つ任意のボリューム・グループに書き込まれます


最適なパフォーマンスを得るには'sameAsSource'オプションを使用します

copyType'パラメータは'repositoryGroupPreference'パラメータとともに使用する必要があります

|===


== 注：

名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。名前の最大文字数は30文字です。

コピー優先度は、ボリュームコピーペアのソースボリュームとターゲットボリュームの間のデータのコピーに使用されるシステムリソースの量を定義します。最高の優先度レベルを選択すると、ほとんどのシステムリソースを使用してボリュームのコピーが実行されるため、ホストのデータ転送パフォーマンスが低下します。
