---
permalink: commands-a-z/create-snapgroup.html 
sidebar: sidebar 
keywords: create, snapshot, group 
summary: create snapGroupコマンドは、新しいSnapshotグループおよび関連するリポジトリボリュームを作成します。 
---
= スナップショットグループの作成 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
create snapGroupコマンドは'新しいスナップショット・グループと関連するリポジトリ・ボリュームを作成します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

Snapshotグループには、関連付けられているベースボリュームの一連のSnapshotイメージが含まれています。Snapshotグループにはリポジトリボリュームがあり、これを使用して、Snapshotグループの一部であるすべてのSnapshotイメージのデータが保存されます。

[NOTE]
====
Snapshotグループを作成する前に、空き容量のあるボリュームグループがあることを確認してください。

====


== 構文

[source, cli, subs="+macros"]
----
create snapGroup userLabel=pass:quotes[_"snapGroupName_" sourceVolume=_"volumeName"_]
[(repositoryVolume="repos_xxxx" |
repositoryVolume=(pass:quotes[_volumeGroupName_] [capacity=capacityValue]) |
repositoryVolume=(pass:quotes[_diskPoolName_] [capacity=capacityValue]))]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[rollbackPriority=(highest | high | medium | low | lowest)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]|
[enableSchedule=(TRUE | FALSE)]
[schedule (immediate | pass:quotes[_snapshotSchedule_)]]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「userLabel」のように入力します
 a| 
新しいSnapshotグループに付ける名前。Snapshotグループの識別子は二重引用符（""）で囲みます。



 a| 
「sourceVolume」と入力します
 a| 
Snapshotイメージのソースとして使用するボリュームの名前。ソースボリューム名は二重引用符（""）で囲みます。



 a| 
リポジトリボリューム
 a| 
Snapshotグループの変更されたデータが格納されるリポジトリボリュームの名前。

リポジトリボリュームの名前を定義する方法は2つあります。

* 既存のリポジトリボリュームの名前を使用します
* このコマンドを実行するときに新しいリポジトリボリュームを作成します


既存のリポジトリボリュームの名前は次の2つの部分で構成されます。

* 「repos」という用語
* ストレージ管理ソフトウェアがリポジトリボリューム名に割り当てる4桁の数値識別子


既存のリポジトリボリュームの名前は二重引用符（""）で囲みます。

このコマンドを実行するときに新しいリポジトリボリュームを作成する場合は、リポジトリボリュームを含めるボリュームグループまたはディスクプールの名前を入力する必要があります。必要に応じて、リポジトリボリュームの容量を定義することもできます。容量を定義する場合は、次の値を使用できます。

* ベースボリュームの容量の割合を表す整数値
* ベースボリュームの容量の割合を表す小数値
* リポジトリボリュームの具体的なサイズ。サイズは'bytes'KB'MB`'GB'TB'の単位で定義されます


容量オプションを使用しない場合は、ストレージ管理ソフトウェアによって、ベースボリュームの容量の20%に設定されます。

このコマンドを実行すると、ストレージ管理ソフトウェアによって、Snapshotボリューム用のリポジトリボリュームが作成されます。



 a| 
repositoryFullPolicy
 a| 
Snapshotグループのリポジトリボリュームが上限に達している場合にSnapshotイメージ処理をどのように続行するかを定義します。ベース・ボリュームへのI/O書き込みを停止する（failBaseWrites）か'リポジトリ・ボリューム内のスナップショット・イメージ（purgeSnapImages）を削除（パージ）するかを選択できますpurgeSnapImagesオプションは'最も古いスナップショット・イメージを削除して'スペースを解放しますデフォルトのアクションはpurgeSnapImagesです



 a| 
「rollBackPriority」を参照してください
 a| 
システムのパフォーマンスを犠牲にしてシステムリソースをロールバック処理に割り当てるかどうかを決定します。値がHighの場合は'ロールバック・オペレーションが他のすべてのホストI/Oより優先されることを示します値が'low'の場合'ホストI/Oへの影響を最小限に抑えてロールバック操作を実行する必要がありますデフォルト値は「medium」です。



 a| 
repositoryFullLimit
 a| 
リポジトリの容量がこの割合に達すると、Snapshotグループのリポジトリボリュームの上限に近づいているという警告が表示されます。整数値を使用します。たとえば、70という値は70%を意味します。デフォルト値は75です。



 a| 
'autoDeleteLimit'
 a| 
各Snapshotグループでは、Snapshotイメージの自動削除を実行して、グループ内のSnapshotイメージの総数を指定したレベル以下に保つように設定できます。このオプションを有効にすると、Snapshotグループ内に新しいSnapshotイメージが作成されるたびに、制限値に準拠するためにグループ内の最も古いSnapshotイメージが自動的に削除されます。この処理によってリポジトリ容量が解放されて、残りのSnapshotイメージに対するcopy-on-write要求に使用できるようになります。



 a| 
「enableSchedule
 a| 
このパラメータを使用して、Snapshot処理のスケジュール機能をオンまたはオフにします。スナップショットのスケジュール設定をオンにするには'このパラメータをTRUEに設定しますスナップショットのスケジュール設定をオフにするには'このパラメータをFALSEに設定します

|===


== 注：

Snapshotグループ名はそれぞれ一意である必要があります。ユーザラベルには、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。ユーザラベルの最大文字数は30文字です。

Snapshotグループを作成するには、Snapshotイメージの格納先となる、関連付けられたリポジトリボリュームが必要です。既存のリポジトリボリュームを使用するか、新しいリポジトリボリュームを作成できます。リポジトリボリュームは、Snapshotグループの作成時に作成できます。Snapshotグループのリポジトリボリュームは拡張可能なボリュームで、標準ボリュームエンティティを最大16個まで接続することで構成されます。拡張可能なリポジトリボリュームは、最初は1つの要素だけで構成されます。その時点でのリポジトリボリュームの容量は、その要素の容量と同じです。リポジトリボリュームの容量は、標準のリポジトリボリュームを接続することで拡張できます。その後、複数の要素で構成された拡張可能なリポジトリボリュームの容量は、接続されたすべての標準ボリュームの合計容量になります。

Snapshotグループでは、各Snapshotイメージの作成時間に基づいて、Snapshotイメージが厳密に順序付けされます。別のSnapshotイメージよりもあとに作成されたSnapshotイメージは、もう一方のSnapshotイメージに対する後継の_になります。別のSnapshotイメージよりも前に作成されたSnapshotイメージは、もう一方に対する_predecesser_relativeです。

Snapshotグループのリポジトリボリュームは、次の合計サイズの最小容量要件を満たす必要があります。

* 32MB：Snapshotグループのオーバーヘッドを固定し、copy-on-write処理に使用できるようになりました。
* ロールバック処理用の容量。ベースボリュームの容量の1/5000です。


この最小容量は、コントローラファームウェアとストレージ管理ソフトウェアによって適用されます。

Snapshotグループを初めて作成するときは、Snapshotイメージは含まれていません。Snapshotイメージを作成するときに、SnapshotグループにSnapshotイメージを追加します。スナップショット・イメージを作成し'スナップショット・グループにスナップショット・イメージを追加するには'create snapImageコマンドを使用します

Snapshotグループの状態は次のいずれかになります。

* * Optimal *--スナップショットグループは正常に動作しています。
* *フル*--スナップショット・グループのリポジトリがいっぱいですcopy-on-write処理はこれ以上実行できません。この状態にできるのは、Repository FullポリシーがFail Base Writesに設定されているSnapshotグループのみです。フル状態のSnapshotグループがある場合、Needs-Attention条件がストレージアレイに送信されます。
* *しきい値超過*- Snapshotグループのリポジトリボリュームの使用率がアラートしきい値に達しているか、超えています。この状態のSnapshotグループがある場合、Needs-Attention条件がストレージアレイに送信されます。
* *失敗*- Snapshotグループで問題が発生し、SnapshotグループのすべてのSnapshotイメージが使用できなくなりました。たとえば、特定のタイプのリポジトリボリューム障害により、原因 が失敗状態になる可能性があります。Failed状態からリカバリするには'revive SnapGroup'コマンドを使用します


autoDeleteLimitパラメータを使用すると、Snapshotイメージを自動的に削除するように各Snapshotグループを設定できます。Snapshotイメージを自動的に削除すると、不要なイメージを定期的に手動で削除する必要がなくなります。不要なイメージが残っていると、リポジトリボリュームの容量が上限に達しているために、今後Snapshotイメージを作成できなくなる場合があります。autoDeleteLimitパラメータを使用すると'ストレージ管理ソフトウェアはスナップショット・イメージを最も古いものから自動的に削除しますストレージ管理ソフトウェアは'autoDeleteLimit'パラメータで入力した数と同じ数のSnapshotイメージに達するまで'スナップショット・イメージを削除します新しいスナップショット・イメージがリポジトリ・ボリュームに追加されると'ストレージ管理ソフトウェアは'autoDeleteLimit'パラメータ番号に達するまで'最も古いスナップショット・イメージを削除します

enableScheduleパラメータとscheduleパラメータを使用すると'スナップショット・グループのスナップショット・イメージの作成をスケジュールできますこれらのパラメータを使用すると、日単位、週単位、または月単位（曜日単位または日付単位）でSnapshotをスケジュールできます。enableScheduleパラメータは'スナップショットをスケジュールする機能をオンまたはオフにしますスケジューリングをイネーブルにする場合は'schedule'パラメータを使用して'スナップショットをいつ実行するかを定義します

次の表では'schedule'パラメータのオプションの使用方法について説明します

|===
| パラメータ | 説明 


 a| 
「スケジュール」
 a| 
スケジュールパラメータの指定に必要です。



 a| 
「即時」
 a| 
処理をただちに開始します。この項目は、他のスケジュールパラメータと同時に指定することはできません。



 a| 
「enableSchedule
 a| 
「true」に設定すると、スケジューリングがオンになります。falseに設定すると'スケジュールはオフになります

[NOTE]
====
デフォルトは「 false 」です。

====


 a| 
「startDate」と入力します
 a| 
処理を開始する特定の日付。日付の入力形式はMM：DD：YYです。デフォルトは現在の日付です。このオプションの例は'startDate=06:27:11`です



 a| 
「scheduleDay」のように指定します
 a| 
処理を開始する曜日。次の値をすべてまたは1つ以上指定できます。

* 「月曜」
* 「火曜日」
* 「水曜日」
* 「木曜日」
* 「Friday`」
* 「土曜」
* 日曜日


[NOTE]
====
値はかっこで囲みます。たとえば、「scheduleDay=（wednesday）」のように指定します。

====
複数の曜日を指定する場合は、各曜日をスペースで区切り、全体を丸かっこで囲みます。たとえば、「scheduleDay=」（monday wednesday friday）を指定します。

[NOTE]
====
このパラメータは、月次スケジュールとは互換性がありません。

====


 a| 
「startTime」と入力します
 a| 
処理を開始する時刻。時刻の入力形式はHH：MMで、HHは時間、MMは分です。24時間方式のクロックを使用します。たとえば、午後2：00は14：00です。このオプションの例は'startTime=14:27`です



 a| 
「scheduleInterval」
 a| 
処理の最小間隔を分単位で指定します。スケジュール間隔は1440（24時間）以下の30の倍数にする必要があります。

このオプションの例は'scheduleInterval=180`です



 a| 
「endDate」
 a| 
処理を停止する特定の日付。日付の入力形式はMM：DD：YYです。終了日を指定する必要がない場合は'noEndDate'を指定できますこのオプションの例は'endDate=11:26:11`です



 a| 
「timesPerDay」を参照してください
 a| 
1日に処理を実行する回数。このオプションの例は'timesPerDay=4`です



 a| 
「timezone」
 a| 
スケジュールに使用するタイムゾーンを指定します。次の2つの方法で指定できます。

* * GMT±HH：MM *
+
GMTからのタイムゾーンのオフセット。例:`timezone=GMT-06：00`。

* *テキスト文字列*
+
標準的なタイムゾーンのテキスト文字列を引用符で囲む必要があります。例:`timezone="America/Chicago"``





 a| 
「scheduleDate」です
 a| 
処理を実行する日にち。日にちの値は1~31の数値です。

[NOTE]
====
このパラメータは、週次スケジュールとは互換性がありません。

====
「scheduleDate」オプションの例は、「scheduleDate=（"15")`です。



 a| 
「月」
 a| 
処理を実行する特定の月。月の値は次のとおりです。

* 1月〜1月
* 2月〜2月
* 「3月」- 3月
* 4月〜4月
* 「5月」- 5月
* 6月〜6月
* 7月〜7月
* 8月〜8月
* 「sep」- 9月
* 10月〜10月
* 11月〜11月
* dec - 12月


[NOTE]
====
値はかっこで囲みます。たとえば'`month=(jan)`と指定します

====
複数の月を指定する場合は、各月をスペースで区切り、全体を丸かっこで囲みます。たとえば'month=(jan jul dec )`と指定します

このパラメータは「scheduleDate」パラメータとともに使用して、特定の日にちに処理を実行します。

[NOTE]
====
このパラメータは、週次スケジュールとは互換性がありません。

====
|===
次の表では'timezone'パラメータの使用方法について説明します

|===
| タイムゾーン名 | GMTオフセット 


 a| 
「Etc/GMT+12」
 a| 
「GMT-12:00」



 a| 
「Etc/GMT+11」
 a| 
「GMT-11：00」



 a| 
太平洋/ホノルル
 a| 
「GMT-10：00」



 a| 
「アメリカ/アンカレッジ」
 a| 
「GMT-09:00」



 a| 
「America/Santa Isabel」と入力します
 a| 
「GMT-08:00」



 a| 
「America/LOS_Angeles
 a| 
「GMT-08:00」



 a| 
「アメリカ/フェニックス」
 a| 
「GMT-07：00」



 a| 
「アメリカ/チワワ」
 a| 
「GMT-07：00」



 a| 
「アメリカ/デンバー」
 a| 
「GMT-07：00」



 a| 
「アメリカ/グアテマラ」
 a| 
「GMT-06：00」



 a| 
「America/Chicago」と入力します
 a| 
「GMT-06：00」



 a| 
「America/Mexico City」
 a| 
「GMT-06：00」



 a| 
「アメリカ/レジーナ」
 a| 
「GMT-06：00」



 a| 
「アメリカ/ボゴタ」
 a| 
「GMT-05：00」



 a| 
「America/New_York`」
 a| 
「GMT-05：00」



 a| 
「Etc/GMT+5」
 a| 
「GMT-05：00」



 a| 
「アメリカ/カラカス」
 a| 
「GMT-04：30」



 a| 
「アメリカ/アスンシオン」
 a| 
「GMT-04：00」



 a| 
「America/Halifax」
 a| 
「GMT-04：00」



 a| 
「America/Cuiaba」
 a| 
「GMT-04：00」



 a| 
「America/La _Paz」と入力します
 a| 
「GMT-04：00」



 a| 
「アメリカ/サンティアゴ」
 a| 
「GMT-04：00」



 a| 
「America/St_Johns」
 a| 
「GMT-03：30」



 a| 
「America/Sao Paulo」
 a| 
「GMT-03：00」



 a| 
「America/Buenos Aire`
 a| 
「GMT-03：00」



 a| 
「America/Cayenne」
 a| 
「GMT-03：00」



 a| 
「America/Godthab
 a| 
「GMT-03：00」



 a| 
「アメリカ/モンテビデオ」
 a| 
「GMT-03：00」



 a| 
「Etc/GMT+2」
 a| 
「GMT-02:00」



 a| 
「大西洋/アゾレス」
 a| 
「GMT-01：00」



 a| 
「Atlantic」または「Cape Verde」があります
 a| 
「GMT-01：00」



 a| 
アフリカ/カサブランカ
 a| 
「GMT」



 a| 
「Etc/GMT」
 a| 
「GMT」



 a| 
「ヨーロッパ/ロンドン」
 a| 
「GMT」



 a| 
「大西洋/レイキャビク」
 a| 
「GMT」



 a| 
「ヨーロッパ/ベルリン」
 a| 
「GMT+01:00」



 a| 
「ヨーロッパ/ブダペスト」
 a| 
「GMT+01:00」



 a| 
「ヨーロッパ/パリ」
 a| 
「GMT+01:00」



 a| 
「ヨーロッパ/ワルシャワ
 a| 
「GMT+01:00」



 a| 
アフリカ/ラゴス
 a| 
「GMT+01:00」



 a| 
アフリカ/ウィンドフック
 a| 
「GMT+01:00」



 a| 
「アジア/アンマン」
 a| 
「GMT+02:00`」



 a| 
「アジア/ベイルート
 a| 
「GMT+02:00`」



 a| 
アフリカ/カイロ
 a| 
「GMT+02:00`」



 a| 
「アジア/ダマスカス」
 a| 
「GMT+02:00`」



 a| 
アフリカ/ヨハネスブルグ
 a| 
「GMT+02:00`」



 a| 
「ヨーロッパ/キエフ
 a| 
「GMT+02:00`」



 a| 
「アジア/エルサレム」
 a| 
「GMT+02:00`」



 a| 
「ヨーロッパ/イスタンブール」
 a| 
「GMT+03:00`」



 a| 
「ヨーロッパ/ミンスク」
 a| 
「GMT+02:00`」



 a| 
アジア/バグダッド
 a| 
「GMT+03:00`」



 a| 
「アジア/リヤド」
 a| 
「GMT+03:00`」



 a| 
アフリカ/ナイロビ
 a| 
「GMT+03:00`」



 a| 
「アジア/テヘラン」
 a| 
「GMT+03：30`」



 a| 
「ヨーロッパ/モスクワ」
 a| 
「GMT+04：00



 a| 
「アジア/ドバイ」
 a| 
「GMT+04：00



 a| 
「アジア/バクー」
 a| 
「GMT+04：00



 a| 
「インド/モーリシャス」
 a| 
「GMT+04：00



 a| 
「アジア/トビリシ
 a| 
「GMT+04：00



 a| 
「アジア/イェレバン」
 a| 
「GMT+04：00



 a| 
「アジア/カブール
 a| 
「GMT+04：30`



 a| 
「アジア/カラチ」
 a| 
「GMT+05:00



 a| 
「アジア//タシケント」
 a| 
「GMT+05:00



 a| 
「アジア/カルカッタ」
 a| 
「GMT+05：30`



 a| 
「アジア/コロンボ」
 a| 
「GMT+05：30`



 a| 
「アジア/カトマンズ」
 a| 
「GMT+05：45」



 a| 
「アジア/エカテリンブルグ」
 a| 
「GMT+06:00」



 a| 
「アジア/アルマティ」
 a| 
「GMT+06:00」



 a| 
アジア/ダッカ
 a| 
「GMT+06:00」



 a| 
「アジア/ラングーン」
 a| 
「GMT+06:30`」



 a| 
「アジア/ノヴォシビルスク」
 a| 
「GMT+07:00`」



 a| 
「アジア/バンコク」
 a| 
「GMT+07:00`」



 a| 
「asia/Krasnoyarsk.」と入力します
 a| 
「GMT+08:00」



 a| 
「アジア/上海」
 a| 
「GMT+08:00」



 a| 
「アジア/シンガポール」
 a| 
「GMT+08:00」



 a| 
オーストラリア/パース
 a| 
「GMT+08:00」



 a| 
「アジア/台北」
 a| 
「GMT+08:00」



 a| 
「アジア/ウランバートル
 a| 
「GMT+08:00」



 a| 
「アジア/イルクーツク」
 a| 
「GMT+09：00



 a| 
「アジア/東京」
 a| 
「GMT+09：00



 a| 
「アジア/ソウル
 a| 
「GMT+09：00



 a| 
オーストラリア/アデレード
 a| 
「GMT+09:30」



 a| 
「オーストラリア/ダーウィン」
 a| 
「GMT+09:30」



 a| 
「アジア/ヤクーツク」
 a| 
「GMT+10：00



 a| 
「オーストラリア/ブリスベン」
 a| 
「GMT+10：00



 a| 
オーストラリア/シドニー
 a| 
「GMT+10：00



 a| 
「太平洋/ポートモレスビー」
 a| 
「GMT+10：00



 a| 
「オーストラリア/ホバート」
 a| 
「GMT+10：00



 a| 
「Asia / Vladivostok」と入力します
 a| 
「GMT+11:00`」



 a| 
「太平洋/グアダル運河」
 a| 
「GMT+11:00`」



 a| 
「太平洋/オークランド」
 a| 
「GMT+12：00」



 a| 
「Etc/GMT-12」
 a| 
「GMT+12：00」



 a| 
「太平洋/フィジー」
 a| 
「GMT+12：00」



 a| 
「アジア/カムチャッカ」
 a| 
「GMT+12：00」



 a| 
「太平洋/トンガタプ
 a| 
「GMT+13:00」

|===
スケジュールを定義するためのコード文字列の例を次に示します。

[listing]
----
enableSchedule=true schedule startTime=14:27
----
[listing]
----
enableSchedule=true schedule scheduleInterval=180
----
[listing]
----
enableSchedule=true schedule timeZone=GMT-06:00
----
[listing]
----
enableSchedule=true schedule timeZone="America/Chicago"
----
「scheduleInterval」オプションも使用する場合、ファームウェアでは、2つのオプションの最小値を選択することにより、「timesPerDay」オプションと「scheduleInterval」オプションの間が選択されます。ファームウェアは、「scheduleInterval」オプションの値を設定した「scheduleInterval」オプションの値で1440を割ることによって、「scheduleInterval」オプションの整数値を計算します。たとえば、1440/180 = 8のようになります。ファームウェアは'timesPerDay'の整数値と'計算されたscheduleInterval'の整数値を比較し'より小さい値を使用します

スケジュールを削除するには'schedule'パラメータを指定してdelete volumeコマンドを使用します'schedule'パラメータを指定してdelete volumeコマンドを実行すると'スケジュールのみが削除され'スナップショット・ボリュームは削除されません



== 最小ファームウェアレベル

7.83

7.86で、「scheduleDate」オプションおよび「month」オプションが追加されました。
