---
permalink: commands-a-z/delete-diskpool.html 
sidebar: sidebar 
keywords: delete, disk pool 
summary: delete diskPoolコマンドは、ディスクプールを削除します。 
---
= ディスクプールの削除 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
delete diskPoolコマンドは'ディスク・プールを削除します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
*ストレージアレイ構成への損傷の可能性*--このコマンドを実行するとすぐに、ディスクプール内のすべてのデータが失われます。

====
使用しているストレージ管理ソフトウェアのバージョンに応じて、このコマンドはディスクプール内のすべてのボリュームも削除します。ボリュームの自動削除をサポートしていないバージョンのストレージ管理ソフトウェアを使用している場合は、ディスクプールとボリュームを強制的に削除できます。



== 構文

[source, cli, subs="+macros"]
----
delete diskPool pass:quotes[[_diskPoolName_]]
[force=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「diskPoolName」
 a| 
削除するディスクプールの名前。ディスクプール名は角かっこ（[]）で囲みます。ディスクプール名が特殊文字を含んでいる場合または数字のみで構成される場合は、名前を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「フォース」
 a| 
ストレージ管理ソフトウェアがディスクプール内のボリュームの自動削除をサポートしていない場合は、このパラメータによってボリュームを強制的に削除します。ディスク・プールとそれに含まれるボリュームを強制的に削除するには'このパラメータをTRUEに設定しますデフォルトは「FALSE」です。

|===


== 注：

ディスクプール名は一意である必要があります。ユーザラベルには、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。ユーザラベルの最大文字数は30文字です。



== 最小ファームウェアレベル

7.83
