---
permalink: commands-a-z/delete-volume.html 
sidebar: sidebar 
keywords: delete, volume, command, one, standard, volume, supported, array, role 
summary: delete volumeコマンドは、1つ以上の標準ボリュームを削除します。 
---
= ボリュームの削除 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
delete volumeコマンドは'1つまたは複数の標準ボリュームを削除します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
*ストレージアレイの設定に損傷の可能性*--このコマンドを実行するとすぐに、ボリューム内のすべてのデータが失われます。

====
[NOTE]
====
ボリュームのサイズが一定（現在は128TB）を超えた場合、削除はバックグラウンドで実行されており、解放されたスペースをすぐに使用できるとは限りません。

====


== 構文

[source, cli]
----
delete (allVolumes) |
volume [volumeName] |
volumes [volumeName1 ... volumeNameN]
[removeVolumeGroup=(TRUE | FALSE)]
[force=(TRUE | FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allVolumes」
 a| 
このパラメータは、ストレージアレイ内のすべてのボリュームを削除します。



 a| 
「 volume 」
 a| 
削除するボリュームの名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名が特殊文字を含んでいる場合または数字のみで構成される場合は、ボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「ボリューム」
 a| 
削除する複数のボリュームの名前。以下のルールを使用して、ボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


ボリューム名が特殊文字を含んでいる場合または数字のみで構成されている場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
'removeVolumeGroup'
 a| 
ボリュームグループ内の最後のボリュームを削除しても、ボリュームグループは削除されません。スタンドアロンのボリュームグループ（ボリュームが含まれていないもの）を使用することもできます。スタンドアロン・ボリューム・グループを削除するには'このパラメータをTRUEに設定しますスタンドアロン・ボリューム・グループを変更しない場合は'このパラメータをFALSEに設定します



 a| 
「フォース」
 a| 
このパラメータを使用すると、コントローラで他の処理が実行されている場合でも、ボリュームの強制削除がすぐに実行されます。ボリュームの削除をすぐに強制的に実行するには、このパラメータを「true」に設定します。コントローラが他の操作を完了するまで待機するには、このパラメータを使用しないか、このパラメータをFALSEに設定します。

|===


== 注：

allVolumesパラメータを使用する場合'このコマンドは'すべてのボリュームが削除されるまで'またはエラーが発生するまで'ボリュームを削除しますエラーが発生した場合、このコマンドは残りのボリュームを削除しません。異なるボリュームグループからボリュームを削除できます。「removeVolumeGroup」パラメータを「true」に設定すると、空になったボリュームグループはすべて削除されます。

ボリューム・グループ全体を削除する場合は'delete volumegroupコマンドも使用できます



== 最小ファームウェアレベル

6.10

7.10で、「removeVolumeGroup」パラメータが追加されました。
