---
permalink: commands-a-z/delete-hostport.html 
sidebar: sidebar 
keywords: delete, hostport, command, host, port, identification 
summary: DELETE HostPortコマンドは、ホストポートIDを削除します。 
---
= ホストポートの削除 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
delete HostPortコマンドは'ホスト・ポートの識別情報を削除します



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

IDは、コントローラへの物理ホストポートを表すソフトウェア値です。識別情報を削除すると、コントローラでは、ホストポートからの指示やデータが認識されなくなります。

[IMPORTANT]
====
iSCSI環境では、ホストポートがイニシエータとみなされるため、このコマンドは機能しません。代わりに'delete iscsiInitiatorコマンドを使用しますを参照してください xref:delete-iscsiinitiator.adoc[iSCSIイニシエータの削除]。

====


[[syntax]]
== 構文

[source, cli]
----
delete hostPort [hostPortName]
----


[[parameter]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ホストポート」
 a| 
削除するホストポートの名前。ホストポートの名前は角かっこ（[]）で囲みます。ホストポート名が特殊文字を含んでいる場合または数字のみで構成される場合は、二重引用符（""）で囲んだ上で角かっこで囲む必要があります。

|===


[[notes]]
== 注：

ホストポートは、ホストコンピュータ内にあるホストアダプタ上の物理接続です。ホストポートは、ストレージアレイ内のボリュームへのホストアクセスを提供します。



[[minimum-firmware-level]]
== 最小ファームウェアレベル

5.20
