---
permalink: commands-a-z/delete-volume-from-disk-pool.html 
sidebar: sidebar 
keywords: delete, volume, command, normal, thin, disk pool, roles, support 
summary: delete volumeコマンドは、通常のボリュームまたはシンボリュームをディスクプールから削除します。 
---
= ディスクプールからボリュームを削除します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
delete volumeコマンドは'ディスク・プールから通常のボリュームまたはシン・ボリュームを削除します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドを使用して、ボリュームに関連するスケジュールを削除することもできます。スケジュールを削除しても、ボリュームは削除されません。

====
*ストレージアレイの設定に損傷の可能性*--このコマンドを実行するとすぐに、ボリューム内のすべてのデータが失われます。

====


== 構文

[listing, subs="+macros"]
----
delete (allVolumes |
volume [volumeName] |
pass:quotes[volumes ["_volumeName1_" ... "_volumeNameN_"]]
[force=(TRUE | FALSE)]
[schedule]
[retainRepositoryMembers=(TRUE | FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allVolumes」
 a| 
このパラメータは、ディスクプール上のすべてのボリュームを削除します。



 a| 
「 volume 」
 a| 
削除する特定のボリュームの名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名が特殊文字を含んでいる場合または数字のみで構成される場合は、ボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「ボリューム」
 a| 
削除する複数のボリュームの名前。以下のルールを使用して、ボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
「フォース」
 a| 
このパラメータを使用すると、コントローラで他の処理が実行されている場合でも、ボリュームの強制削除がすぐに実行されます。ボリュームの削除をすぐに強制的に実行するには、このパラメータを「true」に設定します。コントローラが他の操作を完了するまで待機するには、このパラメータを使用しないか、このパラメータをFALSEに設定します。



 a| 
「スケジュール」
 a| 
このパラメータは、特定のディスクプールボリュームに関連するスケジュールを削除します。スケジュールのみが削除され、ディスクプールボリュームは残ります。



 a| 
retainRepositoryMembers
 a| 
シンボリュームを削除すると、関連付けられているリポジトリボリュームもデフォルトで削除されます。ただし'retainRepositoryMembersがtrueに設定されている場合'リポジトリ・ボリュームは保持されます通常のボリュームの場合、このパラメータは効果がありません。

|===


== 注：

allVolumesパラメータを使用する場合'このコマンドは'すべてのボリュームが削除されるまで'またはエラーが発生するまで'ボリュームを削除しますエラーが発生した場合、このコマンドは残りのボリュームを削除しません。異なるボリュームグループからボリュームを削除できます。「removeVolumeGroup」パラメータを「true」に設定すると、空になったボリュームグループはすべて削除されます。



== 最小ファームウェアレベル

7.83
