---
permalink: commands-a-z/diagnose-controller-iscsihostport.html 
sidebar: sidebar 
keywords: diagnose, controller, hostport, command, diagnostic, tests, copper, cable, host, interface, cards, support, roles 
summary: DiagnoseController iscsiHostPortコマンドは、iSCSIホストインタフェースカードとコントローラ間の銅線ケーブル上で診断テストを実行します。 
---
= コントローラのiSCSIホストケーブルを診断します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「diagnose controller iscsiHostPort」コマンドは、iSCSIホストインターフェイスカードとコントローラの間の銅線ケーブル上で診断テストを実行します。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

選択したポートまたはすべてのポートで診断を実行できます。ポートはケーブル診断をサポートできる必要があります。ポートがケーブル診断をサポートしていない場合は、エラーが返されます。



== 構文

[listing]
----
diagnose controller [(a|b)]
iscsiHostPort ([all] | [portLabel])
testID=cableDiagnostics
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「controller」と入力します
 a| 
ケーブル診断テストを実行するコントローラ。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラですコントローラの識別子は角かっこ（[]）で囲みます。コントローラを指定しないと、ストレージ管理ソフトウェアから構文エラーが返されます。



 a| 
「iscsiHostPort」のように入力します
 a| 
診断テストを実行するiSCSIホストポート。すべてのiSCSIホストポート上で診断を実行するか、または特定のiSCSIホストポート上で診断を実行できます。

詳細については、次を参照してください。

<<iSCSIホストポートラベルの特定,"iSCSIホストポートラベルの識別">>



 a| 
「testID」
 a| 
実行する診断テストの識別子。この診断テストで選択できるのは「cableDiagnostics」のみです。

|===


== iSCSIホストポートラベルの特定

ホストポートのラベルを指定する必要があります。ホストポートのラベルを指定する手順は、次のとおりです。

. iSCSIホスト・ポートのポート・ラベルがわからない場合は、「show controller」コマンドを実行します。
. 結果のHost interfaceセクションで、選択するホストポートを特定します。
+
[NOTE]
====
ポート・ラベルは'Port'フィールドに返される完全な値です

====
. ポートラベルの値全体を引用符と角かっこで囲みます。["portLabel"]たとえば、ポートラベルが「Ch 2」の場合は、iSCSIホストポートを次のように指定します。
+
[listing]
----
iscsiHostPort[\"ch 2\"]
----
+
[NOTE]
====
Windowsのコマンドラインを使用していて、ラベルにパイプ（|）が含まれている場合は、文字をエスケープする必要があります（｛キャレット｝を使用）。エスケープしない場合は、コマンドと解釈されます。たとえば、ポートラベルが「e0b|0b'」の場合は、iSCSIホストポートを次のように指定します。

====
+
[listing]
----
iscsiHostPort[\"e0b^|0b\"]
----


[NOTE]
====
下位互換性のために、引用符と角かっこではなく角かっこ[]で囲まれているiscsiPortNumberも、引き続きE2700、E5600、EF560の各コントローラ（およびEシリーズまたはEFシリーズの他の旧世代コントローラ）に使用できます。これらのコントローラでは、iscsiPortNumberの有効な値は次のとおりです。

* ホストポートが統合されたコントローラの場合、番号は3、4、5、または6です。
* ホストインターフェイスカード上にのみホストポートがあるコントローラの場合、番号は1、2、3、または4です。


以前の構文の例を次に示します。

[listing]
----
iscsiHostPort[3]
----
====


== 注：

ケーブル診断テストを実行すると、ファームウェアから次の情報が返されます。

* *ホストポート*：診断テストを実行したポート。
* * HIC *：このポートに関連付けられているホストインターフェイスカード。
* テストが実行された日時。
* *ステータス*：
+
** * OK *：すべてのケーブルペアが良好で、故障はありません。
** * Open *：4つのケーブルペアのうち1つ以上が開いています。
** *ショート*：4つのケーブルペアのうち1つ以上がショートしています。
** *不完全*：4つのペアのうち1つ以上が不完全または無効なテスト結果を返しました。


* *長さ*：ケーブルの長さはメートル単位で表示され、ケーブルに関する次の情報が返されます。
+
** ケーブルのステータスがOKの場合は、ケーブルペアのおおよその長さが返されます。ケーブルペアの長さが範囲（L1-L2）として表示されます。これは、ケーブルペアの最短、最長の長さです。
** ケーブルのステータスがOpenまたはShortの場合は、ケーブルペアの障害箇所へのおおよその距離。障害が1つの場合は、そのケーブルペアの長さが報告されます。障害が複数ある場合は、障害までの最短、最長の両方の長さに関する情報が返されます。長さは範囲（L1-L2）として表示されます（L1<L2）。
** ケーブルのステータスがIncompleteの場合は、ファームウェアで正常にテストできる最短、最長のケーブルペアの長さに関する情報が返されます。長さは、有効なケーブルペアの範囲（L1-L2）として表示されます（L1<L2）。


* ケーブル診断レジスタの値を登録します。値は16進形式です。
+
** 2バイトは複合ケーブルステータスを示します（ポートあたり4ビット）。
** 4つの2バイトの数字は、各チャネルの長さを示します。






== 最小ファームウェアレベル

7.77

8.10で、iSCSIホストポートの番号付け方法が改定されました。
