---
permalink: commands-a-z/diagnose-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: diagnose, command, tests, possible, communication, problems, local, storage, array, remote, asynchronous, mirror, group 
summary: asyncMirrorGroupコマンドは、非同期ミラーグループに関連付けられているローカルストレージアレイとリモートストレージアレイ間の通信に関する問題を診断します。 
---
= 非同期ミラーグループ接続をテストします
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「diagnose asyncMirrorGroup」コマンドは、非同期ミラーグループに関連付けられているローカルストレージアレイとリモートストレージアレイ間の通信の問題をテストします。



== サポートされているアレイ

このコマンドは、一部制限付きで個々のストレージアレイを環境 接続します。E2700またはE5600のアレイに対して実行する場合は、制限はありません。

[NOTE]
====
E2800またはE5700アレイに対して実行する場合は、クライアントタイプを「symbol」に設定する必要があります。クライアント・タイプがhttpsに設定されている場合'このコマンドは実行されません

====


== ロール

このコマンドをE2800またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[listing, subs="+macros"]
----
pass:quotes[diagnose asyncMirrorGroup [_asyncMirrorGroupName_]]
testID=(all | connectivity | latency | bandwidth | portConnections)
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「asyncMirrorGroup」
 a| 
テストする既存の非同期ミラーグループの名前。非同期ミラーグループ名は角かっこ（[]）で囲みます。非同期ミラーグループ名に特殊文字または数字が含まれている場合は、非同期ミラーグループ名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「testID」
 a| 
実行する診断テストの識別子。識別子とテストは次のとおりです。

* * all *--このコマンドに関連するすべてのテストを実行します。
* *接続*-- 2台のコントローラに通信パスがあることを確認します接続テストでは、ストレージアレイ間でコントローラ間メッセージを送信して、リモートストレージアレイに対応する非同期ミラーグループが存在するかどうかを検証します。また、非同期ミラーグループのリモートシステム上のボリュームメンバーがローカルシステム上のボリュームメンバーと一致していることを確認します。
* * Latency *--非同期ミラーグループのリモートストレージアレイ上の各ボリュームにSCSIテストユニットコマンドを送信して、最小、平均、最大のレイテンシをテストします。
* *bandwidth*-- 2つのコントローラ間メッセージをリモートストレージアレイに送信して、最小、平均、最大の帯域幅、およびテストを実行しているコントローラ上のポートのネゴシエートされたリンク速度をテストします。
* *ポート接続*--ローカルストレージアレイ上のミラーリングに使用されているポート'およびリモートストレージアレイ上のミラーデータを受信しているポートを表示します


|===


== 最小ファームウェアレベル

7.84
