---
permalink: commands-a-z/diagnose-controller.html 
sidebar: sidebar 
keywords: diagnose, controller, command, run, diagnostic, tests, arrays, roles, context 
summary: diagnostic controllerコマンドは、コントローラで診断テストを実行します。 
---
= コントローラを診断する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「diagnose controller」コマンドは、コントローラ上で診断テストを実行します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

診断テストは、データがドライブに書き込まれ、ドライブから読み取られるループバックテストで構成されます。



== 構文

[source, cli, subs="+macros"]
----
diagnose controller [(a| b)]
loopbackDriveChannel=(allchannels | (1 | 2 | 3 | 4 | 5 | 6 | 7 | 8))
testID=(1 | 2 | 3 | discreteLines)
pass:quotes[[patternFile="_filename_"]]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「controller」と入力します
 a| 
診断テストを実行するコントローラ。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラですコントローラの識別子は角かっこ（[]）で囲みます。コントローラを指定しないと、ストレージ管理ソフトウェアから構文エラーが返されます。



 a| 
「loopbackDriveChannel」のようなものです
 a| 
診断テストを実行するドライブチャネル。すべてのチャネルで診断を実行するか、診断を実行する特定のチャネルを選択することができます。特定のチャネルを選択した場合'ドライブ・チャネルの有効な値は'1''2`'3`'4`'5`です '6`'7`'または'8`



 a| 
「testID」
 a| 
実行する診断テストの識別子。識別子とテストは次のとおりです。

* '1'--読み取りテスト
* `2`--書き込みテスト
* `3`--データのループバックテスト
* 「discreteLines」--個別回線診断テスト




 a| 
「patternFile」のように指定します
 a| 
テストデータとして使用するデータパターンが含まれているファイルパスとファイル名。データパターンのファイル名は二重引用符（""）で囲みます。例：

'file="C:\Program Files\CLI\sup\patfile.txt

|===


== 注：

データのループバックテストを実行するときは、データパターンを含むファイルをオプションで指定できます。ファイルを指定しない場合は、コントローラファームウェアによってデフォルトのパターンが指定されます。

個別回線は、コントローラトレイ内の2つのコントローラ間で接続されている制御回線とステータス回線です個別回線診断テストでは、代替コントローラの制御入力で制御信号の遷移が観察できることをコントローラごとに確認できます。個別回線診断テストは、電源を再投入するたび、またはコントローラをリセットするたびに、自動的に実行されます。個別回線診断テストは、最初の個別回線診断テストに失敗したコンポーネントを交換したあとに実行できます。個別回線診断テストは、次のいずれかのメッセージを返します。

* 個別回線診断テストが正常に実行されると、次のメッセージが表示されます。
+
[listing]
----
The controller discrete lines successfully passed the diagnostic
test. No failures were detected.
----
* 個別回線診断テストが失敗した場合は、次のメッセージが表示されます。
+
[listing]
----
One or more controller discrete lines failed the diagnostic test.
----
* CLIで個別回線診断テストを実行できない場合、CLIはエラー270を返します。これは、個別回線診断テストが開始も完了もできなかったことを意味します。




== 最小ファームウェアレベル

6.10で、読み取りテスト、書き込みテスト、データのループバックテストが追加されました。

6.14で、個別回線診断テストが追加されました。

7.30で、更新されたドライブチャネル識別子が追加されました。
