---
permalink: commands-a-z/download-tray-firmware-file.html 
sidebar: sidebar 
keywords: download, tray, firmware, file, command, environmental, service, module, array, role, context 
summary: download tray firmware fileコマンドは、環境サービスモジュール（ESM）ファームウェアをダウンロードします。 
---
= 環境カードファームウェアのダウンロード - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
download tray firmware fileコマンドは'ESM（環境サービスモジュール）ファームウェアをダウンロードします



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== コンテキスト（Context）

[IMPORTANT]
====
System Managerで管理されるデュプレックスシステム（E2800など）のコントローラでは、IOMの自動同期サービスが実行されています。このサービスは、IOMファームウェアを、コントローラにロードされているSANtricity OSバンドルに含まれるバージョンと自動的に同期します。IOMファームウェアがコントローラにロードされているバージョンにリバートされないようにするには、このサービスを無効にする必要があります。IOMの自動同期サービスは、System ManagerまたはREST APIを使用して中断できます。このサービスを中断しても、自動同期が有効なままの場合はIOMファームウェアが最新の状態に更新される点に注意してください。

====


== 構文

[source, cli, subs="+macros"]
----
download (allTrays | tray [trayID])
pass:quotes[firmware file="_filename_"]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allTrays」
 a| 
このパラメータは、ストレージアレイ内の互換性のあるすべてのトレイに新しいファームウェアをダウンロードします。選択するファームウェアパッケージによって、互換性のあるトレイが決まります。互換性のないトレイはスキップされます。互換性のないトレイに関するエラーメッセージは表示されません。



 a| 
「tray」
 a| 
新しいファームウェアのロード先となるESMカードが含まれているドライブトレイ。トレイIDの値は'0～99ですトレイIDの値は角かっこ（[]）で囲みます。

[NOTE]
====
トレイIDの先頭にゼロを補うことはできません。たとえば、表示されているトレイIDが「02」の場合、このコマンドでは、[02]ではなく[2]と指定する必要があります。

====


 a| 
'file'
 a| 
ファームウェアイメージが含まれているファイルのファイルパスとファイル名。ファームウェアイメージのファイルパスとファイル名は二重引用符（""）で囲みます。例：

`file="C:\Program Files\CLI\dnld\esmfrm.esm"`

有効なファイル名の拡張子は「.ESM」です。

|===


== 注：

trayパラメータは'特定のドライブ・トレイに新しいファームウェアをダウンロードします新しいファームウェアを複数のドライブトレイにダウンロードする必要があるものの、すべてのドライブトレイではない場合は、ドライブトレイごとにこのコマンドを入力する必要があります



== 最小ファームウェアレベル

5.20
