---
permalink: commands-a-z/download-storagearray-nvsram.html 
sidebar: sidebar 
keywords: download, storagearray, down, values, controller, support, role, command, array 
summary: download storageArray NVSRAMコマンドは、ストレージアレイコントローラのNVSRAM値をダウンロードします。 
---
= ストレージアレイNVSRAMのダウンロード - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
download storageArray NVSRAMコマンドは、ストレージアレイコントローラのNVSRAM値をダウンロードします。



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage AdminまたはSupport Adminロールが必要です。



[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
pass:quotes[download storageArray NVSRAM file="_filename_"]
[healthCheckMelOverride=(TRUE | FALSE)]
----


[[parameters]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
'file'
 a| 
ファイルパスと、NVSRAM値が含まれているファイル名。NVSRAMファイル名は二重引用符（""）で囲みます。例：

`file="C:\Program Files\CLI\dnld\afrm.dlp "`

有効なファイル名の拡張子は「.dlp」です。



 a| 
「healthCheckMelOverride」
 a| 
メジャーイベントログ（MEL）の健全性チェックの結果を無視する設定。MELの検証は引き続き行われ、バイパスされません。MELのチェックに失敗した場合は、コマンドの実行時にこのパラメータを使用することで、エラーをバイパスできます。

ダウンロードの前に、コントローラがイベントログをチェックし、新しいNVSRAMのダウンロードを妨げる可能性のあるイベントが発生したかどうかを確認します。そのようなイベントが発生した場合、コントローラは、通常は新しいNVSRAMをダウンロードしません。

このパラメータを指定すると、コントローラは新しいNVSRAMを強制的にダウンロードします。デフォルト値は'FALSE'ですコントローラに新しいNVSRAMを強制的にダウンロードさせる場合は'この値をTRUEに設定します

|===


[[minimum-firmware-level]]
== 最小ファームウェアレベル

6.10

8.10で、「healthCheckMelOverride」パラメータが追加されました。
