---
permalink: commands-a-z/download-tray-configurationsettings.html 
sidebar: sidebar 
keywords: download, tray, configuration, settings, commands, factory, default, drive, array, specific, storage, roles, support 
summary: download tray configurationsettingsコマンドは、ストレージアレイ内のすべてのドライブトレイまたはストレージアレイ内の特定のドライブトレイに工場出荷時のデフォルト設定をダウンロードします。 
---
= ダウンロードトレイの構成設定 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
download tray configurationsettingsコマンドは'ストレージ・アレイ内のすべてのドライブ・トレイまたはストレージ・アレイ内の特定のドライブ・トレイに出荷時のデフォルト設定をダウンロードします



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
pass:quotes[download (allTrays | tray [_trayID_]] configurationSettings
pass:quotes[file="_filename_"]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allTrays」
 a| 
このパラメータは、ストレージアレイ内のすべてのトレイに新しいファームウェアをダウンロードします。



 a| 
「tray」
 a| 
新しいファームウェアのロード先となるESMカードが含まれているドライブトレイ。トレイIDの値は'0～99ですトレイIDの値は角かっこ（[]）で囲みます。



 a| 
'file'
 a| 
ファームウェアイメージが含まれているファイルのファイルパスとファイル名。ファームウェアイメージのファイルパスとファイル名は二重引用符（""）で囲みます。例：

`file="C:\Program Files\CLI\dnld\trayset.dlp "`

有効なファイル名の拡張子は「.dlp」です。

|===


== 注：

trayパラメータは'工場出荷時のデフォルト設定を特定のドライブ・トレイにダウンロードします工場出荷時のデフォルトの設定を複数のドライブトレイにダウンロードする必要があるものの、すべてのドライブトレイではない場合は、各ドライブトレイでこのコマンドを入力する必要があります



== 最小ファームウェアレベル

7.75
