---
permalink: commands-a-z/download-drive-firmware.html 
sidebar: sidebar 
keywords: download, drive, firmware, array, support, role, context, level 
summary: download drive firmwareコマンドは、ファームウェアイメージをドライブにダウンロードします。 
---
= ドライブファームウェアをダウンロードします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
download drive firmwareコマンドは'ファームウェア・イメージをドライブにダウンロードします



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== コンテキスト（Context）

[CAUTION]
====
*ストレージ・アレイの構成に損傷の可能性*--ドライブ・ファームウェアを誤ってダウンロードすると'ドライブが損傷したり'データ・アクセスが失われる可能性があります

====
[NOTE]
====
「content」パラメータは廃止されました。代わりに'firmware'パラメータを使用します

====
このコマンドは、一度に1つのドライブモデルのみにファームウェアイメージをダウンロードするためのものです。スクリプトでこのコマンドを使用する場合は、このコマンドを1回だけ使用してください。このコマンドを複数回使用すると、処理が失敗する可能性があります。download storageArray driveFirmwareコマンドを使用すると、ストレージアレイ内のすべてのドライブにファームウェアイメージを一度にダウンロードできます。



== 構文

[source, cli, subs="+macros"]
----
pass:quotes[download (drive \[_trayID_,[_drawerID,_]pass:quotes[_slotID_] \| drives\ pass:quotes[[_trayID1_,[_drawerID1_,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\])
 [online|offline] firmware file="filename"
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ドライブ」または「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
「online」または「offline」です
 a| 
オンライン・ドライブ・ファームウェアのダウンロードを実行するには'ONLINEを選択し'それ以外の場合はOFFLINEを選択しますデフォルト値は「offline」です。



 a| 
'file'
 a| 
ファームウェアイメージが含まれているファイルのファイルパスとファイル名。ファームウェアイメージのファイルパスとファイル名は二重引用符（""）で囲みます。例：

`file="C:\Program Files\CLI\dnld\drvfrm.dlp "`

有効なファイル名の拡張子は「.dlp」です。



 a| 
「firmware」（ファームウェア）
 a| 
コントローラファームウェアをダウンロードすることを示します。

|===


== 注：

ドライブファームウェアをダウンロードする前に、次の予防措置を取ります。

* 「online」パラメータを使用している場合を除き、ファームウェア・イメージをダウンロードする前に、ストレージ・アレイに対するすべてのI/Oアクティビティを停止してください。'online 'パラメータを指定せずに'download drive firmware'コマンドを実行すると'ダウンロードが完了するか失敗するまで'すべてのI/Oアクティビティがブロックされますただし'予防措置として'ドライブに影響する可能性のあるすべてのI/Oアクティビティが停止していることを確認してください
* ファームウェアイメージファイルにドライブトレイとの互換性があることを確認します選択したドライブトレイと互換性のないファームウェアイメージファイルをダウンロードすると、ドライブトレイが使用できなくなる可能性があります。
* ドライブファームウェアのダウンロード中は、ストレージアレイの設定を変更しないでください。設定を変更しようとすると、原因 でファームウェアのダウンロードが失敗し、選択したドライブが使用できなくなる可能性があります。
* このコマンドを使用してオンラインのドライブファームウェア更新要求が発行された場合、コントローラは、新しいファームウェアのダウンロード先となるドライブのリストからRAID 0ボリュームグループドライブを削除します。個々のドライブの戻りステータスは'［理由を使用しない］に設定されます


ファームウェアをドライブにダウンロードするときは、システムに格納されているファームウェアイメージの完全パスとファイル名を指定する必要があります。

ストレージ・アレイ内のすべてのドライブにファームウェアをインストールする前に'download drive'コマンドを使用して'1台のドライブ上でファームウェアをテストできますダウンロードでは、次のいずれかのステータスが返されます。

* 成功しました
* 理由で失敗しました
* 理由がない


'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。



== 最小ファームウェアレベル

7.60で'drawerID'ユーザ入力が追加されました

8.25で'online'パラメータが追加されました
