---
permalink: commands-a-z/enable-storagearray-externalkeymanagement-file.html 
sidebar: sidebar 
keywords: enable, storage, array, external, key, management, file, command, security, disk, encryption, initial, roles, context, support 
summary: enable storageArray externalKeyManagement fileコマンドは、Full Disk Encryptionドライブを含むストレージアレイの外部セキュリティキー管理を有効にし、最初のドライブセキュリティキーを作成します。 
---
= 外部セキュリティキー管理を有効にする - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
enable storageArray externalKeyManagement fileコマンドは'フルディスク暗号化ドライブを持つストレージ・アレイの外部セキュリティ・キー管理を有効にし'初期ドライブ・セキュリティ・キーを作成します



== サポートされているアレイ

このコマンドは、E4000、E2800、E5700、EF600、またはEF300の個 々 のストレージアレイに適用されます。E2700またはE5600のストレージアレイに対しては機能しません。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Security Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
このコマンドは、外部キー管理にのみ適用されます。

====


== 構文

[source, cli, subs="+macros"]
----
enable storageArray externalKeyManagement
pass:quotes[file="_fileName_"]
pass:quotes[passPhrase="_passPhraseString_"]
pass:quotes[saveFile=_(TRUE | FALSE)_]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
'file'
 a| 
新しいセキュリティキーを格納するファイルパスとファイル名。ファイルパスとファイル名は二重引用符（ "" ）で囲みます。例：

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
ファイル名の拡張子は「.slk」でなければなりません。

====


 a| 
パスフレーズ
 a| 
セキュリティキーを外部ファイルに格納できるように、セキュリティキーを暗号化する文字列。パスフレーズの文字列は二重引用符（""）で囲みます。



 a| 
「saveFile」を参照してください
 a| 
セキュリティキーを検証してファイルに保存します。保存しない場合は'FALSE'に設定し'ファイルのセキュリティ・キーを確認しますデフォルト値は「true」です。

|===


== 注：

パスフレーズは次の条件を満たしている必要があります。

* 8~32文字で指定する必要があります。
* 大文字を1つ以上含む。
* 小文字を1つ以上含む。
* 数字を1つ以上含む。
* 英数字以外の文字（<>@+など）を少なくとも1文字含める必要があります。


[NOTE]
====
パスフレーズがこれらの条件を満たしていない場合は、エラーメッセージが表示されます。

====


== 最小ファームウェアレベル

8.40

8.70で'_saveFile_'パラメータが追加されました
