---
permalink: commands-a-z/establish-asyncmirror-volume.html 
sidebar: sidebar 
keywords: establish, asynmirror, volume, asynchronous, mirrored, remote, storage, array, secondary, existing 
summary: Establish asyncMirror volumeコマンドは、既存の非同期ミラーグループにセカンダリボリュームを追加することで、リモートストレージアレイ上の非同期ミラーペアを作成します。 
---
= 非同期ミラーペアを確立します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
Establish asyncMirror volumeコマンドは'既存の非同期ミラー・グループにセカンダリ・ボリュームを追加することにより'リモート・ストレージ・アレイ上の非同期ミラー・ペアを完成させます



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700などの個 々 のストレージアレイを環境に設定します。 EF600およびEF300アレイ（すべてのSMcliパッケージがインストールされている必要があります。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドを実行する前に、非同期ミラーグループが存在している必要があり、非同期ミラーグループにプライマリボリュームが存在している必要があります。このコマンドが正常に完了すると、プライマリボリュームとセカンダリボリュームの間で非同期ミラーリングが開始されます。

非同期ミラーペアを構成する2つのボリュームは、単一のエンティティとして機能します。非同期ミラーペアを確立すると、ミラーペア全体に対して処理を実行でき、2個のボリュームを個別に処理する必要はありません。



== 構文

[listing, subs="+macros"]
----
pass:quotes[establish asyncMirror volume="_secondaryVolumeName_"]
pass:quotes[asyncMirrorGroup="_asyncMirrorGroupName_"]
pass:quotes[primaryVolume="_primaryVolumeName_"]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
セカンダリボリュームに使用する、リモートストレージアレイ上の既存のボリュームの名前。ボリューム名は二重引用符（""）で囲みます。



 a| 
「asyncMirrorGroup」
 a| 
非同期ミラーペアの格納に使用する既存の非同期ミラーグループの名前。非同期ミラーグループ名は二重引用符（""）で囲みます。



 a| 
「primaryVolume」
 a| 
プライマリボリュームに使用する、ローカルストレージアレイ上の既存のボリュームの名前。ボリューム名は二重引用符（""）で囲みます。

|===


== 注：

非同期ミラーペアは、プライマリボリュームとセカンダリボリュームの2つのボリュームで構成され、同じデータの同一のコピーが含まれます。ミラーペアは非同期ミラーグループの一部です。これにより、ミラーペアは、非同期ミラーグループ内の他のミラーペアと同時に同期できます。

名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。名前の最大文字数は30文字です。

プライマリボリュームとセカンダリボリュームを選択するときは、セカンダリボリュームのサイズをプライマリボリューム以上にする必要があります。セカンダリボリュームのRAIDレベルをプライマリボリュームと同じにする必要はありません。



== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
