---
permalink: commands-a-z/export-storagearray-securitykey.html 
sidebar: sidebar 
keywords: export, storage, array, security, key, command, save, drive, securitykey, file, context, role 
summary: export storageArray securityKeyコマンドは、ドライブセキュリティキーをファイルに保存します。 
---
= ストレージアレイのセキュリティキーをエクスポートします
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「export storageArray securityKey」コマンドは、ドライブセキュリティキーをファイルに保存します。



== サポートされているアレイ

外部キー管理が有効になっている場合、このコマンドはE2800、E5700、EF600、およびEF300アレイにのみ適用されます。内部キー管理が有効になっている場合、すべてのSMcliパッケージがインストールされていれば、コマンド環境 は個々のストレージアレイを対象とします。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Security Adminロールが必要です。



== コンテキスト（Context）

あるストレージアレイからキーファイルがエクスポートされたときに、そのキーを別のストレージアレイにインポートできます。これにより、ストレージアレイ間でセキュリティ対応ドライブを移動できます。

[NOTE]
====
このコマンドは、内部と外部の両方のキー管理を環境 に行います。

====


== 構文

[listing, subs="+macros"]
----
export storageArray securityKey
pass:quotes[passPhrase="_passPhraseString_"]
pass:quotes[file="_fileName_"]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
パスフレーズ
 a| 
セキュリティキーを外部ファイルに格納できるように、セキュリティキーを暗号化する文字列。パスフレーズは二重引用符（""）で囲みます。



 a| 
'file'
 a| 
セキュリティキーの保存先となるファイルパスとファイル名。例：

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
ファイル名の拡張子は「.slk」でなければなりません。

====
|===


== 注：

ドライブの移動先となるストレージアレイには、インポートするドライブ以上の容量を持つドライブが必要です。

コントローラファームウェアによってロックが作成され、Full Disk Encryption（FDE）ドライブへのアクセスが制限されます。FDEドライブには、Security Capableという状態があります。セキュリティキーを作成すると、状態はSecurity Enabledに設定され、これによって、ストレージアレイ内に存在するすべてのFDEドライブへのアクセスが制限されます。

パスフレーズは次の条件を満たしている必要があります。

* 8~32文字で指定する必要があります。
* 空白を含まない。
* 大文字を1つ以上含む。
* 小文字を1つ以上含む。
* 数字を1つ以上含む。
* 英数字以外の文字（<>@+など）を少なくとも1文字含める必要があります。


[NOTE]
====
パスフレーズがこれらの条件を満たしていない場合は、エラーメッセージが表示され、コマンドを再試行するように求められます。

====


== 最小ファームウェアレベル

7.40
