---
permalink: commands-a-z/load-storagearray-dbmdatabase.html 
sidebar: sidebar 
keywords: load, storage array, database, command, management 
summary: load storageArray dbmDatabaseコマンドは、ファイルまたはキャッシュからイメージを取得することによって、データベース管理（DBM）データベースイメージをリストアします。 
---
= ストレージアレイ DBM データベースのロード - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
load storageArray dbmDatabaseコマンドは、ファイルまたはキャッシュからイメージを取得することによって、データベース管理（DBM）データベースイメージをリストアします。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Security Adminロールが必要です。



== コンテキスト（Context）

このコマンドは、「save storageArray dbmDatabase」コマンドを使用してデータベースイメージがキャプチャされたときの正確な構成にストレージアレイのDBMデータベースをリストアします。ファイル内のデータには、RAID構成、ボリュームグループ、およびディスクプールのデータが含まれています。

このコマンドと'file'オプションを使用する前に'まずバリデータ文字列(セキュリティコード)をテクニカルサポートから取得する必要がありますバリデータを取得するには'save storageArray dbmValidatorInfo'コマンドを使用して'バリデータ情報を含むXMLファイルを生成しますテクニカルサポートでは、このXMLファイルを使用して、このコマンドに必要なバリデータ文字列を生成します。



== 構文

[source, cli, subs="+macros"]
----
load storageArray dbmDatabase
pass:quotes[((file="_filename_" validator="_validatorValue_") | sourceLocation=onboard)]
[controller [(a|b)]]
[contentType= all]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
'file'
 a| 
アップロードするDBMデータベースのファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。例：

「file="C:\Array Backups\DBMbackup_03302010.dbm"」このコマンドでは、保存されたファイルにファイル拡張子が自動的に付加されません。ファイル名にはファイル拡張子を指定する必要があります。



 a| 
「バリデータ」
 a| 
ストレージアレイを既存の構成にリストアするために必要な英数字のセキュリティコード。

テクニカルサポートからバリデータを取得する必要があります。バリデータを取得するには'save storageArray dbmValidatorInfo'コマンドを実行して'必要な検証情報のXMLファイルを生成します検証情報のXMLファイルを生成したら、テクニカルサポートに問い合わせてバリデータを取得します。

バリデータは二重引用符（""）で囲みます。



 a| 
「sourceLocation」と入力します
 a| 
このパラメータは、バックアップデータベースの情報を取得する場所を指定します。パラメータは一貫性のために含める必要がありますが'使用できる値は'onboardのみです



 a| 
「controller」と入力します
 a| 
このパラメータは、データの取得元である専用のコントローラを指定します。コントローラの識別子は角かっこ（[]）で囲みます。「controller」パラメータが指定されていない場合は、どちらのコントローラからもデータが取得される可能性があります。

有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラです



 a| 
「contentType」を参照してください
 a| 
このパラメータは、取得するデータのコンテンツタイプを指定します。

このパラメータはデフォルトで「all」に設定されているため、ディスク・プール構成データを含むすべてのデータが取得されます。

|===


== 注：

データベースイメージのサイズによっては、データベースのリストアに30分ほどかかる場合があります。データベースイメージをロードするためのすべての操作がコントローラで完了するまで、ホストソフトウェアには最適状態のコントローラが表示されません。



== 最小ファームウェアレベル

7.75

7.83で、次のパラメータが追加されました

* 「sourceLocation」と入力します
* 「controller」と入力します
* 「contentType」を参照してください

