---
permalink: commands-a-z/recover-sasport-miswire.html 
sidebar: sidebar 
keywords: recover, sas, port, mis-wire 
summary: sasPortの誤配線コマンドは、誤配線状態からリカバリするための修正措置が実行されたことをコントローラに通知します。 
---
= SASポート誤配線をリカバリします
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「recover sasPortの誤配線」コマンドは、誤配線状態からリカバリするための修正措置が実行されたことをコントローラに通知します。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== コンテキスト（Context）

誤配線が検出されたために無効になったSASポートが、コントローラによって再有効化されます。SASの誤配線状態を修正してからこのコマンドを実行してください。

SASの誤配線状態とは次のいずれかです。

* 無効なSASトポロジです
* コントローラのホストポートから拡張トレイへの接続
* イニシエータからドライブトポロジへの接続
* ESMの誤配線




== 構文

[listing]
----
recover sasPort miswire
----


== パラメータ

なし



== 注：

誤配線状態が検出されると、コントローラファームウェアは次の内容を報告します。

* 誤配線状態が存在することを示す重大MELイベント
* 「Needs attention」状態です
* 誤配線を示すリカバリアクション


また、誤配線が原因でアクセスパスが1つしかないドライブ、ESM、およびトレイ（ストレージアレイの下段のトレイなど）についても、「冗長性が失われました」という情報が報告されます。冗長性の損失情報はSASトポロジに固有のものではありません。

SASポートの誤配線に関連するイベント通知を次に示します。

* SASの誤配線が検出されました
* HBAがドライブチャネルに接続されています
* ドライブチャネルはクロス配線されています


誤配線状態の際、SASドメインの整合性を保護するためにコントローラが1つ以上のSASポートを無効にする場合は、次の手順に従ってこの状態からリカバリしてください。

. 間違った場所にあるケーブルを特定して取り外します。最後に新しいケーブルを取り付ける作業を行った場合は、これが最も可能性の高い方法です。そうでない場合は、ストレージアレイの一部ではないデバイスに接続されているケーブルまたはチャネル間で接続されているケーブルを探してください。リカバリイベントでは、誤配線が検出されたチャネル、および場合によってはトレイが報告されます
. ケーブルを取り外した後、またはケーブルを正しい場所に移動した後、「recover sasPort eぶ る」コマンドを実行します。誤配線が検出されたときに無効になったSASポートが、コントローラによって再有効化されます。
. 誤配線が原因で取り外したケーブルまたは正しい場所に移動したケーブルが無効にしたポートへの唯一のアクセスをコントローラに提供していた場合、コントローラは無効にしたSASポートを再有効化できません。リカバリを完了するには、ストレージアレイ内のトレイの電源を再投入する必要があります。




== 最小ファームウェアレベル

8.10で
