---
permalink: commands-a-z/recopy-volumecopy-target.html 
sidebar: sidebar 
keywords: volumecopy, target, command, operation, volume, copy, pair, reinitiate, array, role, context 
summary: recopy VolumeCopy targetコマンドは、既存のボリュームコピーペアを使用してボリュームコピー操作を再開します。 
---
= ボリュームコピーの再コピー - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
recopy VolumeCopy targetコマンドは'既存のボリューム・コピー・ペアを使用してボリューム・コピー操作を再開します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
ファームウェア・バージョン7.83では'copyType=(online | offline)パラメータは使用されなくなりました

====
このコマンドは、Snapshotイメージのボリュームコピーペアに対して有効です。

このコマンドは、Snapshotイメージボリュームを使用して作成したボリュームコピーペアと連携します。

[NOTE]
====
ボリュームコピー処理を開始すると、ターゲットボリューム上の既存のデータはすべて上書きされ、ターゲットボリュームがホストに対して読み取り専用になり、ターゲットボリュームに関連付けられているSnapshotイメージボリュームがある場合はすべて使用が停止されます。以前にターゲットボリュームをコピーとして使用したことがある場合は、データが不要になっていること、またはデータをバックアップ済みであることを確認してください。

====


== 構文

[source, cli]
----
recopy volumeCopy target [targetName]
[source [sourceName]]
[copyPriority=(highest | high | medium | low | lowest)]
[targetReadOnlyEnabled=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「target」と入力します
 a| 
ボリュームコピー処理を再開するターゲットボリュームの名前。ターゲットボリューム名は角かっこ（[]）で囲みます。ターゲットボリューム名が特殊文字を含んでいる場合は、ターゲットボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「source」を参照してください
 a| 
ボリュームコピー処理を再開するソースボリュームの名前。ソースボリューム名は角かっこ（[]）で囲みます。ソースボリューム名に特殊文字が含まれている場合は、ソースボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「copyPriority」
 a| 
ホストのI/Oアクティビティに対するボリュームコピーの優先度。有効な値は'highest'high`'high`'medium`'low''low'lowest`です



 a| 
targetReadOnlyEnabled
 a| 
ターゲットボリュームへの書き込みを可能にするか、ターゲットボリュームからの読み取りのみを可能にするかを選択する設定。ターゲット・ボリュームに書き込むには'このパラメータをFALSEに設定しますターゲット・ボリュームに書き込みできないようにするには'このパラメータをTRUEに設定します

|===


== 注：

コピー優先度は、ボリュームコピーペアのソースボリュームとターゲットボリュームの間のデータのコピーに使用されるシステムリソースの量を定義します。最高の優先度レベルを選択すると、ほとんどのシステムリソースを使用してボリュームのコピーが実行されるため、ホストのデータ転送パフォーマンスが低下します。



== 最小ファームウェアレベル

6.10

7.83で'copyType=(online | offline)パラメータが削除されました
