---
permalink: commands-a-z/recover-volume.html 
sidebar: sidebar 
keywords: recover, raid, volume 
summary: 'recover volumeコマンドは"ドライブ上のユーザーデータ領域を初期化せずに"指定されたプロパティを使用してRAIDボリュームを作成します' 
---
= RAIDボリュームをリカバリします
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
recover volumeコマンドは'ドライブ上のユーザー・データ領域を初期化せずに'指定されたプロパティを持つRAIDボリュームを作成します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

パラメータ値は、ストレージアレイのリカバリプロファイルデータファイル（「recovery-profile.csv」）から取得されます。このコマンドを使用すると、既存のボリュームグループにリカバリボリュームを作成したり、新しいボリュームグループを作成したりできます。

[NOTE]
====
このコマンドはコマンドラインからのみ実行できます。GUIスクリプトエディタからこのコマンドを実行することはできません。ストレージ管理GUIを使用してボリュームをリカバリすることはできません。

====
[NOTE]
====
このコマンドをDynamic Disk Pool（DDP）ボリュームに対して使用することはできません。

====


== 構文

[listing, subs="+macros"]
----
recover volume (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_])) |
(drives=pass:quotes[_trayID1_,pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn,_]pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])) |
volumeGroup=pass:quotes[_volumeGroupName_]))
[newVolumeGroup=pass:quotes[_volumeGroupName_]]
userLabel=pass:quotes["_volumeName_" volumeWWN="_volumeWWN_"
capacity=_volumeCapacity_
offset=_offsetValue_
raidLevel=(0 | 1 | 3 | 5 | 6)
segmentSize=_segmentSizeValue_
dssPreAllocate=(TRUE | FALSE)
SSID=_subsystemVolumeID_]
[owner=(a|b)]
[cacheReadPrefetch=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
[hostUnmapEnabled=(TRUE | FALSE)]
[blockSize=blockSizeValue]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「ドライブ」または「ドライブ」
 a| 
リカバリ対象のボリュームを追加するボリュームグループに割り当てるドライブ。大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
「volumeGroup」のように指定します
 a| 
ボリュームを作成する既存のボリュームグループの名前。（ストレージアレイ内のボリュームグループの名前を決定するには、「show storageArray profile'」コマンドを実行します）。



 a| 
「newVolumeGroup」と入力します
 a| 
新しいボリュームグループに付ける名前。新しいボリュームグループ名は二重引用符（""）で囲みます。



 a| 
「userLabel」のように入力します
 a| 
リカバリするボリュームの名前。ユーザーラベルには、次の2つの部分があります。

* ボリューム名。ボリューム名は二重引用符（""）で囲みます。
* ボリュームのWorld Wide Name（「volumeWWN」）。16バイトの識別子（60080E500017B4320000000049887D77など）で指定します。識別子は二重引用符（""）で囲みます。


ボリューム名とボリュームのWorld Wide Nameの両方を入力する必要があります。最初にボリューム名を入力する必要があります。例：

[listing]
----
userLabel="engdata"
volumeWWN=60080E500017B4320000000049887D77
----


 a| 
「容量」
 a| 
ストレージアレイに追加するボリュームのサイズ。サイズは'bytes'KB'MB`'GB'TB'の単位で定義されます



 a| 
「offset」
 a| 
ボリュームグループの先頭から参照されるボリュームの先頭までのブロックの数。



 a| 
raidLevel
 a| 
ドライブが含まれているボリュームグループのRAIDレベル。有効な値は'0`'1' 3`'5`または'6`です



 a| 
「segmentSize」のように表示されます
 a| 
コントローラがボリュームグループ内の1つのドライブに書き込めるデータ量（KB）を指定します。有効な値は'8`'16`'32`'64`'128`'です 「256」または「512」。



 a| 
dssPreAllocate
 a| 
将来的なセグメントサイズの変更に備えてボリュームのストレージ容量の割り当てをオンまたはオフにするための設定。割り当てをオンにするには'このパラメータをTRUEに設定します割り当てを無効にするには'このパラメータをFALSEに設定します



 a| 
「ssid」
 a| 
ボリュームのストレージアレイサブシステムの識別子。show volumeコマンドを使用して'ストレージ・アレイ・サブシステムの識別子を確認します



 a| 
「owner」をクリックします
 a| 
ボリュームを所有するコントローラ。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラです所有者を指定しない場合は、コントローラファームウェアによって所有者が決定されます。



 a| 
「cacheReadPrefetch」というメッセージが表示されます
 a| 
キャッシュ読み取りプリフェッチをオンまたはオフにする設定。キャッシュ読み取りプリフェッチをオフにするには'このパラメータをFALSEに設定しますキャッシュ読み取りプリフェッチをオンにするには'このパラメータをTRUEに設定します



 a| 
hostUnmapEnabled
 a| 
このパラメータがTrueに設定されている場合'ホストはボリュームへの問題 UNMAPコマンドを許可されますUNMAPコマンドは、リソースプロビジョニングされたボリュームでのみ実行できます。



 a| 
「ブロックサイズ」
 a| 
この設定はボリュームのブロックサイズ（バイト）です。

|===


== 注：

ストレージ管理ソフトウェアは、監視対象のストレージアレイのリカバリプロファイルを収集して、ストレージ管理ステーションにプロファイルを保存します。

'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。

'drive'パラメータまたは'drivs'パラメータを使用してボリュームをリカバリしようとし'ドライブが未割り当て状態の場合'コントローラは自動的に新しいボリューム・グループを作成します新しいボリューム・グループの名前を指定するには'newVolumeGroup'パラメータを使用します

名前には、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。名前の最大文字数は30文字です。

ownerパラメータは'ボリュームを所有するコントローラを定義しますボリュームの優先コントローラ所有者は、ボリュームグループを現在所有しているコントローラです。



== ストレージ容量を事前に割り当てます

dssPreAllocateパラメータを使用すると'ボリュームの再構築に使用される情報を格納するための容量をボリュームに割り当てることができますdssPreallocate'パラメータをtrueに設定すると'コントローラ・ファームウェアのストレージ・スペース割り当てロジックにより'将来のセグメント・サイズの変更に備えてボリューム内のスペースが事前に割り当てられます事前に割り当てられたスペースは、許容される最大セグメントサイズです。コントローラデータベースから取得できないボリューム構成を適切にリカバリするには'dssPreAllocateパラメータが必要です事前割り当て機能をオフにするには'dssPreAllocateを'FALSE'に設定します



== セグメントサイズ

コントローラがボリューム内の1つのドライブに書き込めるデータブロックの数は、セグメントのサイズによって決まります。各データブロックには512バイトのデータが格納されます。データブロックはストレージの最小単位です。セグメントのサイズによって、格納されるデータブロックの数が決まります。たとえば、8KBのセグメントには16個のデータブロックが含まれます。64KBのセグメントには128個のデータブロックが含まれます。

セグメントサイズの値を入力すると、その値は、実行時にコントローラで指定される、サポートされている値と照合されます。入力した値が無効な場合、コントローラは有効な値のリストを返します。1つの要求に対して1つのドライブを使用することで、他のドライブでは他の要求に同時に対応できます。

ボリュームが属している環境で、1人のユーザが大量のデータ（マルチメディアなど）を転送している場合は、1つのデータ転送要求を1つのデータストライプで処理すると、パフォーマンスが最大化されます。（データストライプはセグメントサイズであり、これに、データ転送に使用されるボリュームグループ内のドライブ数が掛けられます）。 この場合、同じ要求に対して複数のドライブが使用されますが、各ドライブへのアクセスは1回だけとなります。

マルチユーザデータベースまたはファイルシステムのストレージ環境で最適なパフォーマンスを実現するには、データ転送要求を満たすために必要なドライブ数が最小限になるように、セグメントサイズを設定します。



== キャッシュ読み取りプリフェッチ

キャッシュ読み取りプリフェッチを使用すると、コントローラは、ホストによって要求されたデータブロックをディスクから読み取ってキャッシュにコピーすると同時に、追加のデータブロックをキャッシュにコピーできます。これにより、以降のデータ要求をキャッシュから処理できる可能性が高くなります。キャッシュ読み取りプリフェッチは、シーケンシャルデータ転送を使用するマルチメディアアプリケーションにとって重要です。使用するストレージアレイの設定によって、コントローラがキャッシュに読み込む追加のデータブロックの数が決まります。「cacheReadPrefetch」パラメータの有効な値は「TRUE」または「FALSE」です。



== 最小ファームウェアレベル

5.43

7.10で、RAID 6レベル機能と「newVolumeGroup」パラメータが追加されました。

7.60で'drawerID'ユーザ入力が追加されました

7.75で'dataAssuranceパラメータが追加されました

8.78で'hostUnmapEnabled'パラメータが追加されました

11.70.1に'blocksize'パラメータが追加されました
