---
permalink: commands-a-z/recreate-storagearray-mirrorrepository.html 
sidebar: sidebar 
keywords: recreate, synchronous, mirror, repository, volume 
summary: recreate storageArray mirrorRepositoryコマンドは、以前のミラーリポジトリボリュームに定義されたパラメータを使用して、新しい同期ミラーリングリポジトリボリューム（ミラーリポジトリボリュームとも呼ばれます）を作成します。 
---
= 同期ミラーリングリポジトリボリュームの再作成 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
recreate storageArray mirrorRepositoryコマンドは、以前のミラーリポジトリボリュームに定義されたパラメータを使用して、新しい同期ミラーリングリポジトリボリューム（ミラーリポジトリボリュームとも呼ばれます）を作成します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
ファームウェアバージョン7.80では、recreate storageArray mirrorRepositoryコマンドは廃止されました。GUIまたはCLIでは、このコマンドはサポートされなくなりました。このコマンドを実行しようとすると、この機能がサポートされなくなったこと、および指定したリモートミラーリポジトリに対する変更が行われないことを示すエラーメッセージが返されます。

====
前提として、ミラーリポジトリボリュームが以前に作成済みである必要があります。このコマンドでは、ユーザ定義のドライブ、ユーザ定義のボリュームグループ、またはユーザ定義のミラーリポジトリボリューム用ドライブ数の3つのうちのいずれかを使用してミラーリポジトリボリュームを定義できます。ドライブ数の定義を選択する場合は、コントローラファームウェアによって、ミラーリポジトリボリュームに使用するドライブが選択されます。



== 構文（ユーザ定義のドライブ）

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDrives=pass:quotes[(_trayID1_,pass:quotes[[_drawerID1,_]]pass:quotes[_slotID1
... trayIDN_],pass:quotes[[_drawerIDN,_]]pass:quotes[_slotIDN_])
[trayLossProtect=(TRUE | FALSE)]
[dataAssurance=(none | enabled)]
----


== 構文（ユーザ定義のボリュームグループ）

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryVolumeGroup=pass:quotes[_volumeGroupName_
[freeCapacityArea=pass:quotes[_freeCapacityIndexNumber_]]
----


== 構文（ユーザ定義のドライブ数）

[source, cli, subs="+macros"]
----
recreate storageArray mirrorRepository
repositoryRAIDLevel=(1 | 3 | 5 | 6)
repositoryDriveCount=pass:quotes[_numberOfDrives_]
(
  [driveMediaType=(HDD | SSD | unknown | allMedia)] |
  [driveType=(SAS | NVMe4K)]
)
[repositoryVolumeGroupUserLabel="userLabel"] |
[trayLossProtect=(TRUE | FALSE)] |
[drawerLossProtect=(true|false)] |
[dataAssurance=(none | enabled)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
repositoryRAIDLevel
 a| 
ミラーリポジトリボリュームのRAIDレベル。有効な値は'1''3`'5`'6`です



 a| 
repositoryDrives
 a| 
ミラーリポジトリボリュームに使用するドライブ。ドロワーIDの値は「1」～「5」です。スロットIDの値は'1'～24'ですトレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。以下のルールを使用して、リポジトリボリュームの名前を入力します。

大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

* トレイIDの値、ドロワーIDの値、およびスロットIDの値はすべて角かっこ（[]）で囲みます。
* トレイIDの値、ドロワーIDの値、およびスロットIDの値はカンマで区切ります。
* ドライブの位置はスペースで区切ります。




 a| 
repositoryVolumeGroup'
 a| 
ミラーリポジトリボリュームが配置されているボリュームグループの名前。



 a| 
repositoryVolumeGroupUserLabel
 a| 
ミラーリポジトリボリュームの配置先となる新しいボリュームグループに付ける名前。ボリュームグループ名は二重引用符（""）で囲みます。



 a| 
「freeCapacityArea」
 a| 
ミラーリポジトリボリュームの再作成に使用する、既存のボリュームグループ内の空きスペースのインデックス番号。空き容量は、ボリュームグループ内の既存のボリューム間の空き容量として定義されます。たとえば、ボリュームグループの領域が、ボリューム1、空き容量、ボリューム2、空き容量、ボリューム3、 空き容量：ボリューム2の次の空き容量を使用するには、次のように指定します。

[listing]
----
freeCapacityArea=2
----
show volumegroupコマンドを実行して'空き容量領域が存在するかどうかを確認します



 a| 
repositoryDriveCount
 a| 
ミラーリポジトリボリュームに使用する未割り当てのドライブの数。



 a| 
driveMediaType
 a| 
情報を取得するドライブメディアのタイプ。有効な値は次のとおりです。

* 「hdd」は、ドライブトレイにハードディスクドライブがあることを示します
* 「ssd」は、ドライブトレイにソリッドステート・ディスクがあることを示します
* 「unknown」は、ドライブトレイ内のドライブメディアのタイプを確認できることを示します
* 「allMedia」は、ドライブトレイ内にすべてのタイプのメディアがあることを示します




 a| 
「ドライブタイプ」
 a| 
ミラーリポジトリボリュームに使用するドライブのタイプ。ドライブタイプを混在させることはできません。

ストレージアレイ内に複数のドライブタイプがある場合は、このパラメータを使用する必要があります。

有効なドライブタイプは次のとおりです。

* 「SAS」
* 「NVMe4K」


ドライブタイプを指定しない場合、このコマンドはデフォルトでany typeになります。



 a| 
「trayLossProtect`」
 a| 
ミラーリポジトリボリュームを作成するときにトレイ損失の保護を有効にする設定。トレイ損失の保護を有効にするには'このパラメータをTRUEに設定しますデフォルト値は'FALSE'です



 a| 
「drawerLossProtect`」
 a| 
ミラーリポジトリボリュームを作成するときにドロワー損失の保護を有効にする設定。ドロワー損失の保護を有効にするには、このパラメータを「true」に設定します。デフォルト値は'FALSE'です

|===


== 注：

ミラーリポジトリボリュームのストレージスペースに対して入力した値が小さすぎると、ミラーリポジトリボリュームに必要なスペースの量を示すエラーメッセージがコントローラファームウェアから返されます。コマンドではミラーリポジトリボリュームの変更は試行されません。ミラーリポジトリボリュームのストレージスペースの値に関するエラーメッセージに記載されている値を使用して、コマンドを再入力できます。

repositoryDrivesパラメータでは、大容量ドライブトレイと小容量ドライブトレイの両方がサポートされます。大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。

ドライブを割り当てるときに、trayLossProtectパラメータをTRUEに設定し、いずれか1つのトレイから複数のドライブを選択した場合、ストレージアレイはエラーを返します。trayLossProtect`パラメータをFALSEに設定すると'ストレージ・アレイは操作を実行しますが'作成するミラー・リポジトリ・ボリュームにはトレイ損失の保護がない可能性があります

コントローラファームウェアがドライブを割り当てるときに、trayLossProtectパラメータをTRUEに設定した場合、トレイ損失の保護を持つ新しいミラーリポジトリボリュームを構成するドライブをコントローラファームウェアが提供できない場合、ストレージアレイはエラーを返します。trayLossProtectパラメータをFALSEに設定すると'ミラーリポジトリボリュームにトレイ損失の保護がない可能性がある場合でも'ストレージアレイは処理を実行します



== Data Assurance管理

Data Assurance（DA）機能を使用すると、ストレージシステム全体のデータの整合性が向上します。ホストとドライブの間でデータが移動されたときにストレージアレイがエラーの有無をチェックします。この機能を有効にすると、ボリューム内の各データブロックに巡回冗長検査（CRC）と呼ばれるエラーチェック用のコードが付加されます。データブロックが移動されると、ストレージアレイはこれらのCRCコードを使用して、転送中にエラーが発生したかどうかを判断します。破損している可能性があるデータはディスクに書き込まれず、ホストにも返されません。

DA機能を使用する場合は、まず最初にDAがサポートされているドライブのみを含むプールまたはボリュームグループを作成します。次に、DA対応ボリュームを作成します。最後に、DAに対応したI/Oインターフェイスを使用してDA対応ボリュームをホストにマッピングします。DAに対応したI/Oインターフェイスには、Fibre Channel、SAS、iSER over InfiniBand（iSCSI Extensions for RDMA/IB）があります。iSCSI over EthernetやSRP over InfiniBandではDAはサポートされていません。

[NOTE]
====
すべてのドライブがDA対応の場合は'dataAssuranceパラメータをEnabledに設定し'特定の操作でDAを使用できますたとえば、DA対応ドライブが含まれるボリュームグループを作成し、そのボリュームグループにDA対応のボリュームを作成できます。DA対応ボリュームを使用する他の処理には、DA機能をサポートするオプションがあります。

====
「dataAssurance」パラメータが「enabled」に設定されている場合、Data Assurance対応のドライブのみがボリューム候補とみなされます。それ以外の場合は、Data Assurance対応ドライブとData Assurance対応でないドライブの両方が考慮されます。DA対応ドライブのみが使用可能な場合、新しいボリュームグループは、有効なDA対応ドライブを使用して作成されます。



== 最小ファームウェアレベル

6.10

7.10で、RAIDレベル6機能が追加されました

7.75で'dataAssuranceパラメータが追加されました

8.60で、「driveMediaType」、「repositoryVolumeGroupUserLabel」、「drawerLossProtect」パラメータが追加されました。
