---
permalink: commands-a-z/recreate-storagearray-securitykey.html 
sidebar: sidebar 
keywords: recreate, external, security key 
summary: recreate storageArray securityKeyコマンドは、外部セキュリティキー管理機能で使用するストレージアレイのセキュリティキーを再生成します。 
---
= 外部セキュリティキーの再作成 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
recreate storageArray securityKey'コマンドは'外部セキュリティキー管理機能で使用するストレージアレイのセキュリティキーを再生成します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Security Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
このコマンドは、外部キー管理にのみ適用されます。

====


== 構文

[source, cli, subs="+macros"]
----
recreate storageArray securityKey
passPhrase=pass:quotes[_"passPhraseString"_
file="_fileName"_]
[deleteOldKey=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
パスフレーズ
 a| 
セキュリティキーを外部ファイルに格納できるように、セキュリティキーを暗号化する文字列。パスフレーズは二重引用符（""）で囲みます。



 a| 
'file'
 a| 
セキュリティキーを含むファイルパスとファイル名。例：

[listing]
----
file="C:\Program Files\CLI\sup\drivesecurity.slk"
----
[NOTE]
====
ファイル名の拡張子は「.slk」でなければなりません。

====


 a| 
「deleteOldKey」と入力します
 a| 
新しいセキュリティキーの作成後に外部キー管理サーバから古いセキュリティキーを削除するには、このパラメータを「true」に設定します。デフォルトは「FALSE」です。

|===


== 注：

パスフレーズは次の条件を満たしている必要があります。

* パスフレーズは8~32文字で指定する必要があります。
* 大文字を1つ以上含む。
* 小文字を1つ以上含む。
* 数字を1つ以上含む。
* パスフレーズには、英数字以外の文字（<>@+など）が少なくとも1文字含まれている必要があります。


[NOTE]
====
パスフレーズがこれらの条件を満たしていない場合は、エラーメッセージが表示されます。

====


== 最小ファームウェアレベル

7.70

11.73では'deleteOldKey'パラメータが追加されました
