---
permalink: commands-a-z/reduce-disk-pool-capacity.html 
sidebar: sidebar 
keywords: reduce, disk pool, capacity 
summary: set diskPoolコマンドは、ドライブをプールから論理的に削除することでディスクプールの容量を削減します。 
---
= ディスクプールの容量を減らしてください
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set diskPool'コマンドは'プールからドライブを論理的に削除することにより'ディスク・プールの容量を削減します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドでは、Dynamic Capacity Reduction（DCR）機能を使用します。この機能により、選択したドライブをディスクプールから削除し、必要に応じてそのドライブを再利用できます。

1回のDCR処理でディスクプールから削除できる最大ドライブ数は60本です。ディスクプールの最小サイズを下回るサイズを指定することはできません。



== 構文

[listing, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
removeDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1
... trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_])
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「diskPool」
 a| 
容量を削減するディスクプールの名前。ディスクプール名は角かっこ（[]）で囲みます。



 a| 
「removeDrives」を参照してください
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

|===


== 注：

ディスクプール名は一意である必要があります。ユーザラベルには、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。ユーザラベルの最大文字数は30文字です。

グループを別途作成したり、不要な容量をストレージアレイから削除したりする必要がある場合は、選択したドライブをディスクプールから削除できます。削除したドライブは未割り当てのドライブになり、ドライブ上のデータはディスクプール内の残りのドライブに再配置されます。ディスクプールの容量は、削除するドライブの容量分だけ縮小されます。ディスクプールからのドライブの削除は必ずバックグラウンドタスクとして実行され、処理中もボリュームは完全にアクセス可能な状態です。削除処理の進捗状況は、長時間の処理のステータスの一部として報告されます。

ディスクプールから削除するドライブ上のすべてのデータを格納するための空き容量がディスクプールに残っているドライブで十分に確保されていない場合、このコマンドは失敗します。ディスクプール内のリザーブ容量は、ディスクプールから削除するドライブ上のデータの格納に使用されることがあります。ただし、リザーブ容量が重大しきい値を下回ると、メジャーイベントログに重大イベントが書き込まれます。

ディスクプールのサイズを縮小すると、必要なリザーブ容量が少なくなる可能性があります。場合によっては、このコマンドが失敗する可能性を抑えるために、このコマンドを実行する前にリザーブ容量を削減し、ディスクプールのデータに使用できるスペースの量を増やしてください。

削除できるドライブ数はコントローラファームウェアで指定されます。削除するドライブはユーザが選択できます。コントローラファームウェアでは、再構築用にリザーブされた容量を消費せずに残りのドライブにデータを再分散するために必要な空きスペースの量に基づいてこのドライブ数を指定します。ディスクプールの空き容量がすでに再構築ドライブのリザーブ容量よりも少ない場合、コントローラはDCR処理の開始を許可しません。

DCR処理によって、設定された容量がプール利用率のしきい値の一方または両方を超える可能性があります。その場合は、通常のしきい値アラートが発行されます。



== 最小ファームウェアレベル

8.10で
