---
permalink: commands-a-z/remove-syncmirror.html 
sidebar: sidebar 
keywords: remove, synchronous, mirror 
summary: remove SyncMirror コマンドは、リモートミラーペアのプライマリボリュームとセカンダリボリュームの間のミラー関係を削除します。 
---
= 同期ミラーリングを削除します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
remove SyncMirror コマンドは'リモート・ミラー・ペアのプライマリ・ボリュームとセカンダリ・ボリュームの間のミラー関係を削除します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700のアレイを含む個々のストレージアレイを環境 で処理します。 すべてのSMcliパッケージがインストールされていること。



== ロール

このコマンドをE2800またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
このコマンドの以前のバージョンでは、機能識別子は「remoteMirror」でした。この機能識別子は有効ではなくなり' SyncMirror に置き換えられます

====


== 構文

[listing, subs="+macros"]
----
remove syncMirror (localVolume pass:quotes[[_volumeName_]] |
localVolumes pass:quotes[[_volumeName1 ... volumeNameN_]])
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「localVolume」です
 a| 
削除するプライマリボリューム（ローカルストレージアレイ上のボリューム）の名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名が特殊文字を含んでいる場合または数字のみで構成される場合は、ボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「localVolumes」を参照してください
 a| 
削除する複数のプライマリボリューム（ローカルストレージアレイ上のボリューム）の名前。以下のルールを使用して、プライマリボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


プライマリボリューム名が特殊文字を含んでいる場合または数字のみで構成されている場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。


|===


== 最小ファームウェアレベル

6.10
