---
permalink: commands-a-z/remove-lunmapping.html 
sidebar: sidebar 
keywords: remove, volume, lun map 
summary: remove lunMappingコマンドを実行すると、論理ユニット番号（LUN）またはネームスペースID（NSID）マッピングが1個以上のボリュームから削除されます。 
---
= ボリュームLUNマッピングの削除 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
remove lunMappingコマンドは'1つ以上のボリュームから論理ユニット番号（LUN）またはネームスペースID（NSID）マッピングを削除します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
remove (volume pass:quotes[[_"volumeName"_]] | accessVolume) lunMapping
(host=pass:quotes[_"hostName_" | hostGroup=(_"hostGroupName"_] | defaultGroup)
----


== 複数ボリュームのLUN / NSIDマッピングからLUN / NSIDマッピングを削除するための構文

[source, cli, subs="+macros"]
----
remove (allVolumes | volumes pass:quotes[[_volumeName1 ... volumeNameN_]])
lunMapping
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
LUN / NSIDマッピングを削除するボリュームの名前。ボリューム名は、二重引用符（""）で囲んだ上で角かっこ（[]）で囲みます。



 a| 
「accessVolume」のようになります
 a| 
このパラメータではアクセスボリュームが削除されます。



 a| 
「allVolumes」
 a| 
このパラメータでは、すべてのボリュームからLUNマッピングが削除されます。



 a| 
「ボリューム」
 a| 
LUN / NSIDマッピングを削除する複数のボリュームの名前。以下のルールを使用して、ボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


ボリューム名が特殊文字を含んでいる場合または数字のみで構成されている場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
ホスト
 a| 
ボリュームのマッピング先であるホストの名前。ホスト名は二重引用符（""）で囲みます。

このパラメータは、1個のボリュームからLUN / NSIDマッピングを削除する場合にのみ機能します。



 a| 
「hostGroup」と入力します
 a| 
ボリュームのマッピング先であるホストを含むホストグループの名前。ホストグループ名は二重引用符（""）で囲みます。defaultGroupの値は'ボリュームがマップされているホストを含むホスト・グループです

このパラメータは、1個のボリュームからLUN / NSIDマッピングを削除する場合にのみ機能します。

|===


== 注：

アクセスボリュームは、ストレージ管理ソフトウェアとストレージアレイコントローラ間の通信に使用されるSAN環境内のボリュームです。アクセスボリュームがLUNアドレスまたはNSIDアドレスを使用し、アプリケーションデータストレージには使用できない20MBのストレージスペースを使用します。アクセスボリュームは、インバンド管理されるストレージアレイでのみ必要です。

[NOTE]
====
*アクセスボリュームを削除すると、構成が損傷する可能性があります*。エージェントはアクセスボリュームを使用してストレージアレイと通信します。エージェントを実行しているホストからストレージアレイのアクセスボリュームのマッピングを削除すると、ストレージ管理ソフトウェアでエージェントを介してストレージアレイを管理できなくなります。

====
非アクセス・ボリュームまたはアクセス・ボリュームを指定する場合は'host'パラメータとhostGroupパラメータを使用する必要があります「allVolumes」パラメータまたは「volumes」パラメータを使用する場合、スクリプトエンジンは「host」パラメータまたは「hostGroup」パラメータを無視します。



== 最小ファームウェアレベル

6.10
