---
permalink: commands-a-z/remove-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: remove, incomplete, asynchronous, mirror, pair, group 
summary: asyncMirrorGroupコマンドを実行すると、ストレージアレイ上の孤立したミラーペアボリュームが削除されます。 
---
= 非同期ミラーグループから不完全な非同期ミラーペアを削除する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
remove asyncMirrorGroupコマンドは'ストレージ・アレイ上の孤立したミラー・ペア・ボリュームを削除します



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E2700、E5600、E2800、E5700、EF600、EF300を含むあらゆるストレージ アレイに適用されます。



[[roles]]
== ロール

このコマンドをE2800、E5700、EF600、またはEF300のストレージ アレイに対して実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

孤立したミラーペアボリュームは、非同期ミラーグループの一方（プライマリまたはセカンダリ）で非同期ミラーグループのメンバーボリュームが削除され、もう一方では削除されていない場合に発生します。

孤立したミラーペアボリュームは、コントローラ間の通信がリストアされ、ミラー構成の両サイドでミラーパラメータが調整されたときに検出されます。

このコマンドは、ミラー関係がローカルストレージアレイまたはリモートストレージアレイで正常に削除されたにもかかわらず、通信の問題が原因で対応するストレージアレイでは削除できない場合に使用します。



[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
remove asyncMirrorGroup pass:quotes[[_"asyncMirrorGroupName"_]]
incompleteMirror volume=pass:quotes[_"volumeName"_]
----


[[parameters]]
== パラメータ

|===
| パラメータ | 説明 


 a| 
「asyncMirrorGroup」
 a| 
孤立したボリュームを削除する非同期ミラーグループの名前。非同期ミラーグループ名は、二重引用符（""）で囲んだ上で角かっこ（[]）で囲みます。



 a| 
「 volume 」
 a| 
非同期ミラーグループから削除する孤立したボリュームの名前。ボリューム名は二重引用符（""）で囲みます。

|===


[[minimum-firmware-level]]
== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
