---
permalink: commands-a-z/remove-drives-from-ssd-cache.html 
sidebar: sidebar 
keywords: remove, drives, ssd, cache 
summary: set ssdCacheコマンドは、ソリッドステートディスク（SSD）を削除することでSSDキャッシュの容量を縮小します。 
---
= SSDキャッシュからドライブを削除します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set ssdCacheコマンドは、ソリッドステートディスク（SSD）を削除することにより、SSDキャッシュの容量を縮小します。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700などの個 々 のストレージアレイを環境に設定します。 EF600およびEF300アレイ（すべてのSMcliパッケージがインストールされている必要があります。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Support Adminロールが必要です。



== 構文

[listing, subs="+macros"]
----
set ssdCache pass:quotes[[_ssdCacheName_]]
removeDrives=pass:quotes[(_trayID1_,]pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1 ... trayIDn_],pass:quotes[[_drawerIDn,_]]pass:quotes[_slotIDn_])
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「ssdCache」
 a| 
SSDを削除するSSDキャッシュの名前。SSDキャッシュ名は角かっこ（[]）で囲みます。SSDキャッシュ名が特殊文字を含んでいる場合または数字のみで構成される場合は、SSDキャッシュ名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「removeDrives」を参照してください
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

|===


== 注：

このコマンドを使用して、SSDキャッシュからすべてのSSDを削除することはできません。少なくとも1本のSSDをSSDキャッシュに残しておく必要があります。SSDキャッシュを完全に削除する場合は、代わりに「delete ssdCache」コマンドを使用します。



== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
