---
permalink: commands-a-z/repair-volume-parity.html 
sidebar: sidebar 
keywords: repair, volume, parity 
summary: repair volume parityコマンドは、ボリューム上のパリティエラーを修復します。 
---
= ボリュームパリティの修復 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「ボリュームパリティの修復」コマンドは、ボリューム上のパリティエラーを修復します。



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

[CAUTION]
====
ボリュームのパリティとボリュームのデータが一致しない場合は、ボリュームのパリティではなくボリュームのデータが破損している可能性があります。ボリュームのパリティを修復すると、必要に応じて、破損したボリュームのデータを修復する機能が削除されます。

====


[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
repair volume pass:quotes[[_volumeName_]] parity
parityErrorFile=pass:quotes[_"filename"_]
[verbose=(TRUE | FALSE)]
----


[[parameters]]
== パラメータ

|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
パリティを修復するボリュームの名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名に特殊文字または数字が含まれている場合は、ボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
'parityErrorFile'
 a| 
エラーの修復に使用するパリティエラー情報を含むファイルのパスと名前。ファイル名は二重引用符（""）で囲みます。例：

'file="C:\Program Files\CLI\sup\parfile.txt

[NOTE]
====
「parityErrorFile」は、以前の「ボリュームのパリティをチェック」操作の結果です。

====


 a| 
「冗長」
 a| 
完了した割合などの進捗状況の詳細をキャプチャするための設定。ボリュームのパリティを修復する際の情報を表示するために使用します。進行状況の詳細をキャプチャするには、このパラメータを「true」に設定します。進行状況の詳細をキャプチャしないようにするには'このパラメータをFALSEに設定します

|===


[[minimum-firmware-level]]
== 最小ファームウェアレベル

6.10
