---
permalink: commands-a-z/replace-drive-replacementdrive.html 
sidebar: sidebar 
keywords: replace, drive 
summary: ドライブの交換ドライブコマンドは、ボリュームグループ内のドライブを交換します。 
---
= ドライブの交換 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Replace drive replacementDriveコマンドを実行すると'ボリューム・グループ内のドライブが置き換えられます



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

ボリュームグループのドライブを交換すると、ボリュームグループの構成が再定義されます。このコマンドを使用して、ドライブを未割り当てのドライブまたは完全に統合されたホットスペアと交換できます。



== 構文

[source, cli]
----
replace (drive \[trayID,[drawerID,]slotID\] \| drives\[trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn\]
 | <"wwID">)
replacementDrive=trayID,drawerID,slotID
[copyDrive][failDrive]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
「ドライブ」
 a| 
交換するドライブのWorld Wide Identifier（WWID）。WWIDは二重引用符（""）で囲んだ上で山かっこ（<>）で囲みます。



 a| 
「replacementDrive」を参照してください
 a| 
交換用として使用するドライブの場所。大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。スロットIDの値は'1'～24'です

|===


== 注：

'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。



== 最小ファームウェアレベル

7.10

7.60で'_drawerID_'ユーザー入力が追加されました
