---
permalink: commands-a-z/reset-iscsiipaddress.html 
sidebar: sidebar 
keywords: reset, iscsi, ip address 
summary: reset iscsiIpAddressコマンドは、リモートストレージアレイのIPアドレスをリセットして、ローカルストレージアレイとの接続を再確立します。 
---
= iSCSI IPアドレスをリセットします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
reset iscsiIpAddressコマンドは、リモートストレージアレイのIPアドレスをリセットして、ローカルストレージアレイとの接続を再確立します。



== サポートされているアレイ

このコマンドは、一部制限付きで個々のストレージアレイを環境 接続します。E2700またはE5600のアレイに対して実行する場合は、制限はありません。

[NOTE]
====
このコマンドは、E4000、E2800、E5700、EF600、およびEF300のプラットフォームではサポートされていません。

====


== ロール

該当なし



== コンテキスト（Context）

このコマンドを使用して、リモートストレージアレイのiSCSI IPアドレスが変更されたこと、および更新が必要であることをローカルストレージアレイに通知できます。

iSCSI接続と非同期ミラーリング関係を確立する際、ローカルおよびリモート両方のストレージアレイは、リモートストレージアレイのIPアドレスを非同期ミラーリング構成に保存します。iSCSIポートのIPアドレスが変わると、そのポートを使用しようとしているリモートストレージアレイで通信エラーが発生します。

IPアドレスが変更されたストレージアレイは、iSCSI接続を介してミラーリングするように設定された非同期ミラーグループに関連付けられている各リモートストレージアレイにメッセージを送信します。このメッセージを受け取ったストレージアレイは、リモートターゲットのIPアドレスを自動的に更新します。

IPアドレスが変更されたストレージアレイがコントローラ間のメッセージをリモートストレージアレイに送信できない場合は、接続問題 のアラートが送信されます。ローカル・ストレージ・アレイとの接続を再確立するには'reset'コマンドを使用します



== 構文

[source, cli]
----
reset (remoteStorageArrayName="storageArrayName" | remoteStorageArrayWwid=<wwID>)
iscsiIpAddress
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
remoteStorageArrayName
 a| 
iSCSI IPアドレスをリセットするリモートストレージアレイの名前。ストレージアレイ名は二重引用符（""）で囲みます。



 a| 
remoteStorageArrayWwid
 a| 
iSCSI IPアドレスをリセットするストレージアレイのWorld Wide Identifier（WWID）。ストレージアレイ名の代わりにWWIDを使用してストレージアレイを識別できます。WWIDは山かっこ（<>）で囲みます。

|===


== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
