---
permalink: commands-a-z/reset-drive.html 
sidebar: sidebar 
keywords: reset, drive 
summary: reset driveコマンドは、ボリュームグループまたはディスクプール内のドライブの電源を再投入して、動作に一貫性がないドライブまたは動作が最適でないドライブのリカバリを支援します。 
---
= ドライブをリセットします
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
reset driveコマンドは'ボリューム・グループまたはディスク・プール内のドライブの電源を再投入して'動作に一貫性がないドライブまたは最適でないドライブのリカバリを支援します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

ドライブの電源を再投入することで、原因 の一貫性がない動作または最適でない動作に関する一部のエラーを解消できます。これにより、重大でない一時的なエラーがドライブで発生し、ドライブが引き続き動作している場合に、ドライブの交換を回避できます。この方法でドライブをリセットすると、システムの停止が軽減され、ドライブの交換を回避できます。

ドライブの電源を再投入することで問題を解決できない場合は、ドライブのデータがコピーされ、ドライブの交換のために電源がオフになります。

[NOTE]
====
Pliant製のSSDドライブにこのコマンドを使用することはできません。ドライブの製造元を表示するには、「show storageArray profile」コマンドまたは「show drive」コマンドを使用します。

====


== 構文

[source, cli]
----
reset drive([trayID,[drawerID,]slotID] | <"wwID">)
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
「ドライブ」
 a| 
交換するドライブのWorld Wide Identifier（WWID）。WWIDは二重引用符（""）で囲んだ上で山かっこ（<>）で囲みます。

|===


== 注：

'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。

ドライブの電源を再投入したら、そのドライブを使用可能な状態に戻す前に、ドライブが動作していることをコントローラで確認する必要があります。検証できないドライブは、障害が発生したドライブとしてマークされます。障害が発生したドライブの電源を再投入するには、グローバルホットスペアドライブが必要です。また、ドライブが使用可能な状態になったら、交換用ドライブへのフルコピーが必要です。

24時間以内に2回以上電源を再投入して、障害が発生したドライブをリセットすることはできません。状況によっては、障害が発生したドライブを2回以上リセットできない場合もあります。ドライブの電源の再投入のしきい値とカウンタは永続的ストレージに保持され、状態キャプチャデータに含まれます。ドライブの電源を再投入すると、情報イベントがログに記録されます。



== 最小ファームウェアレベル

8.20で
