---
permalink: commands-a-z/reset-storagearray-hostportstatisticsbaseline.html 
sidebar: sidebar 
keywords: reset, storage array, host, port, statistics, baseline 
summary: reset storageArray hostPortStatisticsBaselineコマンドは、ストレージアレイのホストポートの統計ベースラインをリセットします。 
---
= ストレージアレイのホストポート統計のベースラインをリセットする - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
reset storageArray hostPortStatisticsBaselineコマンドは、ストレージアレイのホストポートの統計ベースラインをリセットします。



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、個々のE4000、E2800、E5700、EF600、EF300、EF50、およびEF80ストレージアレイに適用されます。E2700またはE5600ストレージアレイでは動作しません。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage AdminまたはStorage Monitorロールが必要です。



[[context]]
== コンテキスト（Context）

[NOTE]
====
このコマンドは、廃止されたを置き換えます xref:reset-storagearray-ibstatsbaseline.adoc[ストレージアレイのInfiniBandの統計ベースラインをリセットします]、 xref:reset-storagearray-iscsistatsbaseline.adoc[ストレージアレイのiSCSIベースラインをリセットします]および xref:reset-storagearray-iserstatsbaseline.adoc[ストレージアレイのiSERベースラインをリセットします] コマンド

====


[[syntax]]
== 構文

[source, cli]
----

reset storageArray hostPortStatisticsBaseline type=(ISCSI| ISER | SRP | NVMEOF)
----


[[parameters]]
== パラメータ

|===
| パラメータ | 説明 


 a| 
「type」と入力します
 a| 
収集する統計のタイプを指定できます。有効な選択肢は、「iscsi」、「isER」、「srp」、「NVMEOF」です。

|===


[[minimum-firmware-level]]
== 最小ファームウェアレベル

8.41
