---
permalink: commands-a-z/reset-controller.html 
sidebar: sidebar 
keywords: reset, controller 
summary: reset controllerコマンドはコントローラをリセットします。このコマンドによってI/O処理が停止します。 
---
= コントローラをリセットします
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
reset controllerコマンドは、コントローラをリセットし、I/O処理を中断します。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
リセットしたコントローラはデータパスから削除され、リセット処理が完了するまでI/O処理に使用できません。リセット対象のコントローラが所有するボリュームをホストが使用している場合は、そのコントローラに対するI/Oが拒否されます。コントローラをリセットする前に、コントローラが所有するボリュームが使用中でないこと、またはそれらのボリュームを使用するすべてのホストにマルチパスドライバがインストールされていることを確認してください。

====
[CAUTION]
====
インバンド管理を使用する場合は、どのコントローラにコマンドを送信するかを制御できず、このコマンドから予期しない結果が返されることがあります。

====


== 構文

[listing]
----
reset controller [(a|b)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「controller」と入力します
 a| 
リセットするコントローラ。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラですコントローラの識別子は角かっこ（[]）で囲みます。コントローラを指定しないと、ストレージ管理ソフトウェアから構文エラーが返されます。

|===


== 注：

reset controllerコマンドを受信するコントローラによって、指定されたコントローラがリセットされます。たとえば、コントローラAのリセットを要求するreset controllerコマンドがコントローラAに送信される場合は、ソフトリブートを実行してコントローラAがリブートされます。コントローラBのリセットを要求するreset controllerコマンドがコントローラAに送信される場合は、コントローラAがコントローラBをリセットに保持し、その後リセットからコントローラBを解放します。これはハードリブートです。一部の製品のソフトリブートでは、IOCチップだけがリセットされます。ハードリブートでは、コントローラのIOCチップとエキスパンダチップの両方がリセットされます。



== 最小ファームウェアレベル

5.20
