---
permalink: commands-a-z/resume-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: resume, asynchronous, mirror, group 
summary: resume asyncMirrorGroupコマンドは、非同期ミラーグループに含まれるすべてのミラーペア間のデータ転送を再開します。 
---
= 非同期ミラーグループの再開 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
resume asyncMirrorGroupコマンドは'非同期ミラーグループ内のすべてのミラーペア間のデータ転送を再開します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

非同期ミラーグループを中断している間にプライマリボリュームに書き込まれたデータが、セカンダリボリュームにただちに書き込まれます。自動同期間隔が設定されている場合は、定期的な同期が再開されます。



== 構文

[source, cli, subs="+macros"]
----
resume asyncMirrorGroup pass:quotes[[_"asyncMirrorGroupName"_]]
[deleteRecoveryPointIfNecessary]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「asyncMirrorGroup」
 a| 
同期を開始する非同期ミラーグループの名前。非同期ミラーグループ名は、二重引用符（""）で囲んだ上で角かっこ（[]）で囲みます。



 a| 
「deleteRecoveryPointIfNecessary」です
 a| 
リカバリ可能な同期データがリカバリの時間のしきい値を超えた場合にリカバリポイントを削除するためのパラメータ。リカバリポイントの経過時間は、プライマリストレージアレイでデータが取得された時間から計測されます。

|===


== 最小ファームウェアレベル

7.84

8.10で、 `deleteRecoveryPointIfNecessary` パラメータ

11.80で、EF600およびEF300アレイのサポートが追加されました。
