---
permalink: commands-a-z/resume-syncmirror.html 
sidebar: sidebar 
keywords: resume, synchronous, mirroring 
summary: resume SyncMirror コマンドは、中断した同期ミラーリング処理を再開します。 
---
= 同期ミラーリングの再開 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
RESUME SyncMirror コマンドは'中断された同期ミラーリング操作を再開します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
このコマンドの以前のバージョンでは、機能識別子は「remoteMirror」でした。この機能識別子は有効ではなくなり' SyncMirror に置き換えられます

====


== 構文

[source, cli, subs="+macros"]
----
resume syncMirror (primary pass:quotes[[_volumeName_]] |
primaries pass:quotes[[_volumeName1 ... volumeNameN_]])
[writeConsistency=(TRUE | FALSE)]
----


== パラメータ

|===
| パラメータ | 説明 


 a| 
「プライマリ」
 a| 
同期ミラーリング処理を再開するプライマリボリュームの名前。プライマリボリューム名は角かっこ（[]）で囲みます。プライマリボリューム名に特殊文字または数字が含まれている場合は、プライマリボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「原色」
 a| 
同期ミラーリング処理を再開する複数のプライマリボリュームの名前。以下のルールを使用して、プライマリボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


プライマリボリューム名が特殊文字を含んでいる場合または数字のみで構成されている場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
「ライトコンシステンシ」
 a| 
書き込み整合性グループ内のボリュームまたは分離されているボリュームをこのコマンドで特定するための設定。同一の書き込み整合性グループに属するボリュームの場合は、このパラメータを「true」に設定します。別のボリュームの場合は、このパラメータを「FALSE」に設定します。

|===


== 注：

「writeConsistency」パラメータを「true」に設定すると、ボリュームは書き込み整合性グループ（またはグループ）に属している必要があります。このコマンドは、ボリュームを含むすべての書き込み整合性グループの同期ミラーリングを再開します。たとえば、ボリュームA、B、Cが書き込み整合性グループに属しており、リモートに対応するA`', B`',およびC`'がある場合、SyncMirror ボリュームの再開["A"] writeConsistency=trueコマンドはA-A`', B-B`', C-C`'を再開します。



== 最小ファームウェアレベル

6.10
