---
permalink: commands-a-z/save-storagearray-soccounts.html 
sidebar: sidebar 
keywords: save, storage, array, soc, counts 
summary: save storageArray SOCCountsコマンドは、SOCエラー統計をファイルに保存します。 
---
= ストレージアレイの SOC カウントを保存する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
save storageArray SOCCountsコマンドは'SOCエラー統計をファイルに保存します



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

このコマンドは、アービトレーテッドループトポロジ内のFibre Channelデバイスに対してのみ有効です。



[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
save storageArray SOCCounts file=pass:quotes["_filename_"]
----


[[parameter]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
'file'
 a| 
SOCエラー統計の保存先となるファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。例：

`file="C:\Program Files\CLI\logs\sockstat.csv "`

SOCエラー統計を格納するファイルのデフォルト名は、「SoC-statistics.csv」です。任意のファイル名を使用できますが'.csv拡張子を使用する必要があります

|===


[[notes]]
== 注：

SOCエラー統計を効率的にファイルに保存するには、次の手順を実行します。

. すべてのSOCカウンタを0に設定するには、「reset storageArray SOCBaseline.」コマンドを実行します。
. ストレージアレイをあらかじめ決めた時間だけ実行します（2時間など）。
. save storageArray SOCCountsファイル`="[.code]`_filename_`コマンドを実行します。




[[minimum-firmware-level]]
== 最小ファームウェアレベル

6.16
