---
permalink: commands-a-z/save-ioclog.html 
sidebar: sidebar 
keywords: save, input, output, controller, ioc, dump 
summary: save IOCLogコマンドは、ストレージアレイ内のコントローラからホスト上のファイルにIOCダンプを保存します。 
---
= 入出力コントローラ（IOC）ダンプを保存する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
save IOCLogコマンドは、ストレージアレイ内のコントローラからホスト上のファイルにIOCダンプを保存します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
save IOCLog [file=pass:quotes["_filename_"]]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
'file'
 a| 
IOCダンプの保存先となるファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。例：

[listing]
----
file="C:\Array Backups\IOCcoredump1.7z"
----
このコマンドは、データを圧縮ファイルに保存し、ファイル拡張子「.7z」を保存されたファイルに追加します。ストレージアレイ内のコントローラのIOC関連データを格納するファイルのデフォルト名には、ストレージアレイのWWNが使用されます。

|===


== 注：

このコマンドは、両方のコントローラからIOCダンプログデータとIOCダンプメタデータを取得します。7zipファイル形式を使用して、取得したデータが指定した名前の単一のファイルに圧縮されてアーカイブされます。この7zipアーカイブファイルの内容は次のとおりです。

* ファイル名+「IOCLog」+[A|B].gz -コントローラAまたはコントローラBから取得されたIOCログ（利用可能な場合）
* ファイル名+「IOCLogInfo」+[A|B].txt -コントローラAまたはコントローラBから取得されたIOCログのメタデータ情報。コントローラからIOCログデータを取得できない場合は、メタデータ.txtファイルにエラーの状態と理由が記録されます。


エラー状態は次のとおりです。

* コントローラプラットフォームとHICがIOCダンプをサポートしていない。
* コントローラでIOCダンプデータが収集されていない。


圧縮されたログは人間が判読できる形式ではありません。テクニカルサポートに渡して評価してもらう必要があります。



== 最小ファームウェアレベル

8.20で
