---
permalink: commands-a-z/save-storagearray-supportdata.html 
sidebar: sidebar 
keywords: save, storage, array, support, data 
summary: save storageArray supportDataコマンドは、ストレージアレイのサポート関連情報をファイルに保存します。 
---
= ストレージアレイのサポートデータを保存する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
save storageArray supportDataコマンドは、ストレージアレイのサポート関連情報をファイルに保存します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== コンテキスト（Context）

次の表に、収集可能なサポートデータの種類を示します。

[cols="2*"]
|===
| データのタイプ | ファイル名と概要 


 a| 
自動ロードバランシングの統計情報
 a| 
「alb - statistics -a. txt」

「ALB -統計- B.txt」

このファイルはコントローラごとに1つずつ生成され、自動ロードバランシング機能に関連するさまざまな統計情報を指定します。この機能を使用すると、オフライン分析ツールでさらに詳細な分析を行うことができます。



 a| 
コアダンプメタデータ
 a| 
「all-cumpcoredump.xml」です

このファイルには、アレイのコアダンプメタデータが格納されます。

[NOTE]
====
リリース8.25で、core-dump-info.xmlからall-coredump.xmlに名前が変更されました。

====


 a| 
AutoSupport のステータス
 a| 
「autosupport.xml」を指定します

このファイルには、特定のアレイについてのASUPの現在のステータスが格納されます。



 a| 
AutoSupport 履歴ファイル
 a| 
「autosupport.history.xml」を指定します

このファイルには、特定のアレイに関するすべてのASUPメッセージ（標準とAutoSupport OnDemandの両方のメッセージ）が指定されます。テーブル内の各エントリは、特定のアレイのいずれかのリポジトリに現在あるASUPメッセージに対応します。



 a| 
AutoSupport ログ
 a| 
asup-transmission-logs.txt

このファイルには、送信されたすべてのAutoSupport メッセージが格納されます。



 a| 
Webサーバークライアント情報
 a| 
client-info.txt

このファイルには、Web Servicesの各種クライアント情報が格納されます。

[NOTE]
====
このパラメータは、E2700アレイとE5600アレイには適用されません。

====


 a| 
ドライブケーブルトポロジ
 a| 
「connection.txt」このファイルには、ドライブトレイ環境サービスモジュール（ESM）とコントローラペアの間の接続に関する情報が含まれます。



 a| 
累積統計のバンドル
 a| 
「cumuls-ddrive -vol-stats.xml」を指定します

このファイルには、コントローラの累積統計が格納されます。



 a| 
動作不良ドライブのログ
 a| 
「controller-droe-error-event-log-txt」というエラーが表示されます

このファイルには、ストレージアレイコントローラのドライブに関するエラーとイベントログメッセージが格納されます。



 a| 
コントローラヘルスイメージのメタデータ
 a| 
「all-cumpcoredump.xml」です

このファイルには、DPLコントローラのヘルスイメージの情報が格納されます。

[NOTE]
====
リリース8.25で、core-dump-info.xmlからall-coredump.xmlに名前が変更されました。

====


 a| 
コントローラAのDOM 0ジャーナルファイル（E2800またはE5700のみ）
 a| 
「dom0-complete-journal-a. 7z」と入力します

このファイルには、各コントローラに1つずつ、詳細なLinuxシステムログが格納されています。これには、Linuxパッケージと標準のLinuxユーティリティおよびサービスのログが含まれます。



 a| 
コントローラBのDOM 0ジャーナルファイル（E2800またはE5700のみ）
 a| 
「dom0-complete-journal-bz7z`.」と入力します

このファイルには、各コントローラに1つずつ、詳細なLinuxシステムログが格納されています。これには、Linuxパッケージと標準のLinuxユーティリティおよびサービスのログが含まれます。



 a| 
コントローラAのその他のDOM 0ログファイル（E2800またはE5700のみ）
 a| 
「dom0-misc-logs-A.7z」を参照してください

このファイルには、各コントローラに1つずつ、ジャーナルに格納できないシステムログが含まれています。RAIDアプリケーションのシリアルログやハイパーバイザーのデバッグログが含まれます。



 a| 
コントローラBのその他のDOM 0ログファイル（E2800またはE5700のみ）
 a| 
「dom0-misc-logs -b.7z」を参照してください

このファイルには、各コントローラに1つずつ、ジャーナルに格納できないシステムログが含まれています。RAIDアプリケーションのシリアルログやハイパーバイザーのデバッグログが含まれます。



 a| 
ドライブのコマンドエージングタイムアウト値
 a| 
'drive-command-aging-timeout.txt'このファイルには'すべてのドライブのコマンドエージングタイムアウトフィールドのデフォルト値と現在の値が含まれています



 a| 
ドライブの健常性ログ
 a| 
「drive-health-data.bin」このファイルには、ドライブのヘルスに関連するさまざまなドライブ情報が含まれています。

[NOTE]
====
このファイルはバイナリファイルであり、判読可能な形式に変換するにはオフラインパーサが必要になります。

====


 a| 
ドライブのパフォーマンス分析データ
 a| 
「drive-performe-log.txt」

このファイルには、ドライブのパフォーマンスデータが格納されます。パフォーマンスが想定よりも低いドライブを特定するのに役立ちます。



 a| 
Enterprise Management Windowの設定
 a| 
emwdata_v04.bin

このファイルには、EMWの設定データストアファイルが格納されます。

[NOTE]
====
このファイルは、E2800とE5700のサポートバンドルには含まれていません。

====


 a| 
トレイのイベントログです
 a| 
expansion-tray -log.txt

ESMのイベントログです。



 a| 
リポジトリの分析に失敗しました
 a| 
'failed-repository-Analysis.txt'と入力します

このファイルには、リポジトリの障害に関する分析情報が格納されます。



 a| 
ストレージアレイの機能
 a| 
「feature-bundle.txt」このファイルには、ストレージアレイで使用可能なボリューム、ドライブ、ドライブトレイの数、および使用可能な機能とその制限のリストが格納されます。



 a| 
ファームウェアインベントリ
 a| 
「firmware-inventory.txt」このファイルには、ストレージアレイ内のすべてのコンポーネントのすべてのファームウェアバージョンのリストが含まれています。



 a| 
InfiniBandインターフェイス統計情報（InfiniBandのみ）
 a| 
ib-statistics.csv`

このファイルには、InfiniBandインターフェイスの統計情報が格納されます。



 a| 
I/Oパス統計情報
 a| 
「io-path-statistics.7z」このファイルには、アプリケーションパフォーマンスの問題の分析に使用できる、各コントローラの生のパフォーマンスデータが含まれています。



 a| 
ホストインターフェイスチップのIOCダンプ情報
 a| 
「IOC-DUMP_info.txt」このファイルには、ホストインターフェイスチップのIOCダンプ情報が格納されています。



 a| 
ホストインターフェイスチップのIOCダンプログ
 a| 
IOC dump.gzこのファイルにはコントローラのホスト・インターフェイス・チップのログ・ダンプが格納されていますこのファイルはgz形式で圧縮されています。zipファイルは、カスタマーサポートバンドル内にファイルとして保存されます。



 a| 
iSCSI接続（iSCSIのみ）
 a| 
「iscsi-session-connections.txt」このファイルには、現在のすべてのiSCSIセッションのリストが含まれています。



 a| 
iSCSI統計（iSCSIのみ）
 a| 
「iscsi-statistics .csv」このファイルには、イーサネットMAC、イーサネット伝送制御プロトコル（TCP）/インターネットプロトコル（IP）、およびiSCSIターゲットの統計情報が含まれる。



 a| 
iSERインターフェイスの統計情報（iSER over InfiniBandのみ）
 a| 
iSER - statistics-csv'このファイルには'iSER over InfiniBandを実行するホスト・インターフェイス・カードの統計情報が含まれています



 a| 
メジャーイベントログ
 a| 
「major-event-log.txt」このファイルには、ストレージ・アレイ上で発生するイベントの詳細なリストが格納されます。このリストは、ストレージアレイ内のディスクのリザーブされた領域に保存されます。リストには、ストレージアレイの設定イベントとコンポーネント障害が記録されます。



 a| 
マニフェストファイル
 a| 
'manifest.xml

このファイルには、アーカイブファイルに含まれるファイルと、各ファイルから収集されたステータスがテーブル形式で格納されます。



 a| 
ストレージ管理ソフトウェアの稼働情報
 a| 
「msw-runtime-info.txt」

このファイルには、ストレージ管理ソフトウェアアプリケーションの稼働情報が格納されます。ストレージ管理ソフトウェアで現在使用されているJREバージョンが含まれます。



 a| 
NVMe-oFの統計
 a| 
「nvmeof - statistics.csv」です

このファイルには、NVMeコントローラ統計、NVMeキュー統計、転送プロトコル（InfiniBandなど）のインターフェイス統計などの統計が格納されます。



 a| 
NVSRAMデータ
 a| 
「NVSRAMデータ.txt」このコントローラファイルは、コントローラのデフォルト設定を指定します。



 a| 
オブジェクトバンドル
 a| 
object-bundle`.bin `object-bundle`.json

このバンドルには、ファイルが生成された時点における、ストレージアレイとそのコンポーネントのステータスの詳細な概要 が含まれます。



 a| 
パフォーマンス統計の要約
 a| 
perf-stat-daily-a.csv`perf-stat-dail-summary-bcsv`

このファイルには、コントローラごとに1つのファイルで構成される、さまざまなコントローラパフォーマンス統計が格納されます



 a| 
永続的予約と登録
 a| 
「persistent-reservations.txt」このファイルには、ストレージアレイ上のボリュームの詳細なリストと永続的予約および登録が含まれています。



 a| 
ストレージ管理ソフトウェアのユーザ設定
 a| 
「pref-01.bin」

このファイルには、ユーザ設定の永続的データストアが格納されます。

[NOTE]
====
このファイルは、E2800またはE5700のサポートバンドルには含まれていません。

====


 a| 
Recovery Guruの手順
 a| 
「recovery-guru -procedures.html」このファイルには、ストレージアレイで検出された問題に応じて発行されたすべてのRecovery Guruトピックの詳細なリストが含まれています。E2800とE5700のアレイでは、Recovery Guruの詳細のみが格納され、HTMLファイルは含まれません。



 a| 
リカバリプロファイル
 a| 
「recovery-profile.csv」：このファイルには、最新のリカバリプロファイルレコードと履歴データの詳細な概要 が含まれています。



 a| 
SAS PHYエラーログ
 a| 
SAS-phy-error-logs.csv

このファイルには、SAS PHYのエラー情報が格納されます。



 a| 
状態キャプチャデータ
 a| 
「state-capture-data.txt」このファイルには、ストレージアレイの現在の状態の詳細な概要 が含まれています。



 a| 
ストレージアレイ構成
 a| 
「storage-array-configuration.cfg」このファイルには、ストレージアレイ上の論理構成の詳細な概要 が含まれます。



 a| 
ストレージアレイプロファイル
 a| 
「storage-array-profile.txt」このファイルには、ストレージアレイのすべてのコンポーネントとプロパティの概要 が含まれています。



 a| 
トレースバッファの内容
 a| 
「trace-buffers.7z」このファイルには、デバッグ情報を記録するために使用されるコントローラのトレースバッファの内容が含まれています。



 a| 
トレイキャプチャデータ
 a| 
tray -component-state-capture.7zトレイにドロワーが含まれている場合'診断データはこのzipファイルにアーカイブされますこのzipファイルには、ドロワーを搭載するトレイごとにテキストファイルが含まれています。Zipファイルは、カスタマーサポートバンドル内にファイルとして保存されます。



 a| 
読み取り不能セクター
 a| 
読み取り不能セクター.txtこのファイルには'ストレージ・アレイに記録されたすべての読み取り不能セクターの詳細なリストが含まれます



 a| 
Webサービストレースログ（E2800またはE5700のみ）
 a| 
「web-server-trace-log-a. 7z

「web-server-trace-log-b. 7z

このファイルには、コントローラごとに1つずつ、デバッグ情報を記録するために使用されるWeb Servicesトレースバッファが含まれています。



 a| 
ワークロードキャプチャ分析ログファイル
 a| 
「WLC-analytics -a.lz4」「WLC-analytics - B. lz4」

このファイルはコントローラごとに1つで、LBAヒストグラム、読み取り/書き込み比率、アクティブなすべてのボリュームにおけるI/Oスループットなど、計算された主なワークロード特性が含まれています。



 a| 
Xヘッダーデータファイル
 a| 
「x-header-data.txt」このAutoSupport メッセージ・ヘッダーは、プレーン・テキストのキーと値のペアで構成されています。このペアには、配列とメッセージ・タイプに関する情報が含まれます。

|===


== 構文

[source, cli, subs="+macros"]
----
save storageArray supportData file=pass:quotes["_filename_"] [force=(TRUE | FALSE)]
----
[source, cli, subs="+macros"]
----
save storageArray supportData file=pass:quotes["_filename_"]
[force=(TRUE | FALSE) |
csbSubsetid=(basic | weekly | event | daily | complete) |
csbTimeStamp=pass:quotes[_hh:mm_]]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
'file'
 a| 
ストレージアレイのサポート関連データの保存先となるファイルパスとファイル名。ファイルパスとファイル名は二重引用符（ "" ）で囲みます。例：

'file="C:\Program Files\CLI\logs\supdat.7z



 a| 
「フォース」
 a| 
コントローラ処理をロックできなかった場合に、サポートデータを強制的に収集するためのパラメータ。サポートデータを強制的に収集するには、このパラメータを「true」に設定します。デフォルト値は'FALSE'です

|===


== 注：

ファームウェアレベル7.86以降では、ファイル名の拡張子は `.7z`。7.86より前のバージョンのファームウェアを実行している場合、ファイル拡張子は `.zip`。



== 最小ファームウェアレベル

7.80で'force'パラメータが追加されました

8.30で、E2800ストレージアレイの情報が追加されました。
