---
permalink: commands-a-z/save-drivechannel-faultdiagnostics-file.html 
sidebar: sidebar 
keywords: save, drive, channel, fault, isolation, diagnostic, status 
summary: save driveChannel faultDiagnostics fileコマンドは、start driveChannel faultDiagnosticsコマンドから返されたドライブチャネルの障害切り分け診断データを保存します。 
---
= ドライブチャネル障害分離診断ステータスの保存 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
save driveChannel faultDiagnostics fileコマンドは'start driveChannel faultDiagnosticsコマンドから返されたドライブチャネル障害切り分け診断データを保存します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
ファームウェアバージョン8.10では、save driveChannel faultDiagnosticsコマンドは廃止されました。

====
診断データは、標準テキストまたはXMLとしてファイルに保存できます。



== 構文

[source, cli, subs="+macros"]
----
save driveChannel faultDiagnostics file=pass:quotes["_filename_"]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
'file'
 a| 
ドライブチャネルでの障害切り分け診断テストの結果の保存先となるファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。例：

'file="C:\Program Files\CLI\sup\fltdiag.txt

このコマンドでは、保存されているファイルにファイル拡張子は自動的に付加されません。ファイル名にはファイル拡張子を指定する必要があります。

|===


== 注：

保存されたファイルには、ファイル拡張子は自動的に付加されません。ファイルに適切な形式のファイル拡張子を指定する必要があります。ファイル拡張子「.txt」を指定すると、出力はテキストファイル形式になります。ファイル拡張子に「.xml」を指定すると、出力はXMLファイル形式になります。



== 最小ファームウェアレベル

この新しい機能は7.15でレガシーコントローラトレイに導入されました。
