---
permalink: commands-a-z/save-storagearray-arvmstats-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: save, asynchronous, mirror, group, statistics 
summary: save storageArray arvmStats asyncMirrorGroupコマンドは、非同期ミラーグループ内の1つ以上のメンバーボリュームの同期統計をファイルに保存します。 
---
= 非同期ミラーグループの統計を保存します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
save storageArray arvmStats asyncMirrorGroupコマンドは、非同期ミラーグループ内の1つ以上のメンバーボリュームの同期統計をファイルに保存します。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700のアレイを含む個々のストレージアレイを環境 で処理します。 すべてのSMcliパッケージがインストールされていること。



== ロール

このコマンドをE2800またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

収集される統計は、ローカルストレージアレイ上のプライマリロールの非同期ミラーグループのメンバーボリュームでのみ使用できます。

ミラー構成が適切に機能しているかどうかを評価するために使用できる同期プロセス中に一連のデータが収集されます。データは_samples_のセットとして収集されます。サンプルは同期プロセスの開始時に作成され、同期プロセスの実行中に定期的に更新されます。

サンプルは'同期プロセスが完了するまで'またはボリューム所有権の転送や読み取り/書き込みエラーなど'同期プロセスの中断が発生するまで'データを収集します同期プロセスの停止が解決されると（ボリュームが代替コントローラに転送された場合など）、新しいサンプルが作成され、同期プロセスの続行に従って更新されます。



== 構文

[listing, subs="+macros"]
----
save storageArray arvmStats asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
arvmStats file=pass:quotes["_filename_"]
"
[volume=pass:quotes["_volumeName_"]]
[sampleType=(all | mostRecent | longestSyncTime | errors)]
[recordLimit=(1-90)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「asyncMirrorGroup」
 a| 
同期の統計を保存する非同期ミラーグループの名前。非同期ミラーグループ名は角かっこ（[]）で囲みます。非同期ミラーグループ名に特殊文字または数字が含まれている場合は、非同期ミラーグループ名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
'file'
 a| 
同期の統計の保存先となるファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。例：

'file="C:\Program Files\CLI\logs\asynchdata.csv

このコマンドでは、保存されているファイルにファイル拡張子は自動的に付加されません。任意のファイル名を使用できますが'.csv拡張子を使用する必要があります



 a| 
「 volume 」
 a| 
このパラメータはオプションです。同期の統計を取得する非同期ミラーグループ内の特定のメンバーボリュームの名前。ボリュームを指定しない場合は、非同期ミラーグループ内のすべてのメンバーボリュームの統計が保存されます。

非同期ミラーグループ内の複数のボリュームについて統計が収集される場合は、すべてのデータが同じファイルに書き込まれます。

ボリューム名は二重引用符（""）で囲みます。



 a| 
「sampleType」
 a| 
このパラメータはオプションです。「sampleType」のデフォルト値は「all」です。

* all -- 3つのサンプルタイプすべてのデータが収集され'同じファイルに書き込まれます
* 「mostrecent」--最新の50件の再同期サンプルの統計が記録されます。
* longestSyncTime'--最新の20件の最も長い再同期サンプルの統計情報が収集されます
* `errors`--直近の20件の失敗した再同期サンプルの統計が記録されますこれらのサンプルには、障害コードが含まれています。




 a| 
「レコード制限」
 a| 
このパラメータはオプションです。レコード制限のデフォルト値は「無制限」です。'recordLimit'は0より大きく90以下である必要があります

|===


== 注：

プライマリロールでは、ミラーボリュームの統計がキャプチャされます。収集される統計には次のデータが含まれます。

* 同期の開始時刻
* 同期タイプ（手動または定期的）
* 同期の期間
* 送信バイト数
* 最大書き込み時間（単一の書き込みの場合）
* 最短の書き込み時間（単一の書き込みの場合）
* 最低の同期データ速度
* 最大同期データ速度
* 合計書き込み時間
* リポジトリの使用率(%)
* リカバリポイントの経過時間


初期同期中は、約15分ごとに統計サンプルがキャプチャされます。

同期の統計はサポートバンドルに含まれています。



== 最小ファームウェアレベル

7.84
