---
permalink: commands-a-z/save-storagearray-autoloadbalancestatistics-file.html 
sidebar: sidebar 
keywords: save, auto-load, balance, statistics 
summary: save storageArray autoLoadBalanceStatistics fileコマンドは、自動I/Oワークロードバランシングを提供し、ホストからの受信I/Oトラフィックが動的に管理されて両方のコントローラに分散されるようにします。 
---
= 自動ロードバランシング統計を保存する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
save storageArray autoLoadBalanceStatistics fileコマンドは、I/Oワークロードの自動バランシングを提供し、ホストからの受信I/Oトラフィックが動的に管理され、両方のコントローラに分散されるようにします。



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

このコマンドは、ストレージアレイの自動ロードバランシングの統計をファイルに保存します。これらの統計には、アレイ内の各ボリュームにおける所有権の変更履歴が表示されます。

[NOTE]
====
このファイルをテクニカルサポートに送信し、調査を依頼してください。

====


[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
 save storageArray autoLoadBalanceStatistics file=pass:quotes["_filename_"]
(numberOfDays=pass:quotes[_numberOfDays_]);
----


[[parameters]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「storageArray storageArray storageArray」
 a| 
このコマンドがストレージアレイに対して機能するように指定します。



 a| 
'file'
 a| 
自動ロードバランシングの統計の保存先となるファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。



 a| 
「日数」
 a| 
統計を保存する日数。このパラメータはオプションで、デフォルト値は0です。これは、使用可能なすべてのデータを示します。

|===


[[example]]
== 例

[listing]
----
SMcli -n Array1 -c "save storageArray autoLoadBalanceStatistics file="filename" numberOfDays=30;"
----
[NOTE]
====
「ドライブがプライマリパスを喪失」状態がアクティブな場合、自動ロードバランシングがワークロードを分散することができません。自動ロードバランシング機能でワークロードが分散されるためには、この状態が非アクティブである必要があります。

====


[[minimum-firmware-level]]
== 最小ファームウェアレベル

8.30
