---
permalink: commands-a-z/save-storagearray-warningevents.html 
sidebar: sidebar 
keywords: save, storage, array, events 
summary: save storageArray warningEventsコマンドは、メジャーイベントログのイベントをファイルに保存します。 
---
= ストレージアレイイベントの保存 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
save storageArray warningEventsコマンドは、メジャーイベントログのイベントをファイルに保存します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドは、メジャーイベントログのイベントをファイルに保存します。保存できるイベントは次のとおりです。

* *重大イベント*--ただちに対処する必要があるストレージアレイでのエラー。このエラーをすぐに修正しないと、データアクセスが失われるおそれがあります。
* *警告イベント*--パフォーマンスの低下や別のエラーからのリカバリ機能の低下をもたらすストレージアレイでのエラー。データへのアクセスは失われませんが、別のエラーが発生した場合にデータアクセスが失われないようにするために、このエラーを修正する必要があります。
* *情報イベント*--通常の動作に影響を与えないストレージアレイでのイベント発生。このイベントでは、設定の変更や、ストレージアレイのパフォーマンスを評価する際に役立つその他の情報が報告されます。
* *デバッグイベント*--エラーの原因となった手順や状態の判別に役立つ情報を提供するストレージアレイで発生したイベント。この情報が記録されたファイルをテクニカルサポートに送信して、エラーの原因 を特定できます。


[NOTE]
====
一部のストレージアレイでは、4つのイベントタイプがすべてサポートされない場合があります。

====


== 構文

[source, cli, subs="+macros"]
----
save storageArray (allEvents | criticalEvents |
warningEvents | infoEvents | debugEvents)
file=pass:quotes["_filename_"]
[count=pass:quotes[_numberOfEvents_]]
[forceSave=(TRUE | FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allEvents」
 a| 
すべてのイベントをファイルに保存するためのパラメータ。



 a| 
「criticalEvents」です
 a| 
重大イベントのみをファイルに保存するためのパラメータ。



 a| 
「warningEvents」
 a| 
警告イベントのみをファイルに保存するためのパラメータ。



 a| 
「infoEvents」
 a| 
情報イベントのみをファイルに保存するためのパラメータ。



 a| 
「debugEvents」
 a| 
デバッグイベントのみをファイルに保存するためのパラメータ。



 a| 
'file'
 a| 
イベントの保存先となるファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。例：

`file="C:\Program Files\CLI\logs\events.txt"`

メジャー・イベント・ログの内容を格納するファイルのデフォルト名は'major-event-log.txt'ですこのコマンドでは、保存されているファイルにファイル拡張子は自動的に付加されません。ファイル名にはファイル拡張子を指定する必要があります。



 a| 
「count」
 a| 
ファイルに保存するイベントの数。countの値を入力しない場合は、指定したイベントタイプに一致するすべてのイベントがファイルに保存されます。countの値を入力した場合は、その数のイベント（最後に入力したイベントからの数）だけがファイルに保存されます。整数値を使用します。



 a| 
「forceSave」をクリックします
 a| 
ビューからフィルタで除外したデバッグイベントを強制的にファイルに保存するためのパラメータ。イベントを強制的に保存するには、このパラメータを「true」に設定します。デフォルト値は'FALSE'です

[NOTE]
====
このパラメータを使用すると、SANtricity イベントビューアからフィルタで除外されたデバッグイベントが保存されます。

====
|===


== 最小ファームウェアレベル

7.77で、次のパラメータが追加されました

* 「warningEvents」
* 「infoEvents」
* 「debugEvents」
* 「forceSave」をクリックします

