---
permalink: commands-a-z/save-auditlog.html 
sidebar: sidebar 
keywords: save, audit log, records 
summary: save auditLogコマンドは、監査ログレコードを取得します。 
---
= 監査ログレコードを保存します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
save auditLogコマンドは'監査ログ・レコードを取得します



== サポートされているアレイ

このコマンドは、E2800、E5700、EF600、またはEF300の個々のストレージアレイを環境 します。E2700またはE5600のストレージアレイに対しては機能しません。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Security Adminロールが必要です。



== 構文

[listing, subs="+macros"]
----

save auditLog (all | (beginDate=pass:quotes[_date_ | endDate=_date_)]
|(beginRecord=pass:quotes[_timestamp_] | endRecord=pass:quotes[_timestamp_))] file=pass:quotes["_filename_"]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「すべて」
 a| 
すべての監査ログレコードを取得できます。



 a| 
「開始日」
 a| 
取得の開始日を指定できます。日付の入力形式は、クライアントタイムゾーンでMM：DD：YYです。取得される最初の監査ログレコードは、指定した日付以降に投稿された最初のレコードです。

[NOTE]
====
午前0時から午前0時までの範囲は、クライアントのタイムゾーンに基づいています。

====


 a| 
「endDate」
 a| 
取得の終了日を指定できます。指定しない場合は、ログの最後のレコードが取得されます。日付の入力形式は、クライアントタイムゾーンでMM：DD：YYです。取得される最後の監査ログレコードは、指定した日付以前に投稿された最後のレコードです。

[NOTE]
====
午前0時から午前0時までの範囲は、クライアントのタイムゾーンに基づいています。

====


 a| 
「beginRecord」
 a| 
取得する最初のレコードを指定できます。この値は、最初の監査ログレコードのタイムスタンプを表す整数値です。指定しない場合は、ログの最初のレコードが取得されます。



 a| 
「endRecord」
 a| 
取得する終了レコードを指定できます。この値は、最後の監査ログレコードのタイムスタンプを表す整数値です。指定しない場合は、ログの最後のレコードが取得されます。



 a| 
'file'
 a| 
監査ログの出力ファイル名を指定できます。

[NOTE]
====
監査ログのレコードは、新しいものから順にファイルに保存されます。

====
|===


== 例

[listing]
----

SMcli -n Array1 -c "save auditLog all file="myAuditLog.txt";"

SMcli -n Array1 -c "save auditLog endRecord=1493070393313 file="myAuditLog.txt";"

SMcli -n Array1 -c "save auditLog beginDate=12:12:16 endDate=04:01:17 file="myAuditLog.txt";"


SMcli completed successfully.
----


== 最小ファームウェアレベル

8.40
