---
permalink: commands-a-z/set-volume-ssdcacheenabled.html 
sidebar: sidebar 
keywords: set, ssd, cache, volume 
summary: set volume ssdCacheEnabledコマンドは、特定のボリュームに対してSSDキャッシュ機能を使用したキャッシュをオンまたはオフにします。 
---
= ボリュームの SSD キャッシュを設定する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set volume ssdCacheEnabledコマンドは'特定のボリュームのSSDキャッシュ機能を使用したキャッシュのオン/オフを切り替えます



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Support Adminロールが必要です。



[[context]]
== コンテキスト（Context）

ボリュームは次のいずれかです。

* 標準ボリューム。名前またはWWIDで識別されます
* Snapshotボリューム
* 整合性グループのSnapshotボリューム




[[syntax-applicable-to-a-standard-volume]]
== 標準ボリュームに適用される構文

[source, cli, subs="+macros"]
----
set volume (pass:quotes[[_volumeName_]] | <"WWID">) ssdCacheEnabled=(TRUE | FALSE)
----


[[syntax-applicable-to-a-snapshot-volume]]
== Snapshotボリュームに適用される構文

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapVolumeName_"]] ssdCacheEnabled=(TRUE | FALSE)
----


[[syntax-applicable-to-a-consistency-group-snapshot-volume]]
== 整合性グループのSnapshotボリュームに適用される構文

[source, cli, subs="+macros"]
----
set cgSnapVolume pass:quotes[["_cgSnapVolumeName_"]] ssdCacheEnabled=(TRUE | FALSE)
----


[[parameters]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
SSDキャッシュをオンまたはオフにする標準ボリュームの名前。ボリュームの名前は角かっこ（[]）で囲みます。ボリューム名に特殊文字または数字が含まれている場合は、ボリューム名を二重引用符（""）で囲んだ上で角かっこ（[]）で囲む必要があります。



 a| 
「 volume 」
 a| 
SSDキャッシュをオンまたはオフにする標準ボリュームのWorld Wide Identifier（WWID）。WWIDは二重引用符（""）で囲んだ上で山かっこ（<>）で囲みます。



 a| 
「SnapVolume」
 a| 
SSDキャッシュをオンまたはオフにするSnapshotボリュームの名前。Snapshotボリュームの名前は、二重引用符（""）で囲んだ上で角かっこ（[]）で囲みます。



 a| 
cgSnapVolume
 a| 
SSDキャッシュをオンまたはオフにする整合性グループのSnapshotボリュームの名前。整合性グループのSnapshotボリュームの名前は、二重引用符（""）で囲んだ上で角かっこ（[]）で囲みます。



 a| 
「ssdCacheEnabled」を入力します
 a| 
SSDキャッシュをオンにするには、このパラメータを「true」に設定します。SSDキャッシュをオフにするには、このパラメータを「FALSE」に設定します。

|===


[[notes]]
== 注：

SSDキャッシュは、一度に1つのボリュームに対してオンまたはオフにすることができます。

ボリュームのSSDキャッシュをオフにすると、そのボリュームのSSDキャッシュがパージされます。



[[minimum-firmware-level]]
== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
