---
permalink: commands-a-z/set-snapvolume-converttoreadwrite.html 
sidebar: sidebar 
keywords: set, read-only, snapshot, volume, read/write, volume 
summary: set SnapVolume convertToReadWriteコマンドは、読み取り専用ボリュームであるSnapshotボリュームを、読み取り/書き込み可能なSnapshotボリュームに変更します。 
---
= 読み取り専用Snapshotボリュームを読み取り/書き込みボリュームに設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set snapVolume convertToReadWriteコマンドは'読み取り専用ボリュームであるスナップショット・ボリュームを'読み取り/書き込みボリュームであるスナップショット・ボリュームに変更します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドを使用して、読み取り/書き込みボリュームに新しいリポジトリボリュームを指定したり、リポジトリボリュームのフルの警告レベルを設定したりすることもできます。



== 構文

[source, cli, subs="+macros"]
----
set snapVolume pass:quotes[["_snapImageVolumeName_"]] convertToReadWrite
[(repositoryVolume="repos_xxxx" |
repositoryVolume=pass:quotes[(_volumeGroupName_)] [capacity=pass:quotes[_capacityValue_]])
repositoryVolume=pass:quotes[(_diskPoolName_)] [capacity=pass:quotes[_capacityValue_]]]
[repositoryFullLimit=pass:quotes[_percentValue_]]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「SnapVolume」
 a| 
読み取り専用から読み取り/書き込みに変更するSnapshotボリュームの名前。Snapshotボリュームの識別子は、二重引用符（""）で囲んだ上で角かっこ（[]）で囲みます。



 a| 
リポジトリボリューム
 a| 
読み取り/書き込みボリュームに使用するリポジトリボリュームの名前。

リポジトリボリュームの名前を定義する方法は2つあります。

* 既存のリポジトリボリュームの名前を使用します
* このコマンドを実行するときに新しいリポジトリボリュームを作成します


既存のリポジトリボリュームの名前は次の2つの部分で構成されます。

* 「repos」という用語
* ストレージ管理ソフトウェアがリポジトリボリューム名に割り当てる4桁の数値識別子


既存のリポジトリボリュームの名前は二重引用符（""）で囲みます。

このコマンドを実行するときに新しいリポジトリボリュームを作成する場合は、リポジトリボリュームを含めるボリュームグループまたはディスクプールの名前を入力する必要があります。必要に応じて、リポジトリボリュームの容量を定義することもできます。容量を定義する場合は、次の値を使用できます。

* ベースボリュームの容量の割合を表す整数値
* ベースボリュームの容量の割合を表す小数値
* リポジトリボリュームの具体的なサイズ。サイズは'bytes'KB'MB`'GB'TB'の単位で定義されます


容量オプションを使用しない場合は、ストレージ管理ソフトウェアによって、ベースボリュームの容量の20%に設定されます。

このコマンドを実行すると、ストレージ管理ソフトウェアによって、Snapshotボリューム用のリポジトリボリュームが作成されます。



 a| 
repositoryFullLimit
 a| 
リポジトリボリュームの容量がこの割合に達すると、Snapshotイメージのリポジトリボリュームの上限に近づいているという警告が表示されます。整数値を使用します。たとえば、70という値は70%を意味します。デフォルト値は75です。

|===


== 注：

ユーザラベルには、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。ユーザラベルの最大文字数は30文字です。

リポジトリボリュームの名前は、新しいSnapshotグループを作成するときに、ストレージ管理ソフトウェアおよびファームウェアによって自動的に作成されます。リポジトリボリュームの名前は変更できません。名前を変更するとSnapshotイメージとのリンクが切断されます。

Snapshotグループのリポジトリボリュームは拡張可能なボリュームで、標準ボリュームエンティティを最大16個まで接続することで構成されます。拡張可能なリポジトリボリュームは、最初は1つの要素だけで構成されます。その時点でのリポジトリボリュームの容量は、その要素の容量と同じです。リポジトリボリュームの容量は、標準のリポジトリボリュームを接続することで拡張できます。その後、複数の要素で構成された拡張可能なリポジトリボリュームの容量は、接続されたすべての標準ボリュームの合計容量になります。

Snapshotグループのリポジトリボリュームは、次の合計サイズの最小容量要件を満たす必要があります。

* 32MB：Snapshotグループのオーバーヘッドを固定し、copy-on-write処理に使用できるようになりました。
* ロールバック処理用の容量。ベースボリュームの容量の1/5000です。


この最小容量は、コントローラファームウェアとストレージ管理ソフトウェアによって適用されます。



== 最小ファームウェアレベル

7.83
