---
permalink: commands-a-z/set-event-alert.html 
sidebar: sidebar 
keywords: set, event, alert, filter 
summary: set event alertコマンドは、特定のアラート対象イベントに関連する通知を無効または有効にすることにより、アラートイベント通知を管理します。特定のアラート対象イベントに関する通知を無効にするには、そのイベントをブロックします。特定のアラート対象イベントに関する通知を有効にする場合は、そのイベントのブロックを解除します。 
---
= イベントアラートのフィルタリングを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「set event alert」コマンドは、特定のアラート対象イベントに関連する通知を無効または有効にすることによって、アラートイベント通知を管理します。特定のアラート対象イベントに関する通知を無効にするには、次のコマンドを実行します。「ブロック」特定のアラート対象イベントに関する通知を有効にするには、そのイベントのブロックを解除します。



== サポートされているアレイ

このコマンドは、E2700とE5600のストレージアレイにのみ適用されます。



== コンテキスト（Context）

[NOTE]
====
このコマンドはSMcliコマンドであり、スクリプトコマンドではありません。このコマンドはコマンドラインから実行する必要があります。このコマンドは、ストレージ管理ソフトウェア内のスクリプトエディタから実行することはできません

====


== コンテキスト（Context）

ストレージアレイを定義する際に、アラートを設定し、イベントアラートの管理方法を定義できます。アラートを送信するようにストレージアレイを設定した場合は、アラート対象イベントが発生したときに指定の受信者に通知が送信されます。通知には、次のいずれかまたはすべての種類を使用できます。

* E メール
* syslog
* SNMPトラップ通知


イベントアラートの設定CLIコマンドは、1つのストレージアレイに対して機能します。あるストレージアレイでこのコマンドを実行すると、そのストレージアレイのみにコマンドが適用されます。CLIコマンドの実行対象でない他のストレージアレイでは、デフォルトの動作が実行されます。

[NOTE]
====
イベントアラートをブロックしても、イベントはシステムイベントログに記録されます。すべてのイベントは引き続きイベントログに記録されます。

====
[NOTE]
====
このコマンドを使用して、アラート対象でないイベントをアラート対象にすることはできません。

====


== イベントアラートをブロックする構文

[source, cli, subs="+macros"]
----
set blockEventAlert pass:quotes[_eventType_]
----


== イベントアラートをブロック解除する構文

[source, cli, subs="+macros"]
----
set unBlockEventAlert pass:quotes[_eventType_]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
_eventType_`
 a| 
このパラメータは、イベントの整数値です。イベント値を16進形式で入力します（0x280Dなど）。値が16進形式であることを示すために、常に「* 0x」で始まるようにしてください。0xを使用しないと、ブロックまたはブロック解除コマンドが適用される前に、値が10進数として解釈されて16進値に変換されます。これにより、原因 が誤ったイベントをブロックまたはブロック解除する可能性があります。

無効なイベントを入力すると、エラーが表示されます。

|===


== 最小ファームウェアレベル

8.10で
