---
permalink: commands-a-z/set-syncmirror.html 
sidebar: sidebar 
keywords: set, synchronous, mirror 
summary: set SyncMirror コマンドは、リモートミラーペアのプロパティを定義します。 
---
= 同期ミラーリングを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set SyncMirror コマンドは'リモート・ミラー・ペアのプロパティを定義します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700のアレイを含む個々のストレージアレイを環境 で処理します。 すべてのSMcliパッケージがインストールされていること。



== ロール

このコマンドをE2800またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
このコマンドの以前のバージョンでは、機能識別子は「remoteMirror」でした。この機能識別子は有効ではなくなり' SyncMirror に置き換えられます

====


== 構文

[listing, subs="+macros"]
----
set syncMirror (localVolume pass:quotes[[_volumeName_]] |
localVolumes pass:quotes[[_volumeName1 ... volumeNameN_]])
[role=(primary | secondary)]
[syncPriority=(highest | high | medium | low | lowest)]
[autoResync=(enabled | disabled)]
[writeOrder=(preserved | notPreserved)]
[writeMode=(synchronous | asynchronous)]
[force=(TRUE | FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「localVolume」です
 a| 
プロパティを定義するローカルボリュームの名前。プライマリボリューム名は角かっこ（[]）で囲みます。プライマリボリューム名に特殊文字または数字が含まれている場合は、プライマリボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「localVolumes」を参照してください
 a| 
プロパティを定義する複数のローカルボリュームの名前。以下のルールを使用して、ボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


ボリューム名が特殊文字を含んでいる場合または数字のみで構成されている場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
「役割」
 a| 
ローカルボリュームをプライマリボリュームまたはセカンダリボリュームとして機能させるための設定。ボリュームをプライマリ・ボリュームとして定義するには'このパラメータをprimaryに設定しますボリュームをセカンダリ・ボリュームとして定義するには'このパラメータをsecondaryに設定しますこのパラメータは、ボリュームがミラー関係にある場合にのみ適用されます。



 a| 
「syncPriority」
 a| 
ホストI/Oアクティビティに対する完全同期の優先度。有効な値は'highest'high`'high`'medium`'low''low'lowest`です



 a| 
「autoResync」
 a| 
リモートミラーペアのプライマリボリュームとセカンダリボリュームの間の自動再同期の設定。このパラメータには次の値があります。

* [enabled]--自動再同期がオンになっています何もしなくても、プライマリボリュームとセカンダリボリュームは再同期されます。
* disabled --自動再同期がオフになっていますプライマリ・ボリュームとセカンダリ・ボリュームを再同期化するには'resume SyncMirror コマンドを実行する必要があります




 a| 
「writeOrder」です
 a| 
このパラメータは、プライマリボリュームとセカンダリボリュームの間のデータ転送の書き込み順序を定義します。有効な値は「preserved」または「notPreserved」です。



 a| 
「writeMode」です
 a| 
このパラメータは、プライマリボリュームからセカンダリボリュームへの書き込み方法を定義します。有効な値は「synchronous」または「asynchronous」です。



 a| 
「フォース」
 a| 
ストレージアレイ間の通信リンクがダウンすると、強制的にロールが反転されるため、ローカル側で昇格または降格を行うと、プライマリまたはセカンダリが二重で存在する状態になります。ロール反転を強制的に実行するには'このパラメータをTRUEに設定しますデフォルト値は'FALSE'です

[NOTE]
====
「force」パラメータは、「role」パラメータを使用する場合にのみ使用してください。

====
|===


== 注：

このコマンドでは、オプションのパラメータを1つ以上指定できます。

同期優先度によって、ミラー関係のプライマリボリュームとセカンダリボリュームの間のデータの同期に使用されるシステムリソースの量が定義されます。最高の優先度レベルを選択すると、ほとんどのシステムリソースを使用してデータの完全同期が実行されるため、ホストのデータ転送パフォーマンスが低下します。

「writeOrder」パラメータは非同期書き込みモードにのみ適用され、整合グループの一部になります。「writeOrder」パラメータを「preserved」に設定すると、リモート・ミラー・ペアは、ホストからプライマリ・ボリュームへの書き込みと同じ順序で、プライマリ・ボリュームからセカンダリ・ボリュームへデータを送信します。送信リンクに障害が発生した場合、完全な同期が行われるまで、データはバッファされます。この処理では、バッファされたデータを維持するために追加のシステムオーバーヘッドが必要になる可能性があるため、処理が遅くなります「writeOrder」パラメータを「notPreserved」に設定すると、システムはバッファ内のデータを維持する必要がなくなりますが、セカンダリボリュームのデータがプライマリボリュームと同じになるように、完全な同期を強制的に実行する必要があります。



== 最小ファームウェアレベル

6.10
