---
permalink: commands-a-z/set-storagearray-odxenabled.html 
sidebar: sidebar 
keywords: enable, disable, odx 
summary: set storageArray odxEnabledコマンドは、ストレージアレイのオフロードデータ転送（ODX）をオンまたはオフにします。 
---
= ODX を有効化または無効化する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set storageArray odxEnabledコマンドは、ストレージアレイのオフロードデータ転送（ODX）をオンまたはオフにします。



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage AdminまたはSupport Adminロールが必要です。



[[context]]
== コンテキスト（Context）

ストレージアレイではもともとODXがオンになっています。ODXを実行しない場合や、ODXが原因でストレージアレイに問題が発生している場合は、このコマンドを使用してODXをオフにします。影響を受けるストレージアレイは、コマンドの実行元のストレージアレイのみです。



[[syntax]]
== 構文

[source, cli]
----
set storageArray odxEnabled=(TRUE | FALSE)
----


[[parameter]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「odxEnabled」
 a| 
ODXをオンまたはオフにするための設定。ODXをオンにするには、このパラメータを「true」に設定します。ODXをオフにするには、このパラメータをFALSEに設定します。デフォルト設定では、ODXはオンになっています。

|===


[[notes]]
== 注：

ODXは、バッファリングされた読み取りおよび書き込み操作を使用せずにデータを転送する方法を提供し、データ転送操作にホストが直接関与する必要がありません。ODXが有効になっていない場合、データはソースストレージからホストに読み込まれ、その後ホストからターゲットストレージに書き込まれます。ODXを有効にすると、データ転送操作はストレージインフラストラクチャによって直接管理されます。データはホストを経由せず、同一アレイ内のソースストレージからターゲットストレージへ直接転送されます。



[[minimum-firmware-level]]
== 最小ファームウェアレベル

8.20で
