---
permalink: commands-a-z/set-storagearray-hostconnectivityreporting.html 
sidebar: sidebar 
keywords: enable, disable, host, connectivity, report 
summary: set storageArray hostConnectivityReportingコマンドは、コントローラでホスト接続レポートを有効または無効にします。 
---
= ホスト接続レポートの有効化または無効化 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set storageArray hostConnectivityReporting'コマンドは、コントローラでホスト接続レポートを有効または無効にします。



== サポートされているアレイ

このコマンドは、E4000、E2800、E5700、EF600、またはEF300の個 々 のストレージアレイに適用されます。E2700またはE5600のストレージアレイに対しては機能しません。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli]
----
set storageArray hostConnectivityReporting (enable | disable)
----


== コンテキスト（Context）

ストレージアレイでホスト接続レポートを有効にすると、ストレージアレイでは、ストレージアレイのコントローラと設定されているホストの間の接続が引き続き監視され、ケーブルの緩み、損傷、欠落またはホストに関するその他の問題によって接続が中断された場合にアラートが表示されます。ストレージアレイでホストタイプが正しく指定されていない場合（フェイルオーバーで問題が発生する可能性があります）も通知されます。

[NOTE]
====
ホスト接続レポートを無効にするには、まず自動ロードバランシングを無効にする必要があります。

====
[NOTE]
====
自動ロードバランシングが無効な場合も、ホスト接続レポートは有効にしておくことができます。

====
[NOTE]
====
ホスト接続レポートおよび自動ロードバランシングは、Linux DHALUA、Windows / Windowsクラスタ、およびVMwareの各ホストタイプでのみ機能します。

====


== パラメータ

なし



== 最小ファームウェアレベル

8.42新しいコマンドパラメータ。
