---
permalink: commands-a-z/set-tray-drawer.html 
sidebar: sidebar 
keywords: set, drawer, service, action, allowed, indicator 
summary: set tray drawerコマンドは、ドライブを格納するドロワーの保守操作可能インジケータライトをオンまたはオフにします。 
---
= ドロワーサービスアクション許可インジケーターの設定 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set tray drawerコマンドは'ドライブを格納するドロワーの保守操作可能インジケータライトをオンまたはオフにします



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

ドロワーは大容量ドライブトレイで使用されます。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。このコマンドは、ドロワーを使用するドライブトレイのみに使用します。ストレージアレイが保守操作可能インジケータライト機能をサポートしていない場合、このコマンドはエラーを返します。ストレージアレイがこのコマンドをサポートしていてもインジケータライトをオンまたはオフにできない場合、このコマンドはエラーを返します。



== 構文

[source, cli, subs="+macros"]
----
set tray pass:quotes[[_trayID_]] drawer pass:quotes[[_drawerID_]]
serviceAllowedIndicator=(on | off | forceOnWarning)
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「tray」
 a| 
ドロワーが配置されているトレイ。トレイIDの値は'0～99ですトレイIDの値は角かっこ（[]）で囲みます。トレイIDの値を入力しない場合は、コントローラトレイのトレイIDがデフォルト値となります。



 a| 
「ドロワー」
 a| 
保守操作可能インジケータライトをオンまたはオフにするドロワーの場所。ドロワーIDの値は「1」～「5」です。ドロワーID値は角かっこ（[]）で囲みます。



 a| 
「serviceAllowedIndicator」というメッセージが表示されます
 a| 
保守操作可能インジケータライトをオンまたはオフにするための設定。保守操作可能インジケータライトをオンにするには、このパラメータを「オン」に設定します。保守操作可能インジケータライトをオフにするには、このパラメータを「オフ」に設定します。

「forceOnWarning」の使用方法については、「Notes」を参照してください。

|===


== 注：

このコマンドを入力するには、ドライブトレイが次の条件を満たしている必要があります。

* ドライブトレイが高温状態でないこと。
* ファンのステータスが最適lである必要があります。
* ドライブトレイのコンポーネントがすべて設置されている。
* ドライブドロワー内のボリュームがデグレード状態でないこと。ボリュームがデグレード状態のときにドライブドロワーからドライブを取り外すと、ボリュームで障害が発生する可能性があります。


[NOTE]
====
上記の条件を1つでも満たしていない場合は、このコマンドを実行しないでください。問題

====
コマンドが送信される前に、対象のドライブドロワー内のドライブを使用するすべてのボリュームがチェックされて、ボリュームがドロワー損失から保護されているかどうかが確認されます。ボリュームがドロワー損失から保護されている場合は、ボリュームへのI/Oアクティビティを停止することなく保守操作可能設定コマンドが続行されます。

該当するドロワーにドロワー損失から保護されないボリュームがある場合は、それらのボリュームへのI/Oアクティビティを停止する必要があります。警告が表示され、このコマンドを完了するべきではないことが示されます。

大容量ドライブトレイ全体の保守操作可能インジケータライトをオンまたはオフにするには' set tray serviceAllowedIndicatorコマンドを使用します



== forceOnWarningパラメータの使用

コンポーネントを取り外す準備をしていて、ボリュームがドロワー損失から保護されないことを通知する警告を無視するには、次のパラメータを入力します。

[listing]
----
serviceAllowedIndicator=forceOnWarning
----
forceOnWarningパラメータは'コンポーネントをコントローラファームウェアに削除する準備をする要求を送信し' set drawer serviceAllowedIndicatorコマンドを強制的に続行します

[NOTE]
====
このパラメータを指定するとドロワー内のすべてのドライブにアクセスできなくなるため、ボリュームが使用停止になる場合があり、ホストのリブートが必要になるなど、リカバリが複雑になる可能性があります。このパラメータを使用するときは注意してください。

====


== 最小ファームウェアレベル

7.60
