---
permalink: commands-a-z/set-storagearray-odxenabled.html 
sidebar: sidebar 
keywords: enable, disable, odx 
summary: set storageArray odxEnabledコマンドは、ストレージアレイのオフロードデータ転送（ODX）をオンまたはオフにします。 
---
= ODX を有効化または無効化する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set storageArray odxEnabledコマンドは、ストレージアレイのオフロードデータ転送（ODX）をオンまたはオフにします。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== コンテキスト（Context）

ストレージアレイではもともとODXがオンになっています。ODXを実行しない場合や、ODXが原因でストレージアレイに問題が発生している場合は、このコマンドを使用してODXをオフにします。影響を受けるストレージアレイは、コマンドの実行元のストレージアレイのみです。



== 構文

[source, cli]
----
set storageArray odxEnabled=(TRUE | FALSE)
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「odxEnabled」
 a| 
ODXをオンまたはオフにするための設定。ODXをオンにするには、このパラメータを「true」に設定します。ODXをオフにするには、このパラメータをFALSEに設定します。デフォルト設定では、ODXはオンになっています。

|===


== 注：

ODXを使用すると、バッファ読み取りとバッファ書き込みの処理を使用せずにデータを転送できます。データ転送処理にホストが直接関与する必要はありません。ODXが有効になっていない場合、ソースストレージからホストにデータが読み取られ、ホストからターゲットストレージに書き込まれます。ODXが有効な場合は、データ転送処理はストレージインフラによって直接管理されます。データはホストを経由せずに、ソースストレージからターゲットストレージに直接移動されます。



== 最小ファームウェアレベル

8.20で
