---
permalink: commands-a-z/set-storagearray-isnsipv4configurationmethod.html 
sidebar: sidebar 
keywords: set, storage, array, isns, server, ipv4, address 
summary: set storageArray isIPv4ConfigurationMethodコマンドは、IPv4 Internet Storage Name Service（iSNS）の設定方法とアドレスを設定します。 
---
= ストレージアレイのiSNSサーバのIPv4アドレスの設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set storageArray isIPv4ConfigurationMethodコマンドは、IPv4 Internet Storage Name Service（iSNS）の設定方法とアドレスを設定します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
set storageArray isnsIPv4ConfigurationMethod=(static | dhcp)
isnsIPv4Address=pass:quotes[_ipAddress_]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「isnsIPv4ConfigurationMethod」を参照してください
 a| 
iSNSサーバ設定を定義する方法。IPv4 iSNSサーバのIPアドレスを入力するには'static'を選択しますIPv4の場合'dhcp'と入力することにより'Dynamic Host Configuration Protocol (DHCP)サーバがiSNSサーバのIPアドレスを選択するように選択できますDHCPを有効にするには'isnsIPV4Address'パラメータを0.0.0.0に設定する必要があります



 a| 
「isnsIPV4Address」と入力します
 a| 
iSNSサーバに使用するIPアドレス。このパラメータは、IPv4設定の「static」値とともに使用します。DHCPサーバでIPv4インターネットiSNSサーバのIPアドレスを設定する場合は'*isnsIPV4Address*'パラメータを0.0.0.0に設定する必要があります

|===


== 注：

iSNSプロトコルは、TCP / IPネットワーク上のiSCSIデバイスとFibre Channelデバイスの自動検出、管理、および設定を支援します。iSNSは、Fibre Channelネットワークと同等のインテリジェントなストレージ検出/管理サービスを提供します。これにより、ストレージエリアネットワークとほぼ同じ容量で機能する汎用IPネットワークが実現します。また、iSNSは、Fibre ChannelファブリックサービスをエミュレートしてiSCSIデバイスとFibre Channelデバイスの両方を管理する機能によって、IPネットワークとFibre Channelネットワークのシームレスな統合を支援します。

DHCPサーバは、ネットワークアドレスなどの設定パラメータをIPノードに渡します。クライアントは、必要なすべてのIP設定パラメータをDHCPから取得できます。再利用可能なネットワークアドレスを自動的に割り当てることができます。



== 最小ファームウェアレベル

7.10
