---
permalink: commands-a-z/set-storagearray-traypositions.html 
sidebar: sidebar 
keywords: set, storage, array, tray, positions 
summary: set storageArray trayPositionsコマンドは、ストレージアレイ内のトレイの位置を定義します。このコマンドには、ストレージアレイ内のすべてのトレイを含める必要があります。 
---
= ストレージアレイのトレイの位置を設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set storageArray trayPositionsコマンドは、ストレージアレイ内のトレイの位置を定義します。このコマンドには、ストレージアレイ内のすべてのトレイを含める必要があります。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
set storageArray trayPositions=pass:quotes[(controller | _trayID_ ... _trayIDn_)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「トレイポジション」
 a| 
すべてのトレイIDのリスト。リストでのトレイIDの順序によって、ストレージアレイ内のコントローラトレイとドライブトレイの位置が定義されます。有効な値は「0」～「99」です。トレイIDの値はスペースで区切って入力します。トレイID値のリストは丸かっこで囲みます。コントローラトレイに有効なトレイ位置の範囲外の識別子が定義されているストレージアレイの場合は' controller値を使用します

|===


== 注：

このコマンドでは、トレイIDの「trayPositions」リスト内の位置によって、ストレージアレイ内のトレイの位置を定義します。たとえば、IDが84のコントローラトレイとIDが1、12のドライブトレイがある場合、 そして50、「trayPositions」シーケンス(841 12 50`)は、コントローラトレイを1番目の位置に、ドライブトレイ1を2番目の位置に、ドライブトレイ12を3番目の位置に、ドライブトレイ50を4番目の位置にそれぞれ配置します。trayPositionsシーケンス(`1 84 50 12`)は'コントローラトレイを2番目の位置に'ドライブトレイ1を1番目の位置に'ドライブトレイ50を3番目の位置に'ドライブトレイ12を4番目の位置に配置します

[NOTE]
====
ストレージアレイ内のすべてのトレイは、trayPositionsパラメータで定義されているリストに含める必要があります。リストのトレイ数がストレージアレイのトレイの総数と一致しない場合は、エラーメッセージが表示されます。

====
[NOTE]
====
管理ソフトウェアでは、最初の位置が上に、以降の位置が下から順に表示されます。

====


== 最小ファームウェアレベル

6.10

6.14と6.16では'controller'は有効な値ではありません
