---
permalink: commands-a-z/set-storagearray-autosupportremotediag.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, remote, diagnostics, feature, individual, E2800, E5700, arrays 
summary: set storageArray autoSupportRemoteDiagコマンドは、AutoSupport OnDemand Remote Diagnostics機能をオンまたはオフにします。この機能により、テクニカルサポートは、サポートデータを要求して問題をリモートで診断できます。 
---
= AutoSupport リモート診断機能を有効または無効にします
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set storageArray autoSupportRemoteDiagコマンドは、AutoSupport OnDemand Remote Diagnostics機能をオンまたはオフにします。この機能により、テクニカルサポートは、サポートデータを要求して問題をリモートで診断できます。



== サポートされているアレイ

このコマンドは、E2800、E5700、EF600、またはEF300の個々のストレージアレイを環境 します。E2700またはE5600のストレージアレイに対しては機能しません。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== コンテキスト（Context）

この機能を有効にする前に、まずAutoSupport 機能、次にAutoSupport OnDemand機能をストレージアレイ上で有効にします。

3つの機能は、次の順序で有効にする必要があります。

. AutoSupport を有効にします
. AutoSupport OnDemandを有効にします
. AutoSupport Remote Diagnosticsを有効にします




== 構文

[listing]
----
set storageArray autoSupportRemoteDiag (enable | disable)
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
'enable|disable
 a| 
AutoSupport リモート診断機能を有効または無効にすることができます。AutoSupport およびAutoSupport OnDemandが無効になっている場合、有効化の操作はエラーになり、まずAutoSupportとAutoSupportを有効にするよう指示されます。

|===


== 例

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupportRemoteDiag enable;"

SMcli completed successfully.
----


== 検証

show storageArray storageArray autoSupport AutoSupport コマンドを使用して、この機能を有効にしているかどうかを確認します。表示される出力の最初の3行には、AutoSupport 機能とAutoSupport OnDemand機能およびAutoSupport Remote Diagnostics機能の有効ステータスが順番に表示されます。

[listing]
----
The AutoSupport feature is enabled on this storage array.
The AutoSupport OnDemand feature is enabled on this storage array.
The AutoSupport Remote Diagnostics feature is enabled on this storage array.
----


== 最小ファームウェアレベル

8.40
