---
permalink: commands-a-z/set-consistency-group-attributes.html 
sidebar: sidebar 
keywords: set, consistency, group, attributes 
summary: set consistencyGroupコマンドは、Snapshot整合性グループのプロパティを定義します。 
---
= 整合性グループの属性を設定する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set consistencyGroupコマンドは'スナップショット・コンシステンシ・グループのプロパティを定義します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
set consistencyGroup pass:quotes[["_consistencyGroupName_"]]
[userLabel=pass:quotes["_consistencyGroupName_"]]
[repositoryFullPolicy=(failBaseWrites | purgeSnapImages)]
[repositoryFullLimit=pass:quotes[_percentValue_]]
[autoDeleteLimit=pass:quotes[_numberOfSnapImages_]]
[rollbackPriority=(lowest | low | medium | high | highest)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「consistencyGroupName」
 a| 
プロパティを設定する整合性グループの名前。整合性グループ名は、二重引用符（""）で囲んだ上で角かっこ（[]）で囲みます。



 a| 
「userLabel」のように入力します
 a| 
Snapshot整合性グループに付ける新しい名前。新しい整合性グループ名は二重引用符（""）で囲みます。



 a| 
repositoryFullPolicy
 a| 
Snapshotリポジトリボリュームの容量が上限に達している場合にSnapshot処理をどのように続行するかを指定します。ベースボリュームへの書き込みを停止する（failBaseWrites）か、Snapshotイメージを削除（パージ）する（purgeSnapImages）かを選択できます。デフォルトのアクションはpurgeSnapImagesです



 a| 
repositoryFullLimit
 a| 
リポジトリの容量がこの割合に達すると、Snapshotリポジトリボリュームの上限に近づいているという警告が表示されます。整数値を使用します。たとえば、70という値は70%を意味します。デフォルト値は75です。



 a| 
'autoDeleteLimit'
 a| 
各整合性グループでは、Snapshotイメージの自動削除を実行して、グループ内のSnapshotイメージの総数を指定したレベル以下に保つように設定できます。このオプションを有効にすると、Snapshotグループ内に新しいSnapshotイメージが作成されるたびに、制限値に準拠するためにグループ内の最も古いSnapshotイメージが自動的に削除されます。この処理によってリポジトリ容量が解放されて、残りのSnapshotイメージに対するcopy-on-write要求に使用できるようになります。



 a| 
「rollBackPriority」を参照してください
 a| 
ストレージアレイが稼働しているときの整合性グループのロールバック処理の優先度。有効な値は'highest'high`'high`'medium`'low''low'lowest`です

|===


== 注：

名前には、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。名前の最大文字数は30文字です。

このコマンドではパラメータを1つ以上指定できます。ただし、すべてのパラメータを使用する必要はありません。

ロールバックの優先度によって、システムパフォーマンスを考慮せずにロールバック処理に割り当てるシステムリソースの量が決まります。値がHighの場合は'ロールバック・オペレーションが他のすべてのホストI/Oより優先されることを示します値が'low'の場合'ホストI/Oへの影響を最小限に抑えてロールバック操作を実行する必要があります



== 自動削除

各SnapshotグループでSnapshotイメージの自動削除を実行して、グループ内のSnapshotイメージの総数を指定したレベル以下に保つように設定できます。Snapshotグループ内のSnapshotイメージの数が上限に達すると、「autoDeleteLimit」パラメータは、Snapshotグループ内に新しいSnapshotイメージが作成されるたびにSnapshotイメージを自動的に削除します。autoDeleteLimitパラメータは、パラメータで定義されたイメージの最大数に達するまで、Snapshotグループ内の最も古いSnapshotイメージを削除します。このようにSnapshotイメージが削除されることでリポジトリ容量が解放されて、残りのSnapshotイメージに対するcopy-on-write要求に使用できるようになります。



== 最小ファームウェアレベル

7.83
