---
permalink: commands-a-z/set-hostport.html 
sidebar: sidebar 
keywords: set, host, port 
summary: set HostPortコマンドは、ホストポートのプロパティを変更します。 
---
= ホストポートを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set HostPortコマンドは'ホスト・ポートのプロパティを変更します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
iSCSI環境では、ホストポートがイニシエータとみなされるため、このコマンドは機能しません。代わりに'set iscsiInitiatorコマンドを使用しますを参照してください xref:set-iscsiinitiator.adoc[iSCSIイニシエータを設定する]。

====


== 構文

[listing, subs="+macros"]
----
set hostPort pass:quotes[[_portLabel_]] userLabel=pass:quotes[_newPortLabel_]
[host=pass:quotes[_hostName_]]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ホストポート」
 a| 
ホストタイプを変更するホストポートの名前、または新しい名前を作成するホストポートの名前。ホストポート名は角かっこ（[]）で囲みます。ホストポート名に特殊文字または数字が含まれている場合は、ホストポート名を二重引用符（""）で囲んだ上で角かっこで囲みます。



 a| 
「userLabel」のように入力します
 a| 
ホストポートに付ける新しい名前。ホストポートの新しい名前は二重引用符（""）で囲みます。



 a| 
ホスト
 a| 
HBAまたはHCAホストポートを定義するホストの名前。ホスト名は二重引用符（""）で囲みます。

|===


== 注：

ユーザラベルには、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。ユーザラベルの最大文字数は30文字です。



== 最小ファームウェアレベル

6.10
