---
permalink: commands-a-z/set-controller-iscsihostport.html 
sidebar: sidebar 
keywords: set, iscsi, host, port, network, properties 
summary: set controller iscsiHostPortコマンドは、ホストポートのネットワークプロパティ（IPv4およびIPv6のプロパティ、ポート速度、最大フレームペイロードなど）を変更します。 
---
= iSCSIのホストポートのネットワークプロパティを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set controller iscsiHostPortコマンドは'IPv4とIPv6のプロパティ'ポート速度'最大フレームペイロードなど'ホストポートのネットワーク・プロパティを変更します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。

[NOTE]
====
このコマンドは廃止され、で置き換えられました xref:set-controller-hostport.adoc[コントローラのホストポートのプロパティを設定します] コマンドを実行します

====


== 構文

[source, cli]
----
set controller [(a|b)]
iscsiHostPort [portLabel]
----
[source, cli]
----
([IPv4Address=(0-255).(0-255).(0-255).(0-255) ]|
----
[source, cli]
----
[IPv6LocalAddress=(0-FFFF):(0-FFFF):(0-FFFF):(0-FFFF): (0-FFFF):(0-FFFF):(0-FFFF):(0-FFFF)] |
----
[source, cli]
----
[IPv6RoutableAddress=(0-FFFF):(0-FFFF):(0-FFFF):(0-FFFF): (0-FFFF):(0-FFFF):(0-FFFF):(0-FFFF) ]|
----
[source, cli]
----
[IPv6RouterAddress=(0-FFFF):(0-FFFF):(0-FFFF):(0-FFFF): (0-FFFF):(0-FFFF):(0-FFFF):(0-FFFF) ]|
----
[source, cli]
----
[enableIPv4=(TRUE | FALSE) | enableIPv6=(TRUE | FALSE)] |
----
[source, cli]
----
[enableIPv4Vlan=(TRUE | FALSE) | enableIPv6Vlan=(TRUE | FALSE)] |
----
[source, cli]
----
[enableIPv4Priority=(TRUE | FALSE) | enableIPv6Priority=(TRUE | FALSE) ]|
----
[source, cli]
----
[IPv4ConfigurationMethod=(static | dhcp) ]|
----
[source, cli]
----
[IPv6ConfigurationMethod=(static | auto)] |
----
[source, cli]
----
[IPv4GatewayIP=(TRUE | FALSE)] |
----
[source, cli]
----
[IPv6HopLimit=[0-255] ]|
----
[source, cli]
----
[IPv6NdDetectDuplicateAddress=[0-256] ]|
----
[source, cli]
----
[IPv6NdReachableTime=[0-65535] ]|
----
[source, cli]
----
[IPv6NdRetransmitTime=[0-65535]] |
----
[source, cli]
----
[IPv6NdTimeOut=[0-65535] ]|
----
[source, cli]
----
[IPv4Priority=[0-7] | IPv6Priority=[0-7] ]|
----
[source, cli]
----
[IPv4SubnetMask=(0-255).(0-255).(0-255).(0-255)] |
----
[source, cli]
----
[IPv4VlanId=[1-4094] | IPv6VlanId=[1-4094]] |
----
[source, cli]
----
[maxFramePayload=[*frameSize*]] |
----
[source, cli]
----
[tcpListeningPort=[3260, 49152-65536] ]|
----
[source, cli]
----
[portSpeed=[(10 | 25)]])
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「enableIPV4」と入力します
 a| 
次のオプションがあります。

* 正しいです
* いいえ




 a| 
enableIPV4Priority
 a| 
ネットワークアクセスの優先度を決定するパラメータを有効にする場合は、このオプションを選択します。スライダを使用して優先度を 1 から 7 の間で選択します。

共有 LAN 環境（イーサネットなど）では、多数のステーションがネットワークアクセスで競合する可能性があります。アクセスは先に行われたものから順に処理されます。2 つのステーションが同時にネットワークにアクセスしようとすると、両方のステーションがオフになり、再試行するまで待機します。スイッチイーサネットでは、 1 つのステーションだけがスイッチポートに接続されるため、このプロセスは最小限に抑えられます。

次のオプションがあります。

* 正しいです
* いいえ


[NOTE]
====
このパラメータはNVMe over RoCE環境ではサポートされていません。

====


 a| 
enableIPV4Vlan
 a| 
VLAN は、同じスイッチ、同じルータ、またはその両方でサポートされる他の物理 LAN （ローカルエリアネットワーク）および仮想 LAN から物理的に分離されたように動作する論理ネットワークです。次のオプションがあります。

* 正しいです
* いいえ


[NOTE]
====
このパラメータはNVMe over RoCE環境ではサポートされていません。

====


 a| 
「enableIPV6」
 a| 
IPv6アドレススペースは128ビットです。コロンで区切られた8つの16ビット16進ブロックで表されます。

次のオプションがあります。

* 正しいです
* いいえ




 a| 
enableIPV6Priority
 a| 
ネットワークアクセスの優先度を決定するパラメータを有効にする場合は、このオプションを選択します。スライダを使用して優先度を 1 から 7 の間で選択します。

共有 LAN 環境（イーサネットなど）では、多数のステーションがネットワークアクセスで競合する可能性があります。アクセスは先に行われたものから順に処理されます。2 つのステーションが同時にネットワークにアクセスしようとすると、両方のステーションがオフになり、再試行するまで待機します。スイッチイーサネットでは、 1 つのステーションだけがスイッチポートに接続されるため、このプロセスは最小限に抑えられます。

次のオプションがあります。

* 正しいです
* いいえ


[NOTE]
====
このパラメータはNVMe over RoCE環境ではサポートされていません。

====


 a| 
enableIPV6Vlan
 a| 
VLAN は、同じスイッチ、同じルータ、またはその両方でサポートされる他の物理 LAN （ローカルエリアネットワーク）および仮想 LAN から物理的に分離されたように動作する論理ネットワークです。

次のオプションがあります。

* 正しいです
* いいえ


[NOTE]
====
このパラメータはNVMe over RoCE環境ではサポートされていません。

====


 a| 
「ipv4address」と入力します
 a| 
次の形式でアドレスを入力します：（0-255）.（0-255）.（0-255）.（0-255）



 a| 
「IPV4ConfigurationMethod」
 a| 
次のオプションがあります。

* 静的
* DHCP




 a| 
「IPV4GatewayIP」
 a| 
次のオプションがあります。

* 正しいです
* いいえ




 a| 
「IPV4Priority」
 a| 
0~7の値を入力します。

[NOTE]
====
このパラメータはNVMe over RoCE環境ではサポートされていません。

====


 a| 
「IPV4SubnetMask」
 a| 
次の形式でサブネットマスクを入力します：（0-255）.（0-255）.（0-255）.（0-255）



 a| 
「IPV4VlanId」
 a| 
1~4094の値を入力します。

[NOTE]
====
このパラメータはNVMe over RoCE環境ではサポートされていません。

====


 a| 
IPV6ConfigurationMethod
 a| 
次のオプションがあります。

* 静的
* 自動




 a| 
「IPV6HopLimit」
 a| 
このオプションは、IPv6パケットが経由できるホップの最大数を設定します。

デフォルト値は「64」です。



 a| 
「IPV6LocalAddress」と入力します
 a| 
次の形式でアドレスを入力します：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）



 a| 
「IPV6NdDetectDuplicateAddress」と入力します
 a| 
0~256の値を入力します。



 a| 
「IPV6NdReachableTime」
 a| 
このオプションは、リモートIPv6モードが到達可能とみなされる時間を設定します。0~65535の値をミリ秒で指定します。

デフォルト値は30000ミリ秒です。



 a| 
「IPV6NdransmitTime」
 a| 
このオプションは、IPv6ノードにパケットを再送信し続ける時間を設定します。0~65535の値をミリ秒で指定します。

デフォルト値は「1000`milliseconds」です。



 a| 
「IPV6NdTimeOut」
 a| 
このオプションは、IPv6ノードのタイムアウト値を設定します。0~65535の値をミリ秒で指定します。

デフォルト値は30000ミリ秒です。



 a| 
「IPV6Priority」
 a| 
0~7の値を入力します。

[NOTE]
====
このパラメータはNVMe over RoCE環境ではサポートされていません。

====


 a| 
「IPV6RoutableAddress」
 a| 
次の形式でアドレスを入力します：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）



 a| 
「IPV6RouterAddress」
 a| 
次の形式でアドレスを入力します：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）：（0-FFFF）



 a| 
「IPV6VlanId」
 a| 
1~4094の値を入力します。

[NOTE]
====
このパラメータはNVMe over RoCE環境ではサポートされていません。

====


 a| 
maxFramePayload
 a| 
「maxFramePayload」オプションはIPv4とIPv6で共有され、ネットワークで送信できる最大のパケットまたはフレームです。標準イーサネット・フレームのペイロード部分は1500に設定され、ジャンボ・イーサネット・フレームは9000に設定されます。ジャンボフレームを使用している場合は、ネットワークパス内のすべてのデバイスが大きなフレームサイズを処理できる必要があります。

デフォルト値は1500バイト/フレームです。1500~9000 の値を入力する必要があります。



 a| 
「portSpeed」
 a| 
次のオプションがあります。

* 10.
* 25


[NOTE]
====
このオプションは、25Gb/sイーサネットホストインターフェイスカードでのみ有効です。1つのポートの速度を変更すると、カード上の4つのポートすべての速度が変更されます。

====
[NOTE]
====
iscsiHostPortパラメータのportSpeedオプションの値は'メガビット/秒（Mb/s）単位です

====


 a| 
tcpListeningPort
 a| 
リスニングポートは、コントローラがホスト iSCSI イニシエータからの iSCSI ログインをリスンするために使用する TCP ポート番号です。デフォルトのリスニングポートは 3260 です。3260 、または 49152~65535 の値を入力する必要があります。

|===


== iSCSIホストポートラベルの特定

ホストポートのラベルを指定する必要があります。ホストポートのラベルを指定する手順は、次のとおりです。

. iSCSIホスト・ポートのポート・ラベルがわからない場合は、「show controller」コマンドを実行します。
. 結果のHost interfaceセクションで、選択するホストポートを特定します。
+
[NOTE]
====
ポート・ラベルは'Port'フィールドに返される完全な値です

====
. ポートラベルの値全体を引用符と角かっこで囲みます。["portLabel"]たとえば、ポートラベルが「Ch 2」の場合は、iSCSIホストポートを次のように指定します。
+
[listing]
----
iscsiHostPort[\"ch 2\"]
----
+
[NOTE]
====
Windowsのコマンドラインを使用していて、ラベルにパイプ（|）が含まれている場合は、文字をエスケープする必要があります（｛キャレット｝を使用）。エスケープしない場合は、コマンドと解釈されます。たとえば、ポートラベルが「e0b|0b'」の場合は、iSCSIホストポートを次のように指定します。

====
+
[listing]
----
iscsiHostPort[\"e0b^|0b\"]
----


[NOTE]
====
下位互換性のために、引用符と角かっこではなく角かっこ[]で囲まれているiscsiPortNumberも、引き続きE2700、E5600、EF560の各コントローラ（およびEシリーズまたはEFシリーズの他の旧世代コントローラ）に使用できます。これらのコントローラでは、iscsiPortNumberの有効な値は次のとおりです。

* ホストポートが統合されたコントローラの場合、番号は3、4、5、または6です。
* ホストインターフェイスカード上にのみホストポートがあるコントローラの場合、番号は1、2、3、または4です。


以前の構文の例を次に示します。

[listing]
----
iscsiHostPort[3]
----
====


== 最小ファームウェアレベル

7.15で、新しいiSCSIホストポートオプションが追加されました。

7.60で'portSpeed'オプションが追加されました

8.10で、iSCSIホストポートの識別方法が改定されました。

8.40で、「iscsiHostPort」パラメータの「portSpeed」オプションが改定されました。これは25Gb/sイーサネットホストインターフェイスカードでのみ有効であり、1つのポートの速度を変更するとカード上の4つのポートすべての速度が変更されることに注意してください。

8.41で、このコマンドは廃止されました。
