---
permalink: commands-a-z/set-autosupport-https-delivery-method-e2800-e5700.html 
sidebar: sidebar 
keywords: 'Specify AutoSupport HTTP(S) delivery method (for individual E2800 or E5700 arrays)' 
summary: set storageArray AutoSupport httpdeliveryMethodコマンドは、AutoSupport メッセージをHTTP（S）に送信するための配信方法を設定します。 
---
= AutoSupport HTTP（S）配信方法の指定（個々のE2800またはE5700アレイ）
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set storageArray AutoSupport httpdeliveryMethodコマンドは、AutoSupport メッセージをHTTP（S）に送信するための配信方法を設定します。



== サポートされているアレイ

このコマンドは、E2800、E5700、EF600、またはEF300の個々のストレージアレイを環境 します。E2700またはE5600のストレージアレイに対しては機能しません。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== 構文

[listing, subs="+macros"]
----

set storageArray autoSupport deliveryMethod={HTTP | HTTPS}
   {direct | proxyConfigScript=pass:quotes["_proxyConfigScriptUrl_"] |
proxyServer hostAddress=pass:quotes[_address_] portNumber=pass:quotes[_portNumber_]
 [userName=pass:quotes["_username_"] password=pass:quotes["_password_"]]}
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「deliveryMethod」を参照してください
 a| 
AutoSupport による収集の配信方法を指定できます。有効な選択肢は次のとおりです。

* E メール
* HTTP
* HTTPS


[NOTE]
====
Eメール方式が設定されている場合、AutoSupport OnDemandとRemote Diagnosticsは無効になります。

====


 a| 
「直接」
 a| 
HTTPまたはHTTPSプロトコルを使用して、テクニカルサポートのシステムに直接接続できます。



 a| 
proxyConfigScript
 a| 
Proxy Auto-Configuration（PAC）スクリプトファイルの場所を指定できます



 a| 
proxyServer
 a| 
テクニカルサポートシステムとの接続を確立するために必要なHTTP（S）プロキシサーバの詳細を指定できます。



 a| 
「ホストアドレス」
 a| 
プロキシサーバのホストアドレスを指定できます。proxyServerを指定する場合は必須です。



 a| 
「portNumber」と入力します
 a| 
プロキシサーバのポート番号を指定できます。proxyServerを指定する場合は必須です。



 a| 
「ユーザ名」
 a| 
プロキシサーバのユーザ名が設定されている場合、そのユーザ名を指定できます。



 a| 
「 password 」と入力します
 a| 
プロキシサーバのパスワードが設定されている場合、ユーザがそのパスワードを指定できます。

|===


== 最小ファームウェアレベル

8.40



== 例

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP direct;"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP
proxyConfigScript=\"http://company.com/~username/proxy.pac\";"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTPS
proxyServer hostAddress=10.117.12.112 portNumber=8080 userName=\"tracyt\" password=\"1234456\";"

SMcli completed successfully.
----


== 検証

「start storageArray AutoSupport deliveryTest」コマンドを使用してテストメッセージを送信し、配信方法が正しく設定されていることを確認します。



== 最小ファームウェアレベル

8.40
