---
permalink: commands-a-z/set-volumegroup.html 
sidebar: sidebar 
keywords: set, volume, group 
summary: set volumeGroupコマンドは、ボリュームグループのプロパティを定義します。 
---
= ボリュームグループの設定 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set volumegroupコマンドは'ボリューム・グループのプロパティを定義します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
1つのコマンドで実行できる処理（ドライブの追加、RAIDレベルの変更、またはボリュームグループ所有権の変更）は1つだけです。1つのコマンドで複数の処理を実行することはできません。

====


== 構文

[source, cli, subs="+macros"]
----
set volumeGroup pass:quotes[[_volumeGroupName_]]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]) ]|
[raidLevel=(0 | 1 | 3 | 5 | 6) ]|
[owner=(a|b)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「volumeGroup」のように指定します
 a| 
プロパティを設定するボリュームグループの名前。ボリュームグループ名は角かっこ（[]）で囲みます。



 a| 
「addDrives」を参照してください
 a| 
ボリュームグループに追加するドライブの場所。大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
raidLevel
 a| 
ボリュームグループのRAIDレベル。有効な値は'0`'1' 3`'5`または'6`です



 a| 
「owner」をクリックします
 a| 
ボリュームグループを所有するコントローラ。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラですこのパラメータは、ボリュームグループの所有者を変更する場合にのみ使用します。

|===


== 注：

ボリューム数が32を超えるボリュームグループでは、ホストI/Oエラーが発生する可能性があります。また、ボリュームグループ定義が設定される前にタイムアウト時間が終了したために、内部コントローラのリブートが発生する場合もあります。この問題 が表示された場合は、ホストI/O処理を休止し、もう一度コマンドを実行します。

このコマンドではパラメータを1つしか指定できません。

[NOTE]
====
'addDrives'パラメータまたは'raidLevel'パラメータを指定すると'長時間実行される処理が開始され'停止することはできません

====
'addDrives'パラメータは'大容量ドライブ・トレイと小容量ドライブ・トレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。



== トラブルシューティング

ドライブを追加して大容量のボリュームグループを拡張しようとすると、Dynamic Capacity Expansion（DCE；動的容量拡張）とも呼ばれ、処理に失敗する場合があります。次のメッセージが表示されます。

リターン・コード：エラー26 -ボリューム・グループ内のドライブ数と関連ボリュームのセグメント・サイズが原因で、変更処理を完了できません。セグメントサイズの変更オプションを使用して、ボリュームグループ内のすべてのボリュームのセグメントサイズを128KB以下に縮小します。次に'操作を再試行します

7.35.xx.xxファームウェアを実行するシステムでは、上記のメッセージではなく次のメッセージが表示されて処理が失敗する場合があります。

リターン・コード:エラー462 -ファームウェアが十分なキャッシュ・メモリを割り当てられなかったため'SYMBOL手順 を実行できませんでしたエラー発生時の操作：proc_startVolum

上記のメッセージに加えて、DCE処理を実行するための十分なキャッシュがないことを通知するメジャーイベントログ（MEL）イベントが発生する場合があります。

この問題は、7.xxファームウェアを実行しているコントローラで発生する可能性があります。

DCEを実行するには、元のボリュームから読み取られたデータと拡張後のボリュームに書き込まれるデータをバッファするための十分なメモリが必要です。拡張処理でのドライブ数、ストライプサイズ、およびミラー処理が有効かどうかという要因の組み合わせによっては、DCE処理を実行するためのメモリが不足することがあります。

上記の状況が発生した場合は、次の方法で対処できます。

* 他の未割り当てのドライブを使用して必要なサイズのボリュームグループを作成します。
* 現在のボリュームグループを削除し、必要な数のドライブでボリュームグループを再作成します。
* 使用するセグメントサイズを縮小して処理を再試行してください。
* 可能であれば、コントローラにメモリを追加してから、処理を再試行してください。




== 最小ファームウェアレベル

7.10で、RAID 6機能が追加されました。

7.30で'availability'パラメータが削除されました

7.60で'drawerID'ユーザ入力が追加されました
