---
permalink: commands-a-z/set-syslog.html 
sidebar: sidebar 
keywords: configure, syslog, set 
summary: set syslogコマンドは、syslogアラート情報を設定します。アラート対象のイベントが発生するたびにsyslogサーバにアラートを送信するように、イベントモニタを設定できます。 
---
= Syslog設定を構成する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set syslog'コマンドは'syslogアラート情報を設定しますアラート対象のイベントが発生するたびにsyslogサーバにアラートを送信するように、イベントモニタを設定できます。



== サポートされているアレイ

このコマンドは、E4000、E2800、E5700、EF600、またはEF300の個 々 のストレージアレイに適用されます。E2700またはE5600のストレージアレイに対しては機能しません。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

* syslogサーバのアドレスを確認しておく必要があります。このアドレスは、完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスのいずれかで指定できます。
* syslogサーバのUDPポート番号を確認しておく必要があります。通常は514です。




== 構文

[source, cli, subs="+macros"]
----
set syslog [defaultFacility=pass:quotes[_facilityNumber_]]
| [defaultTag=pass:quotes[_defaultTag_]]
| [syslogFormat=pass:quotes[_rfc3164_|_rfc5424_]]
| (serverAddresses=pass:quotes[(_serverAddress:portNumber ... serverAddress:portNumber_)]
| addServerAddresses=pass:quotes[(_serverAddress:portNumber ... serverAddress:portNumber_))]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「defaultFacility」
 a| 
任意。デフォルトのファシリティ番号を指定できます。デフォルトのファシリティは、0~23の数値で指定します。



 a| 
defaultTag
 a| 
任意。デフォルトのタグを指定できます。文字列は引用符で囲みます。



 a| 
'syslogFormat'
 a| 
syslogメッセージに使用されるメッセージング形式。次のいずれかの値を指定できます。

* rfc3164`- RFC 3164準拠フォーマット
* rfc5424`- RFC 5424準拠のフォーマット




 a| 
「serverAddresses」と入力します
 a| 
1つ以上のsyslogサーバアドレスを、関連付けられているポート番号とともに設定できます。この設定オプションを使用すると、既存のサーバアドレスが消去されます。syslogサーバのアドレスには、完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスを使用できます。UDPポートは、0~65535の数値で指定します。通常は、syslogのUDPポートは514です。すべてのアドレスをかっこで囲みます。複数のアドレスを入力する場合は、それぞれスペースで区切ります。



 a| 
「addServerAddresses」と入力します
 a| 
1つ以上のsyslogサーバアドレスを、関連付けられているポート番号とともに追加できます。この設定オプションを使用しても、既存のサーバアドレスは消去されません。syslogサーバのアドレスには、完全修飾ドメイン名、IPv4アドレス、またはIPv6アドレスを使用できます。UDPポートは、0~65535の数値で指定します。通常は、syslogのUDPポートは514です。すべてのアドレスをかっこで囲みます。複数のアドレスを入力する場合は、それぞれスペースで区切ります。

|===


== 例

[listing]
----

SMcli -n Array1 -c "set syslog serverAddresses=("ICTM1402S02H2.company.com:22");"

SMcli -n Array1 -c "set syslog addServerAddresses=("serverName1.company.com:514"
"serverName2.company.com:514");"

SMcli completed successfully.
----


== 最小ファームウェアレベル

8.40

11.70.1では、syslogメッセージ形式を指定するための「syslogFormat」パラメータが追加されました。
