---
permalink: commands-a-z/set-snmpuser-username.html 
sidebar: sidebar 
keywords: update, snmpv3, usm, user 
summary: set snmpUser usernameコマンドを実行すると、既存の簡易ネットワーク管理プロトコル（SNMP）USMユーザが更新されます。ユーザ名を持つユーザが1人だけの場合は、変更するUSMユーザがユーザ名で識別されます。ユーザ名とエンジンIDが同じでないユーザが複数ある場合、そのユーザはユーザ名とエンジンIDで識別されます。 
---
= SNMPv3 USMユーザを更新します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set snmpUser usernameコマンドは、既存の簡易ネットワーク管理プロトコル（SNMP）USMユーザを更新します。ユーザ名を持つユーザが1人だけの場合は、変更するUSMユーザがユーザ名で識別されます。ユーザ名とエンジンIDが同じでないユーザが複数ある場合、そのユーザはユーザ名とエンジンIDで識別されます。



== サポートされているアレイ

このコマンドは、E2800、E5700、EF600、またはEF300の個々のストレージアレイを環境 します。E2700またはE5600のストレージアレイに対しては機能しません。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== 構文

[listing]
----
set snmpUser userName="snmpUserName" [engineId=(local | engineId)]
[newUserName="newSnmpUserName"] [newEngineId=(local | engineId)]
[authProtocol=(none | sha | sha256 | sha512) authPassword="authPassword"]
[privProtocol=(none | aes128) privPassword="privPassword"]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ユーザ名」
 a| 
更新するSNMP USMユーザの名前。SNMP USMユーザ名を二重引用符（""）で囲みます。



 a| 
「engineID」
 a| 
更新するSNMP USMユーザのエンジンID。同じユーザ名を使用するUSMユーザが複数ある場合は、エンジンIDが必要です。ローカルSNMPエージェントを指定する値は'local'である場合もあれば'リモートSNMPエージェントエンジンIDを指定するための16進数の数値文字列である場合もあります



 a| 
「newSnmpUserName」を選択します
 a| 
SNMPユーザに付ける新しい名前。SNMPユーザ名は二重引用符（""）で囲みます。デフォルト値は、ユーザに対して以前に定義されたユーザ名です。



 a| 
「newEngineId」
 a| 
ユーザの信頼できるSNMPエンジンIDの識別子として使用する新しいエンジンID。ローカルSNMPエージェントを権限のあるエージェントに指定する場合は「[.code] local」、リモートSNMPエージェントエンジンIDを指定する場合は16進数の文字列を指定する場合は「[.code] local」となります。デフォルト値は、ユーザに対して以前に定義されたエンジンIDです。



 a| 
「authProtocol」
 a| 
ユーザに使用するHMAC（認証プロトコル）。次のいずれかの値を指定できます。

* 'none'- SNMPメッセージの認証なし（デフォルト）
* sha`SHA-1認証
* 「SHA256」-SHA-256認証を使用します
* 「SHA512`-SHA-512認証」を参照してください


デフォルト値は、ユーザに対して以前に定義された認証プロトコルです。



 a| 
「authPassword」
 a| 
ユーザの認証に使用するパスワード。認証プロトコルがSHA、SHA256、またはSHA512'の場合に指定する必要があります



 a| 
「プライベートプロトコル」
 a| 
ユーザに使用されるプライバシープロトコル（暗号化）。次のいずれかの値を指定できます。

* 'none'- SNMPメッセージの暗号化なし（デフォルト）
* `aes128`-aes-18暗号化


デフォルト値は、ユーザに対して以前に定義されたプライバシープロトコルです。



 a| 
「プライベートパスワード」
 a| 
ユーザのプライバシー/暗号化に使用するパスワード。プライバシープロトコルが「[.code]`aes128`」の場合は、この値を指定する必要があります。

|===


== 最小ファームウェアレベル

8.72
