---
permalink: commands-a-z/set-storagearray-securitykey.html 
sidebar: sidebar 
keywords: set, internal, storage, array, security key 
summary: set storageArray securityKeyコマンドは、ドライブセキュリティ機能を実装するためにストレージアレイ全体で使用されるセキュリティキーを設定します。 
---
= 内部ストレージアレイのセキュリティキーを設定する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set storageArray securityKeyコマンドは、ドライブセキュリティ機能を実装するためにストレージアレイ全体で使用されるセキュリティキーを設定します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Security Adminロールが必要です。



== コンテキスト（Context）

ストレージアレイ内のセキュリティ対応ドライブをセキュリティ保護されたボリュームグループまたはディスクプールに割り当てると、そのドライブはセキュリティキーを使用してセキュリティ有効ドライブになります。セキュリティキーを設定する前に、「create storageArray securityKey」コマンドを使用してセキュリティキーを作成する必要があります。

[NOTE]
====
このコマンドは、内部キー管理にのみ適用されます。

====


== 構文

[source, cli]
----
set storageArray securityKey
----


== パラメータ

なし



== 注：

セキュリティ対応ドライブには暗号化処理を高速化するハードウェアが搭載されており、それぞれに固有のドライブキーがあります。セキュリティ対応ドライブは、セキュリティ保護されたボリュームグループに追加されるまで他のドライブと同じように動作し、追加された時点でセキュリティ有効ドライブになります。

セキュリティ有効ドライブは、電源がオンになるたびにコントローラから正しいセキュリティキーを取得する必要があり、取得するまではデータの読み取りや書き込みを実行できません。つまり、セキュリティ有効ドライブは2つのキーを使用します。1つはデータの暗号化と復号化を行うドライブキー、もう1つは暗号化プロセスと復号化プロセスを許可するセキュリティキーです。set storageArray securityKeyコマンドは'ストレージ・アレイ内のすべてのコントローラとセキュリティ対応ドライブにセキュリティ・キーをコミットしますFull Disk Encryption機能により、セキュリティ有効ドライブがストレージアレイから物理的に取り外された場合、セキュリティキーがわからないかぎりそのドライブのデータを他のデバイスから読み取ることはできません。



== 最小ファームウェアレベル

7.50
