---
permalink: commands-a-z/set-tray-identification.html 
sidebar: sidebar 
keywords: set, tray, identification 
summary: set trayコマンドは、ストレージアレイ内のコントローラトレイ、コントローラドライブトレイ、またはドライブトレイのトレイIDを設定します。 
---
= トレイIDを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set trayコマンドは'ストレージ・アレイ内のコントローラ・トレイ'コントローラ・ドライブ・トレイ'またはドライブ・トレイのトレイIDを設定します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドは、トレイIDをコントローラファームウェアから設定可能なコントローラトレイ、コントローラドライブトレイ、またはドライブトレイにのみ有効です。トレイIDをスイッチで設定するコントローラトレイ、コントローラドライブトレイ、またはドライブトレイには使用できません。



== 構文

[source, cli, subs="+macros"]
----
set tray pass:quotes[["_serialNumber_"]] pass:quotes[id=_trayID_]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「tray」
 a| 
トレイIDを設定するコントローラトレイ、コントローラドライブトレイ、またはドライブトレイのシリアル番号。シリアル番号には、英数字を任意に組み合わせて指定できます。文字数に制限はありません。シリアル番号は二重引用符（""）で囲みます。



 a| 
「 id` 」
 a| 
コントローラトレイ、コントローラドライブトレイ、またはドライブトレイのトレイIDの値。トレイIDの値は'0'~'9'または'10'~'99'です

[NOTE]
====
DE5600、DE1600、DE6600の各エンクロージャの場合は、シリアル番号の前にテキスト「SN」とスペースを付加します。たとえば、「SN SV23802522」と入力します。

====
[NOTE]
====
トレイIDの値はかっこで囲む必要はありません。

====
[NOTE]
====
「00」から「09」までのトレイ値は、コントローラによって拒否されます。これらの値を指定するには'0～9を使用します

====
|===


== 注：

このコマンドは、当初CE6998コントローラトレイをサポートしていましたCE6998シリーズのコントローラトレイはさまざまなドライブトレイに接続でき、これにはトレイIDがスイッチで設定されるドライブトレイも含まれます。CE6998シリーズのコントローラトレイをスイッチで設定されたトレイに接続する場合、コントローラトレイの有効なトレイID値は「80~99」です。これにより、接続されたドライブトレイのトレイIDとの競合を回避できます。
