---
permalink: commands-a-z/set-autosupport-https-delivery-method.html 
sidebar: sidebar 
keywords: 'Specify AutoSupport HTTP(S) delivery method' 
summary: set storageArray AutoSupport httpdeliveryMethodコマンドは、AutoSupport メッセージをHTTP（S）に送信するための配信方法を設定します。 
---
= AutoSupport HTTP(S)配信方法を指定する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set storageArray AutoSupport httpdeliveryMethodコマンドは、AutoSupport メッセージをHTTP（S）に送信するための配信方法を設定します。



== サポートされているアレイ

このコマンドは、E4000、E2800、E5700、EF600、またはEF300の個 々 のストレージアレイに適用されます。E2700またはE5600のストレージアレイに対しては機能しません。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----

set storageArray autoSupport deliveryMethod=email mailRelayServer="mail.example.com" senderEmail="sender@example.com"
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「deliveryMethod」を参照してください
 a| 
AutoSupport による収集の配信方法を指定できます。有効な選択肢は次のとおりです。

* E メール
* HTTPS


[NOTE]
====
Eメール方式が設定されている場合、AutoSupport OnDemandとRemote Diagnosticsは無効になります。

====


 a| 
「直接」
 a| 
HTTPまたはHTTPSプロトコルを使用して、テクニカルサポートのシステムに直接接続できます。



 a| 
proxyConfigScript
 a| 
Proxy Auto-Configuration（PAC）スクリプトファイルの場所を指定できます



 a| 
proxyServer
 a| 
テクニカルサポートシステムとの接続を確立するために必要なHTTP（S）プロキシサーバの詳細を指定できます。



 a| 
「ホストアドレス」
 a| 
プロキシサーバのホストアドレスを指定できます。proxyServerを指定する場合は必須です。



 a| 
「portNumber」と入力します
 a| 
プロキシサーバのポート番号を指定できます。proxyServerを指定する場合は必須です。



 a| 
「ユーザ名」
 a| 
プロキシサーバのユーザ名が設定されている場合、そのユーザ名を指定できます。



 a| 
「 password 」と入力します
 a| 
プロキシサーバのパスワードが設定されている場合、ユーザがそのパスワードを指定できます。

|===


== 最小ファームウェアレベル

8.40



== 例

[listing]
----

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP direct;"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTP
proxyConfigScript=\"http://company.com/~username/proxy.pac\";"

SMcli -n Array1 -c "set storageArray autoSupport deliveryMethod=HTTPS
proxyServer hostAddress=10.117.12.112 portNumber=8080 userName=\"tracyt\" password=\"1234456\";"

SMcli completed successfully.
----


== 検証

「start storageArray AutoSupport deliveryTest」コマンドを使用してテストメッセージを送信し、配信方法が正しく設定されていることを確認します。



== 最小ファームウェアレベル

8.40
