---
permalink: commands-a-z/set-storagearray-controllerhealthimageallowoverwrite.html 
sidebar: sidebar 
keywords: set, storage, array, controller, health, image, allow, overwrite 
summary: set storageArray controllerHealthImageAllowOverWriteコマンドは、コントローラヘルスイメージ機能をサポートするストレージアレイで、新しいコントローラヘルスイメージによる既存のコントローラヘルスイメージの上書きを許可するフラグをコントローラに設定します。 
---
= ストレージアレイコントローラのヘルスイメージの上書きを許可する設定 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set storageArray controllerHealthImageAllowOverWriteコマンドは、コントローラヘルスイメージ機能をサポートするストレージアレイで、新しいコントローラヘルスイメージによって既存のコントローラヘルスイメージが上書きされるようにするフラグをコントローラに設定します。



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

ストレージアレイがコントローラヘルスイメージ機能をサポートしていない場合、コマンドはエラーを返します。

[NOTE]
====
ファームウェア・バージョン8.20で'coreDumpAllowOverWriteパラメータが'controllerHealthImageAllowOverWriteパラメータに置き換えられました

====


[[syntax]]
== 構文

[source, cli]
----
set storageArray controllerHealthImageAllowOverWrite
----


[[parameters]]
== パラメータ

なし



[[notes]]
== 注：

コントローラヘルスイメージが取得されると、「allow overwrite」フラグが設定されます。コントローラヘルスイメージが取得されない場合、イメージは48時間で期限切れになり、その後「allow overwrite」フラグが設定されます。「set storageArray controllerHealthImageAllowOverWrite」コマンドを使用して「allow overwrite」フラグを設定すると、イメージが取得された場合と同様に、48時間の期限が適用されなくなります。



[[minimum-firmware-level]]
== 最小ファームウェアレベル

7.86

8.20で'*coreDumpAllowOverWrite *'パラメータが'controllerHealthImageAllowOverWriteパラメータに置き換えられました
