---
permalink: commands-a-z/set-tray-serviceallowedindicator.html 
sidebar: sidebar 
keywords: set, tray, service, action, allowed, indicator 
summary: set tray serviceAllowedIndicatorコマンドは、電源ファンキャニスター、インターコネクトバッテリキャニスター、または環境サービスモジュール（ESM）キャニスターの保守操作可能インジケータライトをオンまたはオフにします。 
---
= トレイサービスアクション許可インジケーターの設定 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set tray serviceAllowedIndicatorコマンドは'電源ファンキャニスター'相互接続バッテリキャニスター'または環境サービスモジュール(ESM)キャニスターの保守操作可能インジケータライトをオンまたはオフにします



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== コンテキスト（Context）

ストレージアレイが保守操作可能インジケータライト機能をサポートしていない場合、このコマンドはエラーを返します。ストレージアレイがこのコマンドをサポートしていてもインジケータライトをオンまたはオフにできない場合、このコマンドはエラーを返します。

コントローラキャニスターの保守操作可能インジケータライトをオンまたはオフにするには'set controller serviceAllowedIndicatorコマンドを使用します



== 構文

[source, cli, subs="+macros"]
----
set tray pass:quotes[[_trayID_]]
(powerFan [(left | right | top | bottom)] |
interconnect |
esm [(left | right | top | bottom)]) |
battery [(left | right)] |
fanCanister [(left | right)]  |
powerCanister [(top | bottom)] |
serviceAllowedIndicator=(on | off)
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「tray」
 a| 
電源ファンキャニスター、インターコネクトキャニスター、ESMキャニスター、またはバッテリキャニスターが取り付けられているトレイ。トレイIDの値は'0～99ですトレイIDの値は角かっこ（[]）で囲みます。トレイIDの値を入力しない場合は、コントローラトレイのトレイIDがデフォルト値となります。



 a| 
「パワーファン」
 a| 
保守操作可能インジケータライトをオンまたはオフにする電源ファンキャニスター。有効な電源ファン・キャニスター識別子は'left'right'top''bottom'です電源ファンキャニスター識別子は角かっこ（[]）で囲みます。



 a| 
相互接続
 a| 
保守操作可能インジケータライトをオンまたはオフにするインターコネクトバッテリキャニスター。



 a| 
「ESM」
 a| 
保守操作可能インジケータライトをオンまたはオフにするESMキャニスター。有効なESMキャニスター識別子は'left'right'top''bottom'です



 a| 
「バッテリ」
 a| 
保守操作可能インジケータライトをオンまたはオフにするバッテリ。有効なバッテリ識別子は'left'またはrightです



 a| 
「fanCanister」の略
 a| 
保守操作可能インジケータライトをオンまたはオフにするファンキャニスター。有効なファン・キャニスター識別子は'left'またはrightです



 a| 
「パワーキャニスタ」
 a| 
保守操作可能インジケータライトをオンまたはオフにする電源キャニスター。有効な電源キャニスター識別子は'top'またはbottom'です



 a| 
「serviceAllowedIndicator」というメッセージが表示されます
 a| 
保守操作可能インジケータライトをオンまたはオフにするための設定。保守操作可能インジケータライトをオンにするには、このパラメータを「オン」に設定します。保守操作可能インジケータライトをオフにするには、このパラメータを「オフ」に設定します。

|===


== 注：

このコマンドは、CE6998コントローラトレイで使用するために定義されたコマンドですCE6998コントローラトレイの発売前に出荷されたコントローラトレイではサポートされません



== 例

次のコマンドは、IPアドレス155.155.155.155のトレイ5に取り付けられている左側のESMの保守操作可能インジケータライトをオンにします。

[listing]
----
SMcli 123.145.167.214 123.145.167.215 -c "set tray [5]
ESM [left] serviceAllowedIndicator=on;"
----


== 最小ファームウェアレベル

6.14で、次のパラメータが追加されました

* 「パワーファン」
* 相互接続


6.16で、次のパラメータが追加されました

* 「tray」
* 「ESM」


7.60で'top'とbottom'の識別子が追加されます

7.60で'powerCanisterおよびfanCanisterパラメータが追加されました
