---
permalink: commands-a-z/set-drive-hotspare.html 
sidebar: sidebar 
keywords: set, drive, hot spare 
summary: set drive hotspareコマンドは、1つ以上のドライブをホットスペアとして割り当てまたは割り当て解除します。 
---
= ドライブのホットスペアを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set drive hotspareコマンドは'1つ以上のドライブをホット・スペアとして割り当てまたは割り当て解除します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
set (drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drivespass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]])
hotSpare=(TRUE | FALSE)
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ドライブ」または「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
「ホットスペア」
 a| 
ドライブをホットスペアとして割り当てるための設定。ドライブをホット・スペアとして割り当てるには'このパラメータをTRUEに設定しますドライブからホットスペアの割り当てを削除するには'このパラメータをFALSEに設定します

|===


== 注：

'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。



== 最小ファームウェアレベル

6.10

7.60で'drawerID'ユーザ入力が追加されました
