---
permalink: commands-a-z/set-disk-pool.html 
sidebar: sidebar 
keywords: set, disk pool 
summary: set diskPoolコマンドは、指定されたパラメータに基づいてディスクプールに関連付けられた属性を設定します。 
---
= ディスクプールを設定する
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set diskPool'コマンドは'指定したパラメータに基づいてディスク・プールに関連づけられた属性を設定します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
set (diskPool pass:quotes[[_diskPoolName_]] |
diskPools pass:quotes[[_diskPoolName1_ ... _diskPoolNameN_]] | allDiskPools)
[reservedDriveCount=pass:quotes[_reservedDriveCountValue_]]
[warningThreshold=(warningThresholdValue | default)]
[criticalThreshold=(criticalThresholdValue | default)]
[criticalPriority=(highest | high | medium |low |lowest)]
[degradedPriority=(highest |high |medium |low |lowest)]
[backgroundPriority=(highest | high | medium |low |lowest)]
[userLabel=pass:quotes[_diskPoolName_]]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「diskPool」
 a| 
属性を設定するディスクプールの名前。ディスクプール名は角かっこ（[]）で囲みます。ディスクプール名が特殊文字を含んでいる場合または数字のみで構成される場合は、ディスクプール名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「diskPools」
 a| 
属性を設定する複数のディスクプールの名前。以下のルールを使用して、ディスクプールの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


ディスクプール名に特殊文字または数字が含まれる場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
「allDiskPools」
 a| 
このパラメータは、ストレージアレイ内のすべてのディスクプールの属性を設定します。



 a| 
「reservedDriveCount」
 a| 
このパラメータは、ディスクプール内のすべてのドライブに、障害ドライブの再構築のみに使用されるスペースを確保します。この数の各単位は、1つの障害ドライブをディスクプールの残りのドライブに再構築するための容量を表します。



 a| 
「warningThreshold」
 a| 
ディスクプールの容量がこの割合に達すると、ディスクプールの上限に近づいているという警告アラートが表示されます。整数値を使用します。たとえば、70という値は70%を意味します。最適な操作を行うには、このパラメータの値を「criticalThreshold」パラメータの値よりも小さくする必要があります。

有効な値は0~100です。

デフォルト値は50です。

このパラメータを「0」に設定すると、警告アラートが無効になります。

これをデフォルトに設定した場合'警告アラートのしきい値はコントローラファームウェアによって決定されます



 a| 
「criticalThreshold」です
 a| 
ディスクプールの容量がこの割合に達すると、ディスクプールの上限に近づいているという重大アラートが表示されます。整数値を使用します。たとえば、70という値は70%を意味します。最適な操作を行うには'このパラメータの値をwarningThresholdパラメータの値よりも大きくする必要があります

有効な値は0~100です。

デフォルト値は85%です。

このパラメータを「0」に設定すると、警告アラートと重大アラートの両方が無効になります。

これをデフォルトに設定した場合'クリティカル・アラートのしきい値はコントローラ・ファームウェアによって決定されます



 a| 
「criticalPriority」です
 a| 
ディスクプール上の重大イベントの再構築処理の優先度。たとえば、少なくとも2つのドライブ障害が発生したあとのディスクプールの再構築などです。

有効な値は'high`'high`'high`'medium`'low''low'lowest`ですデフォルト値は「highest」です。



 a| 
「degradedPriority」
 a| 
ディスクプールでデグレードイベントが発生した場合の再構築処理の優先度。たとえば、1つのドライブ障害が発生したあとのディスクプールの再構築などです。

有効な値は'high`'high`'high`'medium`'low''low'lowest`ですデフォルト値は'high'です



 a| 
「backgroundPriority」
 a| 
ディスクプール上のバックグラウンド処理の優先度。

有効な値は'high`'high`'high`'medium`'low''low'lowest`ですデフォルト値は'low'です



 a| 
「userLabel」のように入力します
 a| 
ディスクプールに付ける新しい名前。ディスクプール名は二重引用符（""）で囲みます。

|===


== 注：

ディスクプール名は一意である必要があります。ユーザラベルには、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。ユーザラベルの最大文字数は30文字です。

任意のディスクプールをセットで指定できます。複数のディスク・プールを選択した場合は'userLabel'の値を設定するとエラーが発生します

オプションパラメータの値を指定しない場合は、デフォルト値が割り当てられます。



== ディスクプールのアラートのしきい値

各ディスクプールには2段階の重大度レベルのアラートがあり、ディスクプールのストレージ容量が上限に近づいたときにユーザに通知します。アラートのしきい値は、ディスクプール内の使用可能な総容量に対する使用済み容量の割合です。アラートは次のとおりです。

* 警告--ディスクプール内の使用済み容量がフルに近づいていることを通知する第1レベルのアラートです。警告アラートのしきい値に達すると、要注意状態が生成され、ストレージ管理ソフトウェアにイベントが送信されます。警告しきい値よりも、重大しきい値のほうが優先されます。デフォルトの警告しきい値は50%です。
* 重大--ディスクプール内の使用済み容量がフルに近づいていることを通知する最も重大なレベルのアラートです重大アラートのしきい値に達すると、要注意状態が生成され、ストレージ管理ソフトウェアにイベントが送信されます。警告しきい値よりも、重大しきい値のほうが優先されます。重大アラートのデフォルトのしきい値は85%です。


警告アラートの値は常に重大アラートの値より小さくする必要があります。警告アラートの値が重大アラートの値と同じ場合は、重大アラートのみが送信されます。



== ディスクプールのバックグラウンド処理

ディスクプールは次のバックグラウンド処理をサポートします。

* 再構築
* Instant Availability Format（IAF）
* の形式で入力し
* 容量の動的拡張（DCE）
* Dynamic Capacity Reduction（DCR）
* Dynamic Volume Expansion（DVE）（ディスクプールの場合、DVEは実際はバックグラウンド処理ではなく、同期処理としてサポートされています）。


ディスクプールでは、バックグラウンドコマンドはキューに配置されません。複数のバックグラウンドコマンドを順次開始できますが、複数のバックグラウンド処理を一度に開始すると、前に開始したコマンドの完了が遅延します。サポートされているバックグラウンド処理の相対的な優先度レベルは次のとおりです。

. 再構築
. の形式で入力し
. IAF
. DCE/DCR




== 最小ファームウェアレベル

7.83
