---
permalink: commands-a-z/set-snapgroup-increase-decreaserepositorycapacity.html 
sidebar: sidebar 
keywords: set, snapshot, group, repository, volume, capacity 
summary: set snapGroup increase/decreaseRepositoryCapacityコマンドは、Snapshotグループのリポジトリボリュームの容量を増減します。 
---
= Snapshotグループのリポジトリボリューム容量の設定
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set snapGroup increase/decreaseRepositoryCapacityコマンドは'スナップショット・グループのリポジトリ・ボリュームの容量を増減します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 容量を増やすための構文

[listing, subs="+macros"]
----
set snapGroup pass:quotes[["_snapGroupName_"]] increaseRepositoryCapacity
(repositoryVolumes="repos_xxxx" | repositoryVolumes=pass:quotes[((_volumeGroupName_]
pass:quotes[[capacity=_capacityValue_]])) | repositoryVolumes=pass:quotes[((_diskPoolName_]
pass:quotes[[capacity=_capacityValue_]])))
----


== 容量を減らす場合の構文

[listing, subs="+macros"]
----
set snapGroup pass:quotes[["_snapGroupName_"]]
decreaseRepositoryCapacity
count=pass:quotes[_numberOfVolumes_]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「SnapGroup」
 a| 
容量を増減するSnapshotグループの名前。Snapshotグループ名は、二重引用符（""）で囲んだ上で角かっこ（[]）で囲みます。



 a| 
リポジトリボリューム
 a| 
容量を拡張するリポジトリボリュームの名前。使用可能な標準ボリュームがリポジトリボリュームに追加され、リポジトリボリュームの容量が拡張されます。

リポジトリボリュームの名前を定義する方法は2つあります。

* 既存のリポジトリボリュームの名前を使用します
* このコマンドを実行するときに新しいリポジトリボリュームを作成します


既存のリポジトリボリュームの名前は次の2つの部分で構成されます。

* 「repos」という用語
* ストレージ管理ソフトウェアがリポジトリボリューム名に割り当てる4桁の数値識別子


既存のリポジトリボリュームの名前は二重引用符（""）で囲みます。

このコマンドを実行するときに新しいリポジトリボリュームを作成する場合は、リポジトリボリュームを含めるボリュームグループまたはディスクプールの名前を入力する必要があります。必要に応じて、リポジトリボリュームの容量を定義することもできます。容量を定義する場合は、次の値を使用できます。

* ベースボリュームの容量の割合を表す整数値
* ベースボリュームの容量の割合を表す小数値
* リポジトリボリュームの具体的なサイズ。サイズは'bytes'KB'MB`'GB'TB'の単位で定義されます


容量オプションを使用しない場合は、ストレージ管理ソフトウェアによって、ベースボリュームの容量の20%に設定されます。

このコマンドを実行すると、ストレージ管理ソフトウェアによって、Snapshotボリューム用のリポジトリボリュームが作成されます。



 a| 
「count」
 a| 
Snapshotグループから削除するリポジトリボリュームの数。整数値を使用します。

|===


== 注：

ユーザラベルには、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。ユーザラベルの最大文字数は30文字です。

リポジトリボリュームの名前は、新しいSnapshotグループを作成するときに、ストレージ管理ソフトウェアおよびファームウェアによって自動的に作成されます。リポジトリボリュームの名前は変更できません。名前を変更すると、Snapshotイメージとのリンクが切断されます。

Snapshotグループのリポジトリボリュームは拡張可能なボリュームで、標準ボリュームエンティティを最大16個まで接続することで構成されます。拡張可能なリポジトリボリュームは、最初は1つの要素だけで構成されます。その時点でのリポジトリボリュームの容量は、その要素の容量と同じです。リポジトリボリュームの容量は、標準のリポジトリボリュームを接続することで拡張できます。その後、複数の要素で構成された拡張可能なリポジトリボリュームの容量は、接続されたすべての標準ボリュームの合計容量になります。

Snapshotグループのリポジトリボリュームは、次の合計サイズの最小容量要件を満たす必要があります。

* 32MB：Snapshotグループのオーバーヘッドを固定し、copy-on-write処理に使用できるようになりました。
* ロールバック処理用の容量。ベースボリュームの容量の1/5000です。


この最小容量は、コントローラファームウェアとストレージ管理ソフトウェアによって適用されます。



== 最小ファームウェアレベル

7.83
