---
permalink: commands-a-z/set-drive-nativestate.html 
sidebar: sidebar 
keywords: set, foreign, drive, native 
summary: set drive nativeStateコマンドを使用すると、見つからない（外部）ドライブが元のボリュームグループに再び追加され、新しいストレージアレイのボリュームグループに追加されます。 
---
= 外部ドライブをネイティブに設定する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「set drive nativeState」コマンドを使用すると、見つからない（外部）ドライブが元のボリュームグループに再び追加され、新しいストレージアレイのボリュームグループに追加されます。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

ストレージアレイのボリュームグループに属しているドライブは、ネイティブとみなされます。ストレージアレイのボリュームグループに属していないドライブ、またはボリュームグループのドライブが新しいストレージアレイに転送される際に一緒にインポートされなかったドライブは、外部ドライブとみなされます。後者の場合は、新しいストレージアレイに不完全なボリュームグループが作成されます。

この処理は、緊急のリカバリ目的で、1つ以上のドライブのステータスを外部からネイティブに変更して元のボリュームグループ内で元のステータスに戻す必要がある場合にのみ使用します。

[NOTE]
====
*データ破損またはデータ損失の可能性*--前述した以外の理由でこのコマンドを使用すると、通知なしにデータが失われる可能性があります。

====


== 構文

[source, cli, subs="+macros"]
----
set (drive=pass:quotes[(_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_)] | drives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)] |
allDrives) nativeState
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ドライブ」または「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800、E5700、EF600、およびEF300コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
「allDrives」を参照してください
 a| 
すべてのドライブを選択するための設定。

|===


== 注：

'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。



== 最小ファームウェアレベル

7.10

7.60で'drawerID'ユーザ入力が追加されました
