---
permalink: commands-a-z/set-storagearray-managementinterface.html 
sidebar: sidebar 
keywords: set, storage, array, management, interface 
summary: set storageArray ManagementInterfaceコマンドは、コントローラの管理インターフェイスを変更します。ストレージアレイとその管理ソフトウェア間の機密性を確保したり、外部ツールにアクセスしたりするには、管理インターフェイスのタイプを変更します。 
---
= ストレージアレイ管理インターフェースの設定 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set storageArray ManagementInterfaceコマンドは、コントローラの管理インターフェイスを変更します。ストレージアレイとその管理ソフトウェア間の機密性を確保したり、外部ツールにアクセスしたりするには、管理インターフェイスのタイプを変更します。


NOTE: SANtricity 12.0以降、ストレージアレイは常に `restOnly=true`モードで動作するため、このコマンドは削除されました。



== サポートされているアレイ

このコマンドは、個々のE4000、E2800、E5700、EF600、EF300、EF50、およびEF80ストレージアレイに適用されます。E2700またはE5600ストレージアレイでは動作しません。



== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Security Adminロールが必要です。



== 構文

[source, cli]
----
set storageArray managementInterface restOnly={true | false}
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「リストア専用」
 a| 
trueに設定すると'RESTfulインターフェイスのみが使用可能な管理インターフェイスになりますこのインターフェイスでは、ストレージアレイと管理ソフトウェアの間の接続が暗号化されます。

falseに設定すると'ストレージ・アレイと管理ソフトウェア間の従来のインタフェースが許可されますこのインターフェイスは暗号化されません。

従来の管理インターフェイス（SANtricity SMI-SプロバイダやOnCommand Insight （OCI）など）と直接通信するツールには、「restOnly」パラメータを「false」に設定しないかぎり機能しません。詳細については、テクニカルサポートにお問い合わせください。

|===


== 例

[listing]
----

SMcli -n Array1 -c "set storageArray managementInterface restOnly=true;"

SMcli completed successfully.
----


== 最小ファームウェアレベル

該当なし。
