---
permalink: commands-a-z/set-volume-logicalunitnumber.html 
sidebar: sidebar 
keywords: set, volume, map 
summary: set volume logicalUnitNumberコマンドは、ボリュームとホストまたはホストグループの間に論理ユニット番号（LUN）またはネームスペースID（NSID）マッピングを定義します。 
---
= ボリュームマッピングを設定
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set volume logicalUnitNumber'コマンドは'ボリュームとホストまたはホストグループ間の論理ユニット番号(LUN)またはネームスペースID (NSID )マッピングを定義します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドは、ボリュームグループまたはディスクプール内のボリュームに対して使用できます。

[NOTE]
====
オンラインボリュームコピーで使用されているSnapshotボリュームには、このコマンドは使用できません。

====


== 構文

[listing, subs="+macros"]
----
set (volume pass:quotes[[_volumeName_]] | volume <"wwID"> | accessVolume)
pass:quotes[logicalUnitNumber=_lun_]
pass:quotes[(host="_hostName_"] |
hostGroup=pass:quotes[("_hostGroupName_"] | defaultGroup)
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
LUNを定義するボリュームの名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名に特殊文字または数字が含まれている場合は、ボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「 volume 」
 a| 
LUNを定義するボリュームのWorld Wide Identifier（WWID）。WWIDは二重引用符（""）で囲んだ上で山かっこ（<>）で囲みます。



 a| 
「accessVolume」のようになります
 a| 
アクセスボリュームの論理ユニット番号。LUNは、アクセスボリュームに設定できる唯一のプロパティです。



 a| 
「logicalUnitNumber」と入力します
 a| 
特定のホストにマッピングするLUNまたはネームスペースID。このパラメータは、ホストをホストグループにも割り当てます。

[NOTE]
====
LUNまたはネームスペースIDには、ホストオペレーティングシステムでサポートされる範囲内の未使用の値を指定する必要があります。ホストでサポートされないLUNまたはネームスペースIDにボリュームをマッピングした場合、エラーは発生しませんが、ホストはボリュームにアクセスできなくなります。

====


 a| 
ホスト
 a| 
ボリュームのマッピング先であるホストの名前。ホスト名は二重引用符（""）で囲みます。



 a| 
「hostGroup」と入力します
 a| 
ボリュームのマッピング先であるホストグループの名前。ホストグループ名は二重引用符（""）で囲みます。defaultGroupは'ボリュームがマッピングされているホストを含むホスト・グループです

|===


== 注：

ホストグループはオプションのトポロジ要素であり、同じボリュームへのアクセスを共有する一連のホストを指定するかどうかを定義できます。ホストグループは論理エンティティです。ホストグループは、同じボリュームへのアクセスを共有できるホストが複数ある場合にのみ定義してください。

名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。名前の最大文字数は30文字です。

アクセスボリュームは、ストレージ管理ソフトウェアとストレージアレイコントローラの間のインバンド通信に使用されるSAN環境内のボリュームです。このボリュームはLUNアドレスまたはNSIDアドレスを使用し、アプリケーションデータストレージには使用できない20MBのストレージスペースを使用します。アクセスボリュームは、インバンド管理されるストレージアレイでのみ必要です。「accessVolume」パラメータを指定した場合、設定できる唯一のプロパティは「logicalUnitNumber」パラメータです。



== 最小ファームウェアレベル

7.83で、ディスクプールのSnapshotボリュームが追加されました。
