---
permalink: commands-a-z/set-volumegroup-forcedstate.html 
sidebar: sidebar 
keywords: set, volume, group, forced, state 
summary: set volumeGroup forcedStateコマンドは、ボリュームグループを強制状態に移行します。 
---
= ボリュームグループの強制状態を設定する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set volumegroup forcedState'コマンドは'ボリュームグループを強制状態に移行します



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

start volumeGroup importコマンドを使用してボリュームグループをインポート済みの状態に移行しない場合、またはハードウェアエラーのためにインポート操作が機能しない場合は、このコマンドを使用します。強制状態のボリュームグループはインポート可能です。インポート後にハードウェアエラーを特定できます。



[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
set volumeGroup pass:quotes[[_volumeGroupName_]] forcedState
----


[[parameter]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「volumeGroup」のように指定します
 a| 
強制状態に移行するボリュームグループの名前。ボリュームグループ名は角かっこ（[]）で囲みます。

|===


[[notes]]
== 注：

ボリュームグループを構成するドライブを、あるストレージアレイから別のストレージアレイに移動できます。CLIには、ドライブを移動するためのコマンドが3つあります。コマンドは'start volumeGroup export'start volumeGroup import'およびset volumeGroup forcedState'です

強制状態のボリュームグループにはインポート処理を実行できます。



[[minimum-firmware-level]]
== 最小ファームウェアレベル

7.10
