---
permalink: commands-a-z/set-controller-service-action-allowed-indicator.html 
sidebar: sidebar 
keywords: set, controller, service, action, allowed, indicator 
summary: set controllerコマンドは、コントローラトレイまたはコントローラドライブトレイ内のコントローラの、保守操作可能インジケータライトをオンまたはオフにします 
---
= コントローラのサービスアクション許可インジケーターの設定 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set controllerコマンドは、コントローラトレイまたはコントローラドライブトレイ内のコントローラの保守操作可能インジケータライトをオンまたはオフにします



== サポートされているアレイ

このコマンドは、E2700アレイとE5600アレイを含む個々のストレージアレイの環境 を行います。



== コンテキスト（Context）

ストレージアレイが保守操作可能インジケータライト機能をサポートしていない場合、このコマンドはエラーを返します。ストレージアレイがこのコマンドをサポートしていてもインジケータライトをオンまたはオフにできない場合、このコマンドはエラーを返します。(電源ファンキャニスターまたはインターコネクトバッテリキャニスターの保守操作可能インジケータライトをオンまたはオフにするには'set tray serviceAllowedIndicatorコマンドを使用します)

[NOTE]
====
このコマンドは、E2700、E5600、EF560（および他の旧世代のEシリーズまたはEFシリーズのコントローラ）でのみ有効です。E2800コントローラトレイには警告インジケータが1つ付いており、1）障害が発生した場合、および2）障害が発生したコンポーネントを安全に取り外すことができる場合にのみ点灯します。

====


== 構文

[source, cli]
----
set controller [(a| b)]
serviceAllowedIndicator=(on | off)
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「controller」と入力します
 a| 
保守操作可能インジケータライトをオンまたはオフにするコントローラ。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラですコントローラの識別子は角かっこ（[]）で囲みます。コントローラを指定しないと、コントローラファームウェアから構文エラーが返されます。



 a| 
「serviceAllowedIndicator」というメッセージが表示されます
 a| 
保守操作可能インジケータライトをオンまたはオフにするための設定。保守操作可能インジケータライトをオンにするには、このパラメータを「オン」に設定します。保守操作可能インジケータライトをオフにするには、このパラメータを「オフ」に設定します。

|===


== 最小ファームウェアレベル

6.14
