---
permalink: commands-a-z/set-host.html 
sidebar: sidebar 
keywords: set, host 
summary: set hostコマンドは、ホストをホストグループに割り当てるか別のホストグループに移動します。 
---
= ホストの設定 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set hostコマンドは'ホストをホスト・グループに割り当てるか'ホストを別のホスト・グループに移動します



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

このコマンドでは、新しいホストグループを作成し、そのホストグループにホストを割り当てることもできます。このコマンドで実行される操作は、ホストに個別のマッピングがあるかどうかによって異なります。



[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
set host [hostName]
hostGroup=pass:quotes[("_hostGroupName_"] | none | defaultGroup)
userLabel=pass:quotes["_newHostName_"]
hostType=pass:quotes[(_hostTypeIndexLabel_ | _hostTypeIndexNumber_)]
----


[[parameters]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
ホスト
 a| 
ホストグループに割り当てるホストの名前。ホスト名は角かっこ（[]）で囲みます。ホスト名に特殊文字または数字が含まれている場合は、ホスト名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「hostGroup」と入力します
 a| 
ホストを割り当てるホストグループの名前。（次の表に、ホストに個別のマッピングがあるかどうかに関係なく、コマンドの実行方法を示します）。 ホストグループ名は二重引用符（""）で囲みます。defaultGroupオプションは'ボリュームがマップされているホストを含むホスト・グループです



 a| 
「userLabel」のように入力します
 a| 
新しいホスト名。ホスト名は二重引用符（""）で囲みます。



 a| 
「hostType」
 a| 
ホストポートのホストタイプのインデックスラベルまたはインデックス番号。使用可能なホストタイプ識別子のリストを生成するには、「show storageArray hostTypeTable」コマンドを使用します。ホストタイプに特殊文字が含まれている場合は、ホストタイプを二重引用符（""）で囲みます。

|===
[cols="3*"]
|===
| ホストグループのパラメータ | ホストに個別の割り当てがあります | ホストに個別の割り当てがありません 


 a| 
「_hostGroupName_」と入力します
 a| 
ホストは現在のホスト・グループから削除され'_hostGroupName_'で定義された新しいホスト・グループの下に配置されます
 a| 
ホストは現在のホスト・グループから削除され'_hostGroupName_'で定義された新しいホスト・グループの下に配置されます



 a| 
「 NONE 」
 a| 
ホストが独立したパーティションとしてホストグループから削除され、ルートノードに配置されます。
 a| 
ホストが現在のホストグループから削除され、デフォルトグループに配置されます。



 a| 
defaultGroup
 a| 
コマンドが失敗します。
 a| 
ホストが現在のホストグループから削除され、デフォルトグループに配置されます。

|===


[[notes]]
== 注：

このコマンドでは、オプションのパラメータを1つ以上指定できます。

名前には、英数字、ハイフン、アンダースコアを任意に組み合わせて使用できます。名前の最大文字数は30文字です。



[[minimum-firmware-level]]
== 最小ファームウェアレベル

6.10
