---
permalink: commands-a-z/set-drive-securityid.html 
sidebar: sidebar 
keywords: set, fips, drive, security, identifier 
summary: set drive securityIDコマンドは、FIPSドライブをメーカー出荷時の設定にリセットするために使用します。 
---
= FIPSドライブセキュリティ識別子の設定 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set drive securityIDコマンドは'FIPSドライブを元の製造元の設定に戻すために使用します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Security Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
このコマンドは、FIPSドライブをメーカー出荷時の設定にリセットし、既存のドライブデータをすべて消去します。この処理は元に戻すことができません。セキュリティキーファイルが無効または見つからないか、パスフレーズが不明なためにドライブがロックされた場合、この処理が必要になることがあります。既存のドライブデータはすべて消去されます。

====
FDEドライブを消去するには'start secureEraseコマンドを使用します



== 構文

[source, cli, subs="+macros"]
----
set drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] securityID="string"
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
「securityID」
 a| 
消去するドライブのセキュリティIDを文字列形式で指定します。この文字列の最大文字数は32文字です。セキュリティIDの形式は製造元によって異なります。

[NOTE]
====
セキュリティIDを確認するには、ドライブを取り外し、キャニスターラベルのセキュリティIDを確認します。

====
|===


== 注：

'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。



== 例

[listing]
----
set drive [1,31,4] securityID="V2zdvLTdGWdWyTALGHns";
----


== 最小ファームウェアレベル

8.25
