---
permalink: commands-a-z/set-storagearray-autoloadbalancingenable.html 
sidebar: sidebar 
keywords: set, storage, array, enable, disable, automatic, load, balance 
summary: set storageArray autoLoadBalancingEnableコマンドは、自動ロードバランシング機能を有効または無効にします。 
---
= 自動ロードバランシングを有効または無効にするストレージアレイを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set storageArray autoLoadBalancingEnableコマンドは、自動ロードバランシング機能を有効または無効にします。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== 構文

[listing]
----
set storageArray autoLoadBalancingEnable=(TRUE | FALSE)
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「storageArray storageArray storageArray」
 a| 
このパラメータがストレージアレイに対して機能することを示します。



 a| 
autoLoadBalancingEnable
 a| 
このパラメータは、コントローラの自動ロードバランシングをオンまたはオフにします。自動ロードバランシングをオンにするには、このパラメータを「true」に設定します。自動ロードバランシングをオフにするには、パラメータをFALSEに設定します。

|===


== 自動ロードバランシングとは何ですか？

自動ロードバランシング機能を使用すると、負荷の変化に動的に対応してボリュームのコントローラ所有権が自動的に調整されるため、コントローラ間でワークロードが移動する際の負荷の不均衡が解消され、I/Oリソースの管理が強化されます。

各コントローラのワークロードは継続的に監視され、ホストにインストールされたマルチパスドライバとの連携により、必要に応じて自動的に負荷を分散できます。ワークロードがコントローラ間で自動的に再分散されるため、ストレージアレイの負荷の変化に合わせてボリュームのコントローラ所有権を手動で調整する必要がなくなり、ストレージ管理者の負担が軽減されます。

自動ロードバランシングを有効にすると、次の機能が実行されます。

* コントローラのリソース利用率を自動的に監視して負荷を分散します。
* ボリュームのコントローラ所有権が必要に応じて自動的に調整され、ホストとストレージアレイの間のI/O帯域幅が最適化されます。




== 自動ロードバランシングの有効化と無効化

自動ロードバランシングは、SANtricity OS（コントローラソフトウェア）8.30以降に付属のすべてのストレージアレイでデフォルトで有効になります。Linux、Windows、VMwareのマルチパスドライバでは、自動ロードバランシング機能を使用できます。コントローラをSANtricity OS（コントローラソフトウェア）8.25以前から8.30以降にアップグレードした場合、自動ロードバランシングはストレージアレイでデフォルトで無効になります。

自動ロードバランシングは、ストレージアレイの状況に応じて無効にすることができます。たとえば、次のような場合です。

* 特定のボリュームのコントローラ所有権については、ワークロードを分散するために自動的に変更されないようにする場合。
* 高度に調整された環境で、コントローラ間の負荷分散が特定の要件を満たすように意図的に設定されている。


SANtricity Storage Managerで、個別のストレージアレイの自動ロードバランシング機能を有効または無効にするには、*ストレージアレイ*>*構成*>*自動ロードバランシング*メニューオプションを選択します。

SANtricity システムマネージャで、*Settings*>*System*を選択し、*Additional Settings*セクションまで下にスクロールして、E**イネーブル/ディセーブル自動ロードバランシング**リンクをクリックし、**Enable/Disable automatic load balancing **チェックボックスを選択して、個々のストレージアレイの機能をイネーブルまたはディセーブルにします。



== 例

[listing]
----
SMcli -n Array1 -c "set storageArray autoLoadBalancingEnable=true;"

SMcli completed successfully.
----
[NOTE]
====
「ドライブがプライマリパスを喪失」状態がアクティブな場合、自動ロードバランシングがワークロードを分散することができません。自動ロードバランシング機能でワークロードが分散されるためには、この状態が非アクティブである必要があります。

====


== 最小ファームウェアレベル

8.30
