---
permalink: commands-a-z/set-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: set, asynchronous, mirror, group 
summary: set asyncMirrorGroupコマンドは、非同期ミラーグループのプライマリ側のコントローラ所有者が初期同期または再同期を実行する際に使用する同期設定と警告しきい値を変更します。 
---
= 非同期ミラーグループを設定します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
set asyncMirrorGroup'コマンドは'非同期ミラー・グループのプライマリ側のコントローラ所有者が初期同期または再同期を実行するときに使用する同期設定と警告しきい値を変更します



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700などの個 々 のストレージアレイを環境に設定します。 EF600およびEF300アレイ（すべてのSMcliパッケージがインストールされている必要があります。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage AdminまたはSupport Adminロールが必要です。



== コンテキスト（Context）

同期設定を変更すると、非同期ミラーグループ内のすべてのミラーペアの同期処理に適用されます。



== 構文

[listing, subs="+macros"]
----
set asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]]
[volume="repos_xxxx" increaseRepositoryCapacity (repositoryVolume=("repos_xxxx")]
[syncInterval=pass:quotes[_integer_] (minutes | hours | days)]
[warningSyncThreshold=pass:quotes[_integer_] (minutes | hours | days)]
[warningRecoveryThreshold=integer (minutes | hours | days)]
[userLabel=pass:quotes["_New_asyncMirrorGroupName_"]]
[warningThresholdPercent=pass:quotes[_percentValue_]]
[role=(primary | secondary)]
[autoResync=(TRUE | FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「asyncMirrorGroup」
 a| 
変更する非同期ミラーグループの名前。非同期ミラーグループ名は角かっこ（[]）で囲みます。非同期ミラーグループ名に特殊文字または数字が含まれている場合は、名前を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「 volume 」
 a| 
容量を拡張する非同期ミラーグループリポジトリボリュームの名前。

リポジトリボリュームの名前は2つの部分で構成されます。

* 「repos」という用語
* ストレージ管理ソフトウェアがリポジトリボリューム名に割り当てる4桁の数値識別子


リポジトリボリュームの名前は二重引用符（""）で囲みます。



 a| 
「syncInterval」
 a| 
変更されたデータの更新をローカルストレージアレイからリモートストレージアレイに自動的に送信する間隔を指定します。時間は、分、時間、または日数で指定できます。



 a| 
「warningSyncThreshold」
 a| 
非同期ミラーグループ内のすべてのボリュームの同期にかかる時間が指定した時間よりも長い場合に、警告がトリガーされるまでの待機時間を指定します。時間は、分、時間、または日数で指定できます。



 a| 
「warningRecoveryThreshold」
 a| 
リモートストレージアレイのポイントインタイムイメージの自動データ更新が指定した時間よりも古くなった場合に、警告がトリガーされるまでの待機時間を指定します。しきい値は、前回の更新終了時点からの経過日数で定義します。時間は、分、時間、または日数で指定できます。

[NOTE]
====
リカバリポイントのしきい値は、同期間隔のしきい値の2倍に設定する必要があります。

====


 a| 
「userLabel」のように入力します
 a| 
非同期ミラーグループに付ける新しい名前。このパラメータは、非同期ミラーグループの名前を変更する場合に使用します。新しい非同期ミラーグループ名は二重引用符（""）で囲みます。



 a| 
「warningThresholdPercent」
 a| 
ミラーリポジトリボリュームの容量が指定した割合に達したときに警告がトリガーされるかどうかを判断するパーセント値を指定します。しきい値は、残りの容量の割合（%）で定義します。



 a| 
「役割」
 a| 
このパラメータを使用して、非同期ミラーグループをプライマリロールに昇格するか、非同期ミラーグループをセカンダリロールに降格します。非同期ミラーグループをプライマリロールとして定義するには'このパラメータをprimaryに設定します非同期ミラーグループをセカンダリロールとして定義するには'このパラメータをsecondaryに設定します



 a| 
「autoResync」
 a| 
非同期ミラーグループ内の非同期ミラーペアのプライマリボリュームとセカンダリボリュームの間の自動再同期の設定。このパラメータには次の値があります。

* [enabled]--自動再同期がオンになっています何もしなくても、プライマリボリュームとセカンダリボリュームは再同期されます。
* disabled --自動再同期がオフになっていますプライマリ・ボリュームとセカンダリ・ボリュームを再同期するには'start asyncMirrorGroupコマンドを実行する必要があります


|===


== 注：

名前には、英数字、アンダースコア（_）、ハイフン（-）、シャープ（#）を任意に組み合わせて使用できます。名前の最大文字数は30文字です。

このコマンドではパラメータを1つ以上指定できます。ただし、すべてのパラメータを使用する必要はありません。

非同期ミラーグループリポジトリボリュームは拡張可能なボリュームで、標準ボリュームエンティティを最大16個まで接続することで構成されます。拡張可能なリポジトリボリュームは、最初は1つのボリュームだけで構成されます。その時点でのリポジトリボリュームの容量は、そのボリュームの容量と同じです。リポジトリボリュームの容量は、未使用のリポジトリボリュームを接続することで拡張できます。その後、複数の要素で構成された拡張可能なリポジトリボリュームの容量は、接続されたすべての標準ボリュームの合計容量になります。



== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
