---
permalink: commands-a-z/set-disk-pool-modify-disk-pool.html 
sidebar: sidebar 
keywords: set, disk pool, modify 
summary: set diskPoolコマンドは、ディスクプールに容量を追加（Dynamic Capacity ExpansionまたはDCE）するか、ディスクプール全体のコントローラ所有権を変更します。 
---
= ディスクプールの設定（ディスクプールの変更）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
set diskPool'コマンドは'ディスク・プール（Dynamic Capacity ExpansionまたはDCE）に容量を追加するか'ディスク・プール全体のコントローラ所有権を変更します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

この2つの処理は同時に実行できません。



== 構文

[source, cli, subs="+macros"]
----
set diskPool pass:quotes[[_diskPoolName_]]
(addDrives=pass:quotes[[_trayID1_,_drawerID1_,_slotID1_ ... _trayIDn_,_drawerIDn_,_slotIDn_]] |
addCapacity=pass:quotes[(_diskPoolCapacity_))]
[owner=(a| b)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「diskPool」
 a| 
変更するディスクプールの名前。ディスクプール名は角かっこ（[]）で囲みます。ディスクプール名が特殊文字を含んでいる場合または数字のみで構成される場合は、名前を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「addDrives」を参照してください
 a| 
ディスクプールに追加するドライブ。大容量ドライブトレイの場合は、追加するドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、追加するドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。スロットIDの値は'1'～24'ですトレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

[NOTE]
====
この機能の最大ドライブ数は12本です。

====


 a| 
「addCapacity」
 a| 
ディスクプールに追加するストレージ容量。このパラメータを指定すると、必要な追加容量を満たすドライブが自動的に選択されます。容量は'bytes'KB'MB`'GB'TB'の単位で定義されます



 a| 
「owner」をクリックします
 a| 
ディスクプールを所有するコントローラ。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラです所有者を指定しない場合は、コントローラファームウェアによって所有者が決定されます。

|===


== 注：

ディスクプール内の既存のボリュームは、新しいドライブを追加する間もオンラインのままで、I/O処理が可能です。容量を追加するには、ディスクプールが完了状態である必要があります。ディスク・プールがcomplete状態でない場合は'新しいドライブを追加する前にset diskPool completeコマンドを実行します

容量を追加するには'addDrives'パラメータで個のドライブを指定するか'addCapacity'パラメータでドライブ容量を指定します「addDrives」を使用する場合、ホストは、操作を実行する前にドライブセットを検証する必要があります。「addCapacity」パラメータを使用すると、指定した容量が追加する最小容量として使用されます。候補ドライブのうち、サービス品質が最適で、かつ指定した以上の容量を持つドライブが使用されます。最小限の要件を満たす候補がない場合や、指定したドライブを使用できない場合や属性の不一致が検出された場合は、処理が失敗します。

このコマンドを使用して、ディスクプールの所有権をストレージアレイ内のあるコントローラから別のコントローラに変更することもできます。所有権の変更とドライブまたは容量の追加を同時に実行することはできません。



== 最小ファームウェアレベル

7.83
