---
permalink: commands-a-z/show-drivechannel-stats.html 
sidebar: sidebar 
keywords: show, drive channel, statistics 
summary: show driveChannel statsコマンドを実行すると、ドライブチャネルの累積データ転送とエラー情報が表示されます。 
---
= ドライブチャネル統計情報の表示 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「show driveChannel stats」コマンドは、ドライブチャネルの累積データ転送とエラー情報を表示します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

コントローラが自動的にドライブチャネルをデグレードした場合、このコマンドは区間統計も表示します。このコマンドを使用すると、1つの特定のドライブチャネル、複数のドライブチャネル、またはすべてのドライブチャネルに関する情報を表示できます。



== 構文

[source, cli]
----
show (driveChannel [(1 | 2 | 3 | 4 | 5 | 6 | 7 | 8)] |
   driveChannels [1 2 3 4 5 6 7 8] |
   allDriveChannels) stats
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
driveChannel
 a| 
情報を表示するドライブチャネルの識別番号。有効なドライブ・チャネル値は'1''2`'3`'4`'5`'です '6`'7`'または'8`ドライブチャネルは角かっこ（[]）で囲みます。

このパラメータは、1つのドライブチャネルの統計情報のみを表示する場合に使用します。



 a| 
「ドライブチャネル」
 a| 
情報を表示する複数のドライブチャネルの識別番号。有効なドライブ・チャネル値は'1''2`'3`'4`'5`'です '6`'7`'または'8`ドライブチャネルの値をスペースで区切って指定し、角かっこ（[]）で囲みます。

このパラメータは、複数のドライブチャネルの統計を表示する場合に使用します。



 a| 
「allDriveChannels」のようになります
 a| 
ドライブチャネルをすべて選択する識別子。

|===


== 注：

なし



== 最小ファームウェアレベル

6.10

7.15で、ドライブチャネル識別子の更新が追加されました。
