---
permalink: commands-a-z/show-storagearray-autosupport.html 
sidebar: sidebar 
keywords: show, autosupport, configuration, e2800, e5700, storage, arrays 
summary: show storageArray storageArray autoSupport AutoSupport コマンドは、ストレージアレイのAutoSupport バンドル収集設定を表示します。 
---
= AutoSupport の設定を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
show storageArray autoSupport AutoSupport コマンドを使用すると、ストレージアレイのAutoSupport バンドル収集設定が表示されます。



== サポートされているアレイ

このコマンドは、E4000、E2800、E5700、EF600、およびEF300のストレージアレイが対象です。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Admin、Support Admin、またはStorage Monitorロールが必要です。



== コンテキスト（Context）

このコマンドからのコマンド出力は、次の設定情報を表示します。

* AutoSupport 機能、AutoSupport OnDemand機能、およびAutoSupport Remote Diagnostics機能の管理ドメインのアクティブ化ステータス
* 設定された配信方法に応じた配信パラメータ：
+
** 配信方法がEメール（SMTP）：送信先のEメールアドレス、メールリレーサーバ、および送信者のEメールアドレスが表示されます
** 配信方法がHTTPまたはHTTPS：
+
*** 直接接続-宛先IPアドレスが表示されます
*** プロキシサーバ接続-ホストアドレス、ポート番号、および認証の詳細が表示されます
*** 自動プロキシ設定スクリプト（PAC）接続-スクリプトの場所が表示されます




* AutoSupport の日単位および週単位の優先される時間範囲
* ASUPの機能、シャーシのシリアル番号、および設定されている日次/週次スケジュールに関する情報




== 構文

[source, cli]
----
show storageArray autoSupport
----


== パラメータ

なし



=== 例

[listing]
----

  SMcli -n Array1 -c "show storageArray autoSupport;"

   The AutoSupport feature is enabled on this storage array.
   The AutoSupport OnDemand feature is enabled on this storage array.
   The AutoSupport Remote Diagnostics feature is enabled on this storage array.

  Delivery Method: Email (SMTP)
    Destination email address: autosupport@netapp.com
    Mail relay server: mail.example.com
    Sender email address: sender@example.com
    Server encryption type: None
    Server port: 25
    Server username:
    Server password: ***
    Dispatch size limit: 5242880

  Delivery Method: Email (SMTP)
    Destination email address: destination1@example.com, destination2@example.com
    Mail relay server: mail.example.com
    Sender email address: sender@example.com
    Server encryption type: None
    Server port: 25
    Server username:
    Server password: ***
    Dispatch size limit: 5242880

  Delivery Method: HTTPS
    Destination IP address: https://support.netapp.com/put/AsupPut/
    Connection: Direct
    Dispatch size limit: 52428800

  Delivery Method: HTTPS
    Destination IP address: https://support.netapp.com/put/AsupPut/
    Connection: Direct
    Dispatch size limit: Unlimited

   The AutoSupport daily schedule preferred time range is from 12:00 AM to 01:00 AM.
   The AutoSupport weekly schedule preferred time range is from 10:00 PM to 11:00 PM on Thursday, Saturday.

   AutoSupport Capable  AutoSupport OnDemand Capable  Chassis Serial Number  Daily Schedule  Weekly Schedule
   Yes (enabled)        Yes                           SX94500434             12:55 AM        10:08 PM on Thursdays

   SMcli completed successfully.
----


== 最小ファームウェアレベル

8.40
