---
permalink: commands-a-z/show-volume-summary.html 
sidebar: sidebar 
keywords: show, volume 
summary: show volume summaryコマンドは、ボリュームに関する情報を返します。 
---
= ボリュームを表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
show volume summaryコマンドは'ボリュームに関する情報を返します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはStorage Monitorロールが必要です。



== コンテキスト（Context）

このコマンドは、ストレージアレイ内のボリュームについて次の情報を返します。

* ボリュームの数
* 名前
* ステータス
* 容量
* RAIDレベル
* ボリュームが配置されているボリュームグループ
* 詳細：
+
** ボリュームID
** サブシステムID
** ドライブタイプ（SAS）
** トレイ損失の保護
** 優先所有者
** 現在の所有者
** セグメントサイズ
** 修正の優先順位
** 読み取りキャッシュのステータス（有効または無効）
** 書き込みキャッシュのステータス（有効または無効）
** バッテリなしの書き込みキャッシュのステータス（有効または無効）
** ミラーリングありの書き込みキャッシュのステータス（有効または無効）
** 書き込みキャッシュをフラッシュします
** キャッシュ読み取りプリフェッチの設定（TRUEまたはFALSE）
** バックグラウンドメディアスキャンの有効化ステータス（有効または無効）
** 冗長性チェックを伴うメディアスキャンのステータス（有効または無効）


* ミラーリポジトリボリューム




== 構文

[source, cli, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]]) summary
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allVolumes」
 a| 
このパラメータは、ストレージアレイ内のすべてのボリュームに関するパフォーマンス統計を返します。



 a| 
「 volume 」
 a| 
情報を取得するボリュームの名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名に特殊文字または数字が含まれている場合は、名前を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「ボリューム」
 a| 
情報を取得する複数のボリュームの名前。以下のルールを使用して、ボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


ボリューム名に特殊文字または数字が含まれる場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
「概要」
 a| 
ボリュームに関する概要情報をリストで返すための設定。

|===