---
permalink: commands-a-z/show-alldrives-performancestats.html 
sidebar: sidebar 
keywords: show, drive, performance, statistics 
summary: show allDrives performanceStatsコマンドは、ドライブのパフォーマンスに関する情報を返します。 
---
= ドライブのパフォーマンス統計を表示する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
show allDrives performanceStatsコマンドは'ドライブのパフォーマンスに関する情報を返します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドは、ストレージアレイ内の各ドライブについて次の情報を返します。

* ドライブを含むストレージアレイ
* 現在のI/Oレイテンシ
* 最大I/Oレイテンシ
* 最小I/Oレイテンシ
* 平均I/Oレイテンシ




== 構文

[source, cli, subs="+macros"]
----
show (allDrives |drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]]) performanceStats
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allDrives」を参照してください
 a| 
ストレージアレイ内のすべてのドライブに関する情報を返すための設定。



 a| 
「ドライブ」または「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

|===


== 注：

'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。

次の例に示すように'show drive performanceStatsコマンドは'ドライブのパフォーマンス統計を返します

[listing]
----
"Performance Monitor Statistics for Storage Array: remote_pp -
Date/Time: 10/23/12 3:47:27 PM -
Polling interval in seconds: 5"

"Objects","Current IO Latency","Maximum IO Latency","Minimum IO Latency",
"Average IO Latency"

"Capture Iteration: 1","","","",""
"Date/Time: 10/23/12 3:47:27 PM","","","",""
"Drive Tray 0, Slot 1","0.0","0.0","0.0","0.0"
----


== 最小ファームウェアレベル

7.86
