---
permalink: commands-a-z/show-storagearray-autoconfiguration.html 
sidebar: sidebar 
keywords: show, storage, array, auto, configuration 
summary: autoConfigure storageArrayコマンドを実行すると、ストレージアレイが作成するデフォルトの自動設定がshow storageArray autoConfigurationコマンドで表示されます。 
---
= ストレージアレイの自動構成を表示する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「autoConfigure storageArray autoConfiguration」コマンドを実行すると、ストレージアレイが作成するデフォルトの自動設定が表示されます。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはStorage Monitorロールが必要です。



== コンテキスト（Context）

ストレージアレイが特定のプロパティをサポートするかどうかを確認するには、このコマンドを実行するときにプロパティのパラメータを入力します。設定情報を取得する場合、このコマンドのパラメータを入力する必要はありません。



== 構文

[source, cli, subs="+macros"]
----
show storageArray autoConfiguration
[driveType=(SAS | NVMe4K)
driveMediaType=(HDD | SSD | unknown | allMedia)
raidLevel=(0 | 1 | 3 | 5 | 6)
pass:quotes[volumeGroupWidth=_numberOfDrives_]
pass:quotes[volumeGroupCount=_numberOfVolumeGroups_]
pass:quotes[volumesPerGroupCount=_numberOfVolumesPerGroup_]
pass:quotes[hotSpareCount=_numberOfHotspares_]
pass:quotes[segmentSize=_segmentSizeValue_]
cacheReadPrefetch=(TRUE | FALSE)
securityType=(none | capable | enabled)
secureDrives=(fips | fde)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ドライブタイプ」
 a| 
ストレージアレイに使用するドライブのタイプ。

ストレージ・アレイ内にドライブのタイプが1つだけの場合は'drivetypeパラメータは必要ありませんストレージアレイ内に複数のドライブタイプがある場合は、このパラメータを使用する必要があります。

有効なドライブタイプは次のとおりです。

* 「SAS」
* 「NVMe4K」




 a| 
driveMediaType
 a| 
ミラーリポジトリボリュームグループに使用するドライブメディアのタイプ。有効なドライブメディアは次のとおりです。

* [HDD]--ドライブトレイにハードドライブがある場合は'このオプションを使用します
* SSD'--ドライブトレイにソリッドステートドライブがある場合は'このオプションを使用します
* 不明--ドライブトレイ内のドライブメディアのタイプが不明な場合に使用します
* [allMedia]--ドライブトレイにあるすべてのタイプのドライブメディアを使用する場合に'このオプションを使用します


このパラメータは'repositoryDriveCount'パラメータを使用する場合に使用します

ストレージアレイ内に複数のタイプのドライブメディアがある場合は、このパラメータを使用する必要があります。



 a| 
raidLevel
 a| 
ストレージアレイ内にドライブが含まれているボリュームグループのRAIDレベル。有効なRAIDレベルは'0'1' 3'5'または'6'です



 a| 
'volumeGroupWidth'
 a| 
ストレージアレイ内のボリュームグループ内のドライブ数。ドライブの容量によって異なります。整数値を使用します。



 a| 
「volumeGroupCount」のように指定します
 a| 
ストレージアレイ内のボリュームグループの数。整数値を使用します。



 a| 
「volumesPerGroupCount」
 a| 
ボリュームグループあたりの容量が同じボリュームの数。整数値を使用します。



 a| 
「hotSpareCount」と入力します
 a| 
ストレージアレイ内に必要なホットスペアの数。整数値を使用します。



 a| 
「segmentSize」のように表示されます
 a| 
コントローラがボリューム内の1つのドライブに書き込めるデータ量（KB）を指定します。有効な値は'8`'16`'32`'64`'128`'です 「256」または「512」。



 a| 
「cacheReadPrefetch」というメッセージが表示されます
 a| 
キャッシュ読み取りプリフェッチをオンまたはオフにする設定。キャッシュ読み取りプリフェッチをオフにするには'このパラメータをFALSEに設定しますキャッシュ読み取りプリフェッチをオンにするには'このパラメータをTRUEに設定します



 a| 
「securityType」
 a| 
ボリュームグループおよび関連するすべてのボリュームの作成時にセキュリティレベルを指定する設定。有効な設定は次のとおりです。

* 'none`--ボリュームグループとボリュームは安全ではありません。
* capable --ボリュームグループとボリュームにはセキュリティを設定する機能がありますが'セキュリティは有効になっていません
* 有効-ボリューム・グループとボリュームでセキュリティが有効になっています




 a| 
「secureDrives」を参照してください
 a| 
ボリュームグループで使用するセキュアドライブのタイプ。有効な設定は次のとおりです。

* fips -- FIPS準拠のドライブのみを使用します
* fde -- FDE準拠のドライブを使用します


[NOTE]
====
このパラメータは'securityType'パラメータとともに使用しますsecurityTypeパラメータに「none」を指定すると、「secureDrives」パラメータの値は無視されます。これは、セキュアでないボリュームグループにセキュアドライブタイプを指定する必要がないためです。

====
|===


== 注：

プロパティを指定しない場合は、ドライブタイプごとにRAIDレベル5の候補が返されます。RAIDレベル5の候補がない場合は、RAIDレベル6、RAIDレベル3、RAIDレベル1、またはRAIDレベル0の候補を返します。自動設定のプロパティを指定すると、ファームウェアがプロパティをサポートできるかどうかがコントローラによって検証されます。



== ドライブとボリュームグループ

ボリュームグループは、ストレージアレイのコントローラによって論理的にグループ化された一連のドライブです。ボリュームグループ内のドライブ数は、RAIDレベルとコントローラファームウェアによって制限されます。ボリュームグループを作成する際は、次のガイドラインに従ってください。

* ファームウェアバージョン7.10以降では、あとから使用するために容量をリザーブできるように、空のボリュームグループを作成できます。
* SASとFibre Channelなどのドライブタイプを1つのボリュームグループ内で混在させることはできません。
* ボリュームグループの最大ドライブ数は、次の条件によって異なります。
+
** コントローラのタイプ
** RAIDレベル


* RAIDレベルには、0、1、10、3、5が含まれます。 および6.
+
** CDE3992またはCDE3994ストレージアレイでは、RAIDレベル0のボリュームグループとRAIDレベル10のボリュームグループには最大112本のドライブを配置できます。
** CE6998ストレージアレイでは、RAIDレベル0のボリュームグループとRAIDレベル10のボリュームグループには最大224本のドライブを配置できます。
** RAIDレベル3、RAIDレベル5、またはRAIDレベル6のボリュームグループに配置できるドライブは最大30本です。
** RAIDレベル6のボリュームグループには、少なくとも5本のドライブが必要です。
** RAIDレベル1のボリュームグループに4本以上のドライブがある場合、ストレージ管理ソフトウェアはボリュームグループをRAIDレベル10に自動的に変換します。RAIDレベル1 + RAIDレベル0です。


* ボリュームグループに容量の異なるドライブが含まれている場合は、容量の最も小さいドライブに基づいてボリュームグループ全体の容量が計算されます。
* トレイ/ドロワー損失の保護を有効にする場合のその他の条件については、次の表を参照してください。


[cols="3*"]
|===
| レベル | トレイ損失の保護の基準 | 必要なトレイの最小数 


 a| 
ディスク・プール
 a| 
ディスクプールに同じトレイのドライブが3本以上含まれない
 a| 
6.



 a| 
「RAID 6」
 a| 
ボリュームグループに同じトレイのドライブが3本以上含まれない
 a| 
3.



 a| 
RAID 3またはRAID 5
 a| 
ボリュームグループ内のドライブがすべて別々のトレイに配置されている
 a| 
3.



 a| 
RAID 1
 a| 
RAID 1ペアのドライブがそれぞれ別のトレイに配置されている
 a| 
2.



 a| 
RAID 0
 a| 
トレイ損失の保護は実現できない。
 a| 
該当なし

|===
[cols="3*"]
|===
| レベル | ドロワー損失の保護の基準 | 必要なドロワーの最小数 


 a| 
ディスク・プール
 a| 
プールに5つのドロワーすべてのドライブが含まれていて、各ドロワーに同じ数のドライブが配置されている。60ドライブのトレイでは、ディスクプールの構成が15、20、25、30、35の場合にドロワー損失の保護を実現できます。 40、45、50、55、または60ドライブ。
 a| 
5.



 a| 
「RAID 6」
 a| 
ボリュームグループに同じドロワーのドライブが3本以上含まれない。
 a| 
3.



 a| 
RAID 3またはRAID 5
 a| 
ボリュームグループ内のドライブがすべて別々のドロワーに配置されている。
 a| 
3.



 a| 
RAID 1
 a| 
ミラーペアのドライブがそれぞれ別のドロワーに配置されている。
 a| 
2.



 a| 
RAID 0
 a| 
ドロワー損失の保護は実現できない。
 a| 
該当なし

|===


== ホットスペア

ボリュームグループでは、データを保護するための重要な戦略は、ストレージアレイ内の使用可能なドライブをホットスペアドライブとして割り当てることです。ホットスペアは、データが格納されていないドライブで、RAID 1、RAID 3、RAID 5、またはRAID 6のボリュームグループでドライブに障害が発生した場合に、ストレージアレイでスタンバイとして機能します。ホットスペアを使用すると、ストレージアレイの冗長性が向上します。

一般に、ホットスペアドライブには、保護対象のドライブの使用済み容量以上の容量が必要です。ホットスペアドライブのメディアタイプ、インターフェイスタイプ、および容量は、保護対象のドライブと同じである必要があります。

ストレージアレイのドライブで障害が発生した場合、通常は障害が発生したドライブの代わりにホットスペアが自動的に使用されます。ドライブ障害の発生時にホットスペアが使用可能であれば、冗長性データパリティを使用してホットスペアにデータが再構築されます。データ退避のサポートでは、障害が発生したドライブとしてマークされる前に、データをホットスペアにコピーすることもできます。

障害が発生したドライブを物理的に交換したら、次のいずれかのオプションを使用してデータをリストアできます。

障害が発生したドライブを交換すると、ホットスペアのデータが交換用ドライブにコピーされます。この操作をコピーバックと呼びます。

ホットスペアドライブをボリュームグループの永続的メンバーとして指定する場合は、コピーバック処理は不要です。

ボリュームグループのトレイ損失の保護およびドロワー損失の保護が可能かどうかは、ボリュームグループを構成するドライブの場所によって異なります。ドライブの障害とホットスペアドライブの場所によっては、トレイ損失の保護とドロワー損失の保護が失われる場合があります。トレイ損失の保護とドロワー損失の保護が影響を受けないようにするには、障害が発生したドライブを交換してコピーバックプロセスを開始する必要があります。

ストレージアレイでは、Data Assurance（DA）が有効なボリュームのホットスペア対象範囲としてDA対応ドライブが自動的に選択されます。

DAが有効なボリュームのホットスペア対象範囲のストレージアレイにDA対応ドライブがあることを確認してください。DA対応ドライブの詳細については、Data Assurance機能を参照してください。

セキュリティ対応（FIPSおよびFDE）ドライブは、セキュリティ対応とセキュリティ非対応の両方のドライブのホットスペアとして使用できます。セキュリティ非対応ドライブは、他のセキュリティ非対応ドライブに対して、また、ボリュームグループでセキュリティが有効になっていない場合はセキュリティ対応ドライブに対しても、対応可能です。FIPSボリュームグループは、FIPSドライブのみをホットスペアとして使用できます。ただし、FIPSホットスペアは、セキュリティ非対応、セキュリティ対応、およびセキュリティ有効のボリュームグループに対して使用できます。

ホットスペアがない場合でも、ストレージアレイの動作中に、障害が発生したドライブを交換できます。RAID 1、RAID 3、RAID 5、またはRAID 6のボリュームグループの一部であるドライブは、冗長性データパリティを使用して、交換用ドライブにデータを自動的に再構築します。この操作を再構築と呼びます。



== セグメントサイズ

コントローラがボリューム内の1つのドライブに書き込めるデータブロックの数は、セグメントのサイズによって決まります。各データブロックには512バイトのデータが格納されます。データブロックはストレージの最小単位です。セグメントのサイズによって、格納されるデータブロックの数が決まります。たとえば、8KBのセグメントには16個のデータブロックが含まれます。64KBのセグメントには128個のデータブロックが含まれます。

セグメントサイズの値を入力すると、その値は、実行時にコントローラで指定される、サポートされている値と照合されます。入力した値が無効な場合、コントローラは有効な値のリストを返します。1つの要求に対して1つのドライブを使用することで、他のドライブでは他の要求に同時に対応できます。ボリュームが属している環境で、1人のユーザが大量のデータ（マルチメディアなど）を転送している場合は、1つのデータ転送要求を1つのデータストライプで処理すると、パフォーマンスが最大化されます。（データストライプはセグメントサイズであり、これに、データ転送に使用されるボリュームグループ内のドライブ数が掛けられます）。 この場合、同じ要求に対して複数のドライブが使用されますが、各ドライブへのアクセスは1回だけとなります。

マルチユーザデータベースまたはファイルシステムのストレージ環境で最適なパフォーマンスを実現するには、データ転送要求を満たすために必要なドライブ数が最小限になるように、セグメントサイズを設定します。



== キャッシュ読み取りプリフェッチ

キャッシュ読み取りプリフェッチを使用すると、コントローラは、ホストによって要求されたデータブロックをドライブから読み取ってキャッシュにコピーすると同時に、追加のデータブロックをキャッシュにコピーできます。これにより、以降のデータ要求をキャッシュから処理できる可能性が高くなります。キャッシュ読み取りプリフェッチは、シーケンシャルデータ転送を使用するマルチメディアアプリケーションにとって重要です。「cacheReadPrefetch」パラメータの有効な値は「TRUE」または「FALSE」です。デフォルトは「true」です。



== セキュリティタイプ

ストレージ・アレイのセキュリティ設定を指定するには'securityType'パラメータを使用します

'securityType'パラメータを'enabled'に設定する前に'ストレージ・アレイのセキュリティ・キーを作成する必要がありますストレージ・アレイのセキュリティ・キーを作成するには'create storageArray securityKey'コマンドを使用します次のコマンドがセキュリティキーに関連しています。

* 「create storageArray securityKey」のように指定します
* 「export storageArray securityKey」のように指定します
* 「import storageArray securityKey」のように入力します
* 「set storageArray securityKey」のように指定します
* [Enable volumeGroup [volumeGroupName] security]を有効にします
* 「enable diskPool [diskPoolName]のセキュリティ」を参照してください




== セキュアドライブ

セキュリティ対応ドライブには、Full Disk Encryption（FDE）ドライブと連邦情報処理標準（FIPS）ドライブがあります。secureDrivesパラメータを使用して、使用するセキュアドライブのタイプを指定します。使用できる値は'FIPs'とFDEです



== コマンドの例

[listing]
----
show storageArray autoConfiguration securityType=capable secureDrives=fips;
----


== 最小ファームウェアレベル

7.10で、RAIDレベル6機能が追加され、ホットスペアの制限がなくなりました。

7.50で、「securityType」パラメータが追加されました。

7.75で'dataAssuranceパラメータが追加されました

8.25で'secureDrives'パラメータが追加されました
