---
permalink: commands-a-z/show-syncmirror-synchronizationprogress.html 
sidebar: sidebar 
keywords: show, synchronous, mirror, volume, synchronization, progress 
summary: show SyncMirror synchronizationProgressコマンドは、同期ミラーリング構成のプライマリボリュームとセカンダリボリューム間のデータ同期の進捗状況を返します。 
---
= 同期ミラーリングボリュームの同期の進行状況を表示する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「show SyncMirror synchronizationProgress」コマンドは、同期ミラーリング構成のプライマリボリュームとセカンダリボリューム間のデータ同期の進捗状況を返します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、またはE5700のストレージアレイに対して実行するには、Storage AdminまたはStorage Monitorロールが必要です。



== コンテキスト（Context）

このコマンドの進捗状況は、完了したデータ同期の割合で示されます。

[NOTE]
====
このコマンドの以前のバージョンでは、機能識別子は「remoteMirror」でした。この機能識別子は有効ではなくなりSyncMirror *'に置き換えられます

====


== 構文

[source, cli, subs="+macros"]
----
show syncMirror (localVolume pass:quotes[[_volumeName_]] |
localVolumes pass:quotes[[_volumeName1_... _volumeNameN_]]) synchronizationProgress
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
同期の進捗状況をチェックするリモートミラーペアのプライマリボリュームの名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名に特殊文字または数字が含まれている場合は、ボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「ボリューム」
 a| 
同期の進捗状況をチェックするリモートミラーペアのプライマリボリュームの名前。以下のルールを使用して、ボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


ボリューム名が特殊文字を含んでいる場合または数字のみで構成されている場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。


|===


== 最小ファームウェアレベル

5.40
