---
permalink: commands-a-z/show-diskpool.html 
sidebar: sidebar 
keywords: show, disk pool 
summary: show diskPoolコマンドは、ディスクプールに関する情報を返します。 
---
= ディスクプールを表示します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
show diskPoolコマンドは'ディスク・プールに関する情報を返します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドは、ディスクプールに関する次の情報を返します。

* ステータス（最適、デグレード、失敗、不明など）
* 合計容量
* 予約済み容量、使用可能容量、使用不可容量
* 使用済み容量、空き容量、使用率
* 現在の所有者（スロットAのコントローラまたはスロットBのコントローラ）
* ドライブメディア（SAS）
* ドライブメディアタイプ（HDDまたはSSD）
* ドライブインターフェイスタイプ（Fibre Channel、iSCSI、InfiniBand、SAS）
* トレイ損失の保護（yesまたはno）
* セキュリティ対応-ディスクプールがセキュリティ対応ドライブだけで構成されているかどうかを示します。セキュリティ対応ドライブには、FDEドライブとFIPSドライブがあります。
* セキュア-ディスクプールでドライブセキュリティがオンになっている（セキュリティ有効）かどうかを示します。
* 残り容量の通知設定（重大警告と早期警告）
* 優先度の設定
* 関連付けられているボリュームと空き容量
* 関連付けられているドライブ
* Data Assurance機能およびData Assuranceが有効なボリュームがある
* リソースプロビジョニング機能




== 構文

[source, cli, subs="+macros"]
----
pass:quotes[show diskPool [_diskPoolName_]]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「diskPool」
 a| 
情報を取得するディスクプールの名前。ディスクプール名は角かっこ（[]）で囲みます。ディスクプール名に特殊文字または数字が含まれている場合は、ディスクプール名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。

|===


== 注：

このコマンドは、ストレージアレイプロファイルのディスクプールに関する内容を表示する場合に使用します。



== 最小ファームウェアレベル

7.83
