---
permalink: commands-a-z/show-asyncmirrorgroup-summary.html 
sidebar: sidebar 
keywords: show, asynchronous, mirror, groups 
summary: show asyncMirrorGroup summaryコマンドは、1つ以上の非同期ミラーグループの設定情報を表示します。 
---
= 非同期ミラーグループの表示 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
「show asyncMirrorGroup summary」コマンドは、1つ以上の非同期ミラーグループの設定情報を表示します。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドでは、不完全な非同期ミラーペアも含め、各非同期ミラーグループに関連付けられている非同期ミラーペアも表示されます。

このコマンドを使用して、非同期ミラーグループ内のすべてのミラーペアについて、定期的なデータ同期の進捗状況を表示することもできます。



== 構文

[source, cli, subs="+macros"]
----
show (allAsyncMirrorGroups |
asyncMirrorGroup pass:quotes[[_asyncMirrorGroupName_]] |
asyncMirrorGroups pass:quotes[[_asyncMirrorGroupName1_ ... _asyncMirrorGroupNameN_]])
[summary]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allAsyncMirrorGroups」を参照してください
 a| 
このパラメータを使用して、すべての非同期ミラーグループのプロパティを表示します。



 a| 
「asyncMirrorGroup」
 a| 
設定情報および定期的なデータ同期の進捗状況を表示する非同期ミラーグループの名前。非同期ミラーグループ名は角かっこ（[]）で囲みます。非同期ミラーグループ名に特殊文字または数字が含まれている場合は、非同期ミラーグループ名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「asyncMirrorGroups」を参照してください
 a| 
情報を取得する複数の非同期ミラーグループの名前。以下のルールを使用して、非同期ミラーグループの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


非同期ミラーグループ名に特殊文字または数字が含まれている場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
「概要」
 a| 
このパラメータは、1つ以上の非同期ミラーグループについて、同期の進捗状況の概要を表示します。

|===


== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
