---
permalink: commands-a-z/show-alldrives.html 
sidebar: sidebar 
keywords: show, drive 
summary: show allDrivesコマンドは、ストレージアレイ内のドライブに関する情報を返します。 
---
= ドライブの表示 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
show allDrivesコマンドを実行すると、ストレージアレイ内のドライブに関する情報が返されます。



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

このコマンドは、ストレージアレイ内の各ドライブについて次の情報を返します。

* ドライブの総数
* ドライブのタイプ（SASまたはNVMe4K）
* 基本ドライブに関する情報
+
** トレイの場所とスロットの場所
** ステータス
** 容量
** データ転送率
** 製品ID
** ファームウェアレベル


* SSDドライブの消耗度に関する情報（アレイにSSDドライブが搭載されていない場合は表示されません）：
+
** 平均消去回数。
** スペアブロックの残量
** 使用済み寿命の割合（11.41リリースの新機能）。使用済み寿命は、これまでにSSDドライブに書き込まれたデータ量を、ドライブの理論上の合計書き込み量で割った値です。


* ドライブチャネルに関する情報
+
** トレイの場所とスロットの場所
** 優先チャネル
** 冗長チャネル


* ホットスペアの適用対象範囲
* 各ドライブの詳細
+
[NOTE]
====
NVMeドライブの製造日情報は返されません。

====




== 構文

[source, cli, subs="+macros"]
----
show ((allDrives
[driveMediaType=(HDD | SSD | unknown | allMedia)] |
[driveType=( SAS | NVMe4K)]) |
(drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]]))
summary
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allDrives」を参照してください
 a| 
ストレージアレイ内のすべてのドライブに関する情報を返すための設定。



 a| 
driveMediaType
 a| 
情報を取得するドライブメディアのタイプ。有効な値は次のとおりです。

* [HDD]--ドライブトレイにハードドライブがある場合は'このオプションを使用します
* SSD'--ドライブトレイにソリッドステートドライブがある場合は'このオプションを使用します
* 不明--どのタイプのドライブメディアがドライブトレイにあるかわからない場合は'このオプションを使用します
* [allMedia]--ドライブトレイにあるすべてのタイプのドライブメディアを使用する場合に'このオプションを使用します




 a| 
「ドライブタイプ」
 a| 
情報を取得するドライブのタイプ。ドライブタイプを混在させることはできません。

有効なドライブタイプは次のとおりです。

* 「SAS」
* 「NVMe4K」


ドライブタイプを指定しない場合、このコマンドはデフォルトでany typeになります。



 a| 
「ドライブ」または「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。



 a| 
「概要」
 a| 
指定したドライブのステータス、容量、データ転送率、製品ID、およびファームウェアバージョンを返すための設定。

|===


== 注：

ストレージ・アレイ内のすべてのドライブのタイプと場所に関する情報を確認するには'allDrivesパラメータを使用します

ストレージアレイ内のSASドライブに関する情報を確認するには、「drivetype」パラメータを使用します。

特定の場所にあるドライブのタイプを確認するには'drive'パラメータを使用し'ドライブのトレイIDとスロットIDを入力します

'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。



== 最小ファームウェアレベル

5.43

7.60で'drawerID'ユーザー入力と'driveMediaType'パラメータが追加されました

8.41で、E2800、E5700、またはEF570システムのSSDドライブの消耗度レポート情報が追加されました。使用済み寿命の割合の形式で表示されます。
