---
permalink: commands-a-z/show-ssd-cache-statistics.html 
sidebar: sidebar 
keywords: show, ssd, cache, statistics 
summary: show ssdCacheコマンドは、SSDキャッシュの使用状況に関するデータを表示します。 
---
= SSDキャッシュの統計を表示します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
「show ssdCache」コマンドは、SSDキャッシュの使用状況に関するデータを表示します。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700などの個 々 のストレージアレイを環境に設定します。 EF600およびEF300アレイ（すべてのSMcliパッケージがインストールされている必要があります。



== ロール

このコマンドをE2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Support Adminロールが必要です。



== 構文

[listing, subs="+macros"]
----
show ssdCache pass:quotes[[_ssdCacheName_]] [ssdCacheStatistics]
[controller=(a|b|both)]
pass:quotes[[file="_filename_"]]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ssdCache」
 a| 
情報を取得するSSDキャッシュの名前。SSDキャッシュ名は角かっこ（[]）で囲みます。SSDキャッシュ名に特殊文字または数字が含まれている場合は、SSDキャッシュ名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「ssdCacheStatistics」と入力します
 a| 
キャッシュ統計情報を取得することを示す'show ssdCacheコマンドのオプションのパラメータ



 a| 
「controller」と入力します
 a| 
SSDキャッシュメタデータは、それぞれが所有するボリュームについて各コントローラに格納されています。したがって、SSDキャッシュ統計はコントローラごとに管理および表示されます。有効なコントローラ識別子は'a`'b`'またはbothですここで'a`はスロットAのコントローラ'`b'はスロットBのコントローラ'bothは両方のコントローラですコントローラの識別子は角かっこ（[]）で囲みます。コントローラを指定しない場合、デフォルト値は「both」です。



 a| 
'file'
 a| 
SSDキャッシュ統計の保存先となるファイルパスとファイル名。ファイルには、画面に出力される以外の統計も保存されます。

ファイル名は二重引用符（""）で囲みます。例：

'file="C:\Program Files\CLI\logs\ssdcachestats.csv"

任意のファイル名を使用できますが'.csv拡張子を使用する必要があります

|===


== 注：

画面には次の統計が表示されます。

* * reads *-- SSDキャッシュ対応ボリュームのホスト読み取りの合計数。
+
読み取り数を書き込み数と比較します。効率的なSSDキャッシュ処理には、読み取り数が書き込み数より多いことが必要です。書き込みに対する読み取りの比率が大きいほど、キャッシュ処理が向上します。

* * writes *- SSDキャッシュが有効なボリュームに対するホストの書き込みの合計数。
* *キャッシュヒット*--キャッシュヒットの数。
* *キャッシュヒット率(%)*--キャッシュヒット数を読み取りの合計数で割った値。
+
効果的なSSDキャッシュ処理には、キャッシュヒットの割合が50%より高いことが必要です。この値が小さい場合は、次のような理由が考えられます。

+
** 書き込みに対する読み取りの比率が小さすぎる
** 読み取りが繰り返されない
** キャッシュ容量が小さすぎる
+
[NOTE]
====
最適なSSDキャッシュ容量を判別するには'start ssdCache [ssdCacheName] performanceModelingコマンドを使用して'Performance Modeling Toolを実行します

====


* *キャッシュ割り当て率（%）*-割り当てられているSSDキャッシュストレージの量。このコントローラで使用可能なSSDキャッシュストレージの割合として表されます。割り当てられたバイト数を使用可能なバイト数で割った値です。
+
キャッシュ割り当ての割合は、通常は100%と表示されます。この数値が100%未満の場合は、キャッシュがウォームアップされていないか、アクセスされているすべてのデータよりもSSDキャッシュ容量が大きいことを意味します。後者の場合、SSDキャッシュ容量を小さくしても同レベルのパフォーマンスが得られる可能性があります。この値は、キャッシュされたデータがSSDキャッシュに配置されたことを示しているわけではなく、SSDキャッシュにデータを配置可能となる前の準備手順にすぎません。

* *キャッシュ使用率（%）*-有効なボリュームのデータを含むSSDキャッシュストレージの量。割り当てられているSSDキャッシュストレージの割合として表されます。この値はSSDキャッシュの利用率または密度を表し、ユーザデータのバイト数を割り当てられたバイト数で割った値です。
+
キャッシュ使用率の割合は、通常は100%より小さく、多くの場合はるかに小さくなります。この数値は、SSDキャッシュ容量のうち、キャッシュデータが書き込まれている割合を示します。この数値が100%より小さい理由は、SSDキャッシュの各割り当て単位であるSSDキャッシュブロックが、サブブロックと呼ばれる小さい単位に分割され、それぞれ独立して確保されるからです。この値が大きいほど一般には有効ですが、小さい数値でもパフォーマンスが大幅に向上する可能性があります。



ファイルには、次の統計も保存されます。

* * Read Blocks *：ホスト読み取りのブロック数
* *書き込みブロック*--ホスト書き込みのブロック数
* *フルヒットブロック*--ブロックキャッシュヒットの数。
+
この値は、SSDキャッシュから完全に読み込まれたブロックの数を示します。SSDキャッシュがパフォーマンスの向上に効果があるのは、フルキャッシュヒットである処理に対してのみです。

* *部分ヒット*-すべてのブロックではなく、少なくとも1つのブロックがSSDキャッシュ内にあったホスト読み取りの数。これはSSDキャッシュ*ミス*で、ベースボリュームから読み取りが行われた場合に発生します。
+
部分キャッシュヒットと部分キャッシュヒットブロックは、SSDキャッシュ内にデータの一部しかない処理の結果として発生します。この場合、キャッシュされているHDDボリュームからデータを取得する必要があります。このタイプのヒットの場合、SSDキャッシュから得られるパフォーマンス上のメリットはありません。部分キャッシュヒットブロック数が完全キャッシュヒットブロック数より多い場合は、別のI/O特性タイプ（ファイルシステム、データベース、またはWebサーバ）を使用するとパフォーマンスが向上する可能性があります。

* *部分ヒット--ブロック*--部分ヒットのブロック数。
+
部分キャッシュヒットと部分キャッシュヒットブロックは、SSDキャッシュ内にデータの一部しかない処理の結果として発生します。この場合、キャッシュされているHDDボリュームからデータを取得する必要があります。このタイプのヒットの場合、SSDキャッシュから得られるパフォーマンス上のメリットはありません。部分キャッシュヒットブロック数が完全キャッシュヒットブロック数より多い場合は、別のI/O特性タイプ（ファイルシステム、データベース、またはWebサーバ）を使用するとパフォーマンスが向上する可能性があります。

* *Misses *-- SSDキャッシュ内にブロックがなかったホスト読み取りの数。これはSSDキャッシュミスで、ベースボリュームから読み取りが行われた場合に発生します。
* *Misses --ブロック*--ミスしたブロックの数。
* *取り込み処理（ホスト読み取り）*-ベースボリュームからSSDキャッシュにデータがコピーされたホスト読み取りの数。
* *取り込み処理（ホスト読み取り）--ブロック*--取り込み処理（ホスト読み取り）のブロック数。
* *取り込み処理（ホスト書き込み）*-ベースボリュームからSSDキャッシュにデータがコピーされたホスト書き込みの数。
+
書き込みI/O処理によってキャッシュが一杯にならないキャッシュ構成設定では、取り込み処理（ホスト書き込み）の数がゼロになることがあります。

* *取り込み処理（ホスト書き込み）--ブロック*--取り込み処理（ホスト書き込み）のブロック数。
* *無効化処理*-データが無効化された/ SSDキャッシュから削除された回数。キャッシュの無効化処理は、各ホスト書き込み要求、Forced Unit Access（FUA）によるホスト読み取り要求、確認要求、およびその他一部の状況で実行されます。
* *リサイクル処理*-別のベースボリュームやLBA範囲、またはその両方にSSDキャッシュブロックが再利用された回数。
+
効果的なキャッシュでは、読み取り処理と書き込み処理の合計数よりも再利用回数が少ないことが重要です。リサイクル処理の回数が読み取りと書き込みの合計数に近い場合、SSDキャッシュはスラッシングしています。キャッシュ容量を増やす必要があります。または、ワークロードがSSDキャッシュの使用に適していません。

* *使用可能バイト数*- SSDキャッシュ内でこのコントローラが使用できるバイト数。
+
使用可能なバイト数、割り当て済みバイト数、およびユーザデータのバイト数を使用して、キャッシュ割り当て率とキャッシュ利用率が計算されます。

* *割り当てバイト数*- SSDキャッシュから割り当てられている、このコントローラのバイト数。SSDキャッシュから割り当てられたバイトは、空の場合と、ベースボリュームのデータが含まれている場合があります。
+
使用可能なバイト数、割り当て済みバイト数、およびユーザデータのバイト数を使用して、キャッシュ割り当て率とキャッシュ利用率が計算されます。

* *ユーザデータバイト数*-- SSDキャッシュ内でベースボリュームのデータを含む割り当てバイト数。
+
使用可能なバイト数、割り当て済みバイト数、およびユーザデータのバイト数を使用して、キャッシュ割り当て率とキャッシュ利用率が計算されます。





== 最小ファームウェアレベル

7.84

11.80で、EF600およびEF300アレイのサポートが追加されました。
