---
permalink: commands-a-z/show-volume.html 
sidebar: sidebar 
keywords: show, thin, volume 
summary: show volumeコマンドは、指定したシンボリュームの拡張履歴または消費容量を返します。 
---
= シンボリュームの表示 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
show volumeコマンドは'指定したシン・ボリュームの拡張履歴または消費容量を返します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage AdminまたはStorage Monitorロールが必要です。



== 構文

[source, cli, subs="+macros"]
----
show (allVolumes | volume pass:quotes[[_volumeName_]] |
volumes pass:quotes[[_volumeName1_ ... _volumeNameN_]])
(consumedCapacity |
(expansionHistory pass:quotes[[file=_fileName_]]))
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「allVolumes」
 a| 
ストレージアレイ内のすべてのシンボリュームに関する情報を返すためのパラメータ。



 a| 
「 volume 」
 a| 
情報を取得するシンボリュームの名前。シンボリューム名は角かっこ（[]）で囲みます。シンボリューム名に特殊文字または数字が含まれている場合は、シンボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「ボリューム」
 a| 
情報を取得する複数のシンボリュームの名前。以下のルールを使用して、ボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


ボリューム名に特殊文字または数字が含まれる場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
「consumedCapacity」です
 a| 
シンボリュームの消費容量に関する概要情報をリストで返すための設定。



 a| 
「拡張の歴史」
 a| 
シンボリュームの拡張履歴に関する概要情報をリストで返すための設定。



 a| 
'file'
 a| 
'file'パラメータは'expansionHistory'パラメータの出力をログに記録するファイルを指定します'file'は'expansionHistory'パラメータとともに使用する場合にのみ有効です無効なファイル名を指定すると、コマンドが失敗します。

|===


== 注：

「expansionHistory」パラメータを指定すると、次の例のような情報が返されます。

「シン・ボリューム名：ボリューム名リポジトリ・ボリューム名：Repos_nnnn」

[cols="4*"]
|===
| ログ時間 | 拡張タイプ | 容量を開始します | 容量の終了 


 a| 
MM/DD/YYYY HH：MM：SS
 a| 
Manual（手動）| Automatic（自動
 a| 
nnnnnnnnバイト
 a| 
nnnnnnnnバイト

|===
consumedCapacityパラメータを指定すると、次の例のような情報が返されます。

[cols="5*"]
|===
| ボリューム | プロビジョニング済み容量 | 使用済み容量 | クォータ | % Prov.消費済み 


 a| 
「VolumeName」
 a| 
500.000 GB
 a| 
230.000 GB
 a| 
700.000 GB
 a| 
46%

|===


== 最小ファームウェアレベル

7.83
