---
permalink: commands-a-z/smcli-supportbundle-schedule.html 
sidebar: sidebar 
keywords: schedule, automatic, support, bundle, collection, configuration 
summary: SMcli supportbundle scheduleコマンドは、1つ以上のストレージアレイでサポートバンドルを保存するスケジュールを作成または削除します。システムと構成の情報をテクニカルサポートに送信して分析と診断を依頼するには、サポートバンドルに情報を収集します。 
---
= 自動サポートバンドル収集構成のスケジュール - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMcli supportbundle scheduleコマンドは'1つまたは複数のストレージアレイにサポートバンドルを保存するスケジュールを作成または削除しますシステムと構成の情報をテクニカルサポートに送信して分析と診断を依頼するには、サポートバンドルに情報を収集します。

[NOTE]
====
このコマンドはSMcliコマンドであり、スクリプトコマンドではありません。このコマンドはコマンドラインから実行する必要があります。このコマンドは、ストレージ管理ソフトウェア内のスクリプトエディタから実行することはできません。

====
次の2種類のスケジュールを作成できます。

* 日次/週次--新しい構成を監視したり、既存の構成をトラブルシューティングするために頻繁にデータを収集する必要がある場合は、このスケジュールを使用します。
* 月次/年次-ストレージアレイの長期的な運用を評価するためにデータを収集する場合は、このスケジュールを使用します。




== 日次/週次スケジュールを作成するための構文

[source, cli, subs="+macros"]
----
SMcli -supportBundle schedule enable
pass:quotes[(all | _storageArrayName_)]
pass:quotes[startTime=_HH:MM_]
pass:quotes[startDate=_MM:DD:YYYY_]
pass:quotes[endDate=_MM:DD:YYYY_]
daysOfWeek=[Sunday Monday Tuesday Wednesday Thursday Friday Saturday]
pass:quotes[data=_pathName_]
----


== 月次/年次スケジュールを作成するための構文

[source, cli, subs="+macros"]
----
SMcli -supportBundle schedule enable
pass:quotes[(all | _storageArrayName_)]
pass:quotes[startTime=_HH:MM_]
pass:quotes[startDate=_MM:DD:YYYY_]
pass:quotes[endDate=_MM:DD:YYYY_]
months=[January February March April May June July August September October
November December]
weekNumber=(First|Second|Third|Fourth|Last)
dayOfWeek=(Sunday|Monday|Tuesday|Wednesday|Thursday|Friday|Saturday)|
onDays=[1-31] |
pass:quotes[data=_pathName_]
----


== スケジュールを削除するための構文

[NOTE]
====
このコマンドは、ストレージアレイのスケジュールを完全に削除します。サポートバンドル情報の保存を再開するには、新しいスケジュールを作成する必要があります。

====
[source, cli, subs="+macros"]
----
SMcli -supportBundle schedule disable
pass:quotes[(all|_storageArrayName_)]
----


== パラメータ

次の表に、日次/週次スケジュールのパラメータを示します。

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「 enable 」を選択します
 a| 
重大なMELイベントが検出されたときに、サポートバンドルの自動収集を有効にします。このパラメータを指定すると、一時停止されていたサポートバンドルデータの収集が再開されます。新しいスケジュールを作成したり既存のスケジュールを変更したりするときは、このパラメータを使用する必要があります。



 a| 
「すべて」
 a| 
ホストで検出されたすべてのストレージアレイを対象に収集スケジュールを設定するには、このパラメータを使用します。



 a| 
「_storageArrayName_`」のように指定します
 a| 
スケジュールを設定する特定のストレージアレイの名前。



 a| 
「startTime」と入力します
 a| 
サポートバンドルの収集を開始する時刻。時刻の入力形式はHH：MMで、HHは時間、MMは分です。24時間制を使用します。

デフォルトの時刻は00：00、深夜0：00です。開始時刻を入力せずにサポートバンドルの収集を有効にすると、データの収集は午前0時に自動的に実行されます。



 a| 
「startDate」と入力します
 a| 
サポートバンドルデータの収集を開始する日付。日付の入力形式はMM：DD：YYです。

デフォルトは現在の日付です。



 a| 
「endDate」
 a| 
サポートバンドルデータの収集を停止する日付。日付の入力形式はMM：DD：YYです。

デフォルトはnoneです。

このパラメータを使用する場合は、開始日から1週間以上経過した過去ではない日付を指定する必要があります。



 a| 
曜日
 a| 
サポートバンドルデータを収集する曜日または曜日。1日以上の曜日にサポートバンドルデータを収集するには、このパラメータを使用します。例：

[listing]
----
daysOfWeek=[Tuesday]
----
[listing]
----
daysOfWeek=[Monday Wednesday Friday]
----
曜日は角かっこ（[]）で囲みます。複数の日を入力する場合は、各日をスペースで区切ります。



 a| 
「データ」
 a| 
サポートバンドルデータの保存先となるファイルパスとファイル名。例：

[listing]
----
file="C:\Program Files\CLI\sup\data.txt"
----
[NOTE]
====
任意のファイル拡張子を使用できます。

====
ファイルのパスと名前は二重引用符（""）で囲みます。

|===
次の表に、月次/年次スケジュールのパラメータを示します。

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「 enable 」を選択します
 a| 
重大なMELイベントが検出されたときに、サポートバンドルの自動収集を有効にします。このパラメータを指定すると、一時停止されていたサポートバンドルデータの収集が再開されます。新しいスケジュールを作成したり既存のスケジュールを変更したりするときは、このパラメータを使用する必要があります。



 a| 
「すべて」
 a| 
ホストで検出されたすべてのストレージアレイを対象に収集スケジュールを設定するには、このパラメータを使用します。



 a| 
「storageArrayName」
 a| 
スケジュールを設定する特定のストレージアレイの名前。



 a| 
「startTime」と入力します
 a| 
サポートバンドルの収集を開始する時刻。時刻の入力形式はHH：MMで、HHは時間、MMは分です。24時間制を使用します。

デフォルトの時刻は00：00、深夜0：00です。開始時刻を入力せずにサポートバンドルの収集を有効にすると、データの収集は午前0時に自動的に実行されます。



 a| 
「startDate」と入力します
 a| 
サポートバンドルデータの収集を開始する日付。日付の入力形式はMM：DD：YYです。

デフォルトは現在の日付です。



 a| 
「endDate」
 a| 
サポートバンドルデータの収集を停止する日付。日付の入力形式はMM：DD：YYです。

デフォルトはnoneです。



 a| 
「月」
 a| 
サポートバンドルデータを収集する年の特定の月または月。1カ月以上のサポートバンドルデータを収集するには、このパラメータを使用します。例：

[listing]
----
months=[June]
----
[listing]
----
months=[January April July October]
----
月は角かっこ（[]）で囲みます。複数の月を入力する場合は、各月をスペースで区切ります。



 a| 
「weekNumber」
 a| 
サポートバンドルデータを収集する週。例：

[listing]
----
weekNumber=first
----


 a| 
「DayOfWeek」
 a| 
サポートバンドルデータを収集する曜日。1日のサポートバンドルデータのみを収集するには、このパラメータを使用します。例：

[listing]
----
dayOfWeek=Wednesday
----


 a| 
「onDays」
 a| 
サポートバンドルデータを収集する特定の日にちと曜日。例：

[listing]
----
onDays=[15]
----
[listing]
----
onDays=[7 21]
----
日は角かっこ（[]）で囲みます。複数の日を入力する場合は、各日をスペースで区切ります。

[NOTE]
====
'*onDays*'パラメータは'*weekNumber*'パラメータまたは*DayOfWeek*'パラメータのいずれかでは使用できません

====


 a| 
「データ」
 a| 
サポートバンドルデータの保存先となるファイルパスとファイル名。例：

[listing]
----
file="C:\Program Files\CLI\sup\data.txt"
----
[NOTE]
====
任意のファイル拡張子を使用できます。

====
ファイルのパスと名前は二重引用符（""）で囲みます。

|===
次の表に、スケジュールを削除する場合のパラメータを示します。

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「不可能」
 a| 
サポートバンドルの自動収集を無効にし、以前に定義されたすべてのスケジュールをただちに削除します。

[NOTE]
====
スケジュールを無効にすると、そのスケジュールも削除されます。

====


 a| 
「すべて」
 a| 
ホストで検出されたすべてのストレージアレイを対象に収集スケジュールを設定するには、このパラメータを使用します。



 a| 
「storageArrayName」
 a| 
スケジュールを設定する特定のストレージアレイの名前。

|===


== 注：

allパラメータを使用してすべてのストレージ・アレイに共通のスケジュールを設定すると'個のストレージ・アレイのスケジュールは削除されますすべてのストレージアレイに1つのスケジュールが設定されている場合、新たに検出されたストレージアレイには同じスケジュールが適用されます。すべてのストレージアレイに1つのスケジュールを設定したあとに単一のストレージアレイにスケジュールを設定すると、新たに検出されたストレージアレイにはスケジュールは設定されません。

このコマンドの使用例を次に示します。最初の例では、次の基準を満たす、サポートバンドルデータ収集用の日次/週次スケジュールを作成します。

* ストレージアレイ名はDevKit4
* 収集開始時刻は02：00（午前2時）
* 開始日は05：01：2013（2013年5月1日）
* データは毎週月曜日と金曜日に収集されます
* このスケジュールには終了日はなく'SMcli supportbundle schedule disableコマンドを実行することによってのみ停止できます


[listing]
----
SMcli -supportBundle schedule enable DevKit4 startTime=02:00
startDate=05:01:2013 endDate=05:10:2014 daysOfWeek=[Monday Friday]
----
2番目の例では、次の基準を満たす、サポートバンドルデータ収集用の月次/年次スケジュールを作成します。

* ストレージアレイ名はeng_usersです
* 収集開始時刻は04：00（午前4時）
* 開始日は05：01：2013（2013年5月1日）
* データは3月、4月、5月、6月、8月に収集されます
* 各月の1日と21日にデータが収集されます
* このスケジュールには終了日はなく'SMcli supportbundle schedule disableコマンドを実行することによってのみ停止できます


[listing]
----
SMcli -supportBundle schedule enable eng_stor1 startTime=04:00
startDate=05:01:2013 months=[March April May June August] onDays=[1 21]
----
3番目の例では、次の基準を満たす、サポートバンドルデータ収集用の月次/年次スケジュールを作成します。

* ストレージアレイ名はfirmware_2です
* 収集開始時刻は22：00（夜10：00）
* 開始日は05：01：2013（2013年5月1日）
* データは3月、4月、5月、6月、8月に収集されます
* 各月の最初の週の金曜日にデータが収集されます
* このスケジュールは05：10：2014（2014年5月10日）に終了


[listing]
----
SMcli -supportBundle schedule enable firmware_2 startTime=22:00
startDate=05:01:2013 endDate=05:10:2014 months=[March April May June August]
weekNumber=First dayOfWeek=Friday
----


== 最小ファームウェアレベル

7.83
