---
permalink: commands-a-z/smcli-enable-disable-autosupportremotediag.html 
sidebar: sidebar 
keywords: enable, disable, autosupport, remote, diagnostics, feature, emw, management, domain, level, smcli 
summary: SMcli の enable/disable autoSupportRemoteDiag コマンドは、AutoSupport リモート診断機能をオンまたはオフにします。この機能により、テクニカルサポートは問題をリモートで診断するためのサポートデータを要求できます。 
---
= EMW管理ドメインレベルでAutoSupportリモート診断機能を有効または無効にする（SMcliのみ） - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMcli enable | disable autoSupportRemoteDiagコマンドは、AutoSupport リモート診断機能をオンまたはオフにします。この機能により、テクニカルサポートは、サポートデータを要求して問題をリモートで診断できます。



[[supported-arrays]]
== サポートされているアレイ

このコマンド環境 は、管理ドメイン内のE2700とE5600のすべてのストレージアレイを一度に削除します。E4000、E2800、E5700のストレージアレイには適用されません。



[[context]]
== コンテキスト（Context）

[NOTE]
====
このコマンドはSMcliコマンドであり、スクリプトコマンドではありません。このコマンドはコマンドラインから実行する必要があります。このコマンドは、ストレージ管理ソフトウェア内のスクリプトエディタから実行することはできません。

====
[NOTE]
====
このコマンドは、管理ドメイン内のすべてのASUP対応ストレージアレイに影響します。

====
この機能を有効にする前に、まずAutoSupport 機能、次にAutoSupport OnDemand機能を管理ドメイン上で有効にします。

3つの機能はこの順序で有効にする必要があります。

. * AutoSupport を有効にします。*
. * AutoSupport OnDemand*を有効にします
. * AutoSupport Remote Diagnosticsを有効にします。*




[[syntax]]
== 構文

[source, cli]
----
SMcli enable|disable autoSupportRemoteDiag
----


[[parameters]]
== パラメータ

なし



[[verification]]
== 検証

SMcli -autoSupportConfig showコマンドを使用して、この機能を有効にしているかどうかを確認します。表示される出力の最初の3行には、AutoSupport 機能とAutoSupport OnDemand機能の有効ステータス、およびAutoSupport Remote Diagnostics機能のステータスが順番に表示されます。

[listing]
----
The AutoSupport feature is activated on this storage management
station.
The AutoSupport OnDemand feature is activated on this storage management
station.
The AutoSupport Remote Diagnostics feature is activated on this storage
management station.
----


[[minimum-firmware-level]]
== 最小ファームウェアレベル

8.25
