---
permalink: commands-a-z/start-controller.html 
sidebar: sidebar 
keywords: start, controller, trace 
summary: start controllerコマンドは、デバッグトレース情報を圧縮ファイルに保存する処理を開始します。 
---
= コントローラのトレースを開始します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
start controllerコマンドは'デバッグ・トレース情報を圧縮ファイルに保存するオペレーションを開始します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

デバッグトレース情報は、テクニカルサポートがストレージアレイの稼働状況を分析するために使用します。



== 構文

[source, cli, subs="+macros"]
----
start controller [(a
 | b
 | both)] trace
dataType=(current | flushed | currentFlushed | all)
forceFlush=(TRUE | FALSE)
pass:quotes[file="_fileName_]"
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「controller」と入力します
 a| 
トレースデバッグ情報を収集するコントローラ。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラです「both」を入力すると、両方のコントローラのデバッグを同時に収集できます。コントローラの識別子は角かっこ（[]）で囲みます。コントローラを指定しないと、ストレージ管理ソフトウェアから構文エラーが返されます。



 a| 
「データ型」
 a| 
収集するデータのタイプ。

* 現在のdqトレース--現在のdqトレースを取得します
* flushed -フラッシュされたすべてのDQトレース
* currentFlushed --現在のDQトレースとフラッシュされたDQトレースの両方を取得します
* all --現在のDQトレース、フラッシュされたDQトレース、およびすべてのプラットフォームDQトレース


[NOTE]
====
'datatype=flushed'および'forceFlush=True'の場合'取得時にバッファにフラッシュできるのはアクティブなトレースだけであることを示すエラーメッセージが返されます

====


 a| 
「* forceFlush *」
 a| 
datatypeパラメータで定義されたDQトレース情報が取得されたときに、現在のバッファのDQ情報をフラッシュバッファに移動するための設定。強制的なフラッシュをイネーブルにするには、このパラメータを「true」に設定します。強制的なフラッシュを無効にするには'このパラメータをFALSEに設定します

[NOTE]
====
'datatype=flushed'および'forceFlush=True'の場合'取得時にバッファにフラッシュできるのはアクティブなトレースだけであることを示すエラーメッセージが返されます

====


 a| 
'file'
 a| 
DQトレース情報の保存先となるファイルパスとファイル名。ファイル名は二重引用符（""）で囲みます。

ファイルの命名方法については、「メモ」セクションを参照してください。

|===


== 注：

DQトレース情報は、.zip拡張子の付いた圧縮ファイルに書き込まれます。ファイル名は、ユーザ定義のファイル名とストレージアレイ識別子（SAID）を組み合わせたものです。末尾に「dq」も追加されます。完全なファイル名の形式は次のとおりです。

[listing]
----
user_defined_file_name-SAID-dq.zip
----
圧縮ファイルに含まれる情報を次の表に示します。

[cols="3*"]
|===
| ファイル名（ File Name ） | ディレクトリ | コメント 


 a| 
「user_provided _file_name - SAID - A.dq」という形式になります
 a| 
「SAID /タイムスタンプ/
 a| 
コントローラAから取得したDQトレースデータ



 a| 
「user_provided _file_name -sSAID -bdq」という形式になります
 a| 
「SAID /タイムスタンプ/
 a| 
コントローラBから取得したDQトレースデータ



 a| 
「user_provided _file_name-sSAID」-「trace_descriptionXM」
 a| 
「SAID /タイムスタンプ/
 a| 
将来のデータマイニングに使用する、DQファイルの属性が記述されたXML形式の概要 ファイル。

|===


== 最小ファームウェアレベル

7.75
