---
permalink: commands-a-z/start-ioclog.html 
sidebar: sidebar 
keywords: start, input, output, controller, ioc, dump 
summary: start IOCLogコマンドは、ホストとコントローラ間のデータ送信のIOCログをダンプします。 
---
= 入出力コントローラ（IOC）ダンプを開始します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
start IOCLogコマンドは、ホストとコントローラ間のデータ送信のIOCログをダンプします。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700を含む個々のストレージアレイ環境 SMcliパッケージがすべてインストールされていれば、EF600およびEF300アレイ



== ロール

このコマンドをE2800、E5700、EF600、またはEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

コントローラは「a」または「b」として識別されます。各コントローラには最大4つのホストチャネルを設定でき、各チャネルは1~8の番号で一意に識別されます。



== 構文

[listing]
----
start IOCLog [(a1 | a2 | a3 | a4 | a5 | a6 | a7 | a8 | b1 | b2 | b3 | b4 | b5 | b6 | b7 | b8)]
[overwrite=(TRUE | FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「コントローラチャネル識別子」
 a| 
このパラメータは、IOCダンプの作成元となるコントローラとホストチャネルを指定します。有効なコントローラ識別子は「a」または「b」です。「a」はスロットAのコントローラ、「b」はスロットBのコントローラですホストチャネルは数値で識別されます。コントローラとホストチャネルの識別子は角かっこ（[]）で囲みます。

有効なコントローラ識別子とホストチャネルの値は `a1`、、 `a2`、 `a3` `a4` `a5`、、です。 `a6` `a7`、、 `a8`、 `b1`、、 `b2` `b3` `b4`、、 `b5`、 `b6`、、 `b7` `b8`または。

コントローラを指定しないと、ストレージ管理ソフトウェアから構文エラーが返されます。



 a| 
「上書き」
 a| 
このパラメータを使用すると、新しいIOCログダンプで既存のダンプが上書きされます。既存のダンプを上書きするには'このパラメータをTRUEに設定しますデフォルト値は'FALSE'です

|===


== 注：

このコマンドは、選択したコントローラのIOCからデバッグログを生成し、コントローラ上の永続的メモリバッファにデータを圧縮して格納します。save IOCLogコマンドを使用すると、デバッグログからデータを取得できます。コントローラから次の状況のエラーが返されます。

* コントローラプラットフォームとHICがIOCダンプをサポートしていない。
* 指定したコントローラに未処理のIOCダンプがあり、overwriteパラメータがfalseに設定されている。
* 指定したコントローラ識別子またはチャネル識別子が有効な範囲外です。




== 最小ファームウェアレベル

8.20で
