---
permalink: commands-a-z/start-secureerase-drive.html 
sidebar: sidebar 
keywords: start, fde, secure, drive, erase 
summary: start secureErase driveコマンドは、Full Disk Encryption（FDE）ドライブのすべてのデータを消去して、FDEドライブとして再利用できるようにします。 
---
= FDEドライブの完全消去を開始します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
start secureErase driveコマンドは'1つまたは複数のFull Disk Encryption (FDE)ドライブからすべてのデータを消去して'FDEドライブとして再利用できるようにします



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Security Adminロールが必要です。



== コンテキスト（Context）

このコマンドは、FDEドライブがセキュアなボリュームグループまたはディスクプールのメンバーでなくなった場合、またはセキュリティキーが不明な場合にのみ実行します。

[NOTE]
====
ドライブがロックされていて、そのドライブのロックを解除するためのセキュリティキーが使用できないときにFIPSドライブを消去するには、「set drive securityID」コマンドを使用します。

====


== 構文

[source, cli, subs="+macros"]
----
[start secureErase (drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] | drives pass:quotes[[_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_]])
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ドライブ」または「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

[NOTE]
====
drivesリストにストレージアレイのすべてのドライブを指定するとコマンドが拒否されます。すべてのドライブを完全消去するには、ドライブのリストを2つのグループに分けて指定し、このコマンドを2回実行します。

====
|===


== 注：

コントローラファームウェアによってロックが作成され、FDEドライブへのアクセスが制限されます。FDEドライブには、Security Capableという状態があります。セキュリティキーを作成すると、状態はSecurity Enabledに設定され、これによって、ストレージアレイ内に存在するすべてのFDEドライブへのアクセスが制限されます。



== 最小ファームウェアレベル

7.40
