---
permalink: commands-a-z/start-volume-initialize.html 
sidebar: sidebar 
keywords: initialize, thin volume 
summary: start volume initializeコマンドは、シンボリュームを初期化または再初期化します。 
---
= シンボリュームの初期化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
start volume initialize'コマンドは'シン・ボリュームを初期化または再初期化します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

使用するパラメータに応じて操作が異なります。

* オプションパラメータなしでこのコマンドを使用すると、シンボリューム上のデータが削除されます。リポジトリボリュームの容量には影響しません。
* オプションのパラメータを指定して、原因 の再初期化およびリポジトリボリュームの操作を実行します。


[NOTE]
====
シンボリュームの初期化は長時間の処理で、途中で停止することはできません。

====


== 構文

[source, cli, subs="+macros"]
----
pass:quotes[start volume [_volumeName_]] initialize
pass:quotes[[existingRepositoryLabel=_existingRepositoryName_]]
pass:quotes[[diskPool=_diskPoolName_ capacity=_capacityValue_]]
[retainRepositoryMembers=(TRUE|FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
初期化を開始するボリュームの名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名が特殊文字を含んでいる場合または数字のみで構成される場合は、ボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
'existingRepositoryLabel'です
 a| 
このパラメータは、リポジトリボリュームを指定したボリュームの候補で置き換えます。

* 指定する値は、既存のリポジトリボリュームのユーザラベルです。指定するボリュームは、適切な形式の名前を持つ未使用のリポジトリボリュームである必要があります。
* 新しく指定したリポジトリボリュームが別のディスクプール上にある場合、シンボリュームはそのプールに所有権を移します。
* デフォルトでは、古いリポジトリボリュームは削除されます。


既存のリポジトリボリューム名が特殊文字を含んでいる場合または数字のみで構成される場合は、ボリューム名を二重引用符（""）で囲む必要があります。



 a| 
「diskPool」
 a| 
指定した容量を持つ新しいリポジトリボリュームを作成するディスクプールの名前。ディスクプール名が特殊文字を含んでいる場合または数字のみで構成される場合は、ディスクプール名を二重引用符（""）で囲む必要があります。

指定した容量を持つ新しいリポジトリ・ボリュームを作成するには'このパラメータをcapacityパラメータとともに使用する必要があります



 a| 
「容量」
 a| 
作成するリポジトリボリュームに設定するサイズ。サイズは'bytes'KB'MB`'GB'TB'の単位で定義されます

最小物理容量は4GBです。

最大物理容量は257TBです。

指定した容量を持つ新しいリポジトリ・ボリュームを作成するには'diskPool'パラメータとともにこのパラメータを使用する必要があります



 a| 
retainRepositoryMembers
 a| 
このパラメータがTRUEに設定されている場合'古いリポジトリは保持されますデフォルトでは、古いリポジトリは削除されます。既存のリポジトリが再利用される場合、このパラメータは無視されます。

|===


== 注：

volumeパラメータでボリュームを指定しない場合'このコマンドはリポジトリ内のメタデータをリセットし'実際には'ホストに対してシン・ボリュームが空であると表示されます「* volume *」パラメータでボリュームを指定した場合、そのボリュームは新しく作成されたボリュームに置き換えられます。「existingRepositoryLabel」パラメータを使用してボリュームを指定した場合は、既存のボリュームに置き換えられます。別のディスク・プールにある既存のボリュームを'existingRepositoryLabel'パラメータで指定すると'シン・ボリュームは新しいディスク・プールに所有権を変更します

仮想容量、クォータ、警告しきい値など、シンボリュームのボリュームパラメータは、シンボリュームの再初期化後も以前の値のままです。

[NOTE]
====
Immediate Availability Format（IAF）は、64TBを超えるボリュームには適用されません。

====
次の表に、シンボリュームの容量制限を示します。

[cols="2*"]
|===
| 容量のタイプ | サイズ 


 a| 
最小仮想容量
 a| 
32 MB



 a| 
最大仮想容量
 a| 
256 TB



 a| 
最小物理容量
 a| 
4 GB



 a| 
最大物理容量
 a| 
257TB

|===
シンボリュームでは、標準ボリュームで行われるすべての処理がサポートされます。ただし、次の例外があります。

* シンボリュームのセグメントサイズは変更できません。
* シンボリュームでは読み取り前冗長性チェックを有効にできません。
* ボリュームコピーでは、シンボリュームをターゲットボリュームとして使用できません。
* 同期ミラーリング処理ではシンボリュームを使用できません。


シンボリュームを標準ボリュームに変更する場合は、ボリュームコピー処理を使用してシンボリュームのコピーを作成します。ボリュームコピーのターゲットは常に標準ボリュームです。



== 最小ファームウェアレベル

7.83

8.30で、シンボリュームの最大容量が256TBに拡張されました。
