---
permalink: commands-a-z/start-drive-initialize.html 
sidebar: sidebar 
keywords: start, drive, initialize 
summary: start drive initializeコマンドは、ドライブの初期化を開始します。 
---
= ドライブの初期化を開始する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
start drive initializeコマンドは'ドライブの初期化を開始します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700、EF600、EF300を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
*ストレージ・アレイ構成への損傷の可能性*--このコマンドを入力すると'すべてのユーザー・データが破棄されます

====


== 構文

[source, cli, subs="+macros"]
----
start drive pass:quotes[[_trayID_],pass:quotes[[_drawerID_,]]pass:quotes[_slotID_]] initialize
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

|===


== 注：

'drive'パラメータは'大容量ドライブトレイと小容量ドライブトレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。



== 最小ファームウェアレベル

6.10

7.60で'drawerID'ユーザ入力が追加されました
