---
permalink: commands-a-z/start-volumegroup-resourceprovisioning.html 
sidebar: sidebar 
keywords: start, volume, group, resource, provision 
summary: start volumeGroup resourceProvisioningコマンドは、指定されたボリュームグループでリソースプロビジョニングを有効にし、ボリュームグループ内の各ボリュームで非同期処理を実行するリソースプロビジョニング有効化処理を開始します。リソースのプロビジョニングでは、ボリュームグループ内のすべてのドライブがNVMeのDULBE機能をサポートしている必要があります。 
---
= ボリュームグループリソースのプロビジョニングを開始する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
start volumeGroup resourceProvisioningコマンドは'指定されたボリュームグループでリソースプロビジョニングを有効にし'ボリュームグループ内の各ボリュームで非同期オペレーションを実行するリソースプロビジョニングを開始しますリソースをプロビジョニングするには、ボリュームグループ内のすべてのドライブがNVMeのDULBE機能をサポートしている必要があります。



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、EF600、EF300、EF50、EF80アレイを含む、あらゆる個々のストレージアレイに適用されます（ただし、すべてのSMcliパッケージがインストールされている必要があります）。



[[roles]]
== ロール

EF600、EF300、EF50、およびEF80ストレージアレイでこのコマンドを実行するには、Storage AdminまたはSupport Adminロールが必要です。



[[context]]
== コンテキスト（Context）

ボリュームグループでリソースのプロビジョニングを無効にするには、フルプロビジョニングコマンドとオプションを使用して、リソースのプロビジョニングを無効にします。すべてのドライブがDULBE対応で、ストレージアレイの「resourceProvisionedVolumes」設定が「true」の場合、ボリュームグループは作成時にリソースをプロビジョニングします。



[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup[_volumeGroupName_]] resourceProvisioning
----


[[parameters]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「volumeGroupName」と入力します
 a| 
リソースプロビジョニング機能を有効にするボリュームグループ。ボリュームグループ名は角かっこ（[]）で囲みます。

|===


[[minimum-firmware-level]]
== 最小ファームウェアレベル

11.73
