---
permalink: commands-a-z/start-volumegroup-export.html 
sidebar: sidebar 
keywords: start, volume, group, export 
summary: start volumeGroup exportコマンドは、ボリュームグループをエクスポート状態に移行します。 
---
= ボリュームグループのエクスポートを開始する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
start volumeGroup exportコマンドは'ボリューム・グループをエクスポート状態に移行します



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

その後、ボリュームグループを構成するドライブを取り外して、別のストレージアレイに再度取り付けることができます。

[CAUTION]
====
xref:../get-started/learn-about-volume-group-migration.adoc[ボリュームグループの移行について説明します。]に記載されている手順を先に実行せずに、これらの手順を実行しないでください。

====
[NOTE]
====
ボリュームグループ内では、機能に関連付けられているボリュームをストレージアレイ間で移動することはできません。

====


[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
pass:quotes[start volumeGroup [_volumeGroupName_]] export
----


[[parameter]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「volumeGroup」のように指定します
 a| 
エクスポートするボリュームグループの名前。ボリュームグループ名は角かっこ（[]）で囲みます。

|===


[[notes]]
== 注：

このコマンドが正常に実行されると'start volumeGroup importコマンドを実行して'ボリューム・グループの完全な状態への移動を完了できますこれにより'ボリューム・グループを新しいストレージ・アレイで使用できるようになります

ハードウェアの問題によってエクスポートが完了できなかったためにこのコマンドが失敗した場合は、「set volumeGroup forceState」コマンドを使用します。set volumeGroup forceStateコマンドを使用すると'start volumeGroup importコマンドを使用してボリュームグループをインポートできます

ボリュームグループがエクスポート状態または強制状態になったら、ボリュームグループを構成するドライブをストレージアレイから取り外すことができます。ドライブを別のストレージアレイに再度取り付けることができます。



[[minimum-firmware-level]]
== 最小ファームウェアレベル

7.10
