---
permalink: commands-a-z/start-increasevolumecapacity-volume.html 
sidebar: sidebar 
keywords: increase, capacity, volume, disk pool, volume, group 
summary: start increaseVolumeCapacityコマンドは、ディスクプールまたはボリュームグループ内の標準ボリュームまたはリポジトリボリュームの容量を拡張します。 
---
= ディスクプールまたはボリュームグループ内のボリュームの容量を増やす - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
start increaseVolumeCapacity volumeコマンドは'ディスク・プールまたはボリューム・グループ内の標準ボリュームまたはリポジトリ・ボリュームの容量を拡張します



[[supported-arrays]]
== サポートされているアレイ

このコマンドは、すべての SMcli パッケージがインストールされている限り、E4000、E2700、E5600、E2800、E5700、EF600、EF300、EF50、および EF80 アレイを含む、あらゆる個々のストレージアレイに適用されます。



[[roles]]
== ロール

E4000、E2800、E5700、EF600、EF300、EF50、またはEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



[[context]]
== コンテキスト（Context）

このコマンドでは、標準ボリュームはシックボリュームとも呼ばれます。

[NOTE]
====
このコマンドを使用してシンボリュームの容量を拡張することはできません。

====


[[syntax]]
== 構文

[source, cli, subs="+macros"]
----
pass:quotes[start increaseVolumeCapacity volume="_volumeName_"
incrementalCapacity=_volumeCapacity_]
[addDrives=pass:quotes[(_trayID1_],pass:quotes[[_drawerID1_,]]pass:quotes[_slotID1_] ... pass:quotes[_trayIDn_],pass:quotes[[_drawerIDn_,]]pass:quotes[_slotIDn_)]]
----


[[parameters]]
== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「 volume 」
 a| 
容量を拡張するディスクプールまたはボリュームグループ内のボリュームの名前。ボリューム名は二重引用符（""）で囲みます。



 a| 
「増分容量」
 a| 
ボリュームのストレージサイズ（容量）を拡張するための設定。サイズは'bytes'KB'MB`'GB'TB'の単位で定義されますデフォルト値は「bytes」です。



 a| 
「addDrives」を参照してください
 a| 
ボリュームに新しいドライブを追加するための設定。大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

[NOTE]
====
「addDrives」パラメータは、ボリュームグループの容量を増やす場合にのみ使用できます。パラメータを使用してディスクプールの容量を拡張することはできません。

====
|===


[[notes]]
== 注：

場合によっては'drive'パラメータがコマンド構文の有効な入力として表示されることがありますただし'このコマンドでは'drive'パラメータを使用できません

「incrementalCapacity」パラメータを設定すると、長時間実行される処理が開始され、途中で停止することはできません。長時間の処理はバックグラウンドで実行され、他のコマンドの実行が妨げられることはありません。長時間実行中の処理の進捗状況を表示するには、「show volume actionProgress」コマンドを使用します。

'addDrives'パラメータは'大容量ドライブ・トレイと小容量ドライブ・トレイの両方をサポートします大容量ドライブトレイには、ドライブを格納するドロワーがあります。ドロワーをドライブトレイから引き出して、ドライブへのアクセスを提供します。小容量ドライブトレイにはドロワーはありません。大容量ドライブトレイの場合は、ドライブトレイの識別子（ID）、ドロワーのID、ドライブが配置されているスロットのIDを指定する必要があります。小容量ドライブトレイの場合は、ドライブトレイのIDと、ドライブが格納されているスロットのIDだけを指定する必要があります。小容量ドライブトレイの場合、ドライブトレイのIDを指定し、ドロワーのIDを「0」に設定し、ドライブが格納されているスロットのIDを指定する方法もあります。



[[minimum-firmware-level]]
== 最小ファームウェアレベル

7.83
