---
permalink: commands-a-z/start-diskpool-fullprovisioning.html 
sidebar: sidebar 
keywords: start, disk pool, full, provision 
summary: start diskPool fullProvisioningコマンドは、ディスクプール内のすべてのボリュームでフルプロビジョニング処理を開始し、オプションでディスクプール上のリソースプロビジョニングを無効にします。 
---
= ディスクプールのフルプロビジョニングを開始します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
start diskPool fullProvisioningコマンドは'ディスク・プール内のすべてのボリュームでフル・プロビジョニング操作を開始し'オプションでディスク・プール上のリソース・プロビジョニングを無効にします



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、EF600およびEF300アレイを含むすべてのストレージアレイを環境 します。



== ロール

このコマンドをEF600およびEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

リソースプロビジョニング機能を使用すると、ドライブブロックの大部分を標準ボリュームよりも未割り当ての状態にしておくことで、SSDの寿命が延び、書き込みパフォーマンスが向上します。リソースプロビジョニングボリュームは、SSDボリュームグループまたはプール内のシックボリュームで、ドライブ容量が割り当てられていますが（ボリュームに割り当てられて）、ボリュームの作成時にドライブブロックが割り当て解除（マッピング解除）されます。ドライブブロックは、ホスト書き込みIOを完了するために必要に応じて割り当てられます。ホストのマッピング解除処理によって、ドライブブロックを未割り当て状態に戻すことができます。リソースプロビジョニングでは、時間制限付きのバックグラウンド初期化が排除されるため、大容量のボリュームを迅速に初期化できます。

リソースプロビジョニングボリュームはSSDボリュームグループおよびプールでのみサポートされます。グループまたはプール内のすべてのドライブでNVMe Deallocated or Unwritten Logical Block Error Enable（DULBE）エラーリカバリ機能がサポートされます。パフォーマンスの向上はドライブのモデルや容量によって異なります。

完全なプロビジョニング形式では、ストレージプール内のボリュームに必要なすべてのブロックがドライブ上で完全にマッピングされます。このコマンドは、プロビジョニングされたリソースのストレージプールにのみ適用できます。disableResourceProvisioningオプションがFALSEに設定されていない場合でも'ボリュームはリソースプロビジョニングされ'ストレージプールに作成された新しいボリュームはリソースプロビジョニングされますリソース・プロビジョニングを無効にするオプションがtrueに設定されている場合'ボリュームはリソース・プロビジョニングされなくなり'ストレージ・プールに作成された新しいボリュームはリソース・プロビジョニングされません



== 構文

[listing]
----
start diskPool[diskPoolName] fullProvisioning [disableResourceProvisioning=(TRUE | FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「diskPool」
 a| 
フルプロビジョニング処理を開始するディスクプール。ディスクプール名は角かっこで囲みます（[]）。



 a| 
disableResourceProvisioning
 a| 
フルプロビジョニング処理の完了後にリソースプロビジョニングを無効にするかどうかを指定する設定。リソースプロビジョニングの無効化をスキップするには'これをFALSEに設定しますデフォルト値は「true」です。

[NOTE]
====
ストレージ・プールおよび関連するすべてのボリュームでリソース・プロビジョニングを再度有効にするには' Start Disk Pool Resource Provisioningコマンドを使用します

====
|===


== 最小ファームウェアレベル

11.72
