---
permalink: commands-a-z/start-diskpool-resourceprovisioning.html 
sidebar: sidebar 
keywords: start, disk pool, resource, provision 
summary: start diskPool resourceProvisioningコマンドは、所定のディスクプールでリソースプロビジョニングを有効にし、ディスクプール内の各ボリュームでリソースプロビジョニング有効化非同期処理を開始します。リソースのプロビジョニングでは、ディスクプール内のすべてのドライブがNVMeのDULBE機能をサポートしている必要があります。 
---
= ディスクプールのリソースプロビジョニングを開始する - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
start diskPool resourceProvisioningコマンドを使用すると'所定のディスク・プールでリソース・プロビジョニングを有効にし'ディスク・プール内の各ボリュームで非同期オペレーションを実行するリソース・プロビジョニングを開始できますリソースをプロビジョニングするには、ディスクプール内のすべてのドライブがNVMeのDULBE機能をサポートしている必要があります。



== サポートされているアレイ

このコマンドは、EF600、EF300、EF50、EF80アレイを含む、あらゆる個々のストレージアレイに適用されます（ただし、すべてのSMcliパッケージがインストールされている必要があります）。



== ロール

EF600、EF300、EF50、およびEF80ストレージアレイでこのコマンドを実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

ディスクプールでリソースのプロビジョニングを無効にするには、フルプロビジョニングコマンドとオプションを使用して、リソースのプロビジョニングを無効にします。すべてのドライブがDULBE対応で'ストレージアレイのresourceProvisionedVolumes設定が「true」の場合'ディスクプールは作成時にリソースをプロビジョニングします



== 構文

[source, cli, subs="+macros"]
----
start diskPoolpass:quotes[[_diskPoolName_]] resourceProvisioning
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「diskPoolName」
 a| 
リソースプロビジョニング機能を有効にするディスクプール。ディスクプール名は角かっこ（[]）で囲みます。

|===


== 最小ファームウェアレベル

11.73
