---
permalink: commands-a-z/start-volumegroup-fullprovisioning.html 
sidebar: sidebar 
keywords: start, volume, group, full provision 
summary: start volumeGroup fullProvisioningコマンドは、ディスクプール内のすべてのボリュームで完全なプロビジョニング処理を開始し、必要に応じてボリュームグループでのリソースプロビジョニングを無効にします。 
---
= ボリュームグループのフルプロビジョニングを開始します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
start volumeGroup fullProvisioningコマンドは'ディスク・プール内のすべてのボリュームに対してフル・プロビジョニング操作を開始し'オプションでボリューム・グループ上のリソース・プロビジョニングを無効にします



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、EF600およびEF300アレイを含むすべてのストレージアレイを環境 します。



== ロール

このコマンドをEF600およびEF300ストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

リソースプロビジョニング機能を使用すると、ドライブブロックの大部分を標準ボリュームよりも未割り当ての状態にしておくことで、SSDの寿命が延び、書き込みパフォーマンスが向上します。リソースプロビジョニングボリュームは、SSDボリュームグループまたはプール内のシックボリュームで、ドライブ容量が割り当てられていますが（ボリュームに割り当てられて）、ボリュームの作成時にドライブブロックが割り当て解除（マッピング解除）されます。ドライブブロックは、ホスト書き込みIOを完了するために必要に応じて割り当てられます。ホストのマッピング解除処理によって、ドライブブロックを未割り当て状態に戻すことができます。リソースプロビジョニングでは、時間制限付きのバックグラウンド初期化が排除されるため、大容量のボリュームを迅速に初期化できます。

リソースプロビジョニングボリュームはSSDボリュームグループおよびプールでのみサポートされます。グループまたはプール内のすべてのドライブでNVMe Deallocated or Unwritten Logical Block Error Enable（DULBE）エラーリカバリ機能がサポートされます。パフォーマンスの向上はドライブのモデルや容量によって異なります。

完全なプロビジョニング形式では、ボリュームグループ内のボリュームに必要なすべてのブロックがドライブ上で完全にマッピングされます。このコマンドは、プロビジョニングされたリソースボリュームグループにのみ適用できます。disableResourceProvisioningオプションがFALSEに設定されていない場合でも'ボリュームはリソースプロビジョニングされ'ボリュームグループ上に作成された新しいボリュームはリソースプロビジョニングされますリソース・プロビジョニングを無効にするオプションがtrueに設定されている場合'ボリュームはリソース・プロビジョニングされなくなり'ボリューム・グループに作成された新しいボリュームはリソース・プロビジョニングされません



== 構文

[listing]
----
start volumeGroup[volumeGroupName] fullProvisioning [disableResourceProvisioning=(TRUE | FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「volumeGroup」のように指定します
 a| 
フルプロビジョニング処理を開始するボリュームグループ。ボリュームグループ名は角かっこで囲みます（[]）。



 a| 
disableResourceProvisioning
 a| 
フルプロビジョニング処理の完了後にリソースプロビジョニングを無効にするかどうかを指定する設定。リソースプロビジョニングの無効化をスキップするには'これをFALSEに設定しますデフォルト値は「true」です。

[NOTE]
====
ボリューム・グループおよび関連するすべてのボリュームでリソース・プロビジョニングを再度有効にするには'Start Volume Group Resource Provisioning'コマンドを使用します

====
|===


== 最小ファームウェアレベル

11.72
