---
permalink: commands-a-z/start-drive-erase.html 
sidebar: sidebar 
keywords: start, drive, erase 
summary: start drive eraseコマンドを実行すると、1つ以上のドライブのデータがすべて消去されます。 
---
= ドライブ消去の開始 - SANtricity CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
start drive eraseコマンドを実行すると、1つまたは複数のドライブからすべてのデータが消去されます。



== サポートされているアレイ

このコマンドは、E4000、E2800、E5700、EF600、またはEF300の個 々 のアレイに適用されます。E2700およびE5600のストレージアレイでは動作しません。



== ロール

このコマンドをE4000、E2800、E5700、EF600、またはEF300のストレージアレイに対して実行するには、Security Adminロールが必要です。



== コンテキスト（Context）

このコマンドは、ドライブ上のすべてのデータを完全に削除する場合にのみ実行してください。ドライブがセキュリティ有効の場合、start drive eraseコマンドオプションは暗号化消去を実行し、ドライブのセキュリティ属性をセキュア対応にリセットします。

[NOTE]
====
消去操作は元に戻せません。このコマンドを使用するときは、正しいドライブを選択していることを確認してください。

====


== 構文

[source, cli, subs="+macros"]
----
start (drive [trayID,[drawerID,]slotID] | drives[trayID1,[drawerID1,]slotID1 ... trayIDn,[drawerIDn,]slotIDn]) erase
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「ドライブ」
 a| 
大容量ドライブトレイの場合は、ドライブのトレイIDの値、ドロワーIDの値、およびスロットIDの値を指定します。小容量ドライブトレイの場合は、ドライブのトレイIDの値とスロットIDの値を指定します。トレイIDの値は'0～99ですドロワーIDの値は「1」～「5」です。

スロットIDの最大値はすべて24です。スロットIDの値は、トレイのモデルに応じて0または1で始まります。E2800コントローラおよびE5700コントローラと互換性があるドライブトレイのスロットID番号は0から始まります。E2700およびE5600コントローラと互換性のあるドライブトレイのスロットID番号は1から始まります。

トレイIDの値、ドロワーIDの値、およびスロットIDの値は角かっこ（[]）で囲みます。

[NOTE]
====
drivesリストにストレージアレイのすべてのドライブを指定するとコマンドが拒否されます。

====
|===


== 最小ファームウェアレベル

11.70.1
