---
permalink: commands-a-z/suspend-syncmirror-primaries.html 
sidebar: sidebar 
keywords: suspend, synchronous, mirror 
summary: suspend SyncMirror primariesコマンドは、同期ミラーリング処理を一時停止します。 
---
= 同期ミラーリングを中断します
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
suspend SyncMirror primariesコマンドは'同期ミラーリング操作を一時停止します



== サポートされているアレイ

このコマンドは、すべてのSMcliパッケージがインストールされていれば、E4000、E2700、E5600、E2800、E5700を含む個 々 のストレージアレイに適用されます。



== ロール

このコマンドをE4000、E2800、またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

[NOTE]
====
このコマンドの以前のバージョンでは、機能識別子は「remoteMirror」でした。この機能識別子は有効ではなくなり' SyncMirror に置き換えられます

====


== 構文

[source, cli, subs="+macros"]
----

suspend syncMirror (primary pass:quotes[[_primaryVolumeName_]]
primaries pass:quotes[[_primaryVolumeName1_ ... _primaryVolumeNameN_])]
[writeConsistency=(TRUE | FALSE)]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「プライマリ」
 a| 
処理を中断するプライマリボリュームの名前。ボリューム名は角かっこ（[]）で囲みます。ボリューム名に特殊文字または数字が含まれている場合は、ボリューム名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。



 a| 
「原色」
 a| 
処理を中断する複数のプライマリボリュームの名前。すべてのボリュームに同じプロパティが適用されます。以下のルールを使用して、ボリュームの名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 名前はそれぞれスペースで区切ります。


ボリューム名に特殊文字または数字が含まれる場合は、次のルールに従って名前を入力します。

* すべての名前は角かっこ（[]）で囲みます。
* 各名前は二重引用符（""）で囲みます。
* 名前はそれぞれスペースで区切ります。




 a| 
「ライトコンシステンシ」
 a| 
このパラメータは、このコマンドで特定したボリュームが書き込み整合性グループ内にあるか、別々のボリュームであるかを定義します。同じ書き込み整合性グループ内のボリュームの場合は、このパラメータを「true」に設定します。別々のボリュームの場合は、このパラメータを「FALSE」に設定します。

|===


== 注：

「writeConsistency」パラメータを「true」に設定すると、ボリュームは書き込み整合性グループ（またはグループ）に属している必要があります。このコマンドは、ボリュームを含むすべての書き込み整合性グループの同期ミラーリングを中断します。たとえば'ボリュームA ' B 'およびCが書き込み整合性グループに属しており'リモートの対応するボリュームA'''B''およびC`'がある場合'コマンドは次のようになります

[listing]
----
suspend syncMirror volume ["A"] writeConsistency=TRUE
----
このコマンドは'A-A'、B-B'、C-C'の同期ミラーリングを中断します。書き込み整合性グループ1=｛A、B、C｝と書き込み整合性グループ2=｛D、E、F｝があるとします。

[listing]
----
suspend syncMirror volumes ["A" "D"] writeConsistency=TRUE
----
両方の書き込み整合性グループの中断



== 最小ファームウェアレベル

6.10
