---
permalink: commands-a-z/suspend-asyncmirrorgroup.html 
sidebar: sidebar 
keywords: suspend, asynchronous, mirror, group 
summary: asyncMirrorGroupコマンドは、すべてのミラーペアのデータの同期を非同期ミラーグループレベルで中断します。 
---
= 非同期ミラーグループを中断します
:allow-uri-read: 
:icons: font
:imagesdir: ./media/


[role="lead"]
suspend asyncMirrorGroupコマンドは、すべてのミラーペアのデータの同期を非同期ミラーグループレベルで中断します。



== サポートされているアレイ

このコマンドは、E2700、E5600、E2800、E5700のアレイを含む個々のストレージアレイを環境 で処理します。 すべてのSMcliパッケージがインストールされていること。



== ロール

このコマンドをE2800またはE5700のストレージアレイに対して実行するには、Storage Adminロールが必要です。



== コンテキスト（Context）

この'suspend'コマンドは'ローカル・ストレージ・アレイ上の変更されたデータがリモート・ストレージ・アレイにコピーされるときに発生する可能性のあるホスト・アプリケーションのパフォーマンスへの影響を軽減します



== 構文

[listing, subs="+macros"]
----

pass:quotes[suspend asyncMirrorGroup [_asyncMirrorGroupName_]]
----


== パラメータ

[cols="2*"]
|===
| パラメータ | 説明 


 a| 
「asyncMirrorGroup」
 a| 
データの同期を中断する非同期ミラーグループの名前。非同期ミラーグループ名は角かっこ（[]）で囲みます。非同期ミラーグループ名に特殊文字または数字が含まれている場合は、非同期ミラーグループ名を二重引用符（""）で囲んだ上で角かっこで囲む必要があります。

|===


== 注：

中断状態の非同期ミラーグループでは、ミラーペアのプライマリボリュームからセカンダリボリュームへのデータのコピーは試行されません。非同期ミラーグループのプライマリ側への書き込みは、関連付けられているミラーリポジトリボリュームに永続的に記録されます。非同期ミラーグループが再開されると、プライマリボリュームの変更された領域だけがセカンダリボリュームに書き込まれます。



== 最小ファームウェアレベル

7.84
